Repository NomicFoundation/hardhat, pull requests merged in 2023-12, with the labels that each got.

#4637 refactor: pass spec id instead of data to transaction to rpc result
  crates/edr_provider/src/requests/eth/blocks.rs
  crates/edr_provider/src/requests/eth/transactions.rs
Labels: status:triaging, area:edr

#4641 added hardhat-web3-v4 plugin
  docs/src/content/hardhat-runner/plugins/plugins.ts
Labels: status:triaging, no changeset needed

#4640 Add redirect for hh-waffle guide
  docs/redirects.config.js
Labels: status:ready, no changeset needed

#4571 chore(chain-config): deprecate xDai && update chiado urls
  .changeset/hungry-flies-confess.md
  packages/hardhat-verify/src/internal/chain-config.ts
Labels: status:triaging

#4586 Add experimental support for using ESM modules with TypeScript
  .changeset/shaggy-hornets-exercise.md
  packages/hardhat-core/src/builtin-tasks/test.ts
  packages/hardhat-core/src/internal/core/project-structure.ts
  packages/hardhat-core/src/internal/core/typescript-support.ts
Labels: status:ready

#4647 Exclude artifacts/package.json from artifacts in getArtifactPaths
  .changeset/dry-moose-draw.md
  packages/hardhat-core/src/internal/artifacts.ts
Labels: status:ready, no changeset needed

#4649 fix: overwrite genesis account nonces and code in fork mode
  crates/edr_eth/src/remote/client.rs
  crates/edr_provider/src/data.rs
Labels: status:triaging, area:edr

#4631 Added a guide for verifying contracts with hardhat ignition
  docs/src/content/ignition/docs/guides/_dirinfo.yaml
  docs/src/content/ignition/docs/guides/verify.md
  docs/temp/tabsConfig.json
Labels: no changeset needed

#4620 Create good end to end tests
  .github/workflows/e2e-tests.yml
  docs/src/content/hardhat-runner/docs/getting-started/index.md
  docs/src/content/hardhat-runner/docs/guides/project-setup.md
  docs/src/content/hardhat-runner/docs/other-guides/waffle-testing.md
  docs/src/content/tutorial/creating-a-new-hardhat-project.md
  e2e/.gitignore
  e2e/README.md
  e2e/clean.sh
  e2e/fixture-projects/clean/contracts/Lock.sol
  e2e/fixture-projects/clean/hardhat.config.js
  e2e/fixture-projects/clean/package.json
  e2e/fixture-projects/clean/test.sh
  e2e/fixture-projects/compile-fail/contracts/Foo.sol
  e2e/fixture-projects/compile-fail/hardhat.config.js
  e2e/fixture-projects/compile-fail/package.json
  e2e/fixture-projects/compile-fail/test.sh
  e2e/fixture-projects/compile/contracts/Foo.sol
  e2e/fixture-projects/compile/hardhat.config.js
  e2e/fixture-projects/compile/package.json
  e2e/fixture-projects/compile/test.sh
  e2e/fixture-projects/flatten/contracts/A.sol
  e2e/fixture-projects/flatten/contracts/B.sol
  e2e/fixture-projects/flatten/contracts/C.sol
  e2e/fixture-projects/flatten/contracts/Lock.sol
  e2e/fixture-projects/flatten/hardhat.config.js
  e2e/fixture-projects/flatten/package.json
  e2e/fixture-projects/flatten/test.sh
  e2e/fixture-projects/gas-reporter/contracts/Foo.sol
  e2e/fixture-projects/gas-reporter/hardhat.config.js
  e2e/fixture-projects/gas-reporter/package.json
  e2e/fixture-projects/gas-reporter/test.sh
  e2e/fixture-projects/gas-reporter/test/test.js
  e2e/fixture-projects/help/hardhat.config.js
  e2e/fixture-projects/help/package.json
  e2e/fixture-projects/help/test.sh
  e2e/fixture-projects/solidity-coverage/contracts/Foo.sol
  e2e/fixture-projects/solidity-coverage/hardhat.config.js
  e2e/fixture-projects/solidity-coverage/package.json
  e2e/fixture-projects/solidity-coverage/test.sh
  e2e/fixture-projects/solidity-coverage/test/test.js
  e2e/fixture-projects/test/contracts/Foo.sol
  e2e/fixture-projects/test/hardhat.config.js
  e2e/fixture-projects/test/package.json
  e2e/fixture-projects/test/test.sh
  e2e/fixture-projects/test/test/test.js
  e2e/fixture-projects/vars/hardhat.config.js
  e2e/fixture-projects/vars/package.json
  e2e/fixture-projects/vars/test.sh
  e2e/helpers.sh
  e2e/run-fixture-projects.sh
  e2e/test-project-initialization.sh
  packages/hardhat-core/sample-projects/javascript-esm/test/Lock.js
  packages/hardhat-core/src/internal/cli/cli.ts
  packages/hardhat-core/src/internal/cli/project-creation.ts
Labels: status:ready, no changeset needed

#4643 Add configurable public client to getContractAt, deployContract and sendDeploymentTransaction
  .changeset/odd-cooks-wait.md
  packages/hardhat-viem/src/internal/contracts.ts
  packages/hardhat-viem/src/types.ts
Labels: status:triaging

#4651 fix: balance override for local accounts in forked blockchain is not applied
  Cargo.lock
  crates/edr_provider/Cargo.toml
  crates/edr_provider/src/data.rs
  crates/edr_provider/src/test_utils.rs
Labels: area:edr

#4659 feat: collect solidity `console.log` messages
  Cargo.lock
  crates/edr_evm/src/block/builder.rs
  crates/edr_evm/src/debug_trace.rs
  crates/edr_evm/src/evm.rs
  crates/edr_evm/src/inspector.rs
  crates/edr_evm/src/miner.rs
  crates/edr_evm/src/runtime.rs
  crates/edr_evm/src/transaction.rs
  crates/edr_napi/index.d.ts
  crates/edr_napi/src/miner.rs
  crates/edr_napi/src/provider.rs
  crates/edr_napi/src/runtime.rs
  crates/edr_napi/src/threadsafe_function.rs
  crates/edr_provider/Cargo.toml
  crates/edr_provider/src/data.rs
  crates/edr_provider/src/data/inspector.rs
  crates/edr_provider/src/lib.rs
  packages/hardhat-core/src/internal/hardhat-network/provider/provider.ts
  packages/hardhat-core/src/internal/hardhat-network/stack-traces/consoleLogger.ts
Labels: area:edr

#4667 ci: enable `eth_getTransactionByHash` tests
  crates/edr_eth/src/transaction/request.rs
  crates/edr_evm/src/blockchain/forked.rs
  crates/edr_evm/tests/blockchain.rs
  crates/edr_napi/src/blockchain.rs
  crates/edr_provider/src/data.rs
  crates/edr_provider/src/test_utils.rs
  packages/hardhat-core/src/internal/hardhat-network/provider/provider.ts
  packages/hardhat-core/test/internal/hardhat-network/helpers/retrieveCommon.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/getTransactionByHash.ts
Labels: status:triaging, area:edr

#4660 test: enable block related tests for EDR provider
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/blockNumber.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/getBlockByHash.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/getBlockByNumber.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/getBlockTransactionCountByHash.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/getBlockTransactionCountByNumber.ts
Labels: area:edr

#4665 feat: add `hardhat_reset` to EDR provider
  Cargo.lock
  crates/edr_eth/src/transaction/request.rs
  crates/edr_evm/src/blockchain/forked.rs
  crates/edr_evm/src/miner.rs
  crates/edr_evm/tests/blockchain.rs
  crates/edr_napi/src/blockchain.rs
  crates/edr_napi/src/provider.rs
  crates/edr_provider/Cargo.toml
  crates/edr_provider/src/config.rs
  crates/edr_provider/src/data.rs
  crates/edr_provider/src/data/inspector.rs
  crates/edr_provider/src/error.rs
  crates/edr_provider/src/lib.rs
  crates/edr_provider/src/requests/hardhat/state.rs
  crates/edr_provider/src/test_utils.rs
  packages/hardhat-core/src/internal/hardhat-network/provider/provider.ts
  packages/hardhat-core/test/internal/hardhat-network/helpers/retrieveCommon.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/getTransactionByHash.ts
Labels: area:edr

#4673 Revert a change to tabsConfig.json
  docs/temp/tabsConfig.json
Labels: status:ready, no changeset needed

#4664 fix typo of ignition
  docs/src/content/ignition/docs/guides/deploy.md
Labels: status:triaging

#4666 test: enable and fix Hardhat eth_call tests
  crates/edr_eth/src/remote.rs
  crates/edr_eth/src/remote/override.rs
  crates/edr_evm/src/block/builder.rs
  crates/edr_evm/src/mempool.rs
  crates/edr_evm/src/runtime.rs
  crates/edr_evm/src/state/overrides.rs
  crates/edr_evm/src/transaction.rs
  crates/edr_evm/src/transaction/pending.rs
  crates/edr_napi/index.d.ts
  crates/edr_napi/src/provider.rs
  crates/edr_napi/src/transaction/pending.rs
  crates/edr_provider/src/data.rs
  crates/edr_provider/src/error.rs
  crates/edr_provider/src/lib.rs
  crates/edr_provider/src/pending.rs
  crates/edr_provider/src/requests.rs
  crates/edr_provider/src/requests/eth/blocks.rs
  crates/edr_provider/src/requests/eth/call.rs
  crates/edr_provider/src/requests/eth/transactions.rs
  crates/edr_provider/src/requests/validation.rs
  packages/hardhat-core/src/internal/hardhat-network/provider/mem-pool/edr.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/block-builder/edr.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/edr.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/call.ts
Labels: area:edr

#4678 test: enable passing provider tests
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/gasUsage.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/newPendingTransactionFilter.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/pendingTransactions.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/receiptsRoot.ts
Labels: area:edr

#4646 build(clippy): Don't lint against deny-by-default Clippy lints
  .cargo/config
Labels: area:edr

#4661 docs: add a `using viem` guide to Ignition
  docs/src/content/ignition/docs/getting-started/index.md
  docs/src/content/ignition/docs/guides/_dirinfo.yaml
  docs/src/content/ignition/docs/guides/tests.md
  docs/src/content/ignition/docs/guides/viem.md
Labels: status:ready, no changeset needed

#4669 Update Standard JSON Input Link
  docs/src/content/hardhat-runner/docs/config/index.md
Labels: status:triaging, no changeset needed

#4674 test: enable `getBalance` and `getTransaction*` integration tests for EDR Provider
  crates/edr_evm/src/runtime.rs
  crates/edr_provider/src/data.rs
  crates/edr_provider/src/requests/eth/blocks.rs
  crates/edr_provider/src/requests/eth/transactions.rs
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/call.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/getBalance.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/getTransactionByBlockHashAndIndex.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/getTransactionByBlockNumberAndIndex.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/getTransactionCount.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/getTransactionReceipt.ts
Labels: area:edr

#4653 feat: add config option for minimum gas price
  crates/edr_evm/src/runtime.rs
  crates/edr_napi/index.d.ts
  crates/edr_napi/src/provider/config.rs
  crates/edr_provider/src/config.rs
  crates/edr_provider/src/data.rs
  crates/edr_provider/src/test_utils.rs
  packages/hardhat-core/src/internal/hardhat-network/provider/provider.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/call.ts
Labels: area:edr

#4684 ci: enable web3 module tests
  packages/hardhat-core/.prettierignore
  packages/hardhat-core/src/internal/hardhat-network/provider/provider.ts
  packages/hardhat-core/test/internal/hardhat-network/helpers/isEdrProvider.ts
  packages/hardhat-core/test/internal/hardhat-network/helpers/retrieveCommon.ts
  packages/hardhat-core/test/internal/hardhat-network/helpers/useProvider.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/web3.ts
Labels: area:edr

#4687 refactor: add client request type
  crates/edr_eth/src/remote.rs
  crates/edr_eth/src/remote/cacheable_method_invocation.rs
  crates/edr_eth/src/remote/client.rs
  crates/edr_eth/src/remote/eth.rs
  crates/edr_eth/src/remote/eth/call_request.rs
  crates/edr_eth/src/remote/eth/get_logs.rs
  crates/edr_eth/src/remote/methods.rs
  crates/edr_eth/src/remote/request_methods.rs
  crates/edr_eth/tests/integration_tests.rs
  crates/edr_provider/src/requests/eth/call.rs
  crates/edr_provider/src/requests/validation.rs
Labels: area:edr

#4688 refactor: move `MethodInvocation` from `edr_eth` to `edr_provider`
  Cargo.lock
  crates/edr_eth/src/remote.rs
  crates/edr_provider/Cargo.toml
  crates/edr_provider/src/lib.rs
  crates/edr_provider/src/requests.rs
  crates/edr_provider/src/requests/eth/evm.rs
  crates/edr_provider/src/requests/methods.rs
  crates/edr_provider/tests/request_serialization.rs
Labels: area:edr

#4693 hardhat-verify: add apiUrl and browserUrl in sourcify options
  .changeset/bright-plums-watch.md
  packages/hardhat-verify/README.md
  packages/hardhat-verify/src/internal/config.ts
  packages/hardhat-verify/src/internal/sourcify.ts
  packages/hardhat-verify/src/internal/tasks/sourcify.ts
  packages/hardhat-verify/src/types.ts
  packages/hardhat-verify/test/unit/config.ts
  packages/hardhat-verify/test/unit/sourcify.ts
Labels: status:ready

#4692 Add solidity survey banner and message
  .changeset/three-boxes-divide.md
  docs/redirects.config.js
  docs/src/config.ts
  packages/hardhat-core/src/internal/cli/cli.ts
  packages/hardhat-core/src/internal/cli/project-creation.ts
Labels: status:ready

#4681 Add support for solc 0.8.23
  .changeset/dirty-pots-exercise.md
  docs/src/content/hardhat-runner/docs/reference/solidity-support.md
  docs/src/model/markdown.tsx
  packages/hardhat-core/src/internal/hardhat-network/stack-traces/constants.ts
  packages/hardhat-core/src/internal/solidity/compiler/solc-info.ts
  packages/hardhat-core/test/builtin-tasks/compile.ts
  packages/hardhat-core/test/fixture-projects/compilation-latest-solc-version/.gitignore
  packages/hardhat-core/test/fixture-projects/compilation-latest-solc-version/contracts/A.sol
  packages/hardhat-core/test/fixture-projects/compilation-latest-solc-version/hardhat.config.js
  packages/hardhat-core/test/internal/hardhat-network/stack-traces/compilers-list.ts
Labels: status:ready

#4696 refactor: merge `edr_rpc_hardhat` into `edr_provider`
  Cargo.lock
  crates/edr_napi/Cargo.toml
  crates/edr_napi/src/provider/config.rs
  crates/edr_provider/Cargo.toml
  crates/edr_provider/src/config.rs
  crates/edr_provider/src/data.rs
  crates/edr_provider/src/lib.rs
  crates/edr_provider/src/requests.rs
  crates/edr_provider/src/requests/hardhat.rs
  crates/edr_provider/src/requests/hardhat/config.rs
  crates/edr_provider/src/requests/hardhat/rpc_types.rs
  crates/edr_provider/src/requests/hardhat/rpc_types/compiler.rs
  crates/edr_provider/src/requests/hardhat/rpc_types/config.rs
  crates/edr_provider/src/requests/hardhat/rpc_types/metadata.rs
  crates/edr_provider/src/requests/hardhat/state.rs
  crates/edr_provider/src/requests/methods.rs
  crates/edr_provider/src/test_utils.rs
  crates/edr_provider/tests/common.rs
  crates/edr_provider/tests/eth_request_serialization.rs
  crates/edr_provider/tests/fixtures/compiler_input.json
  crates/edr_provider/tests/fixtures/compiler_output.json
  crates/edr_provider/tests/hardhat_request_serialization.rs
  crates/edr_rpc_hardhat/Cargo.toml
  crates/edr_rpc_hardhat/src/lib.rs
  crates/edr_test_utils/src/lib.rs
Labels: area:edr

#4638 Update reference.md to correct mistakes in sample code.
  docs/src/content/hardhat-chai-matchers/docs/reference.md
Labels: no changeset needed

#4697 refactor: custom deserialization for provider request
  crates/edr_provider/src/requests.rs
Labels: area:edr

#4702 ci: enable and fix net module integration tests
  packages/hardhat-core/src/internal/hardhat-network/provider/provider.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/net.ts
Labels: area:edr

#4703 test: enable and fix `eth_getCode` integration tests
  crates/edr_provider/src/data.rs
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/getCode.ts
Labels: area:edr

#4704 test: fix and enable block tag integration tests
  crates/edr_eth/src/remote.rs
  crates/edr_eth/src/remote/block_spec.rs
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/blockTags.ts
Labels: area:edr

#4705 test: enable chain id integration tests
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/chainId.ts
Labels: area:edr

#4706 test: fix and enable personal sign integration tests
  crates/edr_eth/src/signature.rs
  crates/edr_provider/src/lib.rs
  crates/edr_provider/src/requests/eth/sign.rs
  crates/edr_provider/src/requests/methods.rs
  crates/edr_provider/tests/eth_request_serialization.rs
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/personal.ts
Labels: area:edr

#4707 test: fix and enable base fee per gas integration tests
  crates/edr_eth/src/remote/eth.rs
  crates/edr_eth/src/serde.rs
  crates/edr_eth/src/utils.rs
  crates/edr_evm/src/blockchain/local.rs
  crates/edr_evm/src/debug_trace.rs
  crates/edr_provider/src/data.rs
  crates/edr_provider/src/requests/eth/state.rs
  packages/hardhat-core/src/internal/hardhat-network/provider/provider.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/baseFeePerGas.ts
Labels: area:edr

#4709 Report telemetry consent response to Google Analytics
  .changeset/silly-flowers-begin.md
  packages/hardhat-core/src/internal/cli/analytics.ts
  packages/hardhat-core/src/internal/cli/cli.ts
  packages/hardhat-core/src/internal/cli/project-creation.ts
  packages/hardhat-core/src/internal/util/report-telemetry-consent.ts
Labels: status:ready

#4449 Support Addressable in .withArgs and .equals
  .changeset/cold-tables-stare.md
  packages/hardhat-chai-matchers/src/internal/addressable.ts
  packages/hardhat-chai-matchers/src/internal/hardhatChaiMatchers.ts
  packages/hardhat-chai-matchers/src/internal/withArgs.ts
  packages/hardhat-chai-matchers/test/addressable.ts
  packages/hardhat-chai-matchers/test/contracts.ts
  packages/hardhat-chai-matchers/test/events.ts
  packages/hardhat-chai-matchers/test/fixture-projects/hardhat-project/contracts/Events.sol
Labels: status:triaging

#4701 Fix compilation error with latest @types/node
  packages/hardhat-core/src/internal/hardhat-network/stack-traces/solidity-errors.ts
Labels: status:ready, no changeset needed

#4717 Fix syntax error in code example
  docs/src/content/hardhat-runner/docs/advanced/using-viem.md
Labels: status:ready, no changeset needed

#4679 Docs: update lockedAmount
  docs/src/content/hardhat-runner/docs/getting-started/index.md
Labels: status:triaging, no changeset needed

#4710 fix(gas_provider): Prevent submitting transactions with 0 priority fee.
  .changeset/modern-fishes-look.md
  packages/hardhat-core/src/internal/core/providers/gas-providers.ts
Labels: status:triaging

#4657 Port ContractsIdentifier to EDR
  Cargo.lock
  crates/edr_eth/src/lib.rs
  crates/edr_solidity/Cargo.toml
  crates/edr_solidity/src/build_model.rs
  crates/edr_solidity/src/contracts_identifier.rs
  crates/edr_solidity/src/contracts_identifier/radix_tree.rs
  crates/edr_solidity/src/lib.rs
  crates/edr_solidity/src/opcodes.rs
Labels: status:ready
