Repository NomicFoundation/hardhat, pull requests merged in 2023-03, with the labels that each got.

#3723 Fix #3721
  packages/hardhat-core/src/internal/core/runtime-environment.ts
  packages/hardhat-core/test/internal/core/runtime-environment.ts
Labels: no changeset needed

#3668 Use our mirror to download the Vyper compilers
  .changeset/healthy-cups-march.md
  .changeset/quiet-queens-talk.md
  .github/workflows/LATEST_DEPENDENCY_VERSIONS.yml
  .github/workflows/hardhat-vyper-ci.yml
  .github/workflows/pre-release.yml
  packages/hardhat-vyper/.mocharc.json
  packages/hardhat-vyper/README.md
  packages/hardhat-vyper/src/constants.ts
  packages/hardhat-vyper/src/downloader.ts
Labels: status:triaging

#3731 Improve on #3662 by sending less ETH and locking it for a shorter time
  .changeset/hip-cameras-behave.md
  packages/hardhat-core/sample-projects/javascript-esm/scripts/deploy.js
  packages/hardhat-core/sample-projects/javascript/scripts/deploy.js
  packages/hardhat-core/sample-projects/typescript/scripts/deploy.ts
Labels: status:triaging

#3730 Fix hardcoded URL in the etherscan plugin
  packages/hardhat-etherscan/src/etherscan/EtherscanService.ts
  packages/hardhat-etherscan/src/index.ts
  packages/hardhat-etherscan/src/network/prober.ts
  packages/hardhat-etherscan/test/integration/PluginTests.ts
Labels: area:hardhat-etherscan, no changeset needed

#3726 Fix hardhat-solhint plugin error with solhint 3.4.0
  .changeset/strange-drinks-cry.md
  packages/hardhat-solhint/package.json
  packages/hardhat-solhint/src/index.ts
  packages/hardhat-solhint/test/tests.ts
  yarn.lock
Labels: status:triaging

#3739 plugins: remove deprecated plugin
  docs/src/content/hardhat-runner/plugins/plugins.ts
Labels: no changeset needed

#3709 fix: ethers.Signer check in getContractFactory
  .changeset/fix-getContractFactory-signer.md
  packages/hardhat-ethers/src/internal/helpers.ts
Labels: status:triaging

#3735 fix: hardhat-foundry plugin user-configured sources path not match pa…
  .changeset/sharp-experts-play.md
  packages/hardhat-foundry/src/index.ts
Labels: status:triaging

#3575 feat: add ForkDatabase
  crates/rethnet_evm/src/db.rs
  crates/rethnet_evm/src/state/fork.rs
  crates/rethnet_evm/src/state/layered_state.rs
  crates/rethnet_evm/src/state/remote.rs
Labels: area:rethnet

#3761 fix: Rethnet CI
  .github/workflows/rethnet-ci.yml
  crates/rethnet_evm_napi/package.json
  crates/rethnet_evm_napi/test/evm/RethnetDb.ts
  crates/rethnet_evm_napi/test/evm/StateManager.ts
Labels: status:triaging

#3769 Hardhat deals
  docs/src/content/hardhat-runner/plugins/plugins.ts
Labels: status:triaging

#3764 Added hardhat-uniswap-v2-deploy-plugin
  docs/src/content/hardhat-runner/plugins/plugins.ts
Labels: status:triaging

#3774 docs: add infura, and replace goerli with sepolia
  docs/src/content/hardhat-network/docs/guides/forking-other-networks.md
  docs/src/content/hardhat-network/docs/reference/index.md
  docs/src/content/hardhat-runner/docs/config/index.md
  docs/src/content/hardhat-runner/docs/guides/verifying.md
  docs/src/content/tutorial/deploying-to-a-live-network.md
  docs/temp/tabsConfig.json
Labels: status:triaging, no changeset needed

#3784 chore: unpin napi version
  crates/rethnet_evm_napi/Cargo.toml
Labels: status:triaging

#3797 Add hardhat-storage-dumper
  docs/src/content/hardhat-runner/plugins/plugins.ts
  package.json
Labels: status:triaging

#3778 Update hardhat-runtime-environment.md
  docs/src/content/hardhat-runner/docs/advanced/hardhat-runtime-environment.md
Labels: status:triaging, no changeset needed
