Repository NomicFoundation/hardhat, pull requests merged in 2023-04, with the labels that each got.

#3806 Fix aurora api url
  .changeset/polite-mugs-cry.m
  packages/hardhat-etherscan/src/ChainConfig.ts
Labels: status:triaging

#3767 Add support for the shanghai hardfork
  .changeset/orange-boxes-burn.md
  docs/src/content/hardhat-network/docs/reference/index.md
  packages/hardhat-core/package.json
  packages/hardhat-core/src/internal/constants.ts
  packages/hardhat-core/src/internal/core/jsonrpc/types/output/block.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/BlockchainBase.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/TxPool.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/fork/ForkBlockchain.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/fork/rpcToBlockData.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/modules/eth.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/node.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/output.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/transactions/FakeSenderAccessListEIP2930Transaction.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/transactions/FakeSenderEIP1559Transaction.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/transactions/FakeSenderTransaction.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/transactions/ReadOnlyValidEIP1559Transaction.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/transactions/ReadOnlyValidEIP2930Transaction.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/transactions/ReadOnlyValidTransaction.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/transactions/ReadOnlyValidUnknownTypeTransaction.ts
  packages/hardhat-core/src/internal/util/hardforks.ts
  packages/hardhat-core/test/internal/hardhat-network/helpers/contracts.ts
  packages/hardhat-core/test/internal/hardhat-network/helpers/transactions.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/HardhatBlockchain.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/fork/ForkBlockchain.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/debug.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/hardforks.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/node.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/utils/runFullBlock.ts
  yarn.lock
Labels: status:triaging

#3795 Add hardhat-deal amongst hardhat plugins
  docs/src/content/hardhat-runner/plugins/plugins.ts
Labels: status:ready, no changeset needed

#3808 Update hardhat-and-foundry.md
  docs/src/content/hardhat-runner/docs/advanced/hardhat-and-foundry.md
Labels: status:triaging, no changeset needed

#3810 refactor: explicitly make snapshots in block builder
  crates/rethnet_evm/src/state/debug.rs
  crates/rethnet_evm/src/state/layered_state.rs
  crates/rethnet_evm/src/state/request.rs
  crates/rethnet_evm/src/state/sync.rs
  crates/rethnet_evm_napi/Cargo.toml
  crates/rethnet_evm_napi/src/config.rs
  crates/rethnet_evm_napi/src/state.rs
  crates/rethnet_evm_napi/src/tracer/js_tracer.rs
  crates/rethnet_evm_napi/src/transaction/result.rs
  packages/hardhat-core/src/internal/hardhat-network/provider/RethnetState.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/node.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/dual.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/ethereumjs.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/rethnet.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/vm-adapter.ts
Labels: status:triaging

#3831 Update debugging-with-hardhat-network.md
  docs/src/content/tutorial/debugging-with-hardhat-network.md
Labels: status:triaging, no changeset needed

#3850 Add community plugin @truffle/dashboard-hardhat-plugin
  docs/src/content/hardhat-runner/plugins/plugins.ts
Labels: status:triaging, no changeset needed

#3830 Set Shanghai as the default hardfork
  .changeset/plenty-melons-smoke.md
  docs/src/content/hardhat-network/docs/reference/index.md
  packages/hardhat-core/src/internal/core/config/default-config.ts
Labels: status:triaging

#3861 Several shanghai fixes
  packages/hardhat-core/package.json
  packages/hardhat-core/src/internal/hardhat-network/provider/node.ts
  packages/hardhat-core/test/internal/hardhat-network/helpers/providers.ts
  packages/hardhat-core/test/internal/hardhat-network/helpers/useProvider.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/baseFeePerGas.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/forking-different-hardfork.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/getBlockByNumber.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/sendRawTransaction.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/sendTransaction.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/hardhat.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/node.ts
  yarn.lock
Labels: status:triaging, no changeset needed

#3822 Add coinbase wallet to docs
  docs/src/content/hardhat-network/docs/metamask-issue/index.md
  docs/src/content/hardhat-network/docs/overview/index.md
  docs/src/content/hardhat-runner/docs/getting-started/index.md
  docs/src/content/hardhat-runner/docs/guides/verifying.md
  docs/src/content/tutorial/boilerplate-project.md
  docs/src/content/tutorial/deploying-to-a-live-network.md
  docs/src/content/tutorial/index.md
Labels: status:ready, no changeset needed

#3837 improvement: minimize data copied to JS
  .changeset/forty-seals-occur.md
  .github/workflows/LATEST_DEPENDENCY_VERSIONS.yml
  .github/workflows/comment-on-linter-error.yml
  .github/workflows/e2e-ci.yml
  .github/workflows/hardhat-chai-matchers-ci.yml
  .github/workflows/hardhat-core-ci.yml
  .github/workflows/hardhat-ethers-ci.yml
  .github/workflows/hardhat-etherscan-ci.yml
  .github/workflows/hardhat-foundry-ci.yml
  .github/workflows/hardhat-ganache-ci.yml
  .github/workflows/hardhat-network-forking-ci.yml
  .github/workflows/hardhat-network-helpers-ci.yml
  .github/workflows/hardhat-network-tracing-all-solc-versions.yml
  .github/workflows/hardhat-network-tracing-ci.yml
  .github/workflows/hardhat-shorthand-ci.yml
  .github/workflows/hardhat-solhint-ci.yml
  .github/workflows/hardhat-solpp-ci.yml
  .github/workflows/hardhat-toolbox-ci.yml
  .github/workflows/hardhat-truffle4-ci.yml
  .github/workflows/hardhat-truffle5-ci.yml
  .github/workflows/hardhat-vyper-ci.yml
  .github/workflows/hardhat-waffle-ci.yml
  .github/workflows/hardhat-web3-ci.yml
  .github/workflows/hardhat-web3-legacy-ci.yml
  .github/workflows/lint.yml
  .github/workflows/pre-release.yml
  .github/workflows/release.yml
  .github/workflows/rethnet-ci.yml
  .github/workflows/test-recent-mainnet-block.yml
  crates/rethnet_eth/Cargo.toml
  crates/rethnet_evm/Cargo.toml
  crates/rethnet_evm_napi/Cargo.toml
  crates/rethnet_evm_napi/src/runtime.rs
  crates/rethnet_evm_napi/src/state.rs
  crates/rethnet_evm_napi/src/tracer/js_tracer.rs
  packages/hardhat-core/package.json
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/dual.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/ethereumjs.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/rethnet.ts
Labels: status:triaging, area:rethnet

#3840 feat: add hybrid state management
  crates/rethnet_eth/Cargo.toml
  crates/rethnet_eth/src/account.rs
  crates/rethnet_eth/src/state.rs
  crates/rethnet_evm/Cargo.toml
  crates/rethnet_evm/src/state.rs
  crates/rethnet_evm/src/state/account.rs
  crates/rethnet_evm/src/state/contract.rs
  crates/rethnet_evm/src/state/debug.rs
  crates/rethnet_evm/src/state/history.rs
  crates/rethnet_evm/src/state/hybrid.rs
  crates/rethnet_evm/src/state/layered.rs
  crates/rethnet_evm/src/state/layered/changes.rs
  crates/rethnet_evm/src/state/layered_state.rs
  crates/rethnet_evm/src/state/request.rs
  crates/rethnet_evm/src/state/sync.rs
  crates/rethnet_evm/src/state/trie.rs
  crates/rethnet_evm/src/state/trie/account.rs
  crates/rethnet_evm_napi/src/state.rs
  packages/hardhat-core/src/internal/hardhat-network/provider/RethnetState.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/fork/ForkStateManager.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/dual.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/ethereumjs.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/rethnet.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/vm-adapter.ts
Labels: status:triaging, area:rethnet

#3842 refactor: replace background with short-lived tasks
  crates/rethnet_eth/Cargo.toml
  crates/rethnet_evm/Cargo.toml
  crates/rethnet_evm/src/block/builder.rs
  crates/rethnet_evm/src/blockchain.rs
  crates/rethnet_evm/src/blockchain/request.rs
  crates/rethnet_evm/src/blockchain/sync.rs
  crates/rethnet_evm/src/evm.rs
  crates/rethnet_evm/src/inspector.rs
  crates/rethnet_evm/src/lib.rs
  crates/rethnet_evm/src/runtime.rs
  crates/rethnet_evm/src/state.rs
  crates/rethnet_evm/src/state/request.rs
  crates/rethnet_evm/src/state/sync.rs
  crates/rethnet_evm/src/trace.rs
  crates/rethnet_evm_napi/src/blockchain.rs
  crates/rethnet_evm_napi/src/blockchain/js_blockchain.rs
  crates/rethnet_evm_napi/src/context.rs
  crates/rethnet_evm_napi/src/lib.rs
  crates/rethnet_evm_napi/src/state.rs
  crates/rethnet_evm_napi/src/tracer.rs
  crates/rethnet_evm_napi/src/tracer/js_tracer.rs
  crates/rethnet_evm_napi/src/transaction/result.rs
  crates/rethnet_evm_napi/test/evm/RethnetDb.ts
  crates/rethnet_evm_napi/test/evm/StateManager.ts
  packages/hardhat-core/src/internal/core/providers/http.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/RethnetState.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/rethnet.ts
Labels: status:triaging, area:rethnet

#3843 fix: force tsc build to avoid stale code
  crates/rethnet_evm_napi/src/state.rs
  packages/hardhat-core/package.json
Labels: status:triaging, area:rethnet

#3844 improvement: improve tracing
  crates/rethnet_evm_napi/src/account.rs
  crates/rethnet_evm_napi/src/block.rs
  crates/rethnet_evm_napi/src/block/builder.rs
  crates/rethnet_evm_napi/src/blockchain.rs
  crates/rethnet_evm_napi/src/blockchain/js_blockchain.rs
  crates/rethnet_evm_napi/src/config.rs
  crates/rethnet_evm_napi/src/context.rs
  crates/rethnet_evm_napi/src/lib.rs
  crates/rethnet_evm_napi/src/logger.rs
  crates/rethnet_evm_napi/src/state.rs
  crates/rethnet_evm_napi/src/tracer/js_tracer.rs
  crates/rethnet_evm_napi/src/transaction.rs
  crates/rethnet_evm_napi/src/transaction/result.rs
Labels: status:triaging, area:rethnet

#3845 fix: re-enable storage root check
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/dual.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/rethnet.ts
Labels: status:triaging, area:rethnet

#3846 improvement: replace JSTracer with TraceCollector
  crates/rethnet_evm/src/block/builder.rs
  crates/rethnet_evm/src/evm.rs
  crates/rethnet_evm/src/inspector.rs
  crates/rethnet_evm/src/lib.rs
  crates/rethnet_evm/src/runtime.rs
  crates/rethnet_evm/src/trace.rs
  crates/rethnet_evm_napi/src/block/builder.rs
  crates/rethnet_evm_napi/src/lib.rs
  crates/rethnet_evm_napi/src/log.rs
  crates/rethnet_evm_napi/src/runtime.rs
  crates/rethnet_evm_napi/src/trace.rs
  crates/rethnet_evm_napi/src/tracer.rs
  crates/rethnet_evm_napi/src/tracer/js_tracer.rs
  crates/rethnet_evm_napi/src/transaction/result.rs
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/ethereumjs.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/rethnet.ts
Labels: status:triaging, area:rethnet

#3847 improvement: maintain reference count of snapshots
  crates/rethnet_evm/src/collections.rs
  crates/rethnet_evm/src/collections/shared_map.rs
  crates/rethnet_evm/src/lib.rs
  crates/rethnet_evm/src/state.rs
  crates/rethnet_evm/src/state/contract.rs
  crates/rethnet_evm/src/state/history.rs
  crates/rethnet_evm/src/state/hybrid.rs
  crates/rethnet_evm/src/state/layered.rs
  crates/rethnet_evm/src/state/layered/changes.rs
  crates/rethnet_evm/src/state/trie.rs
  crates/rethnet_evm_napi/src/state.rs
  packages/hardhat-core/src/internal/hardhat-network/provider/RethnetState.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/node.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/dual.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/ethereumjs.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/rethnet.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/vm-adapter.ts
Labels: status:triaging, area:rethnet

#3848 improvement: correctly annotate immutable trait functions
  crates/rethnet_evm/src/state/debug.rs
  crates/rethnet_evm/src/state/hybrid.rs
  crates/rethnet_evm/src/state/layered.rs
  crates/rethnet_evm/src/state/trie.rs
  crates/rethnet_evm_napi/src/state.rs
Labels: status:triaging, area:rethnet

#3849 improvement: more validation in `DualModeAdapter`
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/dual.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/rethnet.ts
Labels: status:triaging, area:rethnet

#3886 fix: bug in benchmark of `StateRef::basic()`
  crates/rethnet_evm/benches/state.rs
Labels: status:triaging

#3885 Update PP
  docs/public/privacy-policy.html
Labels: no changeset needed

#3888 Use shanghai in stack traces tests
  packages/hardhat-core/test/internal/hardhat-network/stack-traces/execution.ts
Labels: status:triaging, no changeset needed

#3832 Fix .withArgs when arrays have different length
  .changeset/lazy-hornets-clap.md
  packages/hardhat-chai-matchers/src/internal/emit.ts
  packages/hardhat-chai-matchers/src/internal/reverted/revertedWithCustomError.ts
  packages/hardhat-chai-matchers/test/events.ts
  packages/hardhat-chai-matchers/test/reverted/revertedWithCustomError.ts
Labels: status:ready
