Repository NomicFoundation/hardhat, pull requests merged in 2023-08, with the labels that each got.

#4214 feat: Add `personal_sign` alias for `eth_sign`
  crates/rethnet_eth/src/remote/methods.rs
  crates/rethnet_eth/tests/integration_tests.rs
Labels: status:triaging

#4180 test: A first doctest
  crates/rethnet_eth/src/signature.rs
Labels: status:triaging, area:edr

#4211 Update testing-contracts.md
  docs/src/content/tutorial/testing-contracts.md
Labels: status:triaging, no changeset needed

#4186 add `hardhat-deployed-records` plugin
  docs/src/content/hardhat-runner/plugins/plugins.ts
Labels: status:triaging, no changeset needed

#4197 feat: Port Hardhat Node basic filters
  crates/rethnet/tests/cli.rs
  crates/rethnet_eth/src/remote.rs
  crates/rethnet_eth/src/remote/filter.rs
  crates/rethnet_eth/src/remote/methods.rs
  crates/rethnet_eth/tests/integration_tests.rs
  crates/rethnet_rpc_server/src/filter.rs
  crates/rethnet_rpc_server/src/lib.rs
  crates/rethnet_rpc_server/tests/integration_tests.rs
Labels: area:edr

#4219 feat: Impersonation of accounts
  crates/rethnet/tests/cli.rs
  crates/rethnet_rpc_server/src/lib.rs
  crates/rethnet_rpc_server/tests/integration_tests.rs
Labels: status:triaging, area:edr

#4225 Use version placeholder in flatten tests
  packages/hardhat-core/test/fixture-projects/flatten-task/contracts-pragma-different-directives/expected.sol
  packages/hardhat-core/test/fixture-projects/flatten-task/contracts-pragma-multiple-directives/expected.sol
  packages/hardhat-core/test/fixture-projects/flatten-task/contracts-pragma-same-directives/expected.sol
  packages/hardhat-core/test/fixture-projects/flatten-task/contracts-regex-spdx-licenses-and-pragma-directives/expected.sol
  packages/hardhat-core/test/fixture-projects/flatten-task/contracts-spdx-different-licenses/expected.sol
  packages/hardhat-core/test/fixture-projects/flatten-task/contracts-spdx-different-multiple-licenses/expected.sol
  packages/hardhat-core/test/fixture-projects/flatten-task/contracts-spdx-licenses-and-pragma-directives/expected.sol
  packages/hardhat-core/test/fixture-projects/flatten-task/contracts-spdx-same-licenses/expected.sol
  packages/hardhat-core/test/fixture-projects/flatten-task/contracts-spdx-same-multiple-licenses/expected.sol
  packages/hardhat-core/test/fixture-projects/flatten-task/contracts-task-flatten/expected.sol
Labels: status:ready, no changeset needed

#4216 Hardhat verify docs
  packages/hardhat-verify/README.md
  packages/hardhat-verify/src/internal/etherscan.ts
Labels: status:ready, no changeset needed

#4218 feat: Implement miscelaneous net web3 rpc methods
  crates/rethnet/tests/cli.rs
  crates/rethnet/tests/cli.rs.orig
  crates/rethnet_eth/src/remote/methods.rs
  crates/rethnet_eth/tests/integration_tests.rs
  crates/rethnet_rpc_server/Cargo.toml
  crates/rethnet_rpc_server/build.rs
  crates/rethnet_rpc_server/src/lib.rs
  crates/rethnet_rpc_server/tests/integration_tests.rs
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/web3.ts
Labels: status:triaging

#4226 Update plugins.ts
  docs/src/content/hardhat-runner/plugins/plugins.ts
Labels: status:triaging, no changeset needed

#4229 feat: adding new plugin `hardhat-gasless-deployer`
  docs/src/content/hardhat-runner/plugins/plugins.ts
Labels: status:triaging, no changeset needed

#4238 Adds the Chainstack Sepolia faucet to docs
  docs/src/content/tutorial/deploying-to-a-live-network.md
Labels: status:triaging, no changeset needed

#4250 Allow manually dispatching workflows
  .github/workflows/check-docs-site.yml
  .github/workflows/compile-with-typescript-v4.yml
  .github/workflows/hardhat-chai-matchers-ci.yml
  .github/workflows/hardhat-core-ci.yml
  .github/workflows/hardhat-ethers-ci.yml
  .github/workflows/hardhat-foundry-ci.yml
  .github/workflows/hardhat-ledger-ci.yml
  .github/workflows/hardhat-network-forking-ci.yml
  .github/workflows/hardhat-network-helpers-ci.yml
  .github/workflows/hardhat-shorthand-ci.yml
  .github/workflows/hardhat-solhint-ci.yml
  .github/workflows/hardhat-solpp-ci.yml
  .github/workflows/hardhat-toolbox-ci.yml
  .github/workflows/hardhat-truffle4-ci.yml
  .github/workflows/hardhat-truffle5-ci.yml
  .github/workflows/hardhat-verify-ci.yml
  .github/workflows/hardhat-vyper-ci.yml
  .github/workflows/hardhat-web3-ci.yml
  .github/workflows/hardhat-web3-legacy-ci.yml
  .github/workflows/lint.yml
Labels: status:ready, no changeset needed

#4241 feat: add Base network support
  .changeset/gorgeous-foxes-swim.md
  packages/hardhat-verify/src/internal/chain-config.ts
Labels: status:triaging

#4247 feat: add devcontainer setup for Hardhat + EDR
  .devcontainer/devcontainer.json
  scripts/setup.sh
Labels: area:edr

#4231 feat: strongly typed RPC log & receipt
  crates/rethnet/src/lib.rs
  crates/rethnet_eth/src/block.rs
  crates/rethnet_eth/src/block/detailed.rs
  crates/rethnet_eth/src/block/difficulty.rs
  crates/rethnet_eth/src/block/options.rs
  crates/rethnet_eth/src/lib.rs
  crates/rethnet_eth/src/log.rs
  crates/rethnet_eth/src/log/block.rs
  crates/rethnet_eth/src/log/filter.rs
  crates/rethnet_eth/src/log/receipt.rs
  crates/rethnet_eth/src/receipt.rs
  crates/rethnet_eth/src/receipt/block.rs
  crates/rethnet_eth/src/receipt/eip658.rs
  crates/rethnet_eth/src/receipt/transaction.rs
  crates/rethnet_eth/src/remote.rs
  crates/rethnet_eth/src/remote/client.rs
  crates/rethnet_eth/src/remote/eth.rs
  crates/rethnet_eth/src/remote/methods.rs
  crates/rethnet_eth/src/remote/serde_with_helpers.rs
  crates/rethnet_eth/src/serde.rs
  crates/rethnet_eth/src/transaction/detailed.rs
  crates/rethnet_eth/src/transaction/signed.rs
  crates/rethnet_evm/benches/state/database_commit.rs
  crates/rethnet_evm/src/block.rs
  crates/rethnet_evm/src/block/builder.rs
  crates/rethnet_evm/src/blockchain.rs
  crates/rethnet_evm/src/blockchain/forked.rs
  crates/rethnet_evm/src/blockchain/local.rs
  crates/rethnet_evm/src/blockchain/remote.rs
  crates/rethnet_evm/src/blockchain/storage/contiguous.rs
  crates/rethnet_evm/src/blockchain/storage/sparse.rs
  crates/rethnet_evm/src/miner.rs
  crates/rethnet_evm/src/runtime.rs
  crates/rethnet_evm/src/transaction.rs
  crates/rethnet_evm_napi/src/block.rs
  crates/rethnet_evm_napi/src/block/builder.rs
  crates/rethnet_evm_napi/src/blockchain.rs
  crates/rethnet_evm_napi/src/blockchain/js_blockchain.rs
  crates/rethnet_evm_napi/src/context.rs
  crates/rethnet_evm_napi/src/log.rs
  crates/rethnet_evm_napi/src/log/execution.rs
  crates/rethnet_evm_napi/src/receipt.rs
  crates/rethnet_evm_napi/src/state.rs
  crates/rethnet_evm_napi/src/transaction/result.rs
  crates/rethnet_rpc_server/src/config.rs
  crates/rethnet_rpc_server/src/hardhat_methods.rs
  crates/rethnet_rpc_server/src/lib.rs
  crates/rethnet_rpc_server/tests/integration_tests.rs
  packages/hardhat-core/src/internal/hardhat-network/provider/utils/convertToRethnet.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/block-builder/dual.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/dual.ts
Labels: status:triaging, area:edr

#4255 docs: add test page
  book/src/01_getting_started/03_test.md
  book/src/SUMMARY.md
Labels: area:edr

#4261 docs: contributing
  book/src/99_contributing.md
Labels: area:edr

#4262 docs: clarifications and spelling fixes
  book/src/01_getting_started/03_test.md
Labels: status:triaging, area:edr

#4221 feat: Instantiate blockchain and mempool in server
  crates/rethnet/Cargo.toml
  crates/rethnet/src/config.rs
  crates/rethnet/src/config/number.rs
  crates/rethnet/src/lib.rs
  crates/rethnet_eth/src/lib.rs
  crates/rethnet_rpc_server/src/config.rs
  crates/rethnet_rpc_server/src/filter.rs
  crates/rethnet_rpc_server/src/lib.rs
  crates/rethnet_rpc_server/tests/integration_tests.rs
Labels: area:edr

#4253 Add clarification about chai matchers without automine
  docs/src/content/hardhat-chai-matchers/docs/overview.md
Labels: status:ready, no changeset needed

#4265 Fix escaped double quote in vyper docs
  packages/hardhat-vyper/README.md
Labels: status:ready, no changeset needed

#4252 docs: add automated macOS and manual setup instructions
  .gitignore
  Brewfile
  book/src/01_getting_started/01_setup.md
Labels: status:triaging

#4269 fix: `U256OrUsize` always being deserialized as U256
  crates/rethnet_eth/src/remote/methods.rs
Labels: type:bug, area:edr

#4268 Remove node_modules from remapping results
  .changeset/tasty-monkeys-talk.md
  packages/hardhat-foundry/src/foundry.ts
Labels: status:ready

#4277 Add autoassign workflow
  .github/workflows/autoassign-issues.yml
Labels: status:ready, no changeset needed

#4205 HH Network config reference: Correct formatting on `coinbase`
  docs/src/content/hardhat-network/docs/reference/index.md
Labels: status:triaging, no changeset needed

#4244 fix: use node v18 for hardhat-ledger
  .github/workflows/hardhat-ledger-ci.yml
  packages/hardhat-ledger/package.json
Labels: status:triaging, area:edr

#4272 refactor(evm): remove sync primitives
  crates/rethnet_evm/src/block/builder.rs
  crates/rethnet_evm/src/evm.rs
  crates/rethnet_evm/src/lib.rs
  crates/rethnet_evm/src/miner.rs
  crates/rethnet_evm/src/runtime.rs
  crates/rethnet_evm/src/state/layered/changes.rs
  crates/rethnet_evm_napi/src/block/builder.rs
  crates/rethnet_evm_napi/src/lib.rs
  crates/rethnet_evm_napi/src/miner.rs
  crates/rethnet_evm_napi/src/runtime.rs
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/block-builder/rethnet.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/rethnet.ts
Labels: area:edr

#4284 Fix cron in test-slow-imports-rule workflow
  .github/workflows/test-slow-imports-rule.yml
Labels: status:ready, no changeset needed

#4279 Fix: artifactExists returns false for missing artifacts
  .changeset/ten-trees-smoke.md
  packages/hardhat-core/src/internal/artifacts.ts
  packages/hardhat-core/src/utils/contract-names.ts
  packages/hardhat-core/test/internal/artifacts.ts
  packages/hardhat-verify/src/index.ts
Labels: status:ready

#4287 Add .emit clarification
  packages/hardhat-chai-matchers/README.md
Labels: status:ready, no changeset needed

#4283 Add extra information to hh troubleshooting section
  docs/src/content/hardhat-runner/docs/guides/command-line-completion.md
Labels: status:ready, no changeset needed

#4246 1 new plugin, 1 plugin upgraded
  docs/src/content/hardhat-runner/plugins/plugins.ts
Labels: status:triaging, no changeset needed

#4295 refactor: change allow dead code to underscore prefix for tempdir
  crates/rethnet_eth/src/remote/client.rs
  crates/rethnet_evm/benches/state/util.rs
  crates/rethnet_evm/src/state/fork.rs
  crates/rethnet_rpc_server/tests/integration_tests.rs
Labels: status:triaging

#4293 Add explicit any type to some undici responses
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/call.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/estimateGas.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/sendRawTransaction.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/sendTransaction.ts
  packages/hardhat-verify/src/internal/etherscan.ts
  yarn.lock
Labels: status:ready, no changeset needed

#4258 Improve error message when a directory is imported
  .changeset/tricky-trees-shop.md
  packages/hardhat-core/src/builtin-tasks/compile.ts
  packages/hardhat-core/src/internal/core/errors-list.ts
  packages/hardhat-core/src/internal/solidity/resolver.ts
  packages/hardhat-core/test/builtin-tasks/compile.ts
  packages/hardhat-core/test/fixture-projects/compilation-import-folder-from-module/contracts/A.sol
  packages/hardhat-core/test/fixture-projects/compilation-import-folder-from-module/hardhat.config.js
  packages/hardhat-core/test/fixture-projects/compilation-import-folder-from-module/node_modules/some-lib/package.json
  packages/hardhat-core/test/fixture-projects/compilation-import-folder-from-module/package.json
  packages/hardhat-core/test/fixture-projects/compilation-import-folder-from-path/contracts/A.sol
  packages/hardhat-core/test/fixture-projects/compilation-import-folder-from-path/dir/A.sol
  packages/hardhat-core/test/fixture-projects/compilation-import-folder-from-path/hardhat.config.js
  packages/hardhat-core/test/fixture-projects/compilation-import-non-existing-file-from-module/contracts/A.sol
  packages/hardhat-core/test/fixture-projects/compilation-import-non-existing-file-from-module/hardhat.config.js
  packages/hardhat-core/test/fixture-projects/compilation-import-non-existing-file-from-module/node_modules/some-lib/package.json
  packages/hardhat-core/test/fixture-projects/compilation-import-non-existing-file-from-module/package.json
  packages/hardhat-core/test/fixture-projects/compilation-import-non-existing-file-from-path/contracts/A.sol
  packages/hardhat-core/test/fixture-projects/compilation-import-non-existing-file-from-path/hardhat.config.js
  packages/hardhat-core/test/internal/solidity/resolver.ts
Labels: status:ready

#4296 Update Distributed Lab plugins
  docs/src/content/hardhat-runner/plugins/plugins.ts
Labels: status:triaging, no changeset needed

#4286 Elongated memory data for debug_traceTransaction
  .changeset/heavy-pumas-admire.md
  packages/hardhat-core/src/internal/hardhat-network/stack-traces/vm-debug-tracer.ts
  packages/hardhat-core/test/fixture-debug-traces/elongatedMemoryRegressionTestTrace.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/debug.ts
Labels: status:ready

#4299 refactor: move get_alchemy_url to test utils
  crates/rethnet_eth/src/remote/client.rs
  crates/rethnet_evm/Cargo.toml
  crates/rethnet_evm/src/state/fork.rs
  crates/rethnet_test_utils/src/env.rs
  crates/rethnet_test_utils/src/lib.rs
Labels: area:edr

#4302 fix: transaction type field
  crates/rethnet_eth/src/remote/eth.rs
Labels: area:edr

#4301 fix: next base fee calculation
  crates/rethnet_eth/src/block.rs
  crates/rethnet_evm/src/miner.rs
Labels: area:edr

#4303 fix: broken CI tests
  .github/workflows/hardhat-core-ci.yml
  crates/rethnet_eth/src/remote/eth.rs
  packages/hardhat-core/test/internal/hardhat-network/stack-traces/test.ts
Labels: area:edr

#4309 misc: submit Cargo.lock
  .github/workflows/hardhat-core-ci.yml
  .gitignore
  Cargo.lock
Labels: area:edr

#4304 fix: don't run full blocks in dual mode
  .github/workflows/hardhat-core-ci.yml
  packages/hardhat-core/package.json
  packages/hardhat-core/test/internal/hardhat-network/provider/node.ts
Labels: area:edr

#4294 fix: make EDR RPC cache key unique
  crates/rethnet_eth/src/remote.rs
  crates/rethnet_eth/src/remote/cacheable_method_invocation.rs
  crates/rethnet_eth/src/remote/client.rs
Labels: area:edr

#4270 feat: cache rpc per chain id instead of per provider
  .cargo-husky/hooks/pre-commit
  .github/workflows/hardhat-core-ci.yml
  Cargo.lock
  book/src/01_getting_started/03_test.md
  crates/rethnet_eth/Cargo.toml
  crates/rethnet_eth/src/remote/client.rs
  crates/rethnet_test_utils/src/env.rs
Labels: area:edr

#4245 added Date instances in increaseTo.js in network-helper and its relev…
  .changeset/tender-eyes-draw.md
  packages/hardhat-network-helpers/src/helpers/time/increaseTo.ts
  packages/hardhat-network-helpers/test/helpers/time/increaseTo.ts
Labels: status:triaging

#4318 chore(hooks): simplify pre-commit hooks
  .cargo-husky/hooks/pre-commit
Labels: area:edr

#4315 feat: cache batch requests per method call
  crates/rethnet_eth/Cargo.toml
  crates/rethnet_eth/src/remote/cacheable_method_invocation.rs
  crates/rethnet_eth/src/remote/client.rs
Labels: area:edr

#4325 fix: rpc result serde and avoid rate limits
  Cargo.lock
  crates/rethnet_defaults/src/lib.rs
  crates/rethnet_eth/Cargo.toml
  crates/rethnet_eth/src/receipt.rs
  crates/rethnet_eth/src/remote/client.rs
  crates/rethnet_eth/src/remote/eth.rs
  crates/rethnet_eth/src/serde.rs
  crates/rethnet_eth/tests/receipt.rs
  crates/rethnet_evm/Cargo.toml
  crates/rethnet_evm/benches/state/database_commit.rs
  crates/rethnet_evm/src/blockchain/remote.rs
  crates/rethnet_evm/tests/blockchain.rs
Labels: type:bug, area:edr

#4324 bump: revm
  Cargo.lock
  crates/rethnet/Cargo.toml
  crates/rethnet_eth/Cargo.toml
  crates/rethnet_eth/src/remote/client.rs
  crates/rethnet_eth/src/remote/eth/eip712.rs
  crates/rethnet_eth/src/spec.rs
  crates/rethnet_eth/src/state.rs
  crates/rethnet_eth/tests/integration_tests.rs
  crates/rethnet_evm/Cargo.toml
  crates/rethnet_evm/benches/state/database_commit.rs
  crates/rethnet_evm/benches/state/state_debug.rs
  crates/rethnet_evm/benches/state/state_ref.rs
  crates/rethnet_evm/benches/state/util.rs
  crates/rethnet_evm/src/blockchain/forked.rs
  crates/rethnet_evm/src/blockchain/storage/contiguous.rs
  crates/rethnet_evm/src/blockchain/storage/sparse.rs
  crates/rethnet_evm/src/collections/shared_map.rs
  crates/rethnet_evm/src/lib.rs
  crates/rethnet_evm/src/mempool.rs
  crates/rethnet_evm/src/signer.rs
  crates/rethnet_evm/src/state/fork.rs
  crates/rethnet_evm/src/state/hybrid.rs
  crates/rethnet_evm/src/state/layered.rs
  crates/rethnet_evm/src/state/layered/changes.rs
  crates/rethnet_evm/src/state/remote/cached.rs
  crates/rethnet_evm/src/state/trie.rs
  crates/rethnet_evm/src/state/trie/account.rs
  crates/rethnet_evm_napi/src/account.rs
  crates/rethnet_evm_napi/src/blockchain/js_blockchain.rs
  crates/rethnet_evm_napi/src/config.rs
  crates/rethnet_evm_napi/src/state.rs
  crates/rethnet_rpc_server/Cargo.toml
  crates/rethnet_rpc_server/src/hardhat_methods/add_compilation_result.rs
  crates/rethnet_rpc_server/src/hardhat_methods/reset.rs
  crates/rethnet_rpc_server/src/lib.rs
  crates/rethnet_rpc_server/tests/integration_tests.rs
Labels: area:edr

#4328 feat: retry for rpc client
  Cargo.lock
  crates/rethnet_eth/Cargo.toml
  crates/rethnet_eth/src/remote/client.rs
Labels: area:edr

#4321 fix: hardhat fork blockchain transaction type
  packages/hardhat-core/src/internal/hardhat-network/provider/fork/ForkBlockchain.ts
Labels: status:triaging

#4331 Add enableTransientStorage option
  .changeset/slow-students-deny.md
  packages/hardhat-core/package.json
  packages/hardhat-core/src/internal/core/providers/construction.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/node-types.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/node.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/provider.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/utils/makeCommon.ts
  packages/hardhat-core/src/types/config.ts
  packages/hardhat-core/test/internal/hardhat-network/helpers/useProvider.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/debug.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/node.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/utils/runFullBlock.ts
  packages/hardhat-ledger/package.json
  yarn.lock
Labels: status:ready

#4316 Support state overrides in eth_call
  .changeset/chilled-bats-taste.md
  docs/src/content/hardhat-network/docs/reference/index.md
  packages/hardhat-core/src/internal/core/jsonrpc/types/base-types.ts
  packages/hardhat-core/src/internal/core/jsonrpc/types/input/callRequest.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/modules/eth.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/node.ts
  packages/hardhat-core/test/internal/hardhat-network/helpers/contracts.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/call.ts
Labels: status:ready

#4329 fix: hardhat fork blockchain transaction type
  .changeset/witty-brooms-accept.md
  packages/hardhat-core/src/internal/hardhat-network/provider/fork/ForkBlockchain.ts
Labels: status:ready

#4320 hardhat-viem initial implementation supporting client getters
  packages/hardhat-viem/.eslintignore
  packages/hardhat-viem/.eslintrc.js
  packages/hardhat-viem/.gitignore
  packages/hardhat-viem/.mocharc.json
  packages/hardhat-viem/.prettierignore
  packages/hardhat-viem/LICENSE
  packages/hardhat-viem/README.md
  packages/hardhat-viem/package.json
  packages/hardhat-viem/src/index.ts
  packages/hardhat-viem/src/internal/accounts.ts
  packages/hardhat-viem/src/internal/chains.ts
  packages/hardhat-viem/src/internal/clients.ts
  packages/hardhat-viem/src/internal/errors.ts
  packages/hardhat-viem/src/internal/type-extensions.ts
  packages/hardhat-viem/src/internal/types.ts
  packages/hardhat-viem/src/tsconfig.json
  packages/hardhat-viem/test/.eslintrc.js
  packages/hardhat-viem/test/chains.ts
  packages/hardhat-viem/test/clients.ts
  packages/hardhat-viem/test/fixture-projects/hardhat-project/contracts/Lock.sol
  packages/hardhat-viem/test/fixture-projects/hardhat-project/hardhat.config.js
  packages/hardhat-viem/test/helpers.ts
  packages/hardhat-viem/test/integration.ts
  packages/hardhat-viem/test/mocks/provider.ts
  packages/hardhat-viem/test/setup.ts
  packages/hardhat-viem/tsconfig.json
  yarn.lock
Labels: status:ready, no changeset needed

#4323 feat: remappings support rework on core and hardhat-foundry plugin
  .changeset/chilled-schools-grab.md
  .changeset/rare-eels-wink.md
  packages/hardhat-core/src/builtin-tasks/compile.ts
  packages/hardhat-core/src/builtin-tasks/task-names.ts
  packages/hardhat-core/src/internal/core/errors-list.ts
  packages/hardhat-core/src/internal/solidity/dependencyGraph.ts
  packages/hardhat-core/src/internal/solidity/resolver.ts
  packages/hardhat-core/src/utils/remappings.ts
  packages/hardhat-core/test/builtin-tasks/compile.ts
  packages/hardhat-core/test/fixture-projects/compilation-ambiguous-remappings/.gitignore
  packages/hardhat-core/test/fixture-projects/compilation-ambiguous-remappings/contracts/A.sol
  packages/hardhat-core/test/fixture-projects/compilation-ambiguous-remappings/hardhat.config.js
  packages/hardhat-core/test/fixture-projects/compilation-ambiguous-remappings/node_modules/foo/contracts/Foo.sol
  packages/hardhat-core/test/fixture-projects/compilation-ambiguous-remappings/node_modules/foo/package.json
  packages/hardhat-core/test/fixture-projects/compilation-remappings/.gitignore
  packages/hardhat-core/test/fixture-projects/compilation-remappings/contracts/A.sol
  packages/hardhat-core/test/fixture-projects/compilation-remappings/hardhat.config.js
  packages/hardhat-core/test/fixture-projects/compilation-remappings/node_modules/foo/contracts/Foo.sol
  packages/hardhat-core/test/fixture-projects/compilation-remappings/node_modules/foo/package.json
  packages/hardhat-core/test/internal/solidity/dependencyGraph.ts
  packages/hardhat-core/test/internal/solidity/helpers.ts
  packages/hardhat-core/test/internal/solidity/resolver.ts
  packages/hardhat-core/test/utils/remappings.ts
  packages/hardhat-foundry/src/foundry.ts
  packages/hardhat-foundry/src/index.ts
  packages/hardhat-foundry/test/dummy.ts
  packages/hardhat-foundry/test/foundry.ts
Labels: status:triaging

#4334 Bump hardhat-foundry's peer dependency on Hardhat
  .changeset/honest-mayflies-worry.md
  packages/hardhat-foundry/package.json
Labels: status:ready

#4337 fix: extraData serde
  crates/rethnet_eth/src/remote/eth.rs
Labels: area:edr

#4339 improvement: simplify block nonce encoding
  crates/rethnet_eth/src/block.rs
  crates/rethnet_evm/src/blockchain/local.rs
  crates/rethnet_evm/src/miner.rs
Labels: area:edr

#4338 fix: use insertion ordering for MemPool
  Cargo.lock
  crates/rethnet_evm/Cargo.toml
  crates/rethnet_evm/src/mempool.rs
Labels: area:edr

#4333 fix: disable in-memory cache for unsafe block number
  crates/rethnet_eth/src/block.rs
  crates/rethnet_eth/src/block/reorg.rs
  crates/rethnet_eth/src/remote/cacheable_method_invocation.rs
  crates/rethnet_eth/src/remote/client.rs
  crates/rethnet_evm/src/blockchain/forked.rs
  crates/rethnet_evm/src/blockchain/remote.rs
  crates/rethnet_evm/src/state/remote.rs
  crates/rethnet_evm/src/state/remote/cached.rs
Labels: status:triaging, area:edr

#4344 Fix clippy
  crates/rethnet_evm/src/blockchain/remote.rs
Labels: status:triaging

#4341 feat(blockchain): add reservation of blocks
  crates/rethnet_evm/src/blockchain.rs
  crates/rethnet_evm/src/blockchain/forked.rs
  crates/rethnet_evm/src/blockchain/local.rs
  crates/rethnet_evm/src/blockchain/storage.rs
  crates/rethnet_evm/src/blockchain/storage/reservable.rs
  crates/rethnet_evm/src/blockchain/storage/sparse.rs
  crates/rethnet_evm_napi/src/blockchain.rs
  crates/rethnet_evm_napi/src/blockchain/js_blockchain.rs
Labels: area:edr

#4347 refactor: make blockchain traits async
  Cargo.lock
  crates/rethnet_eth/src/remote/client.rs
  crates/rethnet_evm/Cargo.toml
  crates/rethnet_evm/src/blockchain.rs
  crates/rethnet_evm/src/blockchain/forked.rs
  crates/rethnet_evm/src/blockchain/local.rs
  crates/rethnet_evm/src/blockchain/remote.rs
  crates/rethnet_evm/src/miner.rs
  crates/rethnet_evm/src/runtime.rs
  crates/rethnet_evm/tests/blockchain.rs
  crates/rethnet_evm_napi/Cargo.toml
  crates/rethnet_evm_napi/src/blockchain.rs
  crates/rethnet_evm_napi/src/blockchain/js_blockchain.rs
  crates/rethnet_evm_napi/src/miner.rs
  crates/rethnet_evm_napi/src/runtime.rs
  crates/rethnet_rpc_server/src/filter.rs
  crates/rethnet_rpc_server/src/lib.rs
Labels: area:edr

#4352 docs: improve testing instructions
  book/src/01_getting_started/03_test.md
Labels: area:edr
