Repository NomicFoundation/hardhat, pull requests merged in 2023-06, with the labels that each got.

#3953 `DatabaseCommit` worst case benchmarks
  crates/rethnet_eth/src/remote.rs
  crates/rethnet_eth/src/remote/eth.rs
  crates/rethnet_evm/benches/fixtures/accounts_changed_in_mainnet_block_17295357.json
  crates/rethnet_evm/benches/state.rs
  crates/rethnet_evm/benches/state_debug.rs
  crates/rethnet_evm/benches/state_history.rs
  crates/rethnet_evm/benches/util.rs
  packages/hardhat-core/scripts/test-run-forked-block.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/utils/runFullBlock.ts
Labels: status:triaging

#3970 Use more future-proof type imports from ethers
  packages/hardhat-ethers/src/internal/ethers-utils.ts
  packages/hardhat-ethers/src/internal/hardhat-ethers-provider.ts
  packages/hardhat-ethers/src/signers.ts
Labels: status:triaging, no changeset needed

#3982 Update LICENSE
  packages/hardhat-core/LICENSE
Labels: status:triaging

#3983 Update LICENSE
  packages/hardhat-chai-matchers/LICENSE
Labels: status:triaging

#3985 Update LICENSE
  packages/hardhat-network-helpers/LICENSE
Labels: status:triaging

#3986 Update LICENSE
  packages/hardhat-shorthand/LICENSE
Labels: status:triaging

#3987 Update LICENSE
  packages/hardhat-solhint/LICENSE
Labels: status:triaging

#3988 Update LICENSE
  packages/hardhat-solpp/LICENSE
Labels: status:triaging

#3990 Update LICENSE
  packages/hardhat-truffle4/LICENSE
Labels: status:triaging

#3991 Update LICENSE
  packages/hardhat-truffle5/LICENSE
Labels: status:triaging

#3989 Update LICENSE
  packages/hardhat-toolbox/LICENSE
Labels: status:triaging

#3992 Update LICENSE
  packages/hardhat-verify/LICENSE
Labels: status:triaging

#3993 Update LICENSE
  packages/hardhat-vyper/LICENSE
Labels: status:triaging

#3994 Update LICENSE
  packages/hardhat-web3-legacy/LICENSE
Labels: status:triaging

#3995 Update LICENSE
  packages/hardhat-web3/LICENSE
Labels: status:triaging

#3967 Rethnet: Implement `eth_` requests for JSON-RPC server
  crates/rethnet_eth/src/remote.rs
  crates/rethnet_eth/src/remote/client.rs
  crates/rethnet_eth/src/remote/eth.rs
  crates/rethnet_eth/src/remote/jsonrpc.rs
Labels: status:triaging

#3996 Rename error class & avoid compiling
  .changeset/cuddly-grapes-wink.md
  packages/hardhat-verify/src/errors.ts
  packages/hardhat-verify/src/etherscan.ts
  packages/hardhat-verify/src/index.ts
  packages/hardhat-verify/test/integration/index.ts
  packages/hardhat-verify/test/unit/index.ts
Labels: status:triaging

#4005 Pin `web3` version in installation guides
  docs/src/content/hardhat-runner/docs/other-guides/truffle-testing.md
  packages/hardhat-truffle5/README.md
  packages/hardhat-web3/README.md
Labels: status:triaging

#4007 Fix waitForDeployment in non-automined networks
  .changeset/fluffy-walls-sip.md
  packages/hardhat-ethers/package.json
  packages/hardhat-ethers/src/internal/hardhat-ethers-provider.ts
  packages/hardhat-ethers/test/contracts.ts
  packages/hardhat-ethers/test/helpers.ts
Labels: status:triaging

#3999 fix aurora browser urls
  .changeset/polite-mugs-cry.m
  packages/hardhat-verify/src/chain-config.ts
Labels: status:triaging

#4011 This removes an useless array
  packages/hardhat-core/src/builtin-tasks/compile.ts
Labels: status:triaging

#4018 Add HARDHAT_DISABLE_TELEMETRY_PROMPT envvar
  .changeset/fluffy-papayas-reflect.md
  docs/src/content/hardhat-runner/docs/advanced/scripts.md
  docs/src/content/hardhat-runner/docs/reference/_dirinfo.yaml
  docs/src/content/hardhat-runner/docs/reference/environment-variables.md
  packages/hardhat-core/src/internal/cli/cli.ts
  packages/hardhat-core/src/internal/cli/project-creation.ts
Labels: status:triaging

#4021 Implement JSON-RPC server library
  crates/rethnet_eth/src/remote.rs
  crates/rethnet_eth/src/remote/client.rs
  crates/rethnet_eth/src/remote/jsonrpc.rs
  crates/rethnet_rpc_server/Cargo.toml
  crates/rethnet_rpc_server/src/lib.rs
  crates/rethnet_rpc_server/src/methods.rs
Labels: status:triaging

#4030 hardhat-verify: fix list supported networks issue
  .changeset/silver-meals-tan.m
  packages/hardhat-verify/src/index.ts
  packages/hardhat-verify/src/task-names.ts
  packages/hardhat-verify/test/integration/index.ts
  packages/hardhat-verify/test/unit/index.ts
Labels: status:triaging

#3944 feat: implement block builder to spec
  crates/rethnet_eth/src/access_list.rs
  crates/rethnet_eth/src/block.rs
  crates/rethnet_eth/src/lib.rs
  crates/rethnet_eth/src/log.rs
  crates/rethnet_eth/src/receipt.rs
  crates/rethnet_eth/src/receipt/eip658.rs
  crates/rethnet_eth/src/remote/withdrawal.rs
  crates/rethnet_eth/src/transaction.rs
  crates/rethnet_eth/src/transaction/kind.rs
  crates/rethnet_eth/src/transaction/request.rs
  crates/rethnet_eth/src/transaction/request/eip1559.rs
  crates/rethnet_eth/src/transaction/request/eip2930.rs
  crates/rethnet_eth/src/transaction/request/legacy.rs
  crates/rethnet_eth/src/transaction/signed.rs
  crates/rethnet_eth/src/transaction/signed/eip1559.rs
  crates/rethnet_eth/src/transaction/signed/eip2930.rs
  crates/rethnet_eth/src/transaction/signed/legacy.rs
  crates/rethnet_eth/src/trie.rs
  crates/rethnet_eth/src/utils.rs
  crates/rethnet_evm/src/block.rs
  crates/rethnet_evm/src/block/builder.rs
  crates/rethnet_evm/src/block/difficulty.rs
  crates/rethnet_evm/src/lib.rs
  crates/rethnet_evm/src/runtime.rs
  crates/rethnet_evm/src/state/trie/account.rs
  crates/rethnet_evm/src/transaction.rs
  crates/rethnet_evm_napi/src/access_list.rs
  crates/rethnet_evm_napi/src/block.rs
  crates/rethnet_evm_napi/src/block/builder.rs
  crates/rethnet_evm_napi/src/cast.rs
  crates/rethnet_evm_napi/src/config.rs
  crates/rethnet_evm_napi/src/lib.rs
  crates/rethnet_evm_napi/src/runtime.rs
  crates/rethnet_evm_napi/src/signature.rs
  crates/rethnet_evm_napi/src/transaction.rs
  crates/rethnet_evm_napi/src/transaction/pending.rs
  crates/rethnet_evm_napi/src/transaction/request.rs
  crates/rethnet_evm_napi/src/transaction/signed.rs
  crates/rethnet_evm_napi/src/transaction/signed/eip1559.rs
  crates/rethnet_evm_napi/src/transaction/signed/eip2930.rs
  crates/rethnet_evm_napi/src/transaction/signed/legacy.rs
  packages/hardhat-core/src/internal/hardhat-network/provider/node.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/utils/assertions.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/utils/convertToRethnet.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/block-builder.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/block-builder/dual.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/block-builder/hardhat.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/block-builder/rethnet.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/dual.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/ethereumjs.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/rethnet.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/vm-adapter.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/hardforks.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/utils/runFullBlock.ts
  packages/hardhat-core/test/internal/hardhat-network/stack-traces/execution.ts
Labels: status:triaging, area:rethnet

#3965 Make console.sol assembly "memory-safe"
  .changeset/sharp-books-hide.md
  packages/hardhat-core/console.sol
  packages/hardhat-core/scripts/console-library-generator.js
Labels: status:triaging

#4042 Hardhat-verify: more generic success message
  .changeset/tidy-points-arrive.md
  packages/hardhat-verify/src/index.ts
  packages/hardhat-verify/test/integration/index.ts
Labels: status:triaging

#4041 Fix broken link to hardhat-ethers
  docs/redirects.config.js
  packages/hardhat-toolbox/README.md
Labels: status:triaging, no changeset needed

#4048 Add test for memory-safe console.sol
  packages/hardhat-core/test/console/console.ts
  packages/hardhat-core/test/fixture-projects/memory-safe-console/.gitignore
  packages/hardhat-core/test/fixture-projects/memory-safe-console/contracts/Test.sol
  packages/hardhat-core/test/fixture-projects/memory-safe-console/hardhat.config.js
  packages/hardhat-core/test/fixture-projects/memory-safe-console/package.json
Labels: status:triaging, no changeset needed

#4037 misc: Rethnet state benchmark tweaks
  .cargo-husky/hooks/pre-commit
  .github/workflows/hardhat-core-ci.yml
  crates/rethnet_evm/Cargo.toml
  crates/rethnet_evm/benches/state/database_commit.rs
  crates/rethnet_evm/benches/state/fixtures/accounts_changed_in_mainnet_block_17295357.json
  crates/rethnet_evm/benches/state/state_debug.rs
  crates/rethnet_evm/benches/state/state_history.rs
  crates/rethnet_evm/benches/state/state_history_block_context.rs
  crates/rethnet_evm/benches/state/state_ref.rs
  crates/rethnet_evm/benches/state/util.rs
Labels: status:triaging

#4008 Ledger Wallet provider package
  .changeset/mean-crews-wait.md
  .github/workflows/hardhat-ledger-ci.yml
  config/eslint/eslintrc.js
  docs/src/content/hardhat-runner/docs/advanced/building-plugins.md
  docs/src/content/hardhat-runner/plugins/_dirinfo.yaml
  docs/src/content/hardhat-runner/plugins/plugins.ts
  package.json
  packages/hardhat-core/src/builtin-tasks/node.ts
  packages/hardhat-core/src/internal/cli/cli.ts
  packages/hardhat-core/src/internal/context.ts
  packages/hardhat-core/src/internal/core/config/config-env.ts
  packages/hardhat-core/src/internal/core/config/extenders.ts
  packages/hardhat-core/src/internal/core/errors-list.ts
  packages/hardhat-core/src/internal/core/providers/construction.ts
  packages/hardhat-core/src/internal/core/providers/lazy-initialization.ts
  packages/hardhat-core/src/internal/core/providers/wrapper.ts
  packages/hardhat-core/src/internal/core/runtime-environment.ts
  packages/hardhat-core/src/internal/lib/hardhat-lib.ts
  packages/hardhat-core/src/plugins.ts
  packages/hardhat-core/src/register.ts
  packages/hardhat-core/src/types/runtime.ts
  packages/hardhat-core/test/internal/context.ts
  packages/hardhat-core/test/internal/core/providers/construction.ts
  packages/hardhat-core/test/internal/core/providers/lazy-initialization.ts
  packages/hardhat-core/test/internal/core/providers/mocks.ts
  packages/hardhat-core/test/internal/core/providers/wrapper.ts
  packages/hardhat-core/test/internal/core/runtime-environment.ts
  packages/hardhat-ledger/.eslintrc.js
  packages/hardhat-ledger/.gitignore
  packages/hardhat-ledger/.mocharc.json
  packages/hardhat-ledger/.prettierignore
  packages/hardhat-ledger/LICENSE
  packages/hardhat-ledger/README.md
  packages/hardhat-ledger/package.json
  packages/hardhat-ledger/src/errors.ts
  packages/hardhat-ledger/src/index.ts
  packages/hardhat-ledger/src/internal/cache.ts
  packages/hardhat-ledger/src/internal/create-ledger-provider.ts
  packages/hardhat-ledger/src/internal/utils.ts
  packages/hardhat-ledger/src/internal/with-spinners.ts
  packages/hardhat-ledger/src/internal/wrap-transport.ts
  packages/hardhat-ledger/src/provider.ts
  packages/hardhat-ledger/src/type-extensions.ts
  packages/hardhat-ledger/src/types.ts
  packages/hardhat-ledger/test/.eslintrc.js
  packages/hardhat-ledger/test/errors.ts
  packages/hardhat-ledger/test/internal/cache.ts
  packages/hardhat-ledger/test/internal/create-ledger-provider.ts
  packages/hardhat-ledger/test/internal/utils.ts
  packages/hardhat-ledger/test/internal/with-spinners.ts
  packages/hardhat-ledger/test/mocks.ts
  packages/hardhat-ledger/test/provider.ts
  packages/hardhat-ledger/tsconfig.json
  yarn.lock
Labels: status:triaging

#4033 Google Analytics - Migrate UA to GA4
  .changeset/hungry-horses-hug.md
  packages/hardhat-core/package.json
  packages/hardhat-core/src/internal/cli/analytics.ts
  packages/hardhat-core/src/internal/cli/cli.ts
  yarn.lock
Labels: status:triaging

#4054 chore: bump Rust to 1.70
  crates/rethnet_eth/src/remote/client.rs
  rust-toolchain
Labels: type:chore, status:triaging, area:rethnet

#4056 Add a prefix to the ledger spinner messages
  packages/hardhat-ledger/src/internal/with-spinners.ts
Labels: status:triaging, no changeset needed

#4049 Remove compilation artifacts in the hardhat-core/clean script
  packages/hardhat-core/package.json
Labels: status:triaging, no changeset needed

#4061 [hardhat-foundry] Fix cached value that was set asynchronously
  .changeset/heavy-dryers-film.md
  packages/hardhat-foundry/src/foundry.ts
Labels: status:ready

#4066 chore: migrate to auguwu clippy action
  .github/workflows/hardhat-core-ci.yml
Labels: type:chore, status:triaging, area:rethnet

#4068 ♻️ Remove Deprecated Test Networks from `hardhat-verify`
  .changeset/grumpy-pigs-complain.md
  packages/hardhat-verify/src/chain-config.ts
  packages/hardhat-verify/test/unit/config.ts
Labels: status:triaging

#4071 Add support for `contract.on`
  .changeset/three-yaks-reply.md
  packages/hardhat-ethers/package.json
  packages/hardhat-ethers/src/internal/errors.ts
  packages/hardhat-ethers/src/internal/hardhat-ethers-provider.ts
  packages/hardhat-ethers/test/contracts.ts
  packages/hardhat-ethers/test/helpers.ts
  packages/hardhat-ethers/test/provider-events.ts
  yarn.lock
Labels: status:ready

#4075 Consume downloads instead of piping them
  .changeset/tricky-parents-warn.md
  packages/hardhat-core/src/internal/util/download.ts
Labels: status:ready

#4076 Add tests for provider error messages
  packages/hardhat-core/test/internal/core/providers/errors.ts
  packages/hardhat-ethers/test/error-messages.ts
  packages/hardhat-ethers/test/fixture-projects/error-messages/.gitignore
  packages/hardhat-ethers/test/fixture-projects/error-messages/contracts/Contract.sol
  packages/hardhat-ethers/test/fixture-projects/error-messages/hardhat.config.js
Labels: status:ready, no changeset needed

#4086 Add support for solc 0.8.19 and 0.8.20
  .changeset/two-ants-allow.md
  docs/src/content/hardhat-runner/docs/advanced/create-task.md
  docs/src/content/hardhat-runner/docs/advanced/using-esm.md
  docs/src/content/hardhat-runner/docs/config/index.md
  docs/src/content/hardhat-runner/docs/getting-started/index.md
  docs/src/content/hardhat-runner/docs/guides/compile-contracts.md
  docs/src/content/hardhat-runner/docs/guides/project-setup.md
  docs/src/content/hardhat-runner/docs/other-guides/waffle-testing.md
  docs/src/content/hardhat-runner/docs/reference/solidity-support.md
  docs/src/content/tutorial/creating-a-new-hardhat-project.md
  docs/src/content/tutorial/debugging-with-hardhat-network.md
  docs/src/content/tutorial/deploying-to-a-live-network.md
  docs/src/content/tutorial/writing-and-compiling-contracts.md
  docs/src/model/markdown.tsx
  packages/hardhat-core/sample-projects/javascript-esm/hardhat.config.cjs
  packages/hardhat-core/sample-projects/javascript/hardhat.config.js
  packages/hardhat-core/sample-projects/typescript/hardhat.config.ts
  packages/hardhat-core/src/internal/cli/project-creation.ts
  packages/hardhat-core/src/internal/hardhat-network/stack-traces/constants.ts
  packages/hardhat-core/src/internal/hardhat-network/stack-traces/solidityTracer.ts
  packages/hardhat-core/test/fixture-projects/solidity-config-warnings/multiple-unsupported-solc.js
  packages/hardhat-core/test/fixture-projects/solidity-config-warnings/unsupported-new-solc.js
  packages/hardhat-core/test/fixture-projects/solidity-config-warnings/unsupported-solc-in-override.js
  packages/hardhat-core/test/internal/hardhat-network/stack-traces/compilers-list.ts
Labels: status:ready
