Repository NomicFoundation/hardhat, pull requests merged in 2023-01, with the labels that each got.

#3537 Add status:triaging to pull requests too
  .github/workflows/add-label-to-new-issue.yml
Labels: status:triaging

#3543 Use infura in test suite
  .github/workflows/test-recent-mainnet-block.yml
  docs/src/content/hardhat-network/docs/guides/forking-other-networks.md
  docs/src/content/hardhat-runner/docs/guides/verifying.md
  docs/src/content/tutorial/deploying-to-a-live-network.md
  docs/src/content/tutorial/final-thoughts.md
  packages/hardhat-core/scripts/test-recent-mainnet-block.ts
  packages/hardhat-core/test/fixture-projects/hardhat-network-fork-from-old-block/hardhat.config.js
  packages/hardhat-core/test/fixture-projects/hardhat-network-fork-tangerine-whistle/hardhat.config.js
  packages/hardhat-core/test/internal/hardhat-network/helpers/providers.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/baseFeePerGas.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/fork/ForkBlockchain.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/fork/ForkStateManager.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/forked-provider.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/hardhat-network-options.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/interval-mining-provider.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/debug.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/getTransactionByHash.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/hardhat.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/node.ts
Labels: status:triaging

#3073 Add changeset check
  .github/workflows/check-changeset-added.yml
Labels: no changeset needed

#3558 Remove solidity survey message
  .changeset/twelve-seals-dream.md
  docs/src/config.ts
  packages/hardhat-core/src/internal/cli/cli.ts
  packages/hardhat-core/src/internal/cli/project-creation.ts
Labels: status:triaging

#3560 Inclusion of coc extension into Privacy Policy
  docs/public/privacy-policy.html
Labels: no changeset needed

#3561 refactor: simplify async generics
  crates/rethnet_evm/src/block/builder.rs
  crates/rethnet_evm/src/blockchain/sync.rs
  crates/rethnet_evm/src/db.rs
  crates/rethnet_evm/src/db/sync.rs
  crates/rethnet_evm/src/evm.rs
  crates/rethnet_evm/src/runtime.rs
  crates/rethnet_evm_napi/src/blockchain.rs
  crates/rethnet_evm_napi/src/state.rs
Labels: type:improvement

#3573 Remove misleading tabs in foundry guide
  docs/src/content/hardhat-runner/docs/advanced/hardhat-and-foundry.md
Labels: status:triaging, no changeset needed

#3572 Add a new 'reset' network helper
  .changeset/kind-humans-grow.md
  docs/src/content/hardhat-network-helpers/docs/reference.md
  docs/src/content/hardhat-network/docs/guides/forking-other-networks.md
  docs/src/content/hardhat-network/docs/reference/index.md
  packages/hardhat-network-helpers/src/helpers/reset.ts
  packages/hardhat-network-helpers/src/index.ts
  packages/hardhat-network-helpers/src/utils.ts
  packages/hardhat-network-helpers/test/fixture-projects/.gitignore
  packages/hardhat-network-helpers/test/helpers/reset.ts
  packages/hardhat-network-helpers/test/setup.ts
Labels: status:ready

#3578 Fix #1324 (WebSocket BatchRequest) supports Batch requests via WebSockets
  .changeset/plenty-comics-bow.md
  packages/hardhat-core/src/internal/hardhat-network/jsonrpc/handler.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/websocket.ts
Labels: status:ready

#3592 Add hardhat scilla plugin to community plugins list.
  docs/src/content/hardhat-runner/plugins/plugins.ts
Labels: no changeset needed

#3579 add hardhat-insight plugin to docs
  docs/src/content/hardhat-runner/plugins/plugins.ts
Labels: no changeset needed

#3595 Fix scilla plugin URL.
  docs/src/content/hardhat-runner/plugins/plugins.ts
Labels: status:triaging, no changeset needed

#3594 doc: add hardhat-flat-exporter plugin to community plugins list
  docs/src/content/hardhat-runner/plugins/plugins.ts
Labels: status:triaging

#3614 feat: dependabot support for Rust
  .github/dependabot.yml
Labels: status:triaging
