Repository NomicFoundation/hardhat, pull requests merged in 2023-05, with the labels that each got.

#3887 fix: store code when inserting account in `LayeredState`
  crates/rethnet_evm/src/state/hybrid.rs
  crates/rethnet_evm/src/state/layered.rs
  crates/rethnet_evm/src/state/layered/changes.rs
Labels: status:triaging

#3881 feat: add worst-case benchmark for `StateRef::code_by_hash`
  crates/rethnet_evm/benches/state.rs
Labels: status:triaging

#3612 feat: implement fork state management
  .gitignore
  crates/rethnet_eth/Cargo.toml
  crates/rethnet_eth/src/lib.rs
  crates/rethnet_eth/src/remote.rs
  crates/rethnet_eth/src/remote/client.rs
  crates/rethnet_eth/src/remote/eth.rs
  crates/rethnet_eth/src/remote/jsonrpc.rs
  crates/rethnet_eth/src/remote/withdrawal.rs
  crates/rethnet_evm/Cargo.toml
  crates/rethnet_evm/src/block/builder.rs
  crates/rethnet_evm/src/lib.rs
  crates/rethnet_evm/src/random.rs
  crates/rethnet_evm/src/state.rs
  crates/rethnet_evm/src/state/debug.rs
  crates/rethnet_evm/src/state/fork.rs
  crates/rethnet_evm/src/state/history.rs
  crates/rethnet_evm/src/state/hybrid.rs
  crates/rethnet_evm/src/state/layered.rs
  crates/rethnet_evm/src/state/layered/changes.rs
  crates/rethnet_evm/src/state/remote.rs
  crates/rethnet_evm/src/state/remote/cached.rs
  crates/rethnet_evm/src/state/trie.rs
  crates/rethnet_evm/src/state/trie/account.rs
  crates/rethnet_evm/src/transaction.rs
  crates/rethnet_evm_napi/Cargo.toml
  crates/rethnet_evm_napi/src/context.rs
  crates/rethnet_evm_napi/src/state.rs
  crates/rethnet_evm_napi/src/transaction/result.rs
  crates/rethnet_evm_napi/test/evm/StateManager.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/RethnetState.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/fork/ForkStateManager.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/node.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/utils/makeForkClient.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/utils/random.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/block-builder.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/dual.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/ethereumjs.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/exit.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/rethnet.ts
  packages/hardhat-core/src/internal/hardhat-network/stack-traces/opcodes.ts
  packages/hardhat-core/test/internal/hardhat-network/helpers/assertions.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/logs.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/hardforks.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/utils/assertEqualBlocks.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/utils/runFullBlock.ts
  rust-toolchain
Labels: area:rethnet

#3899 chore(ci): enable tests for all targets
  .github/workflows/hardhat-core-ci.yml
Labels: status:triaging, area:rethnet

#3912 Use alchemy instead of infura in fork tests
  .github/workflows/test-recent-mainnet-block.yml
  packages/hardhat-core/scripts/test-recent-mainnet-block.ts
  packages/hardhat-core/test/fixture-projects/hardhat-network-fork-from-old-block/hardhat.config.js
  packages/hardhat-core/test/fixture-projects/hardhat-network-fork-tangerine-whistle/hardhat.config.js
  packages/hardhat-core/test/internal/hardhat-network/helpers/providers.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/baseFeePerGas.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/fork/ForkBlockchain.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/fork/ForkStateManager.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/forked-provider.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/hardhat-network-options.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/interval-mining-provider.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/debug.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/getTransactionByHash.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/hardhat.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/node.ts
Labels: status:triaging, no changeset needed

#3920 Use node 18.15 in CI
  .github/workflows/hardhat-chai-matchers-ci.yml
  .github/workflows/hardhat-core-ci.yml
  .github/workflows/hardhat-ethers-ci.yml
  .github/workflows/hardhat-foundry-ci.yml
  .github/workflows/hardhat-network-helpers-ci.yml
  .github/workflows/hardhat-network-tracing-all-solc-versions.yml
  .github/workflows/hardhat-network-tracing-ci.yml
  .github/workflows/hardhat-shorthand-ci.yml
  .github/workflows/hardhat-solhint-ci.yml
  .github/workflows/hardhat-solpp-ci.yml
  .github/workflows/hardhat-toolbox-ci.yml
  .github/workflows/hardhat-truffle4-ci.yml
  .github/workflows/hardhat-truffle5-ci.yml
  .github/workflows/hardhat-verify-ci.yml
  .github/workflows/hardhat-vyper-ci.yml
  .github/workflows/hardhat-web3-ci.yml
  .github/workflows/hardhat-web3-legacy-ci.yml
Labels: status:triaging, no changeset needed

#3917 chore: sync pre-commit hook to CI
  .cargo-husky/hooks/pre-commit
  crates/rethnet/Cargo.toml
Labels: area:rethnet

#3923 Check that all supported hardforks have a history entry
  .changeset/silly-ghosts-sing.md
  packages/hardhat-core/src/internal/core/config/default-config.ts
  packages/hardhat-core/test/internal/core/config/default-config.ts
Labels: status:triaging, no changeset needed

#3910 test: `StateDebug` worst case benchmarks
  crates/rethnet_evm/Cargo.toml
  crates/rethnet_evm/benches/state.rs
  crates/rethnet_evm/benches/state_debug.rs
  crates/rethnet_evm/benches/util.rs
Labels: status:triaging

#3907 Add Infura Sepolia Faucet to docs #3906
  docs/src/content/tutorial/deploying-to-a-live-network.md
Labels: status:triaging, no changeset needed

#3931 chore: set `RUSTFLAGS` and run `cargo check` in pre-commit hooks
  .cargo-husky/hooks/pre-commit
Labels: status:triaging

#3946 Gelato w3f plugin
  docs/src/content/hardhat-runner/plugins/plugins.ts
Labels: status:triaging, no changeset needed

#3921 test: `StateHistory` worst case benchmarks
  crates/rethnet_evm/Cargo.toml
  crates/rethnet_evm/benches/state.rs
  crates/rethnet_evm/benches/state_debug.rs
  crates/rethnet_evm/benches/state_history.rs
  crates/rethnet_evm/benches/util.rs
Labels: status:triaging

#3952 Gelato w3f plugin update link
  docs/src/content/hardhat-runner/plugins/plugins.ts
Labels: status:triaging

#3937 test: Add `ForkState` to worst case benchmarks
  .cargo-husky/hooks/pre-commit
  .github/workflows/hardhat-core-ci.yml
  crates/rethnet_eth/Cargo.toml
  crates/rethnet_eth/src/remote/client.rs
  crates/rethnet_evm/Cargo.toml
  crates/rethnet_evm/benches/state_debug.rs
  crates/rethnet_evm/benches/state_history.rs
  crates/rethnet_evm/benches/state_history_block_context.rs
  crates/rethnet_evm/benches/util.rs
  crates/rethnet_evm/src/state/fork.rs
  crates/rethnet_evm/src/state/layered.rs
  crates/rethnet_evm/src/state/layered/changes.rs
  crates/rethnet_evm/src/state/remote.rs
Labels: status:triaging
