Repository NomicFoundation/hardhat, pull requests merged in 2023-02, with the labels that each got.

#3631 Made capitalization consistent
  docs/src/content/tutorial/testing-contracts.md
Labels: status:triaging

#3658 add eslint rule for hardhat plugin errors
  .changeset/cyan-knives-study.md
  config/eslint/eslintrc.js
  packages/eslint-plugin/index.js
  packages/eslint-plugin/onlyHardhatErrorRule.js
Labels: status:ready

#3660 Delete the hardhat-waffle plugin
  .github/workflows/hardhat-waffle-ci.yml
  package.json
  packages/hardhat-waffle/.eslintignore
  packages/hardhat-waffle/.eslintrc.js
  packages/hardhat-waffle/.gitignore
  packages/hardhat-waffle/.mocharc.json
  packages/hardhat-waffle/.prettierignore
  packages/hardhat-waffle/CHANGELOG.md
  packages/hardhat-waffle/LICENSE
  packages/hardhat-waffle/README.md
  packages/hardhat-waffle/package.json
  packages/hardhat-waffle/src/constants.ts
  packages/hardhat-waffle/src/deploy.ts
  packages/hardhat-waffle/src/fixtures.ts
  packages/hardhat-waffle/src/hardhatChaiMatchersIncompatibilityCheck.ts
  packages/hardhat-waffle/src/index.ts
  packages/hardhat-waffle/src/link.ts
  packages/hardhat-waffle/src/matchers.ts
  packages/hardhat-waffle/src/type-extensions.ts
  packages/hardhat-waffle/src/waffle-chai.ts
  packages/hardhat-waffle/src/waffle-provider-adapter.ts
  packages/hardhat-waffle/test/.eslintrc.js
  packages/hardhat-waffle/test/fixture-projects/hardhat-project-custom-accounts/hardhat.config.js
  packages/hardhat-waffle/test/fixture-projects/hardhat-project/.gitignore
  packages/hardhat-waffle/test/fixture-projects/hardhat-project/contracts/Contract.sol
  packages/hardhat-waffle/test/fixture-projects/hardhat-project/contracts/Token.sol
  packages/hardhat-waffle/test/fixture-projects/hardhat-project/hardhat.config.js
  packages/hardhat-waffle/test/fixture-projects/hardhat-project/test/test-with-explicit-chai-use.js
  packages/hardhat-waffle/test/fixture-projects/hardhat-project/test/tests.js
  packages/hardhat-waffle/test/helpers.ts
  packages/hardhat-waffle/test/index.ts
  packages/hardhat-waffle/tsconfig.json
Labels: no changeset needed

#3637 Overriding subtask parameters
  .changeset/brave-steaks-sort.md
  packages/hardhat-core/src/internal/core/config/config-env.ts
  packages/hardhat-core/src/internal/core/runtime-environment.ts
  packages/hardhat-core/src/internal/core/tasks/dsl.ts
  packages/hardhat-core/src/internal/core/tasks/task-definitions.ts
  packages/hardhat-core/src/types/runtime.ts
  packages/hardhat-core/test/internal/core/runtime-environment.ts
Labels: status:ready

#3662 Corrected a too hight amount of eth sent to example Lock.
  .changeset/chilly-papayas-dance.md
  packages/hardhat-core/sample-projects/javascript/scripts/deploy.js
  packages/hardhat-core/sample-projects/typescript/scripts/deploy.ts
Labels: status:triaging

#3131 Add a guide about how to use Chainlink
  docs/src/content/hardhat-runner/docs/supporter-guides/_dirinfo.yaml
  docs/src/content/hardhat-runner/docs/supporter-guides/oracles.md
  docs/src/content/layouts.yaml
Labels: no changeset needed

#3336 Included another HardHat smart contract tutorial
  docs/src/content/tutorial/final-thoughts.md
Labels: no changeset needed

#3601 Website UI improvements: hero x-index order and sidebar scrollbar
  docs/src/components/DocumentationLayout.tsx
  docs/src/components/landingBlocks/HeroBlock.tsx
Labels: no changeset needed

#3611 Add hardhat-markup plugin to community plugins list
  docs/src/content/hardhat-runner/plugins/plugins.ts
Labels: no changeset needed

#3648 Adding Chiado
  .changeset/stupid-mangos-raise.md
  packages/hardhat-etherscan/src/ChainConfig.ts
Labels: status:triaging

#3666 Remove hardhat-ganache and hardhat-docker from the monorepo
  .changeset/quiet-queens-talk.md
  .changeset/stupid-apricots-occur.md
  .github/workflows/LATEST_DEPENDENCY_VERSIONS.yml
  .github/workflows/e2e-ci.yml
  .github/workflows/hardhat-ganache-ci.yml
  .github/workflows/hardhat-vyper-ci.yml
  .github/workflows/pre-release.yml
  docs/src/components/Navigation.mocks.json
  docs/src/content/hardhat-runner/plugins/_dirinfo.yaml
  docs/src/content/hardhat-runner/plugins/plugins.ts
  package.json
  packages/hardhat-core/src/builtin-tasks/compile.ts
  packages/hardhat-core/src/internal/core/providers/http.ts
  packages/hardhat-core/src/internal/util/download.ts
  packages/hardhat-core/test/internal/hardhat-network/helpers/useProvider.ts
  packages/hardhat-docker/.eslintrc.js
  packages/hardhat-docker/.gitignore
  packages/hardhat-docker/.prettierignore
  packages/hardhat-docker/CHANGELOG.md
  packages/hardhat-docker/README.md
  packages/hardhat-docker/package.json
  packages/hardhat-docker/src/errors.ts
  packages/hardhat-docker/src/hardhat-docker.ts
  packages/hardhat-docker/src/index.ts
  packages/hardhat-docker/src/streams.ts
  packages/hardhat-docker/src/types.ts
  packages/hardhat-docker/test/.eslintrc.js
  packages/hardhat-docker/test/tests.ts
  packages/hardhat-docker/tsconfig.json
  packages/hardhat-etherscan/src/ABITypes.ts
  packages/hardhat-ganache/.eslintignore
  packages/hardhat-ganache/.eslintrc.js
  packages/hardhat-ganache/.gitignore
  packages/hardhat-ganache/.mocharc.json
  packages/hardhat-ganache/.prettierignore
  packages/hardhat-ganache/LICENSE
  packages/hardhat-ganache/README.md
  packages/hardhat-ganache/package.json
  packages/hardhat-ganache/src/ganache-options-ti.ts
  packages/hardhat-ganache/src/ganache-service.ts
  packages/hardhat-ganache/src/index.ts
  packages/hardhat-ganache/test/.eslintrc.js
  packages/hardhat-ganache/test/fixture-projects/hardhat-project-with-configs/hardhat.config.ts
  packages/hardhat-ganache/test/fixture-projects/hardhat-project-with-configs/scripts/custom-accounts-sample.js
  packages/hardhat-ganache/test/fixture-projects/hardhat-project/.gitignore
  packages/hardhat-ganache/test/fixture-projects/hardhat-project/contracts/EVMInspector.sol
  packages/hardhat-ganache/test/fixture-projects/hardhat-project/hardhat.config.ts
  packages/hardhat-ganache/test/fixture-projects/hardhat-project/scripts/accounts-sample.js
  packages/hardhat-ganache/test/fixture-projects/hardhat-project/scripts/delayed-sample.js
  packages/hardhat-ganache/test/fixture-projects/hardhat-project/test/test.js
  packages/hardhat-ganache/test/helpers.ts
  packages/hardhat-ganache/test/index.ts
  packages/hardhat-ganache/tsconfig.json
  packages/hardhat-vyper/README.md
  packages/hardhat-waffle/README.md
  yarn.lock
Labels: no changeset needed

#3669 docs: fix typos
  docs/src/content/hardhat-chai-matchers/docs/overview.md
  docs/src/content/hardhat-chai-matchers/docs/reference.md
  docs/src/content/hardhat-network/docs/reference/index.md
Labels: no changeset needed

#3698 Make error/warning colons consistent
  packages/hardhat-core/src/builtin-tasks/compile.ts
Labels: status:triaging

#3654 Support Solidity 0.8.18
  .changeset/rude-walls-wait.md
  docs/src/content/hardhat-runner/docs/reference/solidity-support.md
  docs/src/content/tutorial/creating-a-new-hardhat-project.md
  packages/hardhat-core/sample-projects/javascript/hardhat.config.js
  packages/hardhat-core/sample-projects/typescript/hardhat.config.ts
  packages/hardhat-core/src/internal/cli/project-creation.ts
  packages/hardhat-core/src/internal/hardhat-network/stack-traces/constants.ts
  packages/hardhat-core/test/fixture-projects/solidity-config-warnings/multiple-unsupported-solc.js
  packages/hardhat-core/test/fixture-projects/solidity-config-warnings/unsupported-new-solc.js
  packages/hardhat-core/test/fixture-projects/solidity-config-warnings/unsupported-solc-in-override.js
  packages/hardhat-core/test/internal/hardhat-network/stack-traces/test.ts
Labels: status:triaging

#3696 updates copyright year at the footer using Date module
  docs/src/assets/trustedTeamsLogos/logos.ts
  docs/src/components/LandingFooter.tsx
  docs/src/content/home.ts
Labels: status:triaging

#3682 docs: wording improvement
  packages/hardhat-core/src/internal/core/errors-list.ts
Labels: status:triaging

#3701 Deduplicate unsupported versions
  .changeset/rare-guests-listen.md
  packages/hardhat-core/src/internal/core/config/config-loading.ts
Labels: status:triaging

#3593 feat: tracing in Rethnet using JS callbacks
  crates/rethnet_eth/Cargo.toml
  crates/rethnet_eth/src/account.rs
  crates/rethnet_eth/src/block.rs
  crates/rethnet_eth/src/lib.rs
  crates/rethnet_eth/src/receipt.rs
  crates/rethnet_eth/src/remote.rs
  crates/rethnet_eth/src/transaction.rs
  crates/rethnet_eth/src/utils.rs
  crates/rethnet_evm/Cargo.toml
  crates/rethnet_evm/src/block/builder.rs
  crates/rethnet_evm/src/blockchain/request.rs
  crates/rethnet_evm/src/blockchain/sync.rs
  crates/rethnet_evm/src/db.rs
  crates/rethnet_evm/src/debug.rs
  crates/rethnet_evm/src/evm.rs
  crates/rethnet_evm/src/inspector.rs
  crates/rethnet_evm/src/lib.rs
  crates/rethnet_evm/src/random.rs
  crates/rethnet_evm/src/runtime.rs
  crates/rethnet_evm/src/state.rs
  crates/rethnet_evm/src/state/layered_db.rs
  crates/rethnet_evm/src/state/remote.rs
  crates/rethnet_evm/src/state/request.rs
  crates/rethnet_evm/src/state/sync.rs
  crates/rethnet_evm/src/trace.rs
  crates/rethnet_evm/src/transaction.rs
  crates/rethnet_evm_napi/Cargo.toml
  crates/rethnet_evm_napi/src/account.rs
  crates/rethnet_evm_napi/src/block/builder.rs
  crates/rethnet_evm_napi/src/blockchain.rs
  crates/rethnet_evm_napi/src/blockchain/js_blockchain.rs
  crates/rethnet_evm_napi/src/cast.rs
  crates/rethnet_evm_napi/src/config.rs
  crates/rethnet_evm_napi/src/lib.rs
  crates/rethnet_evm_napi/src/log.rs
  crates/rethnet_evm_napi/src/receipt.rs
  crates/rethnet_evm_napi/src/runtime.rs
  crates/rethnet_evm_napi/src/state.rs
  crates/rethnet_evm_napi/src/tracer.rs
  crates/rethnet_evm_napi/src/tracer/js_tracer.rs
  crates/rethnet_evm_napi/src/transaction.rs
  crates/rethnet_evm_napi/src/transaction/result.rs
  packages/hardhat-core/src/internal/hardhat-network/provider/node.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/utils/convertToRethnet.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/block-builder.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/creation.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/dual.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/ethereumjs.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/exit.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/rethnet.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/vm-adapter.ts
  packages/hardhat-core/src/internal/hardhat-network/stack-traces/error-inferrer.ts
  packages/hardhat-core/src/internal/hardhat-network/stack-traces/message-trace.ts
  packages/hardhat-core/src/internal/hardhat-network/stack-traces/model.ts
  packages/hardhat-core/src/internal/hardhat-network/stack-traces/vm-tracer.ts
  packages/hardhat-core/test/internal/hardhat-network/helpers/contracts.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/hardforks.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/sendTransaction.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/utils/runFullBlock.ts
  packages/hardhat-core/test/internal/hardhat-network/stack-traces/execution.ts
Labels: area:rethnet

#3683 refactor: remove unnecessary dependencies
  crates/rethnet_eth/src/signature.rs
  crates/rethnet_evm/Cargo.toml
  crates/rethnet_evm_napi/Cargo.toml
  crates/rethnet_evm_napi/src/lib.rs
  crates/rethnet_evm_napi/src/state.rs
  crates/rethnet_evm_napi/src/transaction/result.rs
Labels: status:triaging, area:rethnet

#3685 feat: add trace when a custom inspector is used
  crates/rethnet_evm/src/evm.rs
  crates/rethnet_evm/src/inspector.rs
  crates/rethnet_evm/src/trace.rs
Labels: status:triaging, area:rethnet

#3687 bump: upgrade napi to 2.11.1
  crates/rethnet_evm_napi/Cargo.toml
  crates/rethnet_evm_napi/src/config.rs
Labels: status:triaging

#3693 fix(rethnet): remove second LayeredDatabase::remove_account function
  crates/rethnet_evm/src/state/layered_db.rs
Labels: status:triaging

#3686 improvement: reduce build time by annotating types in napi macros
  crates/rethnet_evm_napi/src/block/builder.rs
  crates/rethnet_evm_napi/src/runtime.rs
  crates/rethnet_evm_napi/src/state.rs
Labels: status:triaging, area:rethnet

#3684 refactor: combine code and hash in bytecode
  crates/rethnet_evm_napi/src/account.rs
  crates/rethnet_evm_napi/src/cast.rs
  crates/rethnet_evm_napi/src/state.rs
  packages/hardhat-core/src/internal/hardhat-network/provider/RethnetState.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/dual.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/ethereumjs.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/rethnet.ts
Labels: status:triaging, area:rethnet

#3688 refactor: rename state-related files
  crates/rethnet_evm/src/lib.rs
  crates/rethnet_evm/src/state.rs
  crates/rethnet_evm/src/state/debug.rs
  crates/rethnet_evm/src/state/layered_state.rs
  crates/rethnet_evm/src/state/request.rs
  crates/rethnet_evm/src/state/sync.rs
  crates/rethnet_evm_napi/src/state.rs
Labels: status:triaging, area:rethnet

#3694 docs(rethnet): clarify that modify_account operates on empty accounts
  crates/rethnet_evm/src/state/debug.rs
  crates/rethnet_evm/src/state/layered_state.rs
Labels: status:triaging, area:rethnet

#3672 allow linting classes that extend the HardhatPluginError class
  .changeset/lazy-seas-exercise.md
  packages/eslint-plugin/onlyHardhatErrorRule.js
Labels: status:triaging

#3704 add 2 plugins (hardhat-contract-clarity and transaction-retry-tool)
  docs/src/content/hardhat-runner/plugins/plugins.ts
Labels: status:triaging

#3706 Remove wrongly added files
  packages/hardhat-foundry/dist/src/foundry.d.ts
  packages/hardhat-foundry/dist/src/foundry.d.ts.map
  packages/hardhat-foundry/dist/src/foundry.js
  packages/hardhat-foundry/dist/src/foundry.js.map
  packages/hardhat-foundry/dist/src/index.d.ts
  packages/hardhat-foundry/dist/src/index.d.ts.map
  packages/hardhat-foundry/dist/src/index.js
  packages/hardhat-foundry/dist/src/index.js.map
  packages/hardhat-foundry/node_modules/.bin/_mocha
  packages/hardhat-foundry/node_modules/.bin/eslint
  packages/hardhat-foundry/node_modules/.bin/eslint-config-prettier
  packages/hardhat-foundry/node_modules/.bin/hardhat
  packages/hardhat-foundry/node_modules/.bin/mocha
  packages/hardhat-foundry/node_modules/.bin/prettier
  packages/hardhat-foundry/node_modules/.bin/rimraf
  packages/hardhat-foundry/node_modules/.bin/ts-node
  packages/hardhat-foundry/node_modules/.bin/ts-node-cwd
  packages/hardhat-foundry/node_modules/.bin/ts-node-esm
  packages/hardhat-foundry/node_modules/.bin/ts-node-script
  packages/hardhat-foundry/node_modules/.bin/ts-node-transpile-only
  packages/hardhat-foundry/node_modules/.bin/ts-script
  packages/hardhat-foundry/node_modules/.bin/tsc
  packages/hardhat-foundry/node_modules/.bin/tsserver
Labels: status:triaging

#3707 Remove e2e package
  .changeset/config.json
  .github/workflows/e2e-ci.yml
  packages/e2e/.eslintignore
  packages/e2e/.eslintrc.js
  packages/e2e/.gitignore
  packages/e2e/.mocharc.json
  packages/e2e/.prettierignore
  packages/e2e/LICENSE
  packages/e2e/README.md
  packages/e2e/package.json
  packages/e2e/run-tests.js
  packages/e2e/test/fixture-projects/basic-project/.gitignore
  packages/e2e/test/fixture-projects/basic-project/contracts/Contract.sol
  packages/e2e/test/fixture-projects/basic-project/hardhat.config.js
  packages/e2e/test/fixture-projects/basic-project/package.json
  packages/e2e/test/fixture-projects/basic-project/scripts/multi-run-test.js
  packages/e2e/test/fixture-projects/basic-project/test/another-test.js
  packages/e2e/test/fixture-projects/basic-project/test/simple.js
  packages/e2e/test/fixture-projects/empty/.gitkeep
  packages/e2e/test/fixture-projects/javascript-sample-project/package.json
  packages/e2e/test/fixture-projects/type-error-in-config/.gitignore
  packages/e2e/test/fixture-projects/type-error-in-config/hardhat.config.ts
  packages/e2e/test/fixture-projects/type-error-in-config/package.json
  packages/e2e/test/fixture-projects/type-error-in-script/.gitignore
  packages/e2e/test/fixture-projects/type-error-in-script/hardhat.config.ts
  packages/e2e/test/fixture-projects/type-error-in-script/package.json
  packages/e2e/test/fixture-projects/type-error-in-script/script.ts
  packages/e2e/test/fixture-projects/type-error-in-test/.gitignore
  packages/e2e/test/fixture-projects/type-error-in-test/hardhat.config.ts
  packages/e2e/test/fixture-projects/type-error-in-test/package.json
  packages/e2e/test/fixture-projects/type-error-in-test/test/test.ts
  packages/e2e/test/fixture-projects/typescript-sample-project/package.json
  packages/e2e/test/helpers.ts
  packages/e2e/test/index.ts
  packages/e2e/tsconfig.json
Labels: status:triaging

#3710 Simplify ts config
  config/typescript/@types/adm-zip/index.d.ts
  config/typescript/@types/ethereumjs-abi/index.d.ts
  config/typescript/@types/solc/index.d.ts
  config/typescript/@types/solhint/index.d.ts
  config/typescript/@types/solpp/index.d.ts
  config/typescript/@types/tabtab/index.d.ts
  config/typescript/tsconfig.json
  packages/hardhat-chai-matchers/package.json
  packages/hardhat-core/package.json
  packages/hardhat-core/src/internal/hardhat-network/provider/return-data.ts
  packages/hardhat-core/src/internal/hardhat-network/stack-traces/compiler-to-model.ts
  packages/hardhat-core/src/internal/solidity/compiler/downloader.ts
  packages/hardhat-core/src/internal/solidity/compiler/index.ts
  packages/hardhat-core/test/internal/hardhat-network/stack-traces/execution.ts
  packages/hardhat-ethers/package.json
  packages/hardhat-etherscan/package.json
  packages/hardhat-foundry/package.json
  packages/hardhat-network-helpers/package.json
  packages/hardhat-shorthand/package.json
  packages/hardhat-shorthand/src/completion.ts
  packages/hardhat-solhint/package.json
  packages/hardhat-solhint/src/index.ts
  packages/hardhat-solpp/package.json
  packages/hardhat-solpp/src/index.ts
  packages/hardhat-truffle4/package.json
  packages/hardhat-truffle5/package.json
  packages/hardhat-vyper/package.json
  packages/hardhat-web3-legacy/package.json
  packages/hardhat-web3/package.json
  yarn.lock
Labels: no changeset needed

#3679 Propagate HttpProviderError exception message
  .changeset/twenty-toys-wave.md
  packages/hardhat-core/src/internal/core/providers/http.ts
Labels: status:triaging

#3659 Set "resolveJsonModule": true in sample tsconfig
  .changeset/dull-files-dream.md
  packages/hardhat-core/sample-projects/typescript/tsconfig.json
Labels: status:triaging

#3715 Add Fireblocks plugin
  docs/src/content/hardhat-runner/plugins/plugins.ts
Labels: no changeset needed
