Repository NomicFoundation/hardhat, pull requests merged in 2023-10, with the labels that each got.

#4434 fix: fix RPC cache when tmp is on different filesystem
  Cargo.lock
  crates/rethnet_eth/Cargo.toml
  crates/rethnet_eth/src/remote/client.rs
Labels: status:triaging, area:edr

#4433 feat: debug trace call
  crates/rethnet_evm/src/debug_trace.rs
  crates/rethnet_evm/src/lib.rs
  crates/rethnet_evm_napi/src/debug_trace.rs
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/dual.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/rethnet.ts
Labels: status:triaging, area:edr

#3719 Scoped hardhat tasks
  .changeset/funny-cats-sing.md
  docs/src/content/hardhat-runner/docs/advanced/create-task.md
  packages/hardhat-core/src/builtin-tasks/help.ts
  packages/hardhat-core/src/internal/cli/ArgumentsParser.ts
  packages/hardhat-core/src/internal/cli/HelpPrinter.ts
  packages/hardhat-core/src/internal/cli/cli.ts
  packages/hardhat-core/src/internal/core/config/config-env.ts
  packages/hardhat-core/src/internal/core/errors-list.ts
  packages/hardhat-core/src/internal/core/runtime-environment.ts
  packages/hardhat-core/src/internal/core/tasks/dsl.ts
  packages/hardhat-core/src/internal/core/tasks/task-definitions.ts
  packages/hardhat-core/src/internal/core/tasks/util.ts
  packages/hardhat-core/src/internal/lib/hardhat-lib.ts
  packages/hardhat-core/src/register.ts
  packages/hardhat-core/src/types/runtime.ts
  packages/hardhat-core/test/builtin-tasks/compile.ts
  packages/hardhat-core/test/fixture-projects/scoped-tasks/hardhat.config.js
  packages/hardhat-core/test/fixture-projects/scoped-tasks/package.json
  packages/hardhat-core/test/internal/cli/ArgumentsParser.ts
  packages/hardhat-core/test/internal/core/runtime-environment.ts
  packages/hardhat-core/test/internal/core/scoped-tasks.ts
  packages/hardhat-core/test/internal/core/tasks/dsl.ts
  packages/hardhat-core/test/internal/core/tasks/task-definitions.ts
  packages/hardhat-core/test/types/config-env.ts
Labels: status:ready

#4435 Report ignition deploy to GA
  packages/hardhat-core/src/internal/cli/analytics.ts
  packages/hardhat-core/src/internal/cli/cli.ts
Labels: status:ready

#4415 ci: edr evm napi release
  .github/workflows/edr-npm-release.yml
  Cargo.lock
  book/src/02_release.md
  crates/rethnet_evm_napi/.cargo/config.toml
  crates/rethnet_evm_napi/.gitignore
  crates/rethnet_evm_napi/Cargo.toml
  crates/rethnet_evm_napi/index.d.ts
  crates/rethnet_evm_napi/index.js
  crates/rethnet_evm_napi/npm/darwin-arm64/README.md
  crates/rethnet_evm_napi/npm/darwin-arm64/package.json
  crates/rethnet_evm_napi/npm/darwin-x64/README.md
  crates/rethnet_evm_napi/npm/darwin-x64/package.json
  crates/rethnet_evm_napi/npm/linux-arm64-gnu/README.md
  crates/rethnet_evm_napi/npm/linux-arm64-gnu/package.json
  crates/rethnet_evm_napi/npm/linux-arm64-musl/README.md
  crates/rethnet_evm_napi/npm/linux-arm64-musl/package.json
  crates/rethnet_evm_napi/npm/linux-x64-gnu/README.md
  crates/rethnet_evm_napi/npm/linux-x64-gnu/package.json
  crates/rethnet_evm_napi/npm/linux-x64-musl/README.md
  crates/rethnet_evm_napi/npm/linux-x64-musl/package.json
  crates/rethnet_evm_napi/npm/win32-ia32-msvc/README.md
  crates/rethnet_evm_napi/npm/win32-ia32-msvc/package.json
  crates/rethnet_evm_napi/npm/win32-x64-msvc/README.md
  crates/rethnet_evm_napi/npm/win32-x64-msvc/package.json
  crates/rethnet_evm_napi/package.json
  crates/rethnet_evm_napi/test/evm/RethnetDb.ts
  crates/rethnet_evm_napi/test/evm/StateManager.ts
  crates/rethnet_evm_napi/yarn.lock
  packages/hardhat-core/package.json
  packages/hardhat-core/src/internal/hardhat-network/provider/RethnetState.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/blockchain/rethnet.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/context/rethnet.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/mem-pool/rethnet.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/miner/rethnet.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/utils/convertToRethnet.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/block-builder/rethnet.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/ethereumjs.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/exit.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/rethnet.ts
  packages/hardhat-core/src/internal/hardhat-network/stack-traces/message-trace.ts
  packages/hardhat-core/src/internal/hardhat-network/stack-traces/vm-tracer.ts
  yarn.lock
Labels: area:edr

#4444 chore: fix edr package version in hardhat-core
  packages/hardhat-core/package.json
Labels: status:triaging, area:edr

#4448 test: re-enable tests related to max initcode size
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/hardforks.ts
Labels: status:triaging, area:edr

#4414 Print the evmVersion used when compiling
  .changeset/spotty-tomatoes-press.md
  packages/hardhat-core/src/builtin-tasks/compile.ts
  packages/hardhat-core/src/internal/solidity/compiler/solc-info.ts
  packages/hardhat-core/test/builtin-tasks/compile.ts
  packages/hardhat-core/test/fixture-projects/compilation-multiple-files-different-evm-versions/.gitignore
  packages/hardhat-core/test/fixture-projects/compilation-multiple-files-different-evm-versions/contracts/A.sol
  packages/hardhat-core/test/fixture-projects/compilation-multiple-files-different-evm-versions/contracts/B.sol
  packages/hardhat-core/test/fixture-projects/compilation-multiple-files-different-evm-versions/contracts/C.sol
  packages/hardhat-core/test/fixture-projects/compilation-multiple-files-different-evm-versions/contracts/D.sol
  packages/hardhat-core/test/fixture-projects/compilation-multiple-files-different-evm-versions/hardhat.config.js
Labels: status:ready

#4451 bump: Rust to v1.73.0
  crates/rethnet_evm/src/state/irregular.rs
  crates/rethnet_rpc_server/src/filter.rs
  rust-toolchain
Labels: area:edr

#4454 fix: windows rpc cache test
  crates/rethnet_eth/src/remote/client.rs
Labels: area:edr

#4458 Redirect /ignition-discord to a channel-specific invite
  docs/redirects.config.js
Labels: status:ready, no changeset needed

#4462 ci: remove uncached test fork job
  .github/workflows/hardhat-core-ci.yml
Labels: area:edr

#4452 feat: allow configuring max initcode size
  Cargo.lock
  crates/rethnet_eth/Cargo.toml
  crates/rethnet_evm/Cargo.toml
  crates/rethnet_evm_napi/index.d.ts
  crates/rethnet_evm_napi/src/cast.rs
  crates/rethnet_evm_napi/src/config.rs
  packages/hardhat-core/src/internal/hardhat-network/provider/context/rethnet.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/rethnet.ts
Labels: status:triaging, area:edr

#4466 Fix script in viem sample project
  packages/hardhat-core/sample-projects/typescript-viem/scripts/deploy.ts
Labels: status:ready, no changeset needed

#4461 feat: solidity coverage support in EDR mode
  crates/rethnet_evm/src/trace.rs
  crates/rethnet_evm_napi/index.d.ts
  crates/rethnet_evm_napi/src/trace.rs
  packages/hardhat-core/src/internal/hardhat-network/provider/context/rethnet.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/miner/rethnet.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/ethereumjs.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/rethnet.ts
Labels: status:triaging, area:edr

#4467 ci: enable ethereumjs mode tests
  .github/workflows/hardhat-core-ci.yml
Labels: area:edr

#4443 feat: Cancun support in EDR
  crates/rethnet_eth/src/block.rs
  crates/rethnet_eth/src/block/options.rs
  crates/rethnet_eth/src/receipt.rs
  crates/rethnet_eth/src/remote/eth.rs
  crates/rethnet_eth/src/transaction/request.rs
  crates/rethnet_eth/src/transaction/request/eip4844.rs
  crates/rethnet_eth/src/transaction/signed.rs
  crates/rethnet_eth/src/transaction/signed/eip4844.rs
  crates/rethnet_evm/src/block/builder.rs
  crates/rethnet_evm/src/block/remote.rs
  crates/rethnet_evm/src/transaction.rs
  crates/rethnet_evm/src/transaction/pending.rs
  crates/rethnet_evm_napi/index.d.ts
  crates/rethnet_evm_napi/src/block.rs
  crates/rethnet_evm_napi/src/transaction/pending.rs
  crates/rethnet_evm_napi/src/transaction/signed.rs
  crates/rethnet_evm_napi/src/transaction/signed/eip4844.rs
  packages/hardhat-core/src/internal/hardhat-network/provider/context/dual.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/context/rethnet.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/mem-pool/rethnet.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/miner.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/miner/hardhat.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/miner/rethnet.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/node.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/utils/convertToRethnet.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/creation.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/dual.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/ethereumjs.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/exit.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/rethnet.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/vm-adapter.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/node.ts
  yarn.lock
Labels: area:edr

#4468 misc: use EthereumJS by default and rename EDR
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/creation.ts
Labels: status:triaging, area:edr

#4470 docs: update book to switch from rethnet to edr mode
  book/src/01_getting_started/03_test.md
Labels: status:triaging, area:edr

#4463 feat: state overrides
  .github/workflows/hardhat-viem-ci.yml
  Cargo.lock
  crates/rethnet_eth/Cargo.toml
  crates/rethnet_eth/src/block.rs
  crates/rethnet_eth/src/block/options.rs
  crates/rethnet_evm/Cargo.toml
  crates/rethnet_evm/src/block/builder.rs
  crates/rethnet_evm/src/block/local.rs
  crates/rethnet_evm/src/blockchain/local.rs
  crates/rethnet_evm/src/blockchain/storage/reservable.rs
  crates/rethnet_evm/src/evm.rs
  crates/rethnet_evm/src/runtime.rs
  crates/rethnet_evm/src/state.rs
  crates/rethnet_evm/src/state/overrides.rs
  crates/rethnet_evm/src/upcast.rs
  crates/rethnet_evm/tests/blockchain.rs
  crates/rethnet_evm_napi/index.d.ts
  crates/rethnet_evm_napi/index.js
  crates/rethnet_evm_napi/src/block.rs
  crates/rethnet_evm_napi/src/blockchain.rs
  crates/rethnet_evm_napi/src/debug_trace.rs
  crates/rethnet_evm_napi/src/runtime.rs
  crates/rethnet_evm_napi/src/state.rs
  crates/rethnet_evm_napi/src/state/overrides.rs
  packages/hardhat-core/src/internal/hardhat-network/provider/node.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/utils/convertToRethnet.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/rethnet.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/call.ts
Labels: area:edr

#4475 fix: EDR build on Windows ARM
  .github/workflows/edr-npm-release.yml
  Cargo.lock
  crates/rethnet/Cargo.toml
  crates/rethnet/src/config.rs
  crates/rethnet/tests/cli.rs
  crates/rethnet_defaults/src/lib.rs
  crates/rethnet_eth/Cargo.toml
  crates/rethnet_eth/src/lib.rs
  crates/rethnet_eth/src/signature.rs
  crates/rethnet_eth/src/transaction/request/eip155.rs
  crates/rethnet_eth/src/transaction/request/eip1559.rs
  crates/rethnet_eth/src/transaction/request/eip2930.rs
  crates/rethnet_eth/src/transaction/request/eip4844.rs
  crates/rethnet_eth/src/transaction/request/legacy.rs
  crates/rethnet_eth/src/transaction/signed/eip155.rs
  crates/rethnet_eth/src/transaction/signed/eip1559.rs
  crates/rethnet_eth/src/transaction/signed/eip2930.rs
  crates/rethnet_eth/src/transaction/signed/legacy.rs
  crates/rethnet_evm/Cargo.toml
  crates/rethnet_evm/tests/blockchain.rs
  crates/rethnet_evm_napi/Cargo.toml
  crates/rethnet_evm_napi/index.d.ts
  crates/rethnet_evm_napi/npm/win32-arm64-msvc/README.md
  crates/rethnet_evm_napi/npm/win32-arm64-msvc/package.json
  crates/rethnet_evm_napi/package.json
  crates/rethnet_evm_napi/src/account.rs
  crates/rethnet_rpc_server/Cargo.toml
  crates/rethnet_rpc_server/src/config.rs
  crates/rethnet_rpc_server/src/lib.rs
  crates/rethnet_rpc_server/tests/integration_tests.rs
  packages/hardhat-core/src/internal/hardhat-network/provider/RethnetState.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/context/rethnet.ts
Labels: area:edr

#4483 fix: hardhat-viem tests failure on windows
  .gitattributes
Labels: status:ready

#4480 fix: broken state override tests
  .github/workflows/hardhat-viem-ci.yml
  crates/edr_evm_napi/src/state/overrides.rs
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/edr.ts
Labels: area:edr

#4481 refactor: replace vm stub in adapters with vm proxy in node
  packages/hardhat-core/src/internal/hardhat-network/provider/context/edr.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/miner.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/miner/dual.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/miner/edr.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/miner/hardhat.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/node.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/dual.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/edr.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/ethereumjs.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/proxy-vm.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/vm-adapter.ts
Labels: status:ready

#4486 misc: add benchmark CLI
  crates/tools/src/benchmark.rs
  crates/tools/src/main.rs
Labels: area:edr

#4496 fix: unmatched edr exceptional halt
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/exit.ts
Labels: area:edr

#4497 misc: bump ethereumjs dependencies
  packages/hardhat-core/package.json
  packages/hardhat-ledger/package.json
  yarn.lock
Labels: status:ready

#4495 misc: add compare test runs tool
  Cargo.lock
  book/src/03_tools.md
  book/src/SUMMARY.md
  crates/tools/Cargo.toml
  crates/tools/src/compare_test_runs.rs
  crates/tools/src/main.rs
Labels: area:edr

#4487 feat: JS tracer callbacks
  crates/edr_eth/src/remote/eth.rs
  crates/edr_eth/src/transaction/request/eip1559.rs
  crates/edr_eth/src/transaction/request/eip2930.rs
  crates/edr_eth/src/transaction/signed.rs
  crates/edr_eth/src/transaction/signed/eip1559.rs
  crates/edr_eth/src/transaction/signed/eip2930.rs
  crates/edr_evm/src/inspector.rs
  crates/edr_evm/src/lib.rs
  crates/edr_evm/src/miner.rs
  crates/edr_evm/src/trace.rs
  crates/edr_evm/src/transaction/pending.rs
  crates/edr_evm_napi/index.d.ts
  crates/edr_evm_napi/index.js
  crates/edr_evm_napi/src/block.rs
  crates/edr_evm_napi/src/lib.rs
  crates/edr_evm_napi/src/log/execution.rs
  crates/edr_evm_napi/src/miner.rs
  crates/edr_evm_napi/src/runtime.rs
  crates/edr_evm_napi/src/trace.rs
  crates/edr_evm_napi/src/tracer.rs
  crates/edr_evm_napi/src/tracer/js_tracer.rs
  crates/edr_evm_napi/src/transaction/pending.rs
  crates/edr_evm_napi/src/transaction/result.rs
  crates/edr_evm_napi/src/transaction/signed.rs
  crates/edr_evm_napi/src/transaction/signed/eip1559.rs
  crates/edr_evm_napi/src/transaction/signed/eip2930.rs
  crates/edr_rpc_server/src/node.rs
  packages/hardhat-core/src/internal/hardhat-network/provider/miner.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/miner/dual.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/miner/edr.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/miner/hardhat.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/utils/convertToEdr.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/dual.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/edr.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/ethereumjs.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/proxy-vm.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/vm-adapter.ts
Labels: area:edr

#4503 misc: add clinic directory to gitignore
  .gitignore
Labels: status:triaging, area:edr

#4502 Fix compiler download
  .changeset/unlucky-pens-melt.md
  packages/hardhat-core/src/internal/util/download.ts
Labels: status:ready

#4427 add plugin hardhat-logger
  docs/src/content/hardhat-runner/plugins/plugins.ts
Labels: status:triaging, no changeset needed

#4505 fix: lazy init global edr context
  packages/hardhat-core/src/internal/hardhat-network/provider/context/edr.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/miner/dual.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/block-builder/dual.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/dual.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/edr.ts
  yarn.lock
Labels: status:triaging, area:edr

#4499 fix: static state change error
  packages/hardhat-core/src/internal/hardhat-network/provider/miner/edr.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/utils/convertToEdr.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/block-builder/edr.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/edr.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/ethereumjs.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/exit.ts
  packages/hardhat-core/src/internal/hardhat-network/stack-traces/vm-tracer.ts
Labels: area:edr

#4509 ci: enable ethereumjs for provider tests
  .github/workflows/hardhat-core-ci.yml
Labels: area:edr

#4510 docs: update the `Module execution` page of the Ignition docs
  docs/src/content/ignition/docs/advanced/execution.md
Labels: status:ready

#4508 Polish Hardhat Ignition's docs
  docs/src/content/ignition/docs/advanced/execution.md
  docs/src/content/ignition/docs/config/index.md
  docs/src/content/ignition/docs/getting-started/index.md
  docs/src/content/ignition/docs/guides/creating-modules.md
  docs/src/content/ignition/docs/guides/deploy.md
  docs/src/content/ignition/docs/guides/tests.md
  docs/src/content/ignition/docs/guides/visualize.md
Labels: status:ready

#4511 docs: ignition docs advanced
  docs/src/content/ignition/docs/advanced/deployments.md
  docs/src/content/ignition/docs/advanced/reconciliation.md
  docs/src/content/ignition/docs/advanced/versioning.md
Labels: status:ready

#4515 docs: use the word function/method consistently
  docs/src/content/ignition/docs/guides/creating-modules.md
  docs/src/content/ignition/docs/guides/tests.md
Labels: status:ready

#4512 fix: add missing type defs to EDR NPM package
  .github/workflows/edr-npm-release.yml
  crates/edr_evm_napi/.gitignore
  crates/edr_evm_napi/npm/darwin-arm64/package.json
  crates/edr_evm_napi/npm/darwin-x64/package.json
  crates/edr_evm_napi/npm/linux-arm64-gnu/package.json
  crates/edr_evm_napi/npm/linux-arm64-musl/package.json
  crates/edr_evm_napi/npm/linux-x64-gnu/package.json
  crates/edr_evm_napi/npm/linux-x64-musl/package.json
  crates/edr_evm_napi/npm/win32-arm64-msvc/package.json
  crates/edr_evm_napi/npm/win32-ia32-msvc/package.json
  crates/edr_evm_napi/npm/win32-x64-msvc/package.json
  crates/edr_evm_napi/package.json
Labels: area:edr

#4521 Fix minor typos
  docs/src/content/hardhat-runner/docs/supporter-guides/oracles.md
  packages/hardhat-verify/src/internal/solc/bytecode.ts
Labels: status:triaging, no changeset needed

#4523 docs: add instructions for local EDR NPM publish
  book/src/02_development.md
  book/src/02_development/01_tools.md
  book/src/02_development/02_verdaccio.md
  book/src/02_development/03_local_release.md
  book/src/03_release.md
  book/src/SUMMARY.md
Labels: area:edr

#4525 Report ignition deploy to GA
  .changeset/fast-windows-search.md
  packages/hardhat-core/src/internal/cli/analytics.ts
  packages/hardhat-core/src/internal/cli/cli.ts
Labels: status:ready

#4513 Add basic support for verification on Sourcify
  .changeset/tough-gorillas-matter.md
  packages/hardhat-verify/README.md
  packages/hardhat-verify/src/index.ts
  packages/hardhat-verify/src/internal/config.ts
  packages/hardhat-verify/src/internal/errors.ts
  packages/hardhat-verify/src/internal/etherscan.ts
  packages/hardhat-verify/src/internal/etherscan.types.ts
  packages/hardhat-verify/src/internal/sourcify.ts
  packages/hardhat-verify/src/internal/sourcify.types.ts
  packages/hardhat-verify/src/internal/task-names.ts
  packages/hardhat-verify/src/internal/tasks/etherscan.ts
  packages/hardhat-verify/src/internal/tasks/sourcify.ts
  packages/hardhat-verify/src/internal/type-extensions.ts
  packages/hardhat-verify/src/internal/undici.ts
  packages/hardhat-verify/src/internal/utilities.ts
  packages/hardhat-verify/src/sourcify.ts
  packages/hardhat-verify/src/types.ts
  packages/hardhat-verify/test/fixture-projects/hardhat-project/hardhat.config.js
  packages/hardhat-verify/test/helpers.ts
  packages/hardhat-verify/test/integration/index.ts
  packages/hardhat-verify/test/integration/mocks/sourcify.ts
  packages/hardhat-verify/test/unit/config.ts
  packages/hardhat-verify/test/unit/index.ts
  packages/hardhat-verify/test/unit/sourcify.ts
  packages/hardhat-verify/test/unit/utilities.ts
Labels: status:ready

#4530 refactor: move server methods to node
  Cargo.lock
  crates/edr_rpc_server/Cargo.toml
  crates/edr_rpc_server/src/lib.rs
  crates/edr_rpc_server/src/node.rs
Labels: status:triaging, area:edr

#4534 feat: stub the RPC server's logger
  crates/edr_rpc_server/src/lib.rs
  crates/edr_rpc_server/src/logger.rs
Labels: area:edr

#4536 refactor: update mempool after changing block gas limit
  crates/edr_evm/src/mempool.rs
  crates/edr_evm_napi/index.d.ts
  crates/edr_evm_napi/src/mempool.rs
  packages/hardhat-core/src/internal/hardhat-network/provider/mem-pool/edr.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/mem-pool/hardhat.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/node.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/TxPool.ts
Labels: area:edr

#4528 docs: add Ignition tip to deploying contracts guide
  docs/src/content/hardhat-runner/docs/guides/deploying.md
Labels: status:ready, no changeset needed

#4532 added missing square brackets for args
  docs/src/content/ignition/docs/guides/creating-modules.md
Labels: status:triaging, no changeset needed

#4539 refactor: port server methods to node
  Cargo.lock
  crates/edr/src/lib.rs
  crates/edr/tests/cli.rs
  crates/edr_rpc_server/Cargo.toml
  crates/edr_rpc_server/src/config.rs
  crates/edr_rpc_server/src/filter.rs
  crates/edr_rpc_server/src/lib.rs
  crates/edr_rpc_server/src/node.rs
  crates/edr_rpc_server/src/node/node_data.rs
  crates/edr_rpc_server/src/node/node_error.rs
  crates/edr_rpc_server/src/server.rs
  crates/edr_rpc_server/tests/integration_tests.rs
Labels: area:edr

#4545 add plugin hardhat-contract-signatures
  docs/src/content/hardhat-runner/plugins/plugins.ts
Labels: status:triaging, no changeset needed

#4547 refactor: eliminate unnecessary clones during request handling
  crates/edr_rpc_server/src/node.rs
  crates/edr_rpc_server/src/server.rs
Labels: status:triaging, area:edr
