Repository NomicFoundation/hardhat, pull requests merged in 2023-07, with the labels that each got.

#4091 Drop support for node v14 and add support for node v20
  .changeset/beige-kids-jam.md
  .github/workflows/LATEST_DEPENDENCY_VERSIONS.yml
  .github/workflows/comment-on-linter-error.yml
  .github/workflows/hardhat-chai-matchers-ci.yml
  .github/workflows/hardhat-core-ci.yml
  .github/workflows/hardhat-ethers-ci.yml
  .github/workflows/hardhat-foundry-ci.yml
  .github/workflows/hardhat-ledger-ci.yml
  .github/workflows/hardhat-network-forking-ci.yml
  .github/workflows/hardhat-network-helpers-ci.yml
  .github/workflows/hardhat-network-tracing-all-solc-versions.yml
  .github/workflows/hardhat-network-tracing-ci.yml
  .github/workflows/hardhat-shorthand-ci.yml
  .github/workflows/hardhat-solhint-ci.yml
  .github/workflows/hardhat-solpp-ci.yml
  .github/workflows/hardhat-toolbox-ci.yml
  .github/workflows/hardhat-truffle4-ci.yml
  .github/workflows/hardhat-truffle5-ci.yml
  .github/workflows/hardhat-verify-ci.yml
  .github/workflows/hardhat-vyper-ci.yml
  .github/workflows/hardhat-web3-ci.yml
  .github/workflows/hardhat-web3-legacy-ci.yml
  .github/workflows/lint.yml
  .github/workflows/pre-release.yml
  .github/workflows/release.yml
  .github/workflows/test-recent-mainnet-block.yml
  docs/src/content/tutorial/setting-up-the-environment.md
  packages/hardhat-chai-matchers/package.json
  packages/hardhat-core/package.json
  packages/hardhat-core/src/internal/cli/bootstrap.ts
  packages/hardhat-core/src/internal/cli/constants.ts
  packages/hardhat-core/src/internal/cli/project-creation.ts
  packages/hardhat-core/src/internal/util/caller-package.ts
  packages/hardhat-core/test/internal/cli/node-version.ts
  packages/hardhat-ethers/package.json
  packages/hardhat-foundry/package.json
  packages/hardhat-ledger/package.json
  packages/hardhat-network-helpers/package.json
  packages/hardhat-shorthand/package.json
  packages/hardhat-solhint/package.json
  packages/hardhat-solpp/package.json
  packages/hardhat-toolbox/package.json
  packages/hardhat-truffle4/package.json
  packages/hardhat-truffle5/package.json
  packages/hardhat-verify/package.json
  packages/hardhat-vyper/package.json
  packages/hardhat-web3-legacy/package.json
  packages/hardhat-web3/package.json
  yarn.lock
Labels: status:ready

#4109 Add support for Base Goerli testnet
  .changeset/wicked-squids-obey.md
  packages/hardhat-verify/src/chain-config.ts
Labels: status:triaging

#4108 Add explainer about stack traces tests
  packages/hardhat-core/test/internal/hardhat-network/stack-traces/README.md
Labels: status:ready, no changeset needed

#4112 Remove test boilerplate
  packages/eslint-plugin-hardhat-internal-rules/package.json
  packages/eslint-plugin-hardhat-internal-rules/tests/lib/rules/only-hardhat-error.js
  packages/eslint-plugin-hardhat-internal-rules/tests/lib/rules/only-hardhat-plugin-error.js
  packages/eslint-plugin-slow-imports/package.json
  packages/eslint-plugin-slow-imports/tests/lib/rules/no-top-level-external-import.js
  yarn.lock
Labels: status:triaging, no changeset needed

#4111 Re-enable test skipped because of Alchemy bug
  packages/hardhat-core/test/internal/hardhat-network/jsonrpc/client.ts
Labels: status:triaging, no changeset needed

#4114 Fix issues with contract.on
  .changeset/forty-dingos-lie.md
  packages/hardhat-ethers/src/internal/hardhat-ethers-provider.ts
  packages/hardhat-ethers/test/contracts.ts
  packages/hardhat-ethers/test/example-contracts.ts
  packages/hardhat-ethers/test/transactions.ts
Labels: status:ready

#4124 remove duplicate "Other helpers" section
  docs/src/content/hardhat-network-helpers/docs/reference.md
Labels: status:triaging, no changeset needed

#3998 feat: `rethnet_rpc_server` crate
  crates/rethnet_eth/Cargo.toml
  crates/rethnet_eth/src/remote.rs
  crates/rethnet_eth/src/remote/client.rs
  crates/rethnet_eth/src/remote/eth.rs
  crates/rethnet_eth/src/remote/eth/eip712.rs
  crates/rethnet_eth/src/remote/jsonrpc.rs
  crates/rethnet_eth/src/remote/methods.rs
  crates/rethnet_eth/src/remote/serde_with_helpers.rs
  crates/rethnet_evm/benches/state/database_commit.rs
  crates/rethnet_rpc_server/Cargo.toml
  crates/rethnet_rpc_server/src/hardhat_methods.rs
  crates/rethnet_rpc_server/src/hardhat_methods/add_compilation_result.rs
  crates/rethnet_rpc_server/src/hardhat_methods/reset.rs
  crates/rethnet_rpc_server/src/hardhat_methods/test_fixtures/compiler_input.json
  crates/rethnet_rpc_server/src/hardhat_methods/test_fixtures/compiler_output.json
  crates/rethnet_rpc_server/src/lib.rs
  crates/rethnet_rpc_server/tests/integration_tests.rs
  crates/rethnet_test_utils/Cargo.toml
  crates/rethnet_test_utils/src/lib.rs
Labels: status:triaging

#4057 feat: rethnet CLI `node` command
  crates/rethnet/Cargo.toml
  crates/rethnet/src/lib.rs
  crates/rethnet/src/main.rs
  crates/rethnet/tests/cli.rs
  crates/rethnet_rpc_server/Cargo.toml
  crates/rethnet_rpc_server/src/lib.rs
  crates/rethnet_rpc_server/tests/integration_tests.rs
Labels: status:triaging

#4115 Loss of precision when using %d and %i in console.log
  packages/hardhat-core/src/internal/hardhat-network/stack-traces/consoleLogger.ts
  packages/hardhat-core/test/fixture-projects/console-log/.gitignore
  packages/hardhat-core/test/fixture-projects/console-log/contracts/Test.sol
  packages/hardhat-core/test/fixture-projects/console-log/hardhat.config.js
  packages/hardhat-core/test/fixture-projects/console-log/package.json
  packages/hardhat-core/test/internal/hardhat-network/console-log.ts
Labels: status:triaging, no changeset needed

#4128 Fix deletion of valid build-info file
  .changeset/seven-shrimps-tell.md
  packages/hardhat-core/src/internal/artifacts.ts
  packages/hardhat-core/test/builtin-tasks/compile.ts
  packages/hardhat-core/test/fixture-projects/compilation-contract-with-deps/.gitignore
  packages/hardhat-core/test/fixture-projects/compilation-contract-with-deps/contracts/A.sol
  packages/hardhat-core/test/fixture-projects/compilation-contract-with-deps/contracts/C.sol
  packages/hardhat-core/test/fixture-projects/compilation-contract-with-deps/contracts/E.sol
  packages/hardhat-core/test/fixture-projects/compilation-contract-with-deps/hardhat.config.js
  packages/hardhat-core/test/fixture-projects/compilation-contract-with-deps/node_modules/dependency/contracts/console.sol
  packages/hardhat-core/test/fixture-projects/compilation-contract-with-deps/node_modules/dependency/package.json
Labels: status:triaging

#4142 Re-enable hardhat-ethers test
  packages/hardhat-ethers/test/contracts.ts
  yarn.lock
Labels: status:ready, no changeset needed

#4131 Negative block number queried when forked network block number is near zero
  .changeset/healthy-poems-talk.md
  packages/hardhat-core/src/internal/hardhat-network/provider/utils/makeForkClient.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/fork/ForkBlockchain.ts
Labels: type:bug, status:triaging, no changeset needed

#4143 Update create-task.md
  docs/src/content/hardhat-runner/docs/advanced/create-task.md
Labels: status:triaging, no changeset needed

#4152 Don't run changesets check in changesets PR
  .github/workflows/check-changeset-added.yml
Labels: no changeset needed

#4148 [hardhat-vyper] Warn when test mode directive is present in contract sources
  .changeset/five-colts-remain.md
  packages/hardhat-vyper/README.md
  packages/hardhat-vyper/package.json
  packages/hardhat-vyper/src/parser.ts
  packages/hardhat-vyper/test/fixture-projects/compilation-single-file-test-directive/contracts/A.vy
  packages/hardhat-vyper/test/fixture-projects/compilation-single-file-test-directive/hardhat.config.js
  packages/hardhat-vyper/test/tests.ts
Labels: type:bug, status:ready

#4139 debug_traceTransaction ignores "tracer" param
  .changeset/three-maps-judge.md
  packages/hardhat-core/src/internal/core/jsonrpc/types/input/debugTraceTransaction.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/modules/debug.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/debug.ts
Labels: type:bug, status:ready

#4157 Remove engines field from package.json
  packages/hardhat-core/package.json
  packages/hardhat-core/test/internal/cli/node-version.ts
Labels: status:ready, no changeset needed

#4150 Test slow-imports rule
  .github/workflows/test-slow-imports-rule.yml
Labels: status:ready, no changeset needed

#4155 removed abort-controller dependency from core
  .changeset/chilly-meals-enjoy.md
  packages/hardhat-core/package.json
  packages/hardhat-core/src/internal/cli/analytics.ts
  yarn.lock
Labels: status:triaging

#4161 Add credit to a changeset
  .changeset/chilly-meals-enjoy.md
Labels: status:ready, no changeset needed

#4132 improvement: JSON-RPC types
  crates/rethnet/src/lib.rs
  crates/rethnet/tests/cli.rs
  crates/rethnet_eth/src/remote.rs
  crates/rethnet_eth/src/remote/client.rs
  crates/rethnet_eth/src/remote/eth.rs
  crates/rethnet_eth/src/remote/eth/eip712.rs
  crates/rethnet_eth/src/remote/methods.rs
  crates/rethnet_eth/tests/integration_tests.rs
  crates/rethnet_evm/src/state/fork.rs
  crates/rethnet_evm/src/state/remote.rs
  crates/rethnet_rpc_server/Cargo.toml
  crates/rethnet_rpc_server/src/lib.rs
  crates/rethnet_rpc_server/tests/integration_tests.rs
  crates/rethnet_test_utils/src/lib.rs
Labels: status:triaging, area:rethnet

#4177 improvement: simplify sync RwLock types
  crates/rethnet_evm/src/block/builder.rs
  crates/rethnet_evm/src/runtime.rs
  crates/rethnet_evm_napi/src/blockchain.rs
  crates/rethnet_evm_napi/src/state.rs
  crates/rethnet_rpc_server/src/lib.rs
Labels: status:triaging, area:rethnet

#3895 Handle 429 responses withouto retry-after header
  .changeset/ten-hairs-attend.md
  packages/hardhat-core/src/internal/core/providers/http.ts
  packages/hardhat-core/test/internal/core/providers/http.ts
Labels: status:triaging

#4183 feat: add eth_blockNumber & eth_chainId calls to client
  crates/rethnet_eth/src/remote/client.rs
Labels: status:triaging, area:edr

#4181 fix: test-remote feature flag
  crates/rethnet_eth/Cargo.toml
Labels: status:triaging, area:edr

#4182 feat: add helper functions for determining spec
  crates/rethnet_eth/src/lib.rs
  crates/rethnet_eth/src/spec.rs
Labels: status:triaging, area:edr

#4189 feat: add factory functions for block tags
  crates/rethnet_eth/src/remote.rs
Labels: status:triaging, area:edr

#4191 fix: Block & Transaction RPC types
  crates/rethnet_eth/src/remote/client.rs
  crates/rethnet_eth/src/remote/eth.rs
  crates/rethnet_eth/src/remote/serde_with_helpers.rs
  crates/rethnet_eth/src/spec.rs
Labels: status:triaging, area:edr

#4192 improvement: capture rpc server test output
  crates/rethnet_rpc_server/tests/integration_tests.rs
Labels: status:triaging

#4162 docs: add `cargo doc` to CI & git hook
  .github/workflows/hardhat-core-ci.yml
  crates/rethnet_eth/src/remote/serde_with_helpers.rs
  crates/rethnet_eth/src/transaction.rs
  crates/rethnet_eth/src/utils.rs
  crates/rethnet_evm/src/blockchain.rs
  crates/rethnet_evm/src/state.rs
  crates/rethnet_evm/src/state/debug.rs
  crates/rethnet_evm/src/state/history.rs
  crates/rethnet_evm/src/state/layered/changes.rs
  crates/rethnet_evm/src/trace.rs
Labels: status:triaging

#4095 test: Add Rethnet provider as JSON-RPC provider in Hardhat tests
  crates/rethnet/tests/cli.rs
  crates/rethnet_eth/src/remote.rs
  crates/rethnet_eth/src/remote/methods.rs
  crates/rethnet_eth/tests/integration_tests.rs
  crates/rethnet_evm/src/state/hybrid.rs
  crates/rethnet_rpc_server/src/lib.rs
  crates/rethnet_rpc_server/tests/integration_tests.rs
  packages/hardhat-core/test/internal/hardhat-network/helpers/providers.ts
  packages/hardhat-core/test/internal/hardhat-network/helpers/spawnRethnetProvider.ts
  packages/hardhat-core/test/internal/hardhat-network/helpers/useProvider.ts
  packages/hardhat-core/test/setup.ts
Labels: status:triaging

#4184 Upgrade to typescript v5
  .github/workflows/compile-with-typescript-v4.yml
  package.json
  packages/hardhat-chai-matchers/package.json
  packages/hardhat-core/package.json
  packages/hardhat-core/src/internal/hardhat-network/provider/fork/rpcToTxData.ts
  packages/hardhat-core/src/internal/util/unsafe.ts
  packages/hardhat-ethers/package.json
  packages/hardhat-foundry/package.json
  packages/hardhat-ledger/package.json
  packages/hardhat-network-helpers/package.json
  packages/hardhat-shorthand/package.json
  packages/hardhat-solhint/package.json
  packages/hardhat-solpp/package.json
  packages/hardhat-toolbox/package.json
  packages/hardhat-truffle4/package.json
  packages/hardhat-truffle5/package.json
  packages/hardhat-verify/package.json
  packages/hardhat-vyper/package.json
  packages/hardhat-web3-legacy/package.json
  packages/hardhat-web3/package.json
  yarn.lock
Labels: status:ready, no changeset needed

#4201 Make flatten task smarter: improve warning messages and add check for null metadata
  packages/hardhat-core/src/builtin-tasks/flatten.ts
  packages/hardhat-core/test/builtin-tasks/flatten.ts
  packages/hardhat-core/test/fixture-projects/flatten-task/no-contracts/hardhat.config.js
Labels: status:ready, no changeset needed

#4154 Pure console.sol
  .changeset/slimy-dots-prove.md
  packages/hardhat-core/console.sol
  packages/hardhat-core/scripts/console-library-generator.js
  packages/hardhat-core/test/internal/hardhat-network/stack-traces/test-files/version-independent/pure-console-log/c.sol
  packages/hardhat-core/test/internal/hardhat-network/stack-traces/test-files/version-independent/pure-console-log/test.json
Labels: type:improvement, status:ready, area:console-log

#4198 Hardhat verify external api
  .changeset/warm-taxis-sneeze.md
  packages/hardhat-verify/.eslintignore
  packages/hardhat-verify/.eslintrc.js
  packages/hardhat-verify/.gitignore
  packages/hardhat-verify/.prettierignore
  packages/hardhat-verify/package.json
  packages/hardhat-verify/src/etherscan.ts
  packages/hardhat-verify/src/index.ts
  packages/hardhat-verify/src/internal/abi-validation-extras.ts
  packages/hardhat-verify/src/internal/chain-config.ts
  packages/hardhat-verify/src/internal/config.ts
  packages/hardhat-verify/src/internal/errors.ts
  packages/hardhat-verify/src/internal/etherscan.ts
  packages/hardhat-verify/src/internal/solc/artifacts.ts
  packages/hardhat-verify/src/internal/solc/bytecode.ts
  packages/hardhat-verify/src/internal/solc/metadata.ts
  packages/hardhat-verify/src/internal/task-names.ts
  packages/hardhat-verify/src/internal/type-extensions.ts
  packages/hardhat-verify/src/internal/undici.ts
  packages/hardhat-verify/src/internal/utilities.ts
  packages/hardhat-verify/src/tsconfig.json
  packages/hardhat-verify/test/.eslintrc.js
  packages/hardhat-verify/test/helpers.ts
  packages/hardhat-verify/test/integration/index.ts
  packages/hardhat-verify/test/unit/chain-config.ts
  packages/hardhat-verify/test/unit/config.ts
  packages/hardhat-verify/test/unit/etherscan.ts
  packages/hardhat-verify/test/unit/index.ts
  packages/hardhat-verify/test/unit/solc/artifacts.ts
  packages/hardhat-verify/test/unit/solc/metadata.ts
  packages/hardhat-verify/test/unit/utilities.ts
  packages/hardhat-verify/tsconfig.json
Labels: status:ready

#4202 Add support for solc 0.8.21
  .changeset/quick-pumas-rest.md
  docs/src/content/hardhat-runner/docs/reference/solidity-support.md
  packages/hardhat-core/src/internal/hardhat-network/stack-traces/constants.ts
  packages/hardhat-core/test/fixture-projects/solidity-config-warnings/multiple-unsupported-solc.js
  packages/hardhat-core/test/fixture-projects/solidity-config-warnings/unsupported-new-solc.js
  packages/hardhat-core/test/fixture-projects/solidity-config-warnings/unsupported-solc-in-override.js
  packages/hardhat-core/test/internal/hardhat-network/stack-traces/compilers-list.ts
  packages/hardhat-core/test/internal/hardhat-network/stack-traces/test.ts
Labels: status:ready
