Repository NomicFoundation/hardhat, pull requests merged in 2023-09, with the labels that each got.

#4356 fix: make sure code can be fetched by hash
  crates/rethnet_evm/src/state/remote/cached.rs
Labels: area:edr

#4357 docs: add rust backtrace instructions
  Cargo.lock
  book/src/01_getting_started/03_test.md
Labels: area:edr

#4360 fix: cache block numbers for block time duration
  crates/rethnet_defaults/src/lib.rs
  crates/rethnet_eth/src/block.rs
  crates/rethnet_eth/src/block/reorg.rs
  crates/rethnet_eth/src/remote/client.rs
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/hardhat.ts
Labels: status:triaging, area:edr

#4364 ci: fix clippy custom rules not applied
  .cargo-husky/hooks/pre-commit
  .github/workflows/hardhat-core-ci.yml
Labels: status:triaging, area:edr

#4345 fix: avoid disk cache write race conditions
  crates/rethnet_eth/Cargo.toml
  crates/rethnet_eth/src/remote/client.rs
Labels: area:edr

#4363 refactor: add node type for RPC
  Cargo.lock
  crates/rethnet_eth/src/block.rs
  crates/rethnet_eth/src/block/reorg.rs
  crates/rethnet_evm/Cargo.toml
  crates/rethnet_evm/src/blockchain/forked.rs
  crates/rethnet_evm/src/blockchain/local.rs
  crates/rethnet_evm/src/blockchain/remote.rs
  crates/rethnet_evm/src/state.rs
  crates/rethnet_evm/src/state/irregular.rs
  crates/rethnet_evm/tests/blockchain.rs
  crates/rethnet_rpc_server/Cargo.toml
  crates/rethnet_rpc_server/src/lib.rs
  crates/rethnet_rpc_server/src/node.rs
Labels: status:triaging, area:edr

#4370 fix: WETH contract test
  crates/rethnet_evm/benches/state/state_debug.rs
  crates/rethnet_evm/src/state/fork.rs
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/dual.ts
Labels: type:bug

#4371 fix: pre-merge genesis block difficulty
  crates/rethnet_eth/src/block.rs
Labels: type:bug, area:edr

#4374 Don't add edr issues/prs to the project
  .github/workflows/add-issue-to-project.yml
Labels: status:ready, no changeset needed

#4372 refactor: make ForkState construction fallible
  crates/rethnet_evm/benches/state/util.rs
  crates/rethnet_evm/src/state/fork.rs
  crates/rethnet_evm/src/state/remote.rs
  crates/rethnet_evm/src/state/remote/cached.rs
  crates/rethnet_evm_napi/src/block/builder.rs
  crates/rethnet_evm_napi/src/blockchain.rs
  crates/rethnet_evm_napi/src/context.rs
  crates/rethnet_evm_napi/src/state.rs
  crates/rethnet_evm_napi/test/evm/StateManager.ts
  crates/rethnet_rpc_server/src/lib.rs
  packages/hardhat-core/src/internal/hardhat-network/provider/RethnetState.ts
Labels: area:edr

#4369 fix: MemPool update logic
  crates/rethnet_evm/src/mempool.rs
  crates/rethnet_evm/src/miner.rs
Labels: type:bug, area:edr

#4375 fix: align Hardhat Network safe reorg depth with Rethnet
  packages/hardhat-core/src/internal/hardhat-network/provider/utils/reorgs-protection.ts
Labels: status:triaging

#4379 refactor: lazily fetch remote receipts
  crates/rethnet_eth/src/block.rs
  crates/rethnet_eth/src/block/detailed.rs
  crates/rethnet_eth/tests/receipt.rs
  crates/rethnet_eth/tests/transaction.rs
  crates/rethnet_evm/src/block.rs
  crates/rethnet_evm/src/block/builder.rs
  crates/rethnet_evm/src/block/local.rs
  crates/rethnet_evm/src/block/remote.rs
  crates/rethnet_evm/src/blockchain.rs
  crates/rethnet_evm/src/blockchain/forked.rs
  crates/rethnet_evm/src/blockchain/local.rs
  crates/rethnet_evm/src/blockchain/remote.rs
  crates/rethnet_evm/src/blockchain/storage.rs
  crates/rethnet_evm/src/blockchain/storage/contiguous.rs
  crates/rethnet_evm/src/blockchain/storage/reservable.rs
  crates/rethnet_evm/src/blockchain/storage/sparse.rs
  crates/rethnet_evm/src/evm.rs
  crates/rethnet_evm/src/miner.rs
  crates/rethnet_evm/src/runtime.rs
  crates/rethnet_evm/tests/blockchain.rs
  crates/rethnet_evm_napi/src/block.rs
  crates/rethnet_evm_napi/src/block/builder.rs
  crates/rethnet_evm_napi/src/blockchain.rs
  crates/rethnet_evm_napi/src/blockchain/js_blockchain.rs
  crates/rethnet_evm_napi/src/miner/result.rs
  crates/rethnet_rpc_server/src/filter.rs
  crates/rethnet_rpc_server/src/lib.rs
  crates/rethnet_rpc_server/src/node.rs
Labels: area:edr

#4380 ci: use cargo hack instead of cargo check
  .github/workflows/hardhat-core-ci.yml
  crates/rethnet_eth/src/block.rs
  crates/rethnet_eth/src/signature.rs
Labels: status:triaging, area:edr

#4353 Add "debug_traceCall" JSON-RPC method
  .changeset/orange-paws-promise.md
  .gitignore
  docs/src/content/hardhat-network/docs/reference/index.md
  packages/hardhat-core/src/internal/hardhat-network/provider/modules/base.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/modules/debug.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/modules/eth.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/node.ts
  packages/hardhat-core/test/fixture-debug-traces/traceCall/contractAGetMessage.ts
  packages/hardhat-core/test/fixture-debug-traces/traceCall/contractAGetMessageDebugConfig.ts
  packages/hardhat-core/test/fixture-debug-traces/traceCall/contractAThrowError.ts
  packages/hardhat-core/test/fixture-debug-traces/traceCall/ethTransfer.ts
  packages/hardhat-core/test/internal/hardhat-network/helpers/contracts.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/debug/traceCall.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/debug/traceTransaction.ts
Labels: status:ready

#4393 Ethereum Studio is no longer available
  docs/src/content/hardhat-network/docs/overview/index.md
Labels: status:ready, no changeset needed

#4396 Add more info to Truffle's migration guide
  docs/src/content/hardhat-runner/docs/other-guides/truffle-migration.md
Labels: status:ready, no changeset needed

#4397 Add /debug/ to .gitignore
  .gitignore
Labels: status:ready, no changeset needed

#4401 fix: use TryCast for B256 in napi to avoid panics
  crates/rethnet_evm_napi/src/access_list.rs
  crates/rethnet_evm_napi/src/account.rs
  crates/rethnet_evm_napi/src/block.rs
  crates/rethnet_evm_napi/src/blockchain.rs
  crates/rethnet_evm_napi/src/cast.rs
  crates/rethnet_evm_napi/src/context.rs
  crates/rethnet_evm_napi/src/mempool.rs
  crates/rethnet_evm_napi/src/miner.rs
  crates/rethnet_evm_napi/src/state.rs
  crates/rethnet_evm_napi/src/transaction/request.rs
  crates/rethnet_evm_napi/src/transaction/signed/eip1559.rs
  crates/rethnet_evm_napi/src/transaction/signed/eip2930.rs
Labels: area:edr

#4384 Add hh init command
  .changeset/friendly-moles-explode.md
  packages/hardhat-core/src/internal/cli/cli.ts
  packages/hardhat-core/src/internal/core/errors-list.ts
Labels: status:ready

#4417 fix: revm bug when balance check disabled
  Cargo.lock
  crates/rethnet_eth/Cargo.toml
  crates/rethnet_evm/Cargo.toml
  crates/rethnet_evm/src/block/builder.rs
  crates/rethnet_evm/src/transaction.rs
  crates/rethnet_evm/src/transaction/pending.rs
  crates/rethnet_evm_napi/src/block.rs
  crates/rethnet_evm_napi/src/transaction/request.rs
  crates/rethnet_evm_napi/src/transaction/result.rs
  crates/rethnet_rpc_server/src/lib.rs
  packages/hardhat-core/src/internal/hardhat-network/provider/modules/eth.ts
Labels: area:edr

#4419 improvement: add more tracing markers
  crates/rethnet_evm/src/block/builder.rs
  crates/rethnet_evm/src/collections/shared_map.rs
  crates/rethnet_evm/src/mempool.rs
  crates/rethnet_evm/src/miner.rs
  crates/rethnet_evm/src/state/fork.rs
  crates/rethnet_evm_napi/src/mempool.rs
  crates/rethnet_evm_napi/src/miner.rs
Labels: area:edr

#4394 Update docs for the new CLI command `init`
  docs/src/components/mdxComponents/CodeBlocks.stories.tsx
  docs/src/content/hardhat-runner/docs/advanced/hardhat-and-foundry.md
  docs/src/content/hardhat-runner/docs/advanced/scripts.md
  docs/src/content/hardhat-runner/docs/advanced/using-esm.md
  docs/src/content/hardhat-runner/docs/getting-started/index.md
  docs/src/content/hardhat-runner/docs/guides/project-setup.md
  docs/src/content/hardhat-runner/docs/guides/typescript.md
  docs/src/content/hardhat-runner/docs/other-guides/truffle-testing.md
  docs/src/content/hardhat-runner/docs/other-guides/waffle-testing.md
  docs/src/content/tutorial/creating-a-new-hardhat-project.md
  packages/hardhat-core/README.md
Labels: status:ready, no changeset needed

#4398 feat: debug trace transaction
  crates/rethnet_evm/src/debug_trace.rs
  crates/rethnet_evm/src/lib.rs
  crates/rethnet_evm_napi/src/debug_trace.rs
  crates/rethnet_evm_napi/src/lib.rs
  packages/hardhat-core/src/internal/hardhat-network/provider/context/rethnet.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/miner/rethnet.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/utils/convertToRethnet.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/block-builder/rethnet.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/dual.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/rethnet.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/vm-adapter.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/debug.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/utils/assertEqualTraces.ts
Labels: area:edr
