Repository NomicFoundation/hardhat, pull requests merged in 2024-10, with the labels that each got.

#5790 feat: expose getTmpDir helper from the test utils
  v-next/hardhat-test-utils/src/fs.ts
  v-next/hardhat/test/internal/builtin-plugins/console/task-action.ts
Labels: status:ready

#5789 feat: add doNotUseFetch helper to the test utils
  v-next/hardhat-test-utils/src/global.ts
  v-next/hardhat-test-utils/src/index.ts
Labels: status:ready

#5780 add skeleton EDR Solidity Testing integration
  pnpm-lock.yaml
  v-next/example-project/.gitignore
  v-next/example-project/contracts/Counter.sol
  v-next/example-project/contracts/Counter.t.sol
  v-next/example-project/contracts/Rocket.sol
  v-next/hardhat-build-system/package.json
  v-next/hardhat-build-system/src/internal/solidity/compiler/compiler-input.ts
  v-next/hardhat-errors/src/descriptors.ts
  v-next/hardhat/package.json
  v-next/hardhat/src/internal/builtin-plugins/artifacts/artifacts-manager.ts
  v-next/hardhat/src/internal/builtin-plugins/artifacts/hook-handlers/hre.ts
  v-next/hardhat/src/internal/builtin-plugins/compile/index.ts
  v-next/hardhat/src/internal/builtin-plugins/compile/task-action.ts
  v-next/hardhat/src/internal/builtin-plugins/index.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity-test/helpers.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity-test/index.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity-test/task-action.ts
  v-next/hardhat/test/internal/cli/main.ts
  v-next/hardhat/tsconfig.json
Labels: status:ready, no changeset needed

#5799 chore: bump EDR to 0.6.3
  .changeset/healthy-pets-poke.md
  packages/hardhat-core/package.json
  pnpm-lock.yaml
Labels: status:ready

#5800 Update hot-spoons-sparkle.md from `minor` to `patch`
  .changeset/hot-spoons-sparkle.md
Labels: status:ready, no changeset needed

#5801 Revert "feat: add doNotUseFetch helper to the test utils"
  v-next/hardhat-test-utils/src/global.ts
  v-next/hardhat-test-utils/src/index.ts
Labels: status:ready

#5774 feat: implement alpha of hardhat --init for v3
  .github/workflows/v-next-ci.yml
  pnpm-lock.yaml
  pnpm-workspace.yaml
  v-next/hardhat-errors/src/descriptors.ts
  v-next/hardhat-utils/src/package.ts
  v-next/hardhat/package.json
  v-next/hardhat/src/internal/cli/init/constants.ts
  v-next/hardhat/src/internal/cli/init/init.ts
  v-next/hardhat/src/internal/cli/init/package-manager.ts
  v-next/hardhat/src/internal/cli/init/project-creation.ts
  v-next/hardhat/src/internal/cli/init/prompt.ts
  v-next/hardhat/src/internal/cli/init/sample-config-file.ts
  v-next/hardhat/src/internal/cli/init/subprocess.ts
  v-next/hardhat/src/internal/cli/init/template.ts
  v-next/hardhat/src/internal/cli/main.ts
  v-next/hardhat/src/internal/config-loading.ts
  v-next/hardhat/src/internal/utils/package.ts
  v-next/hardhat/templates/README.md
  v-next/hardhat/templates/empty-javascript/.gitignore
  v-next/hardhat/templates/empty-javascript/README.md
  v-next/hardhat/templates/empty-javascript/hardhat.config.js
  v-next/hardhat/templates/empty-javascript/package.json
  v-next/hardhat/templates/empty-typescript/.gitignore
  v-next/hardhat/templates/empty-typescript/README.md
  v-next/hardhat/templates/empty-typescript/hardhat.config.ts
  v-next/hardhat/templates/empty-typescript/package.json
  v-next/hardhat/templates/empty-typescript/tsconfig.json
  v-next/hardhat/templates/javascript-with-examples/.gitignore
  v-next/hardhat/templates/javascript-with-examples/README.md
  v-next/hardhat/templates/javascript-with-examples/hardhat.config.js
  v-next/hardhat/templates/javascript-with-examples/package.json
  v-next/hardhat/templates/javascript-with-examples/test/node/example.js
  v-next/hardhat/templates/typescript-with-examples/.gitignore
  v-next/hardhat/templates/typescript-with-examples/README.md
  v-next/hardhat/templates/typescript-with-examples/hardhat.config.ts
  v-next/hardhat/templates/typescript-with-examples/package.json
  v-next/hardhat/templates/typescript-with-examples/test/node/example.ts
  v-next/hardhat/templates/typescript-with-examples/tsconfig.json
  v-next/hardhat/test/fixture-projects/cli/init/empty-folder/.gitignore
  v-next/hardhat/test/fixture-projects/cli/init/valid-project-config/.gitignore
  v-next/hardhat/test/internal/cli/init/init.ts
  v-next/hardhat/test/internal/cli/init/package-manager.ts
  v-next/hardhat/test/internal/cli/init/project-creation.ts
  v-next/hardhat/test/internal/cli/init/prompt.ts
  v-next/hardhat/test/internal/cli/init/subprocess.ts
  v-next/hardhat/test/internal/cli/init/template.ts
  v-next/hardhat/tsconfig.json
Labels: v-next

#5797 docs: fix spelling issues
  packages/hardhat-foundry/README.md
  packages/hardhat-solpp/README.md
Labels: status:triaging, no changeset needed

#5779 test: reduce hardhat-node-test-reporter's integration tests flakiness
  v-next/hardhat-node-test-reporter/integration-tests/index.ts
Labels: status:ready

#5805 release updated `v-next` packages
  .changeset/big-points-try.md
  .changeset/config.json
  .changeset/curly-wombats-wink.md
  .changeset/fuzzy-dolls-flash.md
  .changeset/pre.json
  .changeset/quick-islands-appear.md
  pnpm-lock.yaml
  v-next/example-project/package.json
  v-next/hardhat-build-system/package.json
  v-next/hardhat-errors/package.json
  v-next/hardhat-ethers/package.json
  v-next/hardhat-keystore/package.json
  v-next/hardhat-mocha-test-runner/package.json
  v-next/hardhat-network-helpers/package.json
  v-next/hardhat-node-test-reporter/package.json
  v-next/hardhat-node-test-runner/package.json
  v-next/hardhat-utils/package.json
  v-next/hardhat-zod-utils/package.json
  v-next/hardhat/package.json
  v-next/hardhat/src/cli.ts
  v-next/hardhat/templates/empty-javascript/package.json
  v-next/hardhat/templates/empty-typescript/package.json
  v-next/hardhat/templates/javascript-with-examples/package.json
  v-next/hardhat/templates/typescript-with-examples/package.json
  v-next/template-package/package.json
Labels: status:ready, no changeset needed

#5802 chore: Add hardhat prefix to homepage and repository.directory fields
  v-next/hardhat-network-helpers/package.json
Labels: status:ready, v-next

#5807 fix: disable console for init tests
  v-next/hardhat-test-utils/src/console.ts
  v-next/hardhat-test-utils/src/index.ts
  v-next/hardhat/test/internal/cli/init/init.ts
Labels: status:ready

#5794 Add global parameters to docs
  docs/src/content/ignition/docs/guides/deploy.md
Labels: no changeset needed

#5813 Load type-extensions when the user imports hardhat/types/plugins
  v-next/hardhat/src/config.ts
  v-next/hardhat/src/hre.ts
  v-next/hardhat/src/index.ts
  v-next/hardhat/src/types/plugins.ts
Labels: status:ready

#5810 Move V2 wrapped providers to v3
  v-next/hardhat-errors/src/descriptors.ts
  v-next/hardhat-utils/src/hex.ts
  v-next/hardhat-utils/test/hex.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/hook-handlers/network.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/index.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/json-rpc-request-modifiers/chain-id/chain-id-validator.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/json-rpc-request-modifiers/chain-id/chain-id.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/json-rpc-request-modifiers/gas-properties/automatic-gas-price.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/json-rpc-request-modifiers/gas-properties/automatic-gas.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/json-rpc-request-modifiers/gas-properties/fixed-gas-price.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/json-rpc-request-modifiers/gas-properties/fixed-gas.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/json-rpc-request-modifiers/gas-properties/multiplied-gas-estimation.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/json-rpc-request-modifiers/json-rpc-request-modifier.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/json-rpc-request-modifiers/utils.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/json-rpc.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/json-rpc-request-modifiers/e2e/chain-id.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/json-rpc-request-modifiers/e2e/gas/automatic-gas-price.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/json-rpc-request-modifiers/e2e/gas/automatic-gas.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/json-rpc-request-modifiers/e2e/gas/fixed-gas-price.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/json-rpc-request-modifiers/e2e/gas/fixed-gas.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/json-rpc-request-modifiers/ethereum-mocked-provider.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/json-rpc-request-modifiers/hooks-mock.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/json-rpc-request-modifiers/unit/chain-id/chain-id.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/json-rpc-request-modifiers/unit/gas-properties/automatic-gas-price.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/json-rpc-request-modifiers/unit/gas-properties/automatic-gas.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/json-rpc-request-modifiers/unit/gas-properties/fixed-gas-price.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/json-rpc-request-modifiers/unit/gas-properties/fixed-gas.ts
Labels: no changeset needed

#5832 fix: bump EDR to 0.6.4
  .changeset/stupid-paws-sort.md
  packages/hardhat-core/package.json
  pnpm-lock.yaml
Labels: status:ready

#5838 fix: ignore new node test event type added in v22.10.0
  v-next/hardhat-node-test-reporter/src/reporter.ts
Labels: status:ready

#5819 feat: add bytecode module with resolveLinkedBytecode and linkBytecode…
  v-next/hardhat-utils/package.json
  v-next/hardhat-utils/src/bytecode.ts
  v-next/hardhat-utils/src/errors/bytecode.ts
  v-next/hardhat-utils/src/internal/bytecode.ts
  v-next/hardhat-utils/test/bytecode.ts
Labels: status:ready

#5809 feat: replace spec with a custom hardhat solidity test reporter
  v-next/hardhat-errors/src/descriptors.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity-test/formatters.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity-test/helpers.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity-test/index.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity-test/reporter.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity-test/runner.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity-test/task-action.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity-test/types.ts
Labels: status:ready

#5828 feat: format the solidity test output better
  v-next/example-project/contracts/Counter.t.sol
  v-next/hardhat/src/internal/builtin-plugins/solidity-test/formatters.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity-test/reporter.ts
Labels: status:ready

#5846 fix: pass HTTP to EDR
  .changeset/neat-moose-compare.md
  packages/hardhat-core/src/internal/hardhat-network/provider/provider.ts
Labels: status:ready

#5852 Fix a dependency error in hardhat-web3
  .changeset/chilled-cycles-judge.md
  packages/hardhat-web3/package.json
  pnpm-lock.yaml
Labels: status:ready

#5825 Port hardhat-viem to V3
  pnpm-lock.yaml
  v-next/example-project/hardhat.config.ts
  v-next/example-project/package.json
  v-next/example-project/scripts/viem-plugin-example.ts
  v-next/example-project/tsconfig.json
  v-next/example-project/viem-scketch-plugin.ts
  v-next/hardhat-errors/src/descriptors.ts
  v-next/hardhat-viem/.eslintignore
  v-next/hardhat-viem/.eslintrc.cjs
  v-next/hardhat-viem/.gitignore
  v-next/hardhat-viem/.prettierignore
  v-next/hardhat-viem/LICENSE
  v-next/hardhat-viem/README.md
  v-next/hardhat-viem/package.json
  v-next/hardhat-viem/src/index.ts
  v-next/hardhat-viem/src/internal/accounts.ts
  v-next/hardhat-viem/src/internal/chains.ts
  v-next/hardhat-viem/src/internal/clients.ts
  v-next/hardhat-viem/src/internal/contracts.ts
  v-next/hardhat-viem/src/internal/hook-handlers/network.ts
  v-next/hardhat-viem/src/internal/initialization.ts
  v-next/hardhat-viem/src/type-extensions.ts
  v-next/hardhat-viem/src/types.ts
  v-next/hardhat-viem/test/accounts.ts
  v-next/hardhat-viem/test/chains.ts
  v-next/hardhat-viem/test/clients.ts
  v-next/hardhat-viem/test/contracts.ts
  v-next/hardhat-viem/test/fixture-projects/default-ts-project/.gitignore
  v-next/hardhat-viem/test/fixture-projects/default-ts-project/contracts/ConstructorLib.sol
  v-next/hardhat-viem/test/fixture-projects/default-ts-project/contracts/WithConstructorArgs.sol
  v-next/hardhat-viem/test/fixture-projects/default-ts-project/contracts/WithLibs.sol
  v-next/hardhat-viem/test/fixture-projects/default-ts-project/contracts/WithoutConstructorArgs.sol
  v-next/hardhat-viem/test/fixture-projects/default-ts-project/hardhat.config.ts
  v-next/hardhat-viem/test/fixture-projects/default-ts-project/package.json
  v-next/hardhat-viem/test/fixture-projects/default-ts-project/tsconfig.json
  v-next/hardhat-viem/test/hook-handlers/network.ts
  v-next/hardhat-viem/test/utils.ts
  v-next/hardhat-viem/tsconfig.json
Labels: status:ready, v-next

#5847 chore: format buffers in solidity test output as hex strings
  v-next/hardhat/src/internal/builtin-plugins/solidity-test/reporter.ts
Labels: status:ready

#5841 chore: explicitly opt-in to node test events
  v-next/hardhat-node-test-reporter/src/reporter.ts
Labels: status:ready

#5811 feat: add an EDR Provider to the network manager
  pnpm-lock.yaml
  v-next/example-project/test/node/example-test.ts
  v-next/hardhat-errors/src/descriptors.ts
  v-next/hardhat-utils/src/bytes.ts
  v-next/hardhat-utils/src/number.ts
  v-next/hardhat-utils/test/number.ts
  v-next/hardhat/package.json
  v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/edr-provider.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/errors.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/stack-traces/panic-errors.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/stack-traces/solidity-stack-trace.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/stack-traces/stack-trace-solidity-errors.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/stack-traces/stack-traces.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/types/config.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/types/hardfork.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/types/logger.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/types/node-types.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/types/output.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/utils/client-version.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/utils/console-log-signatures.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/utils/console-logger.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/utils/convert-to-edr.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/utils/hardfork.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/utils/logger.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/hook-handlers/config.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/json-rpc-request-modifiers/json-rpc-request-modifier.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/network-manager.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/type-extensions/config.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/type-validation.ts
  v-next/hardhat/src/internal/constants.ts
  v-next/hardhat/src/types/providers.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/hook-handlers/config.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/json-rpc-request-modifiers/e2e/chain-id.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/json-rpc-request-modifiers/e2e/gas/automatic-gas-price.ts
Labels: status:ready, no changeset needed, v-next

#5767 General dependency cleanup
  .changeset/light-beds-tap.md
  .changeset/purple-starfishes-drive.md
  .changeset/smart-rocks-develop.md
  .changeset/unlucky-humans-dream.md
  config/eslint/constants.js
  packages/hardhat-core/package.json
  packages/hardhat-core/src/builtin-tasks/compile.ts
  packages/hardhat-core/src/builtin-tasks/flatten.ts
  packages/hardhat-core/src/builtin-tasks/node.ts
  packages/hardhat-core/src/builtin-tasks/test.ts
  packages/hardhat-core/src/builtin-tasks/utils/watch.ts
  packages/hardhat-core/src/internal/cli/autocomplete.ts
  packages/hardhat-core/src/internal/cli/bootstrap.ts
  packages/hardhat-core/src/internal/cli/cli.ts
  packages/hardhat-core/src/internal/cli/project-creation.ts
  packages/hardhat-core/src/internal/cli/vars.ts
  packages/hardhat-core/src/internal/cli/version-notifier.ts
  packages/hardhat-core/src/internal/core/config/config-loading.ts
  packages/hardhat-core/src/internal/core/project-structure.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/provider.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/utils/fork-recomendations-banner.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/utils/makeForkClient.ts
  packages/hardhat-core/src/internal/hardhat-network/stack-traces/vm-trace-decoder.ts
  packages/hardhat-core/src/internal/sentry/anonymizer.ts
  packages/hardhat-core/src/internal/util/caller-package.ts
  packages/hardhat-core/src/internal/util/glob.ts
  packages/hardhat-core/src/internal/util/packageInfo.ts
  packages/hardhat-core/test/builtin-tasks/flatten.ts
  packages/hardhat-core/test/internal/cli/vars/vars.ts
  packages/hardhat-core/test/internal/sentry/anonymizer.ts
  packages/hardhat-core/test/setup.ts
  packages/hardhat-ethers/package.json
  packages/hardhat-ethers/test/environment.ts
  packages/hardhat-foundry/package.json
  packages/hardhat-foundry/src/foundry.ts
  packages/hardhat-foundry/src/index.ts
  packages/hardhat-verify/package.json
  packages/hardhat-verify/src/index.ts
  packages/hardhat-verify/src/internal/config.ts
  packages/hardhat-verify/src/internal/tasks/sourcify.ts
  packages/hardhat-verify/src/internal/utilities.ts
  packages/hardhat-verify/test/unit/utilities.ts
  packages/hardhat-viem/package.json
  pnpm-lock.yaml
Labels: status:triaging

#5866 Run `v-next`'s CI on chained PRs
  .github/workflows/v-next-ci.yml
Labels: status:ready

#5829 feat: enhance the solidity test artifacts discovery
  pnpm-lock.yaml
  v-next/hardhat/src/internal/builtin-plugins/solidity-test/helpers.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity-test/task-action.ts
  v-next/hardhat/test/internal/builtin-plugins/solidity-test/helpers.ts
  v-next/hardhat/test/internal/builtin-plugins/solidity-test/test-fixtures/Test.t.sol
Labels: status:ready, v-next

#5859 Rename the `"unknown"` `ChainType` to `"generic"` to be aligned with EDR
  pnpm-lock.yaml
  v-next/hardhat-viem/test/hook-handlers/network.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/hook-handlers/config.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/type-validation.ts
  v-next/hardhat/src/types/network.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/hook-handlers/config.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/json-rpc-request-modifiers/e2e/accounts/automatic-sender.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/json-rpc-request-modifiers/e2e/accounts/fixed-sender.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/json-rpc-request-modifiers/e2e/chain-id.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/json-rpc-request-modifiers/e2e/gas/automatic-gas.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/json-rpc-request-modifiers/e2e/gas/fixed-gas-price.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/json-rpc-request-modifiers/e2e/gas/fixed-gas.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/network-connection.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/network-manager.ts
Labels: status:ready, v-next

#5860 Normalize the builtin plugin names
  v-next/hardhat/src/internal/builtin-plugins/artifacts/index.ts
  v-next/hardhat/src/internal/builtin-plugins/clean/index.ts
  v-next/hardhat/src/internal/builtin-plugins/console/index.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/index.ts
  v-next/hardhat/src/internal/builtin-plugins/run/index.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity-test/index.ts
Labels: status:ready, v-next

#5863 [build-system] Fix potential clash between user remappings and npm roots
  v-next/example-project/hardhat.config.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/dependency-graph-building.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/resolver/dependency-resolver.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/resolver/types.ts
Labels: status:ready, v-next

#5864 Fix automatic sender hook handler
  v-next/hardhat/src/internal/builtin-plugins/network-manager/json-rpc-request-modifiers/accounts/automatic-sender-provider.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/json-rpc-request-modifiers/accounts/fixed-sender-provider.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/json-rpc-request-modifiers/accounts/sender.ts
Labels: status:ready, v-next

#5865 Small improvements to the config resolution of EDR networks
  v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/edr-provider.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/hook-handlers/config.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/network-manager.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/type-extensions/config.ts
Labels: status:ready, v-next

#5872 Some small improvements to the EDR network config resolution
  v-next/hardhat/src/internal/builtin-plugins/network-manager/hook-handlers/config.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/type-extensions/config.ts
Labels: status:ready

#5873 Load the builtin plugin types in /types/config
  v-next/hardhat/src/types/config.ts
Labels: status:ready

#5874 Resolve the EDR cache path config
  v-next/hardhat/src/internal/builtin-plugins/network-manager/hook-handlers/config.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/type-extensions/config.ts
Labels: status:ready, v-next

#5875 Ensure clients extended with L2 actions retain original action types
  v-next/hardhat-viem/src/types.ts
  v-next/hardhat-viem/test/clients.ts
Labels: status:ready, v-next

#5876 update HardhatUserConfig import path in templates
  v-next/example-project/hardhat.config.ts
  v-next/hardhat-viem/test/fixture-projects/default-ts-project/hardhat.config.ts
  v-next/hardhat/templates/empty-typescript/hardhat.config.ts
  v-next/hardhat/templates/typescript-with-examples/hardhat.config.ts
  v-next/hardhat/templates/typescript-with-examples/package.json
Labels: status:ready

#5871 Await output streams
  v-next/hardhat-node-test-runner/src/task-action.ts
  v-next/hardhat-utils/package.json
  v-next/hardhat-utils/src/stream.ts
  v-next/hardhat-utils/test/stream.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity-test/task-action.ts
Labels: status:ready, v-next

#5878 update v-next packages
  .changeset/pre.json
  .changeset/strange-ads-sing.md
  pnpm-lock.yaml
  v-next/example-project/package.json
  v-next/hardhat-errors/package.json
  v-next/hardhat-ethers/package.json
  v-next/hardhat-keystore/package.json
  v-next/hardhat-mocha-test-runner/package.json
  v-next/hardhat-network-helpers/package.json
  v-next/hardhat-node-test-reporter/package.json
  v-next/hardhat-node-test-runner/package.json
  v-next/hardhat-utils/package.json
  v-next/hardhat-viem/package.json
  v-next/hardhat-zod-utils/package.json
  v-next/hardhat/package.json
  v-next/hardhat/templates/empty-javascript/package.json
  v-next/hardhat/templates/empty-typescript/package.json
  v-next/hardhat/templates/javascript-with-examples/package.json
  v-next/hardhat/templates/typescript-with-examples/package.json
  v-next/template-package/package.json
Labels: status:ready

#5806 feat: create a mocha/ethers template project
  .changeset/pre.json
  pnpm-lock.yaml
  v-next/hardhat/templates/mocha-ethers/.gitignore
  v-next/hardhat/templates/mocha-ethers/README.md
  v-next/hardhat/templates/mocha-ethers/contracts/Lock.sol
  v-next/hardhat/templates/mocha-ethers/hardhat.config.ts
  v-next/hardhat/templates/mocha-ethers/package.json
  v-next/hardhat/templates/mocha-ethers/test/Lock.ts
  v-next/hardhat/templates/mocha-ethers/tsconfig.json
Labels: status:ready, v-next

#5877 Change how we print the titles of the test tasks
  v-next/hardhat-mocha-test-runner/src/task-action.ts
  v-next/hardhat-node-test-runner/src/task-action.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity-test/task-action.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/build-system.ts
  v-next/hardhat/src/internal/builtin-plugins/test/task-action.ts
Labels: status:ready

#5882 Hardhat-network-helpers: TODOs as soon as V3 node is ready
  v-next/example-project/scripts/network-helpers.ts
  v-next/hardhat-network-helpers/package.json
  v-next/hardhat-network-helpers/run-tests.ts
  v-next/hardhat-network-helpers/test-tmp/index.ts
  v-next/hardhat-network-helpers/test/assertions.ts
  v-next/hardhat-network-helpers/test/duration/duration.ts
  v-next/hardhat-network-helpers/test/helpers/helpers.ts
  v-next/hardhat-network-helpers/test/index.ts
  v-next/hardhat-network-helpers/test/network-helpers/drop-transaction.ts
  v-next/hardhat-network-helpers/test/network-helpers/get-storage-at.ts
  v-next/hardhat-network-helpers/test/network-helpers/impersonate-account.ts
  v-next/hardhat-network-helpers/test/network-helpers/load-fixture.ts
  v-next/hardhat-network-helpers/test/network-helpers/mine-up-to.ts
  v-next/hardhat-network-helpers/test/network-helpers/mine.ts
  v-next/hardhat-network-helpers/test/network-helpers/reset.ts
  v-next/hardhat-network-helpers/test/network-helpers/set-balance.ts
  v-next/hardhat-network-helpers/test/network-helpers/set-block-gas-limit.ts
  v-next/hardhat-network-helpers/test/network-helpers/set-code.ts
  v-next/hardhat-network-helpers/test/network-helpers/set-coinbase.ts
  v-next/hardhat-network-helpers/test/network-helpers/set-next-block-base-fee-per-gas.ts
  v-next/hardhat-network-helpers/test/network-helpers/set-nonce.ts
  v-next/hardhat-network-helpers/test/network-helpers/set-prevrandao.ts
  v-next/hardhat-network-helpers/test/network-helpers/set-storage-at.ts
  v-next/hardhat-network-helpers/test/network-helpers/stop-impersonating-account.ts
  v-next/hardhat-network-helpers/test/network-helpers/take-snapshot.ts
  v-next/hardhat-network-helpers/test/time/increase-to.ts
  v-next/hardhat-network-helpers/test/time/increase.ts
  v-next/hardhat-network-helpers/test/time/latest-block.ts
  v-next/hardhat-network-helpers/test/time/latest.ts
  v-next/hardhat-network-helpers/test/time/set-next-block-timestamp.ts
Labels: status:triaging, no changeset needed, v-next

#5885 Small `--init` improvements
  v-next/hardhat/src/internal/cli/init/init.ts
  v-next/hardhat/src/internal/cli/init/prompt.ts
  v-next/hardhat/test/internal/cli/init/prompt.ts
Labels: status:ready

#5881 Fix: enable .skipped tests and fix them
  v-next/hardhat-viem/test/chains.ts
  v-next/hardhat-viem/test/clients.ts
  v-next/hardhat-viem/test/contracts.ts
Labels: status:ready, v-next

#5886 Alpha release on 2024-10-29
  .changeset/gold-panthers-kneel.md
  .changeset/pre.json
  pnpm-lock.yaml
  v-next/example-project/package.json
  v-next/hardhat-errors/package.json
  v-next/hardhat-ethers/package.json
  v-next/hardhat-keystore/package.json
  v-next/hardhat-mocha-test-runner/package.json
  v-next/hardhat-network-helpers/package.json
  v-next/hardhat-node-test-reporter/package.json
  v-next/hardhat-node-test-runner/package.json
  v-next/hardhat-utils/package.json
  v-next/hardhat-viem/package.json
  v-next/hardhat-zod-utils/package.json
  v-next/hardhat/package.json
  v-next/hardhat/templates/mocha-ethers/package.json
  v-next/hardhat/templates/node-test-runner-viem/package.json
  v-next/template-package/package.json
Labels: status:ready

#5887 Prevent a shell injection in `--init`
  pnpm-lock.yaml
  v-next/hardhat/src/internal/cli/init/init.ts
  v-next/hardhat/templates/mocha-ethers/package.json
Labels: status:ready

#5888 Fix the EDR Network user config validation
  v-next/hardhat/src/internal/builtin-plugins/network-manager/type-validation.ts
Labels: status:ready

#5889 Small polishing changes
  v-next/hardhat-errors/src/descriptors.ts
  v-next/hardhat-test-utils/src/errors.ts
  v-next/hardhat-test-utils/src/index.ts
  v-next/hardhat-test-utils/test/errors.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/stack-traces/stack-trace-solidity-errors.ts
  v-next/hardhat/src/internal/builtin-plugins/run/task-action.ts
  v-next/hardhat/test/internal/builtin-plugins/run/task-action.ts
Labels: status:ready

#5890 Alpha testing release: 29 Oct 2024 20:00 UTC
  .changeset/calm-ligers-explain.md
  .changeset/pre.json
  pnpm-lock.yaml
  v-next/example-project/package.json
  v-next/hardhat-errors/package.json
  v-next/hardhat-ethers/package.json
  v-next/hardhat-keystore/package.json
  v-next/hardhat-mocha-test-runner/package.json
  v-next/hardhat-network-helpers/package.json
  v-next/hardhat-node-test-reporter/package.json
  v-next/hardhat-node-test-runner/package.json
  v-next/hardhat-test-utils/package.json
  v-next/hardhat-utils/package.json
  v-next/hardhat-viem/package.json
  v-next/hardhat-zod-utils/package.json
  v-next/hardhat/package.json
  v-next/hardhat/templates/mocha-ethers/package.json
  v-next/hardhat/templates/node-test-runner-viem/package.json
  v-next/template-package/package.json
Labels: status:ready

#5891 A few messaging improvements
  v-next/example-project/contracts/Counter.t.sol
  v-next/example-project/contracts/D.sol
  v-next/example-project/contracts/WithForge.t.sol
  v-next/hardhat-mocha-test-runner/src/task-action.ts
  v-next/hardhat-node-test-runner/src/task-action.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity-test/task-action.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/build-system.ts
  v-next/hardhat/src/internal/builtin-plugins/test/task-action.ts
  v-next/hardhat/src/internal/core/tasks/resolved-task.ts
  v-next/hardhat/templates/mocha-ethers/contracts/Counter.sol
  v-next/hardhat/templates/mocha-ethers/contracts/Counter.t.sol
  v-next/hardhat/templates/mocha-ethers/contracts/WithForge.t.sol
  v-next/hardhat/templates/node-test-runner-viem/contracts/Counter.sol
  v-next/hardhat/templates/node-test-runner-viem/contracts/Counter.t.sol
  v-next/hardhat/templates/node-test-runner-viem/contracts/WithForge.t.sol
Labels: status:ready

#5884 Hardhat ethers: enable tests to use V3 node
  v-next/example-project/scripts/hardhat-ethers.ts
  v-next/hardhat-ethers/README.md
  v-next/hardhat-ethers/package.json
  v-next/hardhat-ethers/run-tests.ts
  v-next/hardhat-ethers/test-tmp/index.ts
  v-next/hardhat-ethers/test/contracts.ts
  v-next/hardhat-ethers/test/error-messages.ts
  v-next/hardhat-ethers/test/gas-config.ts
  v-next/hardhat-ethers/test/gas-price.ts
  v-next/hardhat-ethers/test/hardhat-ethers-provider.ts
  v-next/hardhat-ethers/test/hardhat-ethers-signer.ts
  v-next/hardhat-ethers/test/helpers/artifact-manager-mock.ts
  v-next/hardhat-ethers/test/helpers/artifacts/ambiguous-library.ts
  v-next/hardhat-ethers/test/helpers/artifacts/error-messages.ts
  v-next/hardhat-ethers/test/helpers/artifacts/gas-config.ts
  v-next/hardhat-ethers/test/helpers/artifacts/greeter-with-constructor-arg.ts
  v-next/hardhat-ethers/test/helpers/artifacts/greeter.ts
  v-next/hardhat-ethers/test/helpers/artifacts/igreeter.ts
  v-next/hardhat-ethers/test/helpers/artifacts/non-unique-lib.ts
  v-next/hardhat-ethers/test/helpers/artifacts/test-ambiguous-library.ts
  v-next/hardhat-ethers/test/helpers/artifacts/test-contract-lib.ts
  v-next/hardhat-ethers/test/helpers/artifacts/test-library.ts
  v-next/hardhat-ethers/test/helpers/artifacts/test-non-unique-lib.ts
  v-next/hardhat-ethers/test/helpers/example-contracts.ts
  v-next/hardhat-ethers/test/helpers/helpers.ts
  v-next/hardhat-ethers/test/index.ts
  v-next/hardhat-ethers/test/no-accounts.ts
  v-next/hardhat-ethers/test/plugin-functionalities.ts
  v-next/hardhat-ethers/test/provider-events.ts
  v-next/hardhat-ethers/test/transactions.ts
Labels: status:triaging, no changeset needed

#5892 Template improvements
  v-next/hardhat-viem/package.json
  v-next/hardhat/.prettierignore
  v-next/hardhat/src/internal/builtin-plugins/run/task-action.ts
  v-next/hardhat/templates/mocha-ethers/contracts/Counter.t.sol
  v-next/hardhat/templates/mocha-ethers/contracts/Lock.sol
  v-next/hardhat/templates/mocha-ethers/contracts/TestWithForgeStd.t.sol
  v-next/hardhat/templates/mocha-ethers/hardhat.config.ts
  v-next/hardhat/templates/mocha-ethers/scripts/deploy-counter-contract.ts
  v-next/hardhat/templates/mocha-ethers/test/Lock.ts
  v-next/hardhat/templates/mocha-ethers/test/setup.ts
  v-next/hardhat/templates/node-test-runner-viem/contracts/Counter.t.sol
  v-next/hardhat/templates/node-test-runner-viem/contracts/Lock.sol
  v-next/hardhat/templates/node-test-runner-viem/contracts/TestWithForgeStd.t.sol
  v-next/hardhat/templates/node-test-runner-viem/hardhat.config.ts
  v-next/hardhat/templates/node-test-runner-viem/scripts/deploy-counter-contract.ts
  v-next/hardhat/templates/node-test-runner-viem/test/Lock.ts
Labels: status:ready

#5893 Use the `DefaultChainType` as default type parameter
  v-next/hardhat-ethers/src/type-extensions.ts
  v-next/hardhat-network-helpers/src/type-extensions.ts
  v-next/hardhat-viem/src/type-extensions.ts
  v-next/hardhat-viem/src/types.ts
  v-next/hardhat/src/types/network.ts
Labels: status:ready

#5895 Add missing interfaces for hardhat-network-helpers
  v-next/hardhat-network-helpers/package.json
  v-next/hardhat-network-helpers/src/internal/network-helpers/duration/duration.ts
  v-next/hardhat-network-helpers/src/internal/network-helpers/helpers/load-fixture.ts
  v-next/hardhat-network-helpers/src/internal/network-helpers/helpers/reset.ts
  v-next/hardhat-network-helpers/src/internal/network-helpers/network-helpers.ts
  v-next/hardhat-network-helpers/src/internal/network-helpers/time/helpers/increase-to.ts
  v-next/hardhat-network-helpers/src/internal/network-helpers/time/helpers/increase.ts
  v-next/hardhat-network-helpers/src/internal/network-helpers/time/helpers/set-next-block-timestamp.ts
  v-next/hardhat-network-helpers/src/internal/network-helpers/time/time.ts
  v-next/hardhat-network-helpers/src/type-extensions.ts
  v-next/hardhat-network-helpers/src/types.ts
  v-next/hardhat-network-helpers/test/index.ts
  v-next/hardhat-network-helpers/test/network-helpers/drop-transaction.ts
  v-next/hardhat-network-helpers/test/network-helpers/get-storage-at.ts
  v-next/hardhat-network-helpers/test/network-helpers/impersonate-account.ts
  v-next/hardhat-network-helpers/test/network-helpers/load-fixture.ts
  v-next/hardhat-network-helpers/test/network-helpers/mine-up-to.ts
  v-next/hardhat-network-helpers/test/network-helpers/mine.ts
  v-next/hardhat-network-helpers/test/network-helpers/reset.ts
  v-next/hardhat-network-helpers/test/network-helpers/set-balance.ts
  v-next/hardhat-network-helpers/test/network-helpers/set-block-gas-limit.ts
  v-next/hardhat-network-helpers/test/network-helpers/set-code.ts
  v-next/hardhat-network-helpers/test/network-helpers/set-coinbase.ts
  v-next/hardhat-network-helpers/test/network-helpers/set-next-block-base-fee-per-gas.ts
  v-next/hardhat-network-helpers/test/network-helpers/set-nonce.ts
  v-next/hardhat-network-helpers/test/network-helpers/set-prevrandao.ts
  v-next/hardhat-network-helpers/test/network-helpers/set-storage-at.ts
  v-next/hardhat-network-helpers/test/network-helpers/stop-impersonating-account.ts
  v-next/hardhat-network-helpers/test/network-helpers/take-snapshot.ts
  v-next/hardhat-network-helpers/test/time/increase-to.ts
  v-next/hardhat-network-helpers/test/time/increase.ts
  v-next/hardhat-network-helpers/test/time/latest-block.ts
  v-next/hardhat-network-helpers/test/time/latest.ts
  v-next/hardhat-network-helpers/test/time/set-next-block-timestamp.ts
Labels: status:triaging, no changeset needed

#5898 Add missing interfaces for hardhat-ethers
  v-next/hardhat-ethers/src/internal/hardhat-ethers-provider/hardhat-ethers-provider.ts
  v-next/hardhat-ethers/src/internal/signers/signers.ts
  v-next/hardhat-ethers/src/types.ts
  v-next/hardhat-ethers/test/plugin-functionalities.ts
Labels: status:triaging, no changeset needed

#5899 Fix some race conditions when lazy loading things in the HRE hook handlers
  v-next/hardhat/src/internal/builtin-plugins/artifacts/hook-handlers/hre.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/hook-handlers/hre.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/hook-handlers/hre.ts
Labels: status:ready

#5903 update released packages for alpha
  .changeset/pre.json
  .changeset/selfish-queens-double.md
  pnpm-lock.yaml
  v-next/example-project/package.json
  v-next/hardhat-errors/package.json
  v-next/hardhat-ethers/package.json
  v-next/hardhat-keystore/package.json
  v-next/hardhat-mocha-test-runner/package.json
  v-next/hardhat-network-helpers/package.json
  v-next/hardhat-node-test-reporter/package.json
  v-next/hardhat-node-test-runner/package.json
  v-next/hardhat-utils/package.json
  v-next/hardhat-viem/package.json
  v-next/hardhat-zod-utils/package.json
  v-next/hardhat/package.json
  v-next/hardhat/templates/mocha-ethers/package.json
  v-next/hardhat/templates/node-test-runner-viem/package.json
  v-next/template-package/package.json
Labels: status:ready

#5900 [mocha template] Use the NetworkHelpers type
  v-next/hardhat/templates/mocha-ethers/test/Lock.ts
Labels: status:ready

#5906 [quickfix] Add console.sol support
  v-next/hardhat/console.sol
  v-next/hardhat/package.json
  v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/resolver/dependency-resolver.ts
  v-next/hardhat/test/internal/builtin-plugins/solidity/build-system/resolver/dependency-resolver.ts
Labels: status:ready

#5868 Move remaining v2 providers (LocalAccounts and HDWallet)
  pnpm-lock.yaml
  v-next/hardhat-errors/src/descriptors.ts
  v-next/hardhat/package.json
  v-next/hardhat/src/internal/builtin-plugins/network-manager/hook-handlers/network.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/json-rpc-request-modifiers/accounts/derive-private-keys.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/json-rpc-request-modifiers/accounts/hd-wallet.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/json-rpc-request-modifiers/accounts/local-accounts.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/json-rpc-request-modifiers/json-rpc-request-modifier.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/rpc/types/access-list.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/rpc/types/address.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/rpc/types/any.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/rpc/types/data.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/rpc/types/hash.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/rpc/types/quantity.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/rpc/types/tx-request.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/rpc/utils.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/rpc/validate-params.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/json-rpc-request-modifiers/e2e/accounts/hd-wallets.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/json-rpc-request-modifiers/e2e/accounts/local-accounts.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/json-rpc-request-modifiers/ethereum-mocked-provider.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/json-rpc-request-modifiers/unit/accounts/hd-wallet.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/json-rpc-request-modifiers/unit/accounts/local-accounts.ts
Labels: no changeset needed, v-next

#5909 Fix the unionType zod helper
  v-next/hardhat-zod-utils/src/index.ts
  v-next/hardhat-zod-utils/test/index.ts
Labels: status:ready

#5908 Errors and messages improvements
  v-next/hardhat/src/internal/cli/error-handler.ts
  v-next/hardhat/src/internal/cli/init/init.ts
  v-next/hardhat/src/internal/cli/main.ts
  v-next/hardhat/src/internal/cli/node-version.ts
Labels: status:ready

#5912 chore: upgrade edr to v0.6.4-alpha.1
  pnpm-lock.yaml
  v-next/hardhat/package.json
Labels: status:ready

#5913 chore: add @types/node to both templates
  pnpm-lock.yaml
  v-next/hardhat-errors/src/descriptors.ts
  v-next/hardhat/templates/mocha-ethers/package.json
  v-next/hardhat/templates/node-test-runner-viem/package.json
Labels: status:ready

#5914 Accept Configuration Variables in HTTP networks' `accounts`
  v-next/example-project/hardhat.config.ts
  v-next/example-project/scripts/send-op-sepolia-tx.ts
  v-next/hardhat-errors/src/descriptors.ts
  v-next/hardhat-keystore/src/index.ts
  v-next/hardhat-test-utils/src/errors.ts
  v-next/hardhat-test-utils/src/index.ts
  v-next/hardhat-test-utils/src/validations.ts
  v-next/hardhat-test-utils/test/errors.ts
  v-next/hardhat-test-utils/test/validation.ts
  v-next/hardhat-zod-utils/src/index.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/hook-handlers/config.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/json-rpc-request-modifiers/json-rpc-request-modifier.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/type-extensions/config.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/type-validation.ts
  v-next/hardhat/src/internal/cli/main.ts
  v-next/hardhat/src/internal/core/configuration-variables.ts
  v-next/hardhat/src/internal/core/hre.ts
  v-next/hardhat/src/types/config.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/hook-handlers/config.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/json-rpc-request-modifiers/e2e/accounts/automatic-sender.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/json-rpc-request-modifiers/e2e/accounts/fixed-sender.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/json-rpc-request-modifiers/e2e/accounts/hd-wallets.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/json-rpc-request-modifiers/e2e/accounts/local-accounts.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/json-rpc-request-modifiers/e2e/chain-id.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/json-rpc-request-modifiers/e2e/gas/automatic-gas-price.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/json-rpc-request-modifiers/e2e/gas/automatic-gas.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/json-rpc-request-modifiers/e2e/gas/fixed-gas-price.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/json-rpc-request-modifiers/e2e/gas/fixed-gas.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/json-rpc-request-modifiers/hooks-mock.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/network-manager.ts
  v-next/hardhat/test/internal/core/configuration-variables/configuration-variables.ts
Labels: status:ready
