Repository NomicFoundation/hardhat, pull requests merged in 2024-02, with the labels that each got.

#4810 Add @bonadocs/docgen
  docs/src/content/hardhat-runner/plugins/plugins.ts
Labels: no changeset needed

#4811 fix: handle unknown selector error
  crates/edr_provider/src/error.rs
Labels: area:edr

#4816 fix: https://github.com/NomicFoundation/edr/issues/282
  crates/edr_provider/src/error.rs
  packages/hardhat-core/src/internal/hardhat-network/provider/provider.ts
Labels: area:edr

#4819 fix: add cache to snapshot and re-cache irregular states
  crates/edr_evm/src/upcast.rs
  crates/edr_provider/src/data.rs
  crates/edr_provider/src/snapshot.rs
Labels: area:edr

#4825 Send hit for non-scoped deploy task
  packages/hardhat-core/src/internal/cli/analytics.ts
Labels: status:ready, no changeset needed

#4741 Fix typos
  docs/src/content/ignition/docs/advanced/execution.md
  docs/src/content/ignition/docs/advanced/versioning.md
  docs/src/content/ignition/docs/guides/deploy.md
  packages/hardhat-ethers/src/internal/hardhat-ethers-provider.ts
  packages/hardhat-truffle4/test/tests.ts
  packages/hardhat-truffle5/test/tests.ts
Labels: status:triaging

#4795 Fix hardhat-ledger to work with hardhat console
  .changeset/poor-nails-walk.md
  packages/hardhat-ledger/src/internal/with-spinners.ts
Labels: status:triaging

#4765 Assert .revertedWithCustomError and .emit only receives 2 arguments
  .changeset/rare-boats-fetch.md
  packages/hardhat-chai-matchers/src/internal/emit.ts
  packages/hardhat-chai-matchers/src/internal/reverted/revertedWithCustomError.ts
  packages/hardhat-chai-matchers/test/events.ts
  packages/hardhat-chai-matchers/test/reverted/revertedWithCustomError.ts
Labels: status:triaging

#4785 Fix e2e issues
  .github/workflows/e2e-tests.yml
  e2e/clean.sh
  e2e/fixture-projects/clean/test.sh
  e2e/fixture-projects/compile-fail/test.sh
  e2e/fixture-projects/compile/test.sh
  e2e/fixture-projects/flatten/test.sh
  e2e/fixture-projects/gas-reporter/test.sh
  e2e/fixture-projects/help/test.sh
  e2e/fixture-projects/solidity-coverage/test.sh
  e2e/fixture-projects/test/test.sh
  e2e/fixture-projects/vars/test.sh
  e2e/helpers.sh
  e2e/run-fixture-projects.sh
  e2e/test-project-initialization.sh
Labels: status:ready, no changeset needed

#4804 Docs: Using a Custom Solidity Compiler
  docs/src/content/hardhat-runner/docs/advanced/multiple-solidity-versions.md
  docs/src/content/hardhat-runner/docs/other-guides/using-custom-solc.md
Labels: status:triaging, no changeset needed

#4838 Docs[Fix]: Broken Path to Custom Solc Guide
  docs/src/content/hardhat-runner/docs/advanced/multiple-solidity-versions.md
Labels: status:ready, no changeset needed

#4847 Chore/update triaging rules to target
  .github/workflows/autoassign-prs.yml
Labels: status:ready

#4842 test: re-enable ws test
  packages/hardhat-core/src/internal/hardhat-network/provider/provider.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/websocket.ts
Labels: status:ready

#4815 fix: cache block contexts
  .gitignore
  Cargo.lock
  crates/edr_evm/Cargo.toml
  crates/edr_evm/src/block/builder.rs
  crates/edr_evm/src/blockchain/local.rs
  crates/edr_evm/src/blockchain/storage/reservable.rs
  crates/edr_evm/src/upcast.rs
  crates/edr_napi/Cargo.toml
  crates/edr_napi/src/provider.rs
  crates/edr_provider/Cargo.toml
  crates/edr_provider/src/config.rs
  crates/edr_provider/src/data.rs
  crates/edr_provider/src/interval.rs
  crates/edr_provider/src/lib.rs
  crates/edr_provider/src/requests/debug.rs
  crates/edr_provider/src/requests/eth/blockchain.rs
  crates/edr_provider/src/requests/eth/blocks.rs
  crates/edr_provider/src/requests/eth/call.rs
  crates/edr_provider/src/requests/eth/gas.rs
  crates/edr_provider/src/requests/eth/mine.rs
  crates/edr_provider/src/requests/eth/state.rs
  crates/edr_provider/src/requests/eth/transactions.rs
  crates/edr_provider/src/requests/hardhat/state.rs
  crates/edr_provider/src/snapshot.rs
  crates/tools/Cargo.toml
  packages/hardhat-core/src/internal/hardhat-network/provider/utils/convertToEdr.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/getTransactionByHash.ts
Labels: area:edr

#4852 Test new opcodes
  packages/hardhat-core/test/internal/hardhat-network/helpers/contracts.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/node.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/selfdestruct.ts
Labels: status:ready, no changeset needed

#4857 fix: avoid blocking worker threads
  crates/edr_napi/src/provider.rs
  crates/edr_provider/src/lib.rs
Labels: area:edr

#4855 Add support for solc 0.8.24
  .changeset/plenty-roses-enjoy.md
  docs/src/content/hardhat-runner/docs/reference/solidity-support.md
  docs/src/model/markdown.tsx
  packages/hardhat-core/sample-projects/javascript-esm/contracts/Lock.sol
  packages/hardhat-core/sample-projects/javascript-esm/hardhat.config.cjs
  packages/hardhat-core/sample-projects/javascript/contracts/Lock.sol
  packages/hardhat-core/sample-projects/javascript/hardhat.config.js
  packages/hardhat-core/sample-projects/typescript-viem/contracts/Lock.sol
  packages/hardhat-core/sample-projects/typescript-viem/hardhat.config.ts
  packages/hardhat-core/sample-projects/typescript/contracts/Lock.sol
  packages/hardhat-core/sample-projects/typescript/hardhat.config.ts
  packages/hardhat-core/src/internal/cli/project-creation.ts
  packages/hardhat-core/src/internal/hardhat-network/stack-traces/constants.ts
  packages/hardhat-core/src/internal/solidity/compiler/solc-info.ts
  packages/hardhat-core/test/fixture-projects/compilation-latest-solc-version/contracts/A.sol
  packages/hardhat-core/test/fixture-projects/compilation-latest-solc-version/hardhat.config.js
  packages/hardhat-core/test/internal/hardhat-network/stack-traces/compilers-list.ts
Labels: status:ready

#4860 Remove enableTransientStorage custom logic & throw an error if pre-ca…
  packages/hardhat-core/src/internal/core/config/config-resolution.ts
  packages/hardhat-core/src/internal/core/config/config-validation.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/node.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/utils/makeCommon.ts
  packages/hardhat-core/test/internal/core/config/config-resolution.ts
  packages/hardhat-core/test/internal/core/config/config-validation.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/node.ts
Labels: status:ready, no changeset needed

#4856 Reject blob txs with a custom error
  packages/hardhat-core/src/internal/core/jsonrpc/types/input/callRequest.ts
  packages/hardhat-core/src/internal/core/jsonrpc/types/input/transactionRequest.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/modules/eth.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/node-types.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/node.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/call.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/estimateGas.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/sendRawTransaction.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/sendTransaction.ts
Labels: status:ready

#4858 fix: reduce state size cache
  crates/edr_provider/src/data.rs
Labels: area:edr

#4766 improve .withArgs error messages
  .changeset/yellow-dryers-appear.md
  packages/hardhat-chai-matchers/src/internal/bigNumber.ts
  packages/hardhat-chai-matchers/src/internal/emit.ts
  packages/hardhat-chai-matchers/src/internal/reverted/revertedWithCustomError.ts
  packages/hardhat-chai-matchers/src/internal/utils.ts
  packages/hardhat-chai-matchers/test/events.ts
  packages/hardhat-chai-matchers/test/reverted/revertedWithCustomError.ts
Labels: status:triaging

#4864 Fix setStorageAt in untouched addresses
  .changeset/new-rocks-report.md
  .github/workflows/hardhat-network-helpers-ci.yml
  packages/hardhat-core/src/internal/hardhat-network/provider/node.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/hardhat.ts
Labels: status:ready

#4867 Fix 404 supported chains link
  .changeset/modern-pugs-watch.md
  packages/hardhat-viem/src/internal/errors.ts
Labels: status:triaging

#4868 fix: add type field to call request
  crates/edr_eth/src/remote/eth/call_request.rs
  crates/edr_provider/src/requests/eth/call.rs
  crates/edr_provider/tests/eth_request_serialization.rs
Labels: area:edr

#3853 Docs: added the kleros oracle to the supporter guide
  docs/src/content/hardhat-runner/docs/supporter-guides/oracles.md
Labels: status:triaging, no changeset needed

#4869 fix: remove `deny_unknown_fields` from RPC types
  crates/edr_eth/src/remote/eth.rs
  crates/edr_eth/src/remote/eth/call_request.rs
  crates/edr_eth/src/remote/jsonrpc.rs
  crates/edr_eth/src/transaction.rs
Labels: area:edr

#4881 Remove unneeded ethereumjs code and deps
  packages/hardhat-core/package.json
  packages/hardhat-core/src/internal/hardhat-network/provider/fork/ForkStateManager.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/provider.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/utils/convertToEdr.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/exit.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/proxy-vm.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/types.ts
  packages/hardhat-core/src/internal/hardhat-network/stack-traces/vm-debug-tracer.ts
  packages/hardhat-core/src/internal/hardhat-network/stack-traces/vm-tracer.ts
  packages/hardhat-core/src/internal/util/hardforks.ts
  packages/hardhat-core/test/internal/hardhat-network/helpers/retrieveCommon.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/baseFeePerGas.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/fork/ForkStateManager.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/hardforks.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/sendRawTransaction.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/sendTransaction.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/utils/rpcToBlockData.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/utils/rpcToTxData.ts
  packages/hardhat-core/test/internal/hardhat-network/stack-traces/execution.ts
  pnpm-lock.yaml
Labels: status:ready

#4888 fix: don't build edr_napi before testing in CI
  .github/workflows/edr-npm-release.yml
  crates/edr_napi/package.json
Labels: status:triaging, no changeset needed

#4885 Remove edr/main mentions
  .github/workflows/edr-npm-release.yml
  .github/workflows/hardhat-core-ci.yml
  book/src/03_release.md
  book/src/99_contributing.md
  crates/README.md
Labels: status:ready, no changeset needed

#4875 Upgrade hardhat-viem to support viem@2
  .changeset/proud-peas-sort.md
  .github/dependabot.yml
  packages/hardhat-viem/README.md
  packages/hardhat-viem/package.json
  packages/hardhat-viem/src/internal/contracts.ts
  packages/hardhat-viem/src/types.ts
  packages/hardhat-viem/test/integration.ts
  pnpm-lock.yaml
Labels: status:ready

#4900 Temporarily remove EDR changeset
  .changeset/cold-cobras-carry.md
Labels: status:ready

#4897 test: reuse cache for fork mode tests
  .github/workflows/hardhat-core-ci.yml
  Cargo.lock
  crates/edr_eth/Cargo.toml
  crates/edr_eth/tests/receipt.rs
  crates/edr_evm/tests/blockchain.rs
  crates/edr_evm/tests/transaction.rs
  crates/edr_provider/Cargo.toml
  crates/edr_provider/src/data.rs
  crates/edr_provider/src/test_utils.rs
Labels: area:edr

#4895 fix: avoid inserting transactions twice
  crates/edr_evm/src/blockchain.rs
  crates/edr_evm/src/blockchain/forked.rs
  crates/edr_evm/src/blockchain/local.rs
  crates/edr_evm/src/blockchain/remote.rs
  crates/edr_evm/src/blockchain/storage.rs
  crates/edr_evm/src/blockchain/storage/reservable.rs
  crates/edr_evm/src/blockchain/storage/sparse.rs
Labels: status:triaging, area:edr

#4878 Update module parameters docs to include bigint example
  docs/src/content/ignition/docs/guides/deploy.md
Labels: status:ready, no changeset needed

#4896 Move EDR under the `@nomicfoundation` org
  .github/workflows/edr-npm-release.yml
  crates/edr_napi/index.js
  crates/edr_napi/npm/darwin-arm64/README.md
  crates/edr_napi/npm/darwin-arm64/package.json
  crates/edr_napi/npm/darwin-x64/README.md
  crates/edr_napi/npm/darwin-x64/package.json
  crates/edr_napi/npm/linux-arm64-gnu/README.md
  crates/edr_napi/npm/linux-arm64-gnu/package.json
  crates/edr_napi/npm/linux-arm64-musl/README.md
  crates/edr_napi/npm/linux-arm64-musl/package.json
  crates/edr_napi/npm/linux-x64-gnu/README.md
  crates/edr_napi/npm/linux-x64-gnu/package.json
  crates/edr_napi/npm/linux-x64-musl/README.md
  crates/edr_napi/npm/linux-x64-musl/package.json
  crates/edr_napi/npm/win32-arm64-msvc/README.md
  crates/edr_napi/npm/win32-arm64-msvc/package.json
  crates/edr_napi/npm/win32-ia32-msvc/README.md
  crates/edr_napi/npm/win32-ia32-msvc/package.json
  crates/edr_napi/npm/win32-x64-msvc/README.md
  crates/edr_napi/npm/win32-x64-msvc/package.json
  crates/edr_napi/package.json
  packages/hardhat-core/package.json
  packages/hardhat-core/src/internal/hardhat-network/provider/provider.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/utils/convertToEdr.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/exit.ts
  packages/hardhat-core/src/internal/hardhat-network/stack-traces/message-trace.ts
  packages/hardhat-core/src/internal/hardhat-network/stack-traces/vm-tracer.ts
  pnpm-lock.yaml
Labels: status:ready, no changeset needed

#4905 ci: pin napi-rs docker images
  .github/workflows/edr-npm-release.yml
Labels: no changeset needed, area:edr

#4907 edr-0.2.0-alpha.2
  crates/edr_napi/package.json
  packages/hardhat-core/package.json
Labels: status:ready

#4908 Update pnpm-lock.yaml
  pnpm-lock.yaml
Labels: status:ready

#4890 fix: use custom address recovery for fake signature
  crates/edr_eth/src/transaction.rs
  crates/edr_eth/src/transaction/fake_signature.rs
  crates/edr_eth/src/transaction/request.rs
  crates/edr_eth/src/transaction/request/eip155.rs
  crates/edr_eth/src/transaction/request/eip1559.rs
  crates/edr_eth/src/transaction/request/eip2930.rs
  crates/edr_eth/src/transaction/request/eip4844.rs
  crates/edr_eth/src/transaction/request/legacy.rs
  crates/edr_eth/src/transaction/signed.rs
  crates/edr_eth/src/transaction/signed/eip155.rs
  crates/edr_eth/src/transaction/signed/eip1559.rs
  crates/edr_eth/src/transaction/signed/eip2930.rs
  crates/edr_eth/src/transaction/signed/eip4844.rs
  crates/edr_eth/src/transaction/signed/legacy.rs
  crates/edr_evm/src/transaction/executable.rs
  crates/edr_provider/src/requests/eth/transactions.rs
Labels: no changeset needed, area:edr

#4889 fix: Cancun-related tests
  .changeset/new-pandas-dress.md
  crates/edr_eth/src/beacon.rs
  crates/edr_eth/src/block.rs
  crates/edr_eth/src/block/options.rs
  crates/edr_eth/src/lib.rs
  crates/edr_eth/src/remote/eth.rs
  crates/edr_eth/src/remote/eth/call_request.rs
  crates/edr_eth/src/transaction.rs
  crates/edr_evm/src/block/builder.rs
  crates/edr_evm/src/block/local.rs
  crates/edr_evm/src/blockchain.rs
  crates/edr_evm/src/blockchain/forked.rs
  crates/edr_evm/src/blockchain/local.rs
  crates/edr_evm/src/blockchain/storage/reservable.rs
  crates/edr_evm/src/random.rs
  crates/edr_evm/tests/blockchain.rs
  crates/edr_napi/index.d.ts
  crates/edr_napi/src/block.rs
  crates/edr_napi/src/lib.rs
  crates/edr_napi/src/withdrawal.rs
  crates/edr_provider/src/data.rs
  crates/edr_provider/src/error.rs
  crates/edr_provider/src/requests/eth/transactions.rs
  crates/edr_provider/src/requests/validation.rs
  crates/edr_provider/src/snapshot.rs
  crates/edr_provider/tests/eth_request_serialization.rs
  packages/hardhat-core/src/internal/hardhat-network/provider/provider.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/forking-different-hardfork.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/hardforks.ts
Labels: status:ready, area:edr

#4911 fix: avoid recovering address from fake transactions
  crates/edr_provider/src/data.rs
  crates/edr_provider/src/interval.rs
  crates/edr_provider/src/requests/eth/blocks.rs
  crates/edr_provider/src/requests/eth/transactions.rs
Labels: status:triaging, area:edr

#4932 fix: reduce max cached state count
  crates/edr_provider/src/data.rs
Labels: no changeset needed, area:edr

#4933 chore: fix typos
  docs/src/content/hardhat-runner/docs/advanced/building-plugins.md
  docs/src/content/hardhat-vscode/docs/formatting.md
  docs/src/content/ignition/docs/guides/error-handling.md
Labels: status:ready, no changeset needed

#4928 feat: save and replay scenarios
  Cargo.lock
  book/src/02_development/01_tools.md
  crates/edr_eth/src/spec.rs
  crates/edr_evm/src/miner.rs
  crates/edr_napi/Cargo.toml
  crates/edr_napi/package.json
  crates/edr_napi/src/lib.rs
  crates/edr_napi/src/provider.rs
  crates/edr_napi/src/scenarios.rs
  crates/edr_provider/Cargo.toml
  crates/edr_provider/src/config.rs
  crates/edr_provider/src/requests.rs
  crates/tools/Cargo.toml
  crates/tools/src/main.rs
  crates/tools/src/scenario.rs
Labels: no changeset needed, area:edr

#4935 feat: add tool for replaying remote block
  .cargo/config
  .github/workflows/test-recent-mainnet-block.yml
  Cargo.lock
  crates/edr_napi/index.d.ts
  crates/edr_provider/Cargo.toml
  crates/edr_provider/src/data.rs
  crates/edr_provider/src/lib.rs
  crates/edr_provider/src/logger.rs
  crates/edr_provider/src/test_utils.rs
  crates/tools/Cargo.toml
  crates/tools/src/main.rs
  crates/tools/src/remote_block.rs
Labels: no changeset needed, area:edr

#4940 fix: use block builder to replay blocks
  .github/workflows/test-recent-mainnet-block.yml
  crates/edr_napi/index.js
  crates/edr_provider/src/data.rs
  crates/edr_provider/src/test_utils.rs
  packages/hardhat-core/test/internal/hardhat-network/helpers/constants.ts
Labels: status:triaging, no changeset needed, area:edr
