Repository NomicFoundation/hardhat, pull requests merged in 2024-04, with the labels that each got.

#5056 Throw CORRUPTED_LOCKFILE error when requiring EDR fails
  .changeset/tame-apples-admire.md
  packages/hardhat-core/src/common/napi-rs.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/provider.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/utils/convertToEdr.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/exit.ts
  packages/hardhat-core/src/internal/hardhat-network/stack-traces/vm-tracer.ts
  packages/hardhat-core/src/internal/solidity/parse.ts
Labels: status:ready

#5050 chore: fix some comments
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/feeHistory.ts
  packages/hardhat-solpp/test/fixture-projects/hardhat-project/contracts/B.sol
  packages/hardhat-viem/src/internal/clients.ts
Labels: status:triaging, no changeset needed

#5069 fix: increase rate limiting retries
  .changeset/short-rats-double.md
  crates/edr_eth/src/remote/client.rs
Labels: status:ready, area:edr

#5063 feat: add support for tracing to scenario runner
  .cargo/config
  Cargo.lock
  crates/edr_napi/Cargo.toml
  crates/edr_provider/Cargo.toml
  crates/edr_provider/src/data.rs
  crates/tools/Cargo.toml
  crates/tools/src/scenario.rs
Labels: status:ready, no changeset needed, area:edr

#5074 Fix cargo doc warnings
  .github/workflows/hardhat-core-ci.yml
  crates/edr_eth/src/transaction/request.rs
  crates/edr_evm/src/blockchain/forked.rs
  crates/edr_evm/src/transaction.rs
  crates/edr_evm/src/transaction/executable.rs
  crates/edr_provider/src/error.rs
Labels: status:ready, no changeset needed, area:edr

#5067 fix: remove api keys from RPC error messages
  .changeset/brave-scissors-train.md
  Cargo.lock
  crates/edr_eth/Cargo.toml
  crates/edr_eth/src/remote/client.rs
  crates/edr_eth/src/remote/client/reqwest_error.rs
Labels: status:ready, area:edr

#4943 refactor: use mimalloc as global allocator
  Cargo.lock
  crates/edr_napi/Cargo.toml
  crates/edr_napi/src/lib.rs
Labels: status:triaging, no changeset needed, area:edr

#5075 chore: fix some typos
  packages/hardhat-core/src/builtin-tasks/compile.ts
  packages/hardhat-core/src/internal/core/tasks/task-definitions.ts
Labels: status:triaging, no changeset needed

#5077 List ethernaut-cli plugins to docs
  docs/src/content/hardhat-runner/plugins/plugins.ts
Labels: status:ready, no changeset needed

#5076 Check that error object doesn't have unexpected fields
  packages/hardhat-core/test/internal/hardhat-network/provider/error-object.ts
Labels: no changeset needed

#5068 ci: change goerli tests to sepolia
  crates/edr_evm/src/transaction.rs
  crates/edr_evm/src/transaction/executable.rs
  crates/edr_provider/src/data.rs
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/getTransactionByHash.ts
Labels: status:ready, no changeset needed

#5079 test: re-enable evm tests
  crates/edr_evm/src/mempool.rs
  crates/edr_evm/src/test_utils.rs
  crates/edr_evm/tests/mem_pool.rs
  crates/edr_napi/src/provider/config.rs
  crates/edr_provider/src/config.rs
  crates/edr_provider/src/data.rs
  crates/edr_provider/src/error.rs
  crates/edr_provider/src/lib.rs
  crates/edr_provider/src/requests.rs
  crates/edr_provider/src/requests/eth/evm.rs
  crates/edr_provider/src/requests/eth/mine.rs
  crates/edr_provider/src/requests/methods.rs
  crates/edr_provider/src/test_utils.rs
  crates/edr_provider/tests/eth_request_serialization.rs
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/evm.ts
Labels: status:ready, no changeset needed, area:edr

#5085 refactor: retrieve genesis account info in smaller batches
  .changeset/funny-lions-begin.md
  Cargo.toml
  crates/edr_eth/src/remote/client.rs
  crates/edr_evm/src/blockchain/forked.rs
  crates/edr_evm/tests/blockchain.rs
  crates/edr_evm/tests/issue_4974.rs
  crates/edr_evm/tests/optimism.rs
  crates/edr_provider/src/data.rs
  crates/edr_provider/src/test_utils.rs
Labels: status:ready, area:edr

#5087 fix: remove hardfork restriction on eth_getLogs
  .changeset/friendly-steaks-travel.md
  crates/edr_eth/src/remote/filter.rs
  crates/edr_provider/src/requests/eth/filter.rs
  crates/edr_provider/tests/issue_361.rs
Labels: status:ready, area:edr

#5088 edr-0.3.4
  .changeset/brave-scissors-train.md
  .changeset/friendly-steaks-travel.md
  .changeset/funny-lions-begin.md
  .changeset/short-rats-double.md
  .changeset/stupid-balloons-end.md
  crates/edr_napi/CHANGELOG.md
  crates/edr_napi/package.json
Labels: status:ready, no changeset needed, area:edr

#5090 ci: allow trailing space in EDR release commit
  .github/workflows/edr-npm-release.yml
Labels: status:ready, no changeset needed, area:config

#5086 fix: tests with async fn in describe
  packages/hardhat-core/test/internal/context.ts
  packages/hardhat-core/test/internal/core/providers/construction.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/error-object.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/hardhat-network-options.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/blockNumber.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/call.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/estimateGas.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/feeHistory.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/gasPrice.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/getBalance.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/getBlockByHash.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/getBlockByNumber.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/getBlockTransactionCountByHash.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/getBlockTransactionCountByNumber.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/getCode.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/getFilterLogs.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/getLogs.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/getStorageAt.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/getTransactionByBlockHashAndIndex.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/getTransactionByBlockNumberAndIndex.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/getTransactionByHash.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/getTransactionCount.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/getTransactionReceipt.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/index.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/newPendingTransactionFilter.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/pendingTransactions.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/sendRawTransaction.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/sendTransaction.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/unsubscribe.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/evm.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/hardhat.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/net.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/personal.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/web3.ts
Labels: status:ready, no changeset needed, area:edr

#4961 Run gas report and coverage in e2e
  e2e/test-project-initialization.sh
Labels: status:ready, no changeset needed

#5095 ci: fix application of pre-release tag
  .github/workflows/edr-npm-release.yml
Labels: status:ready, no changeset needed, area:edr

#4872 Support Settings (a.k.a. Input JSON Description) in @nomiclabs/hardhat-vyper
  .changeset/fluffy-cups-clap.md
  packages/hardhat-vyper/.mocharc.json
  packages/hardhat-vyper/README.md
  packages/hardhat-vyper/src/compiler.ts
  packages/hardhat-vyper/src/index.ts
  packages/hardhat-vyper/src/types.ts
  packages/hardhat-vyper/test/fixture-projects/.gitignore
  packages/hardhat-vyper/test/fixture-projects/compilation-with-settings-option-variants/optimize-invalid-type/contracts/A.vy
  packages/hardhat-vyper/test/fixture-projects/compilation-with-settings-option-variants/optimize-invalid-type/hardhat.config.js
  packages/hardhat-vyper/test/fixture-projects/compilation-with-settings-option-variants/optimize-set-to-false-always-available-new-versions/contracts/A.vy
  packages/hardhat-vyper/test/fixture-projects/compilation-with-settings-option-variants/optimize-set-to-false-always-available-new-versions/hardhat.config.js
  packages/hardhat-vyper/test/fixture-projects/compilation-with-settings-option-variants/optimize-set-to-false-always-available-old-versions-after-0.3.0/contracts/A.vy
  packages/hardhat-vyper/test/fixture-projects/compilation-with-settings-option-variants/optimize-set-to-false-always-available-old-versions-after-0.3.0/hardhat.config.js
  packages/hardhat-vyper/test/fixture-projects/compilation-with-settings-option-variants/optimize-set-to-false-not-available-old-versions/contracts/A.vy
  packages/hardhat-vyper/test/fixture-projects/compilation-with-settings-option-variants/optimize-set-to-false-not-available-old-versions/hardhat.config.js
  packages/hardhat-vyper/test/fixture-projects/compilation-with-settings-option-variants/optimize-set-to-true/contracts/A.vy
  packages/hardhat-vyper/test/fixture-projects/compilation-with-settings-option-variants/optimize-set-to-true/hardhat.config.js
  packages/hardhat-vyper/test/fixture-projects/compilation-with-settings-option-variants/optimize-string-not-available-old-versions/contracts/A.vy
  packages/hardhat-vyper/test/fixture-projects/compilation-with-settings-option-variants/optimize-string-not-available-old-versions/hardhat.config.js
  packages/hardhat-vyper/test/fixture-projects/compilation-with-settings-option-variants/optimize-true-not-available-new-versions/contracts/A.vy
  packages/hardhat-vyper/test/fixture-projects/compilation-with-settings-option-variants/optimize-true-not-available-new-versions/hardhat.config.js
  packages/hardhat-vyper/test/fixture-projects/compilation-with-settings-option-variants/optimize-true-not-available-old-versions/contracts/A.vy
  packages/hardhat-vyper/test/fixture-projects/compilation-with-settings-option-variants/optimize-true-not-available-old-versions/hardhat.config.js
  packages/hardhat-vyper/test/fixture-projects/compilation-with-vyper-settings/contracts/A.vy
  packages/hardhat-vyper/test/fixture-projects/compilation-with-vyper-settings/contracts/B.vy
  packages/hardhat-vyper/test/fixture-projects/compilation-with-vyper-settings/hardhat.config.js
  packages/hardhat-vyper/test/tests.ts
Labels: status:ready

#5096 Add eslint rule to forbid describes with async functions
  config/eslint/eslintrc.js
  packages/hardhat-chai-matchers/package.json
  packages/hardhat-chai-matchers/test/bigNumber.ts
  packages/hardhat-chai-matchers/test/events.ts
  packages/hardhat-chai-matchers/test/reverted/revertedWithCustomError.ts
  packages/hardhat-core/package.json
  packages/hardhat-core/test/internal/hardhat-network/stack-traces/test.ts
  packages/hardhat-ethers/package.json
  packages/hardhat-foundry/package.json
  packages/hardhat-ledger/package.json
  packages/hardhat-network-helpers/package.json
  packages/hardhat-shorthand/package.json
  packages/hardhat-solhint/package.json
  packages/hardhat-solpp/package.json
  packages/hardhat-solpp/test/tests.ts
  packages/hardhat-toolbox-viem/package.json
  packages/hardhat-toolbox/package.json
  packages/hardhat-truffle4/package.json
  packages/hardhat-truffle5/package.json
  packages/hardhat-verify/package.json
  packages/hardhat-viem/package.json
  packages/hardhat-vyper/package.json
  packages/hardhat-vyper/test/tests.ts
  packages/hardhat-web3-legacy/package.json
  packages/hardhat-web3-v4/package.json
  packages/hardhat-web3/package.json
  pnpm-lock.yaml
Labels: status:ready, no changeset needed

#4699 Add documentation for the `--reset` flag
  docs/src/content/ignition/docs/guides/modifications.md
Labels: no changeset needed

#5070 ci: calibrate performance alert threshold
  crates/tools/js/benchmark/index.js
  crates/tools/python/benchmark-variance.ipynb
  crates/tools/python/ejs-baseline.ipynb
  crates/tools/python/ejs-benchmark/1.json
  crates/tools/python/ejs-benchmark/2.json
  crates/tools/python/ejs-benchmark/3.json
  crates/tools/python/ejs-benchmark/4.json
  crates/tools/python/ejs-benchmark/5.json
  crates/tools/python/js-benchmark-variance/1.json
  crates/tools/python/js-benchmark-variance/10.json
  crates/tools/python/js-benchmark-variance/11.json
  crates/tools/python/js-benchmark-variance/12.json
  crates/tools/python/js-benchmark-variance/13.json
  crates/tools/python/js-benchmark-variance/14.json
  crates/tools/python/js-benchmark-variance/15.json
  crates/tools/python/js-benchmark-variance/16.json
  crates/tools/python/js-benchmark-variance/17.json
  crates/tools/python/js-benchmark-variance/18.json
  crates/tools/python/js-benchmark-variance/19.json
  crates/tools/python/js-benchmark-variance/2.json
  crates/tools/python/js-benchmark-variance/20.json
  crates/tools/python/js-benchmark-variance/21.json
  crates/tools/python/js-benchmark-variance/22.json
  crates/tools/python/js-benchmark-variance/23.json
  crates/tools/python/js-benchmark-variance/24.json
  crates/tools/python/js-benchmark-variance/25.json
  crates/tools/python/js-benchmark-variance/26.json
  crates/tools/python/js-benchmark-variance/27.json
  crates/tools/python/js-benchmark-variance/28.json
  crates/tools/python/js-benchmark-variance/29.json
  crates/tools/python/js-benchmark-variance/3.json
  crates/tools/python/js-benchmark-variance/30.json
  crates/tools/python/js-benchmark-variance/4.json
  crates/tools/python/js-benchmark-variance/5.json
  crates/tools/python/js-benchmark-variance/6.json
  crates/tools/python/js-benchmark-variance/7.json
  crates/tools/python/js-benchmark-variance/8.json
  crates/tools/python/js-benchmark-variance/9.json
  crates/tools/scenarios/snapshot.json
Labels: status:ready, no changeset needed, area:edr

#5098 Add ignition/deployment to gitignore
  packages/hardhat-core/recommended-gitignore.txt
Labels: no changeset needed

#5102 Clarify in the documentation that hardhat-chai-matchers is not compatible with hardhat-viem
  docs/src/content/hardhat-chai-matchers/docs/overview.md
Labels: no changeset needed

#5083 Introduce a template package
  config/v-next/eslint.cjs
  config/v-next/tsconfig.json
  config/v-next/tsconfig.node20.json
  packages/eslint-plugin-hardhat-internal-rules/.eslintrc.js
  packages/eslint-plugin-hardhat-internal-rules/package.json
  packages/eslint-plugin-slow-imports/.eslintrc.js
  packages/eslint-plugin-slow-imports/lib/rules/no-top-level-external-import.js
  packages/template-package/.eslintrc.cjs
  packages/template-package/.gitignore
  packages/template-package/.prettierignore
  packages/template-package/LICENSE
  packages/template-package/README.md
  packages/template-package/package.json
  packages/template-package/src/index.ts
  packages/template-package/src/other-entry-point.ts
  packages/template-package/src/utils/string.ts
  packages/template-package/test/index.ts
  packages/template-package/test/other-entry-point.ts
  packages/template-package/tsconfig.json
  pnpm-lock.yaml
  scripts/check-dependencies.js
Labels: status:ready

#5106 docs(ignition): include config option `maxFeePerGasLimit`
  docs/src/content/ignition/docs/config/index.md
Labels: status:ready, no changeset needed

#5108 build: remove support for i686 & arm windows builds
  .changeset/silver-sheep-exist.md
  .github/workflows/edr-npm-release.yml
  book/src/02_development/04_update_napi_targets.md
  book/src/SUMMARY.md
  crates/edr_napi/index.js
  crates/edr_napi/npm/win32-arm64-msvc/README.md
  crates/edr_napi/npm/win32-arm64-msvc/package.json
  crates/edr_napi/npm/win32-ia32-msvc/README.md
  crates/edr_napi/npm/win32-ia32-msvc/package.json
  crates/edr_napi/package.json
  pnpm-lock.yaml
Labels: status:ready, area:edr

#5117 fix: sporadic test failure in CI
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/getTransactionReceipt.ts
Labels: status:ready, no changeset needed, area:edr

#5113 Fix build with latest viem dependency
  .changeset/short-pillows-march.md
  packages/hardhat-viem/src/internal/contracts.ts
Labels: status:ready

#5100 fix: add missing KZG point evaluation precompile
  .changeset/nervous-tips-grow.md
  Cargo.lock
  crates/edr_eth/Cargo.toml
  crates/edr_eth/src/block/reward.rs
  crates/edr_eth/src/lib.rs
  crates/edr_eth/src/remote/block_spec.rs
  crates/edr_eth/src/remote/eth/call_request.rs
  crates/edr_eth/src/remote/filter.rs
  crates/edr_eth/src/serde.rs
  crates/edr_eth/src/transaction/request/eip1559.rs
  crates/edr_eth/src/transaction/request/eip2930.rs
  crates/edr_eth/src/transaction/request/eip4844.rs
  crates/edr_eth/src/transaction/request/legacy.rs
  crates/edr_eth/src/transaction/signed.rs
  crates/edr_eth/src/transaction/signed/eip155.rs
  crates/edr_eth/src/transaction/signed/eip1559.rs
  crates/edr_eth/src/transaction/signed/eip2930.rs
  crates/edr_eth/src/transaction/signed/eip4844.rs
  crates/edr_eth/src/transaction/signed/legacy.rs
  crates/edr_evm/Cargo.toml
  crates/edr_evm/src/block/builder.rs
  crates/edr_evm/src/lib.rs
  crates/edr_evm/src/mempool.rs
  crates/edr_evm/src/trace.rs
  crates/edr_evm/src/transaction/executable.rs
  crates/edr_evm/tests/issue_364.rs
  crates/edr_napi/Cargo.toml
  crates/edr_provider/Cargo.toml
  crates/edr_provider/src/data.rs
  crates/edr_provider/src/test_utils.rs
Labels: status:ready, area:edr

#5123 Update chain-config.ts : Added Base Sepolia chain
  .changeset/large-phones-relax.md
  packages/hardhat-verify/src/internal/chain-config.ts
Labels: status:triaging

#4953 Legacy ledger derivation path support in hardhat-ledger
  .changeset/selfish-bottles-cross.md
  packages/hardhat-ledger/README.md
  packages/hardhat-ledger/src/errors.ts
  packages/hardhat-ledger/src/internal/create-ledger-provider.ts
  packages/hardhat-ledger/src/provider.ts
  packages/hardhat-ledger/src/type-extensions.ts
  packages/hardhat-ledger/src/types.ts
  packages/hardhat-ledger/test/errors.ts
  packages/hardhat-ledger/test/internal/create-ledger-provider.ts
  packages/hardhat-ledger/test/provider.ts
Labels: status:ready

#5124 Update creating-modules.md
  docs/src/content/ignition/docs/guides/creating-modules.md
Labels: status:triaging, no changeset needed

#5114 Use remote chain id in fork metadata
  .changeset/itchy-maps-film.md
  crates/edr_evm/src/blockchain/forked.rs
  crates/edr_provider/src/data.rs
Labels: status:ready, area:edr

#5103 Re-enable macos CI tests
  .github/workflows/hardhat-chai-matchers-ci.yml
  .github/workflows/hardhat-core-ci.yml
  .github/workflows/hardhat-ethers-ci.yml
  .github/workflows/hardhat-foundry-ci.yml
  .github/workflows/hardhat-ledger-ci.yml
  .github/workflows/hardhat-network-helpers-ci.yml
  .github/workflows/hardhat-shorthand-ci.yml
  .github/workflows/hardhat-solhint-ci.yml
  .github/workflows/hardhat-solpp-ci.yml
  .github/workflows/hardhat-toolbox-ci.yml
  .github/workflows/hardhat-truffle4-ci.yml
  .github/workflows/hardhat-truffle5-ci.yml
  .github/workflows/hardhat-verify-ci.yml
  .github/workflows/hardhat-viem-ci.yml
  .github/workflows/hardhat-web3-ci.yml
  .github/workflows/hardhat-web3-legacy-ci.yml
  .github/workflows/hardhat-web3-v4-ci.yml
Labels: no changeset needed

#5126 edr-0.3.5
  .changeset/itchy-maps-film.md
  .changeset/nervous-tips-grow.md
  .changeset/silver-sheep-exist.md
  .changeset/slow-baboons-press.md
  Cargo.lock
  crates/edr_defaults/Cargo.toml
  crates/edr_eth/Cargo.toml
  crates/edr_evm/Cargo.toml
  crates/edr_napi/CHANGELOG.md
  crates/edr_napi/Cargo.toml
  crates/edr_napi/package.json
  crates/edr_provider/Cargo.toml
  crates/edr_solidity/Cargo.toml
  crates/edr_test_utils/Cargo.toml
  crates/tools/Cargo.toml
Labels: status:ready, no changeset needed, area:edr

#5129 fix: avoid panic when re-setting global default subscriber
  .changeset/twelve-ducks-exercise.md
  crates/edr_napi/src/context.rs
Labels: status:ready, area:edr

#5127 fix: mining blocks when forking non-eth chains
  .changeset/friendly-papayas-drum.md
  crates/edr_evm/src/block/builder.rs
  crates/edr_evm/src/miner.rs
  crates/edr_provider/src/test_utils.rs
  crates/edr_provider/tests/issue_384.rs
Labels: status:ready, area:edr

#5133 chore: remove edr changesets
  .changeset/friendly-papayas-drum.md
  .changeset/tall-cats-learn.md
  .changeset/twelve-ducks-exercise.md
Labels: status:ready, no changeset needed

#5141 build: fix napi binary name
  crates/edr_napi/package.json
Labels: status:ready, no changeset needed, area:edr

#5136 perf: constant time checkpointing
  .changeset/tough-students-compare.md
  Cargo.lock
  crates/edr_evm/Cargo.toml
  crates/edr_evm/src/collections/shared_map.rs
  crates/edr_evm/src/state/trie.rs
  crates/edr_evm/src/state/trie/account.rs
  crates/edr_evm/src/state/trie/persistent_memory_db.rs
  crates/edr_evm/src/state/trie/state_trie.rs
  crates/edr_evm/src/state/trie/storage_trie.rs
  crates/edr_evm/src/state/trie/trie_query.rs
  crates/edr_provider/Cargo.toml
  crates/edr_provider/src/data.rs
  crates/edr_provider/src/snapshot.rs
  crates/tools/Cargo.toml
  crates/tools/src/main.rs
Labels: status:ready, area:edr

#5137 fix: avoid ecrecover for known sender
  .changeset/new-coins-eat.md
  crates/edr_provider/src/data.rs
Labels: status:ready, area:edr

#5138 fix: avoid cloning transaction traces
  .changeset/two-suits-admire.md
  crates/edr_provider/src/data.rs
  crates/edr_provider/src/debug_mine.rs
  crates/edr_provider/src/requests/eth/transactions.rs
Labels: status:ready, area:edr

#5139 fix: avoid transferring traces to JS
  .changeset/wicked-walls-itch.md
  crates/tools/js/benchmark/index.js
  packages/hardhat-core/src/internal/hardhat-network/provider/provider.ts
Labels: status:ready, area:edr

#5154 Fix typo
  book/src/02_development/03_local_release.md
  crates/edr_eth/src/access_list.rs
  crates/edr_eth/src/account.rs
  packages/hardhat-core/test/internal/hardhat-network/stack-traces/test-files/0_6/revert-without-message/README.md
Labels: status:triaging, no changeset needed

#4695 issues/4652: added support for library linking in `hardhat-viem`
  .changeset/dry-jobs-fail.md
  packages/hardhat-viem/README.md
  packages/hardhat-viem/src/internal/bytecode.ts
  packages/hardhat-viem/src/internal/contracts.ts
  packages/hardhat-viem/src/internal/errors.ts
  packages/hardhat-viem/src/types.ts
  packages/hardhat-viem/test/fixture-projects/hardhat-project/contracts/ConstructorLib.sol
  packages/hardhat-viem/test/fixture-projects/hardhat-project/contracts/WithLibs.sol
  packages/hardhat-viem/test/integration.ts
Labels: status:ready

#5152 use absolute path for foundry sources
  .changeset/cyan-cheetahs-add.md
  packages/hardhat-foundry/src/index.ts
Labels: status:ready

#5153 Add `BigInt` task argument type
  .changeset/clever-peaches-obey.md
  packages/hardhat-core/src/internal/core/params/argumentTypes.ts
  packages/hardhat-core/test/internal/core/params/argumentTypes.ts
Labels: status:ready

#5173 Bump EDR dependency to 0.3.7
  .changeset/dry-flowers-help.md
  packages/hardhat-core/package.json
  pnpm-lock.yaml
Labels: status:ready
