Repository NomicFoundation/hardhat, pull requests merged in 2024-05, with the labels that each got.

#5130 Guide for using Ledger devices with Ignition
  docs/src/content/ignition/docs/guides/_dirinfo.yaml
  docs/src/content/ignition/docs/guides/ledger.md
Labels: status:ready, no changeset needed

#5176 docs(ignition): add `maxPriorityFeePerGas` to config
  docs/src/content/ignition/docs/config/index.md
Labels: status:ready, no changeset needed

#5177 Remove EDR changesets
  .changeset/friendly-papayas-drum.md
  .changeset/new-coins-eat.md
  .changeset/tough-students-compare.md
  .changeset/twelve-ducks-exercise.md
  .changeset/two-suits-admire.md
  .changeset/wicked-walls-itch.md
Labels: status:ready, no changeset needed

#5163 Update chain-config.ts : Replace Mumbai by Amoy
  .changeset/new-books-marry.md
  packages/hardhat-verify/src/internal/chain-config.ts
Labels: status:ready

#5180 Update EDR using dependabot
  .github/dependabot.yml
Labels: status:ready, no changeset needed

#5184 Update dependencies
  .changeset/many-baboons-refuse.md
  .changeset/wicked-mugs-itch.md
  .github/workflows/hardhat-core-ci.yml
  package.json
  packages/hardhat-core/package.json
  packages/hardhat-core/src/internal/core/errors-list.ts
  packages/hardhat-core/src/internal/solidity/compiler/index.ts
  packages/hardhat-core/src/internal/solidity/compiler/solcjs-runner.js
  packages/hardhat-core/test/internal/core/config/default-config.ts
  packages/hardhat-core/test/internal/hardhat-network/stack-traces/compilation.ts
  packages/hardhat-ethers/src/internal/hardhat-ethers-provider.ts
  packages/hardhat-ethers/test/no-accounts.ts
  packages/hardhat-web3-legacy/test/pweb3.ts
  pnpm-lock.yaml
Labels: status:ready, no changeset needed

#5164 Enforce contract verification
  .changeset/pink-goats-jam.md
  packages/hardhat-verify/src/index.ts
  packages/hardhat-verify/src/internal/errors.ts
  packages/hardhat-verify/src/internal/etherscan.ts
  packages/hardhat-verify/src/internal/tasks/etherscan.ts
  packages/hardhat-verify/test/integration/index.ts
  packages/hardhat-verify/test/unit/index.ts
Labels: status:ready

#5171 fix(ts): import type adjustments
  packages/hardhat-core/sample-projects/typescript-viem/hardhat.config.ts
Labels: status:needs-more-info

#5157 fix: use `eth_maxPriorityFeePerGas` for determing gas
  .changeset/smart-hotels-fold.md
  packages/hardhat-ethers/src/internal/hardhat-ethers-provider.ts
  packages/hardhat-ethers/test/hardhat-ethers-provider.ts
Labels: status:ready

#5188 [v-next] Reorganize repository
  .github/workflows/hardhat-utils.yml
  .github/workflows/v-next-ci.yml
  pnpm-lock.yaml
  pnpm-workspace.yaml
  scripts/check-v-next-dependencies.js
  v-next/hardhat-utils/.eslintrc.cjs
  v-next/hardhat-utils/.gitignore
  v-next/hardhat-utils/.prettierignore
  v-next/hardhat-utils/LICENSE
  v-next/hardhat-utils/README.md
  v-next/hardhat-utils/package.json
  v-next/hardhat-utils/src/bigint.ts
  v-next/hardhat-utils/src/bytes.ts
  v-next/hardhat-utils/src/common-errors.ts
  v-next/hardhat-utils/src/crypto.ts
  v-next/hardhat-utils/src/date.ts
  v-next/hardhat-utils/src/error.ts
  v-next/hardhat-utils/src/errors/fs.ts
  v-next/hardhat-utils/src/errors/package.ts
  v-next/hardhat-utils/src/errors/request.ts
  v-next/hardhat-utils/src/eth.ts
  v-next/hardhat-utils/src/fs.ts
  v-next/hardhat-utils/src/hex.ts
  v-next/hardhat-utils/src/internal/eth.ts
  v-next/hardhat-utils/src/internal/hex.ts
  v-next/hardhat-utils/src/internal/lang.ts
  v-next/hardhat-utils/src/internal/package.ts
  v-next/hardhat-utils/src/internal/request.ts
  v-next/hardhat-utils/src/lang.ts
  v-next/hardhat-utils/src/number.ts
  v-next/hardhat-utils/src/package.ts
  v-next/hardhat-utils/src/request.ts
  v-next/hardhat-utils/src/string.ts
  v-next/hardhat-utils/test/bigint.ts
  v-next/hardhat-utils/test/bytes.ts
  v-next/hardhat-utils/test/crypto.ts
  v-next/hardhat-utils/test/date.ts
  v-next/hardhat-utils/test/eth.ts
  v-next/hardhat-utils/test/fs.ts
  v-next/hardhat-utils/test/helpers/fs.ts
  v-next/hardhat-utils/test/helpers/request.ts
  v-next/hardhat-utils/test/hex.ts
  v-next/hardhat-utils/test/lang.ts
  v-next/hardhat-utils/test/number.ts
  v-next/hardhat-utils/test/package.ts
  v-next/hardhat-utils/test/request.ts
  v-next/hardhat-utils/test/string.ts
  v-next/hardhat-utils/tsconfig.json
  v-next/template-package/.eslintrc.cjs
  v-next/template-package/.gitignore
  v-next/template-package/.prettierignore
  v-next/template-package/LICENSE
  v-next/template-package/README.md
  v-next/template-package/package.json
  v-next/template-package/src/index.ts
  v-next/template-package/src/other-entry-point.ts
  v-next/template-package/src/utils/string.ts
  v-next/template-package/test/index.ts
  v-next/template-package/test/other-entry-point.ts
  v-next/template-package/tsconfig.json
Labels: status:ready

#4880 fix typos in README.md
  docs/README.md
Labels: type:docs, status:ready, no changeset needed

#4612 fix: flatten 2d array
  .changeset/little-bananas-thank.md
  packages/hardhat-core/src/internal/solidity/compilation-job.ts
Labels: status:triaging

#4926 chore: replace unmaintained eslint-plugin-node with eslint-plugin-n
  packages/eslint-plugin-hardhat-internal-rules/.eslintrc.js
  packages/eslint-plugin-hardhat-internal-rules/package.json
  packages/eslint-plugin-slow-imports/.eslintrc.js
  packages/eslint-plugin-slow-imports/package.json
  pnpm-lock.yaml
Labels: status:ready, no changeset needed

#4797 fix: Stack Trace Source Maps - corrected typo in indexing
  .changeset/happy-mails-impress.md
  packages/hardhat-core/src/internal/hardhat-network/stack-traces/source-maps.ts
Labels: status:triaging

#5197 [v-next] Update the shared config files
  .github/workflows/v-next-ci.yml
  config-v-next/eslint.cjs
  config-v-next/tsconfig.json
  config-v-next/tsconfig.node20.json
  v-next/hardhat-utils/.eslintrc.cjs
  v-next/hardhat-utils/tsconfig.json
  v-next/template-package/.eslintrc.cjs
  v-next/template-package/tsconfig.json
Labels: status:ready

#5204 [v-next] writeUtf8File: throw an error when a path is a directory and not a file
  v-next/hardhat-utils/src/fs.ts
  v-next/hardhat-utils/test/fs.ts
Labels: status:triaging

#5196 [v-next] First version of the new core
  config-v-next/eslint.cjs
  pnpm-lock.yaml
  v-next/core/.eslintrc.cjs
  v-next/core/.gitignore
  v-next/core/.prettierignore
  v-next/core/LICENSE
  v-next/core/README.md
  v-next/core/examples/example-cli.ts
  v-next/core/examples/example-config.ts
  v-next/core/examples/example-plugins/hardhat-foo/hookHandlers/config.ts
  v-next/core/examples/example-plugins/hardhat-foo/hookHandlers/configurationVariables.ts
  v-next/core/examples/example-plugins/hardhat-foo/index.ts
  v-next/core/examples/example-plugins/hardhat-foo/type-extensions.ts
  v-next/core/examples/hardhat.js
  v-next/core/package.json
  v-next/core/scripts/api-extractor.json
  v-next/core/scripts/api-extractor.sh
  v-next/core/scripts/madge.sh
  v-next/core/src/config.ts
  v-next/core/src/index.ts
  v-next/core/src/internal/async-mutex.ts
  v-next/core/src/internal/builtin-functionality.ts
  v-next/core/src/internal/config/configuration-variables.ts
  v-next/core/src/internal/config/validation-utils.ts
  v-next/core/src/internal/hook-manager.ts
  v-next/core/src/internal/hre.ts
  v-next/core/src/internal/plugins/plugin-validation.ts
  v-next/core/src/internal/plugins/sort.ts
  v-next/core/src/internal/user-interruptions.ts
  v-next/core/src/types/config.ts
  v-next/core/src/types/hooks.ts
  v-next/core/src/types/hre.ts
  v-next/core/src/types/plugins.ts
  v-next/core/src/types/user-interruptions.ts
  v-next/core/src/types/utils.ts
  v-next/core/test/nop.ts
  v-next/core/tsconfig.json
Labels: status:ready

#5203 Hardhat verify fixes
  .changeset/clever-hairs-happen.md
  packages/hardhat-verify/src/internal/errors.ts
  packages/hardhat-verify/src/internal/etherscan.ts
  packages/hardhat-verify/src/internal/sourcify.ts
  packages/hardhat-verify/src/internal/tasks/etherscan.ts
  packages/hardhat-verify/test/integration/index.ts
Labels: status:triaging

#5206 feat(@nomiclabs/hardhat-solhint): load .solhintignore file
  .changeset/dull-spies-hope.md
  packages/hardhat-solhint/src/index.ts
  packages/hardhat-solhint/test/fixture-projects/solhintignore-project/.solhint.json
  packages/hardhat-solhint/test/fixture-projects/solhintignore-project/.solhintignore
  packages/hardhat-solhint/test/fixture-projects/solhintignore-project/contracts/Greeter.sol
  packages/hardhat-solhint/test/fixture-projects/solhintignore-project/contracts/Greeter2.sol
  packages/hardhat-solhint/test/fixture-projects/solhintignore-project/contracts/Greeter3.sol
  packages/hardhat-solhint/test/fixture-projects/solhintignore-project/hardhat.config.js
  packages/hardhat-solhint/test/tests.ts
Labels: status:triaging

#5209 Updated changeset to patch
  .changeset/clever-peaches-obey.md
Labels: status:triaging

#5199 feat: check check constructor args type
  .changeset/thick-beers-tie.md
  packages/hardhat-verify/src/internal/utilities.ts
  packages/hardhat-verify/test/unit/utilities.ts
Labels: status:ready

#5217 Remove usage of "node:fs/promises" in test helper file
  v-next/hardhat-utils/test/helpers/fs.ts
Labels: status:triaging

#5221 Add method in hh-utils to read Uint8Array files
  v-next/hardhat-utils/src/fs.ts
  v-next/hardhat-utils/test/fs.ts
Labels: status:triaging

#5218 Bump EDR and remove dependabot
  .changeset/tall-jokes-judge.md
  .github/dependabot.yml
  packages/hardhat-core/package.json
  pnpm-lock.yaml
Labels: status:ready

#5219 Accept predicate functions in balance and token balance change matchers
  .changeset/strange-ladybugs-end.md
  packages/hardhat-chai-matchers/src/internal/changeEtherBalance.ts
  packages/hardhat-chai-matchers/src/internal/changeEtherBalances.ts
  packages/hardhat-chai-matchers/src/internal/changeTokenBalance.ts
  packages/hardhat-chai-matchers/src/types.ts
  packages/hardhat-chai-matchers/test/bigNumber.ts
  packages/hardhat-chai-matchers/test/changeEtherBalance.ts
  packages/hardhat-chai-matchers/test/changeEtherBalances.ts
  packages/hardhat-chai-matchers/test/changeTokenBalance.ts
  packages/hardhat-chai-matchers/test/reverted/revertedWithPanic.ts
Labels: status:triaging

#5205 docs: add new plugin for verifying contracts on evm chains and xlayer…
  docs/src/content/hardhat-runner/plugins/plugins.ts
Labels: status:ready, no changeset needed

#5220 chore/fix npm scripts escaping
  v-next/core/package.json
  v-next/hardhat-build-system/package.json
  v-next/hardhat-errors/package.json
  v-next/hardhat-utils/package.json
  v-next/hardhat-zod-utils/package.json
  v-next/hardhat/package.json
  v-next/template-package/package.json
Labels: status:ready

#5241 hh-errors: add methods in HardhatError add more ErrorDescriptors
  v-next/hardhat-errors/src/descriptors.ts
  v-next/hardhat-errors/src/errors.ts
  v-next/hardhat-errors/test/errors.ts
Labels: status:triaging

#5245 Enable eslint rules to make catching errors safer
  config-v-next/eslint.cjs
  v-next/hardhat-build-system/src/internal/solidity/compiler/downloader.ts
  v-next/hardhat-build-system/src/internal/solidity/compiler/index.ts
  v-next/hardhat-build-system/src/internal/solidity/parse.ts
  v-next/hardhat-build-system/src/internal/utils/fs-utils.ts
  v-next/hardhat-build-system/src/internal/utils/multi-process-mutex.ts
  v-next/hardhat-build-system/test/helpers.ts
  v-next/hardhat/src/cli.ts
Labels: status:ready

#5248 Disable E2E tests on Windows
  .github/workflows/e2e-tests.yml
Labels: status:ready, no changeset needed

#4096 Add config validation for empty network and forking url
  .changeset/seven-tips-float.md
  packages/hardhat-core/src/internal/core/errors-list.ts
  packages/hardhat-core/src/internal/core/providers/http.ts
  packages/hardhat-core/test/internal/core/providers/http.ts
Labels: status:triaging

#4208 adding a function and editing the error message for the issue #4151
  .changeset/wise-cheetahs-confess.md
  packages/hardhat-network-helpers/src/errors.ts
  packages/hardhat-network-helpers/src/helpers/reset.ts
  packages/hardhat-network-helpers/src/loadFixture.ts
  packages/hardhat-network-helpers/test/helpers/reset.ts
Labels: status:triaging

#5243 Replace errors in hh-build-system package with the methods exposed in the hh-error package
  pnpm-lock.yaml
  v-next/hardhat-build-system/package.json
  v-next/hardhat-build-system/src/internal/errors/errors-list.ts
  v-next/hardhat-build-system/src/internal/errors/errors.ts
  v-next/hardhat-build-system/src/internal/solidity/compilation-job.ts
  v-next/hardhat-build-system/src/internal/solidity/compiler/downloader.ts
  v-next/hardhat-build-system/src/internal/solidity/compiler/index.ts
  v-next/hardhat-build-system/src/internal/solidity/dependencyGraph.ts
  v-next/hardhat-build-system/src/internal/solidity/parse.ts
  v-next/hardhat-build-system/src/internal/solidity/resolver.ts
  v-next/hardhat-build-system/src/internal/tasks.ts
  v-next/hardhat-build-system/src/internal/utils/artifacts.ts
  v-next/hardhat-build-system/src/internal/utils/contract-names.ts
  v-next/hardhat-build-system/src/internal/utils/fs-utils.ts
  v-next/hardhat-build-system/src/internal/utils/package-info.ts
  v-next/hardhat-build-system/src/internal/utils/source-names.ts
  v-next/hardhat-build-system/test/helpers.ts
  v-next/hardhat-build-system/test/index.ts
  v-next/hardhat-build-system/test/internal/utils/artifacts.ts
  v-next/hardhat-build-system/tsconfig.json
Labels: status:triaging

#5211 Bring migration guide to docs
  docs/src/content/ignition/docs/advanced/_dirinfo.yaml
  docs/src/content/ignition/docs/advanced/migrating.md
Labels: no changeset needed

#5257 Fix typo in hh-core
  v-next/core/src/internal/tasks/builders.ts
  v-next/core/src/internal/tasks/task-manager.ts
  v-next/core/src/types/tasks.ts
Labels: status:triaging

#5258 Fix typos
  v-next/core/src/types/tasks.ts
Labels: status:triaging

#5259 Improve isValidParamNameCasing
  v-next/core/src/internal/parameters.ts
Labels: status:triaging

#5268 Add eslint rules to enforce `node:assert/strict`
  config-v-next/eslint.cjs
  v-next/core/test/plugins/resolve-plugin-list.ts
  v-next/hardhat-build-system/test/helpers.ts
  v-next/hardhat-build-system/test/index.ts
  v-next/hardhat-build-system/test/internal/utils/artifacts.ts
Labels: status:ready

#5269 Notify through Slack when a review is requested or approved
  .github/workflows/review-approved-slack-notification.yml
  .github/workflows/review-requested-slack-notification.yml
Labels: status:ready, no changeset needed

#5272 Merge `main` into `v-next`
  .changeset/seven-tips-float.md
  .changeset/wise-cheetahs-confess.md
  .github/workflows/e2e-tests.yml
  .github/workflows/review-approved-slack-notification.yml
  .github/workflows/review-requested-slack-notification.yml
  docs/src/content/ignition/docs/advanced/_dirinfo.yaml
  docs/src/content/ignition/docs/advanced/migrating.md
  packages/hardhat-core/src/internal/core/errors-list.ts
  packages/hardhat-core/src/internal/core/providers/http.ts
  packages/hardhat-core/test/internal/core/providers/http.ts
  packages/hardhat-network-helpers/src/errors.ts
  packages/hardhat-network-helpers/src/helpers/reset.ts
  packages/hardhat-network-helpers/src/loadFixture.ts
  packages/hardhat-network-helpers/test/helpers/reset.ts
Labels: status:ready

#5264 Add and test a singleton hre instance
  v-next/hardhat/src/index.ts
  v-next/hardhat/src/internal/cli/main.ts
  v-next/hardhat/src/internal/hre-singleton.ts
  v-next/hardhat/test/hre/index.ts
  v-next/hardhat/test/index.ts
Labels: status:triaging

#5261 feat: plugin install validation
  pnpm-lock.yaml
  v-next/core/package.json
  v-next/core/src/internal/plugins/plugin-validation.ts
  v-next/core/test/plugins/fixture-projects/installed-package/README.md
  v-next/core/test/plugins/fixture-projects/installed-package/node_modules/example/package.json
  v-next/core/test/plugins/fixture-projects/installed-peer-deps-as-sub-node-modules/README.md
  v-next/core/test/plugins/fixture-projects/installed-peer-deps-as-sub-node-modules/node_modules/example/node_modules/peer1/package.json
  v-next/core/test/plugins/fixture-projects/installed-peer-deps-as-sub-node-modules/node_modules/example/node_modules/peer2/package.json
  v-next/core/test/plugins/fixture-projects/installed-peer-deps-as-sub-node-modules/node_modules/example/package.json
  v-next/core/test/plugins/fixture-projects/installed-peer-deps/README.md
  v-next/core/test/plugins/fixture-projects/installed-peer-deps/node_modules/example/package.json
  v-next/core/test/plugins/fixture-projects/installed-peer-deps/node_modules/peer1/package.json
  v-next/core/test/plugins/fixture-projects/installed-peer-deps/node_modules/peer2/package.json
  v-next/core/test/plugins/fixture-projects/not-installed-package/README.md
  v-next/core/test/plugins/fixture-projects/not-installed-package/node_modules/.gitkeep
  v-next/core/test/plugins/fixture-projects/not-installed-peer-dep/README.md
  v-next/core/test/plugins/fixture-projects/not-installed-peer-dep/node_modules/example/package.json
  v-next/core/test/plugins/fixture-projects/not-installed-peer-dep/node_modules/peer1/package.json
  v-next/core/test/plugins/fixture-projects/peer-dep-with-wrong-version/README.md
  v-next/core/test/plugins/fixture-projects/peer-dep-with-wrong-version/node_modules/example/package.json
  v-next/core/test/plugins/fixture-projects/peer-dep-with-wrong-version/node_modules/peer1/package.json
  v-next/core/test/plugins/fixture-projects/peer-dep-with-wrong-version/node_modules/peer2/package.json
  v-next/core/test/plugins/plugin-validation.ts
  v-next/core/test/plugins/resolve-plugin-list.ts
  v-next/hardhat-build-system/package.json
  v-next/hardhat-errors/src/descriptors.ts
Labels: status:ready

#5273 v-next/lazy-plugin-loading
  v-next/core/src/internal/hook-manager.ts
  v-next/core/src/internal/hre.ts
  v-next/core/src/internal/plugins/plugin-validation.ts
  v-next/core/src/internal/plugins/resolve-plugin-list.ts
  v-next/core/src/types/plugins.ts
  v-next/core/test/plugins/plugin-validation.ts
  v-next/core/test/plugins/resolve-plugin-list.ts
  v-next/hardhat-errors/src/descriptors.ts
  v-next/hardhat/src/hre.ts
  v-next/hardhat/src/internal/cli/main.ts
Labels: status:ready

#5274 Tasks builders implementation and testing
  v-next/core/src/internal/tasks/builders.ts
  v-next/core/src/internal/tasks/utils.ts
  v-next/core/src/types/common.ts
  v-next/core/src/types/tasks.ts
  v-next/core/test/internal/tasks/builders.ts
  v-next/core/test/internal/tasks/utils.ts
  v-next/hardhat-errors/src/descriptors.ts
  v-next/hardhat-errors/src/errors.ts
Labels: status:triaging

#5277 Config loading
  v-next/hardhat-errors/src/descriptors.ts
  v-next/hardhat/package.json
  v-next/hardhat/src/index.ts
  v-next/hardhat/src/internal/cli/main.ts
  v-next/hardhat/src/internal/helpers/config-loading.ts
  v-next/hardhat/src/internal/hre-singleton.ts
  v-next/hardhat/test/fixture-projects/config-js/hardhat.config.js
  v-next/hardhat/test/fixture-projects/config-js/nested-folder/index.js
  v-next/hardhat/test/fixture-projects/config-ts/hardhat.config.ts
  v-next/hardhat/test/fixture-projects/config-ts/nested-folder/index.js
  v-next/hardhat/test/fixture-projects/loaded-config/hardhat.config.js
  v-next/hardhat/test/helpers/project.ts
  v-next/hardhat/test/hre/index.ts
Labels: status:triaging

#5290 Migrate to pnpm 9
  .github/workflows/LATEST_DEPENDENCY_VERSIONS.yml
  .github/workflows/check-docs-site.yml
  .github/workflows/comment-on-linter-error.yml
  .github/workflows/e2e-tests.yml
  .github/workflows/hardhat-chai-matchers-ci.yml
  .github/workflows/hardhat-core-ci.yml
  .github/workflows/hardhat-ethers-ci.yml
  .github/workflows/hardhat-foundry-ci.yml
  .github/workflows/hardhat-ledger-ci.yml
  .github/workflows/hardhat-network-helpers-ci.yml
  .github/workflows/hardhat-network-tracing-all-solc-versions.yml
  .github/workflows/hardhat-shorthand-ci.yml
  .github/workflows/hardhat-solhint-ci.yml
  .github/workflows/hardhat-solpp-ci.yml
  .github/workflows/hardhat-toolbox-ci.yml
  .github/workflows/hardhat-truffle4-ci.yml
  .github/workflows/hardhat-truffle5-ci.yml
  .github/workflows/hardhat-verify-ci.yml
  .github/workflows/hardhat-viem-ci.yml
  .github/workflows/hardhat-vyper-ci.yml
  .github/workflows/hardhat-web3-ci.yml
  .github/workflows/hardhat-web3-legacy-ci.yml
  .github/workflows/hardhat-web3-v4-ci.yml
  .github/workflows/lint.yml
  .github/workflows/pre-release.yml
  .github/workflows/release.yml
  .github/workflows/test-slow-imports-rule.yml
  pnpm-lock.yaml
Labels: no changeset needed

#5291 [v-next] Upgrade to pnpm 9
  .github/workflows/LATEST_DEPENDENCY_VERSIONS.yml
  .github/workflows/check-docs-site.yml
  .github/workflows/comment-on-linter-error.yml
  .github/workflows/e2e-tests.yml
  .github/workflows/hardhat-chai-matchers-ci.yml
  .github/workflows/hardhat-core-ci.yml
  .github/workflows/hardhat-ethers-ci.yml
  .github/workflows/hardhat-foundry-ci.yml
  .github/workflows/hardhat-ledger-ci.yml
  .github/workflows/hardhat-network-helpers-ci.yml
  .github/workflows/hardhat-network-tracing-all-solc-versions.yml
  .github/workflows/hardhat-shorthand-ci.yml
  .github/workflows/hardhat-toolbox-ci.yml
  .github/workflows/hardhat-verify-ci.yml
  .github/workflows/hardhat-viem-ci.yml
  .github/workflows/hardhat-vyper-ci.yml
  .github/workflows/hardhat-web3-v4-ci.yml
  .github/workflows/lint.yml
  .github/workflows/pre-release.yml
  .github/workflows/release.yml
  .github/workflows/test-slow-imports-rule.yml
  .github/workflows/v-next-ci.yml
  pnpm-lock.yaml
  v-next/hardhat-build-system/package.json
Labels: status:ready

#5294 refactor/move-plugin-test-to-internal
  v-next/core/test/internal/plugins/fixture-projects/installed-package/README.md
  v-next/core/test/internal/plugins/fixture-projects/installed-package/node_modules/example/package.json
  v-next/core/test/internal/plugins/fixture-projects/installed-peer-deps-as-sub-node-modules/README.md
  v-next/core/test/internal/plugins/fixture-projects/installed-peer-deps-as-sub-node-modules/node_modules/example/node_modules/peer1/package.json
  v-next/core/test/internal/plugins/fixture-projects/installed-peer-deps-as-sub-node-modules/node_modules/example/node_modules/peer2/package.json
  v-next/core/test/internal/plugins/fixture-projects/installed-peer-deps-as-sub-node-modules/node_modules/example/package.json
  v-next/core/test/internal/plugins/fixture-projects/installed-peer-deps/README.md
  v-next/core/test/internal/plugins/fixture-projects/installed-peer-deps/node_modules/example/package.json
  v-next/core/test/internal/plugins/fixture-projects/installed-peer-deps/node_modules/peer1/package.json
  v-next/core/test/internal/plugins/fixture-projects/installed-peer-deps/node_modules/peer2/package.json
  v-next/core/test/internal/plugins/fixture-projects/not-installed-package/README.md
  v-next/core/test/internal/plugins/fixture-projects/not-installed-package/node_modules/.gitkeep
  v-next/core/test/internal/plugins/fixture-projects/not-installed-peer-dep/README.md
  v-next/core/test/internal/plugins/fixture-projects/not-installed-peer-dep/node_modules/example/package.json
  v-next/core/test/internal/plugins/fixture-projects/not-installed-peer-dep/node_modules/peer1/package.json
  v-next/core/test/internal/plugins/fixture-projects/peer-dep-with-wrong-version/README.md
  v-next/core/test/internal/plugins/fixture-projects/peer-dep-with-wrong-version/node_modules/example/package.json
  v-next/core/test/internal/plugins/fixture-projects/peer-dep-with-wrong-version/node_modules/peer1/package.json
  v-next/core/test/internal/plugins/fixture-projects/peer-dep-with-wrong-version/node_modules/peer2/package.json
  v-next/core/test/internal/plugins/plugin-validation.ts
  v-next/core/test/internal/plugins/resolve-plugin-list.ts
Labels: status:ready

#5293 [v-next] Small repo improvements
  .npmrc
  .nvmrc
Labels: status:ready

#5295 Disable compilation errors on unused variables
  config-v-next/tsconfig.json
Labels: status:ready

#5283 Type-safe `HardhatError`
  v-next/hardhat-build-system/src/internal/solidity/compiler/downloader.ts
  v-next/hardhat-build-system/src/internal/solidity/compiler/index.ts
  v-next/hardhat-errors/src/descriptors.ts
  v-next/hardhat-errors/src/errors.ts
  v-next/hardhat-errors/test/errors.ts
Labels: status:ready

#5282 Add parsing for tasks, subtasks and tasks' parameters
  v-next/hardhat-errors/src/descriptors.ts
  v-next/hardhat/src/internal/cli/main.ts
  v-next/hardhat/test/internal/cli/main.ts
Labels: status:triaging

#5286 Add tests for user interruptions
  v-next/core/src/internal/async-mutex.ts
  v-next/core/src/internal/user-interruptions.ts
  v-next/core/test/internal/user-interruptions/async-mutex.ts
  v-next/core/test/internal/user-interruptions/user-interruptions-manager.ts
  v-next/hardhat/package.json
Labels: status:triaging

#5296 [v-next] eslint config update rules
  config-v-next/eslint.cjs
  pnpm-lock.yaml
  v-next/core/package.json
  v-next/core/src/internal/async-mutex.ts
  v-next/core/src/internal/global-parameters.ts
  v-next/core/src/internal/hook-manager.ts
  v-next/core/src/internal/hre.ts
  v-next/core/src/internal/user-interruptions.ts
  v-next/core/test/internal/tasks/builders.ts
  v-next/core/test/internal/user-interruptions/user-interruptions-manager.ts
  v-next/hardhat-build-system/package.json
  v-next/hardhat-build-system/src/internal/solidity/compilation-job.ts
  v-next/hardhat-build-system/src/internal/solidity/compiler/index.ts
  v-next/hardhat-build-system/src/internal/solidity/parse.ts
  v-next/hardhat-build-system/src/internal/solidity/resolver.ts
  v-next/hardhat-build-system/src/internal/tasks.ts
  v-next/hardhat-build-system/src/internal/utils/artifacts.ts
  v-next/hardhat-build-system/src/internal/utils/contract-names.ts
  v-next/hardhat-build-system/src/internal/utils/fs-utils.ts
  v-next/hardhat-build-system/src/internal/utils/multi-process-mutex.ts
  v-next/hardhat-build-system/src/internal/utils/source-names.ts
  v-next/hardhat-build-system/test/index.ts
  v-next/hardhat-build-system/test/internal/utils/artifacts.ts
  v-next/hardhat-errors/package.json
  v-next/hardhat-errors/src/errors.ts
  v-next/hardhat-errors/test/errors.ts
  v-next/hardhat-utils/package.json
  v-next/hardhat-utils/src/crypto.ts
  v-next/hardhat-utils/src/fs.ts
  v-next/hardhat-utils/src/hex.ts
  v-next/hardhat-utils/src/request.ts
  v-next/hardhat-utils/test/bigint.ts
  v-next/hardhat-utils/test/fs.ts
  v-next/hardhat-utils/test/lang.ts
  v-next/hardhat-zod-utils/package.json
  v-next/hardhat/package.json
  v-next/hardhat/test/internal/cli/main.ts
  v-next/template-package/package.json
Labels: status:ready

#5284 Introduce a custom `node:test` reporter
  pnpm-lock.yaml
  v-next/hardhat-node-test-reporter/.eslintrc.cjs
  v-next/hardhat-node-test-reporter/.gitignore
  v-next/hardhat-node-test-reporter/.prettierignore
  v-next/hardhat-node-test-reporter/LICENSE
  v-next/hardhat-node-test-reporter/README.md
  v-next/hardhat-node-test-reporter/integration-tests/README.md
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/example-test/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/example-test/test.ts
  v-next/hardhat-node-test-reporter/integration-tests/index.ts
  v-next/hardhat-node-test-reporter/package.json
  v-next/hardhat-node-test-reporter/src/diagnostics.ts
  v-next/hardhat-node-test-reporter/src/error-formatting.ts
  v-next/hardhat-node-test-reporter/src/formatting.ts
  v-next/hardhat-node-test-reporter/src/node-test-error-utils.ts
  v-next/hardhat-node-test-reporter/src/node-types.ts
  v-next/hardhat-node-test-reporter/src/reporter.ts
  v-next/hardhat-node-test-reporter/test/node-types.ts
  v-next/hardhat-node-test-reporter/tsconfig.json
Labels: status:ready

#5285 TaskManagerImplementation improvements
  v-next/core/src/internal/tasks/builders.ts
  v-next/core/src/internal/tasks/task-manager.ts
  v-next/core/src/internal/tasks/utils.ts
  v-next/core/test/internal/tasks/builders.ts
  v-next/hardhat-errors/src/descriptors.ts
Labels: status:triaging

#5195 `hardhat-tracer` support
  .changeset/tall-coins-sin.md
  packages/hardhat-core/package.json
  packages/hardhat-core/src/internal/hardhat-network/provider/provider.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/utils/convertToEdr.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/minimal-vm.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/types.ts
  packages/hardhat-truffle5/package.json
  pnpm-lock.yaml
Labels: status:ready

#5299 Make the build-system work with solcjs
  pnpm-lock.yaml
  v-next/hardhat-build-system/package.json
  v-next/hardhat-build-system/src/internal/solidity/compiler/index.ts
  v-next/hardhat-build-system/src/internal/solidity/compiler/solcjs-runner.ts
  v-next/hardhat-errors/src/descriptors.ts
Labels: status:ready

#5249 Better `node:test` reporter and scripts
  .github/workflows/v-next-ci.yml
  pnpm-lock.yaml
  scripts/check-v-next-npm-scripts.js
  v-next/core/package.json
  v-next/core/tsconfig.json
  v-next/hardhat-build-system/package.json
  v-next/hardhat-build-system/tsconfig.json
  v-next/hardhat-errors/package.json
  v-next/hardhat-errors/tsconfig.json
  v-next/hardhat-node-test-reporter/integration-tests/index.ts
  v-next/hardhat-node-test-reporter/package.json
  v-next/hardhat-node-test-reporter/tsconfig.json
  v-next/hardhat-utils/package.json
  v-next/hardhat-utils/tsconfig.json
  v-next/hardhat-zod-utils/package.json
  v-next/hardhat-zod-utils/tsconfig.json
  v-next/hardhat/package.json
  v-next/hardhat/tsconfig.json
  v-next/template-package/package.json
  v-next/template-package/tsconfig.json
Labels: status:ready
