Repository NomicFoundation/hardhat, pull requests merged in 2024-03, with the labels that each got.

#4948 Drop support for node v16
  .changeset/clever-lobsters-type.md
  .nvmrc
  crates/edr_napi/package.json
  docs/src/content/tutorial/setting-up-the-environment.md
  packages/hardhat-chai-matchers/package.json
  packages/hardhat-core/package.json
  packages/hardhat-core/src/internal/cli/constants.ts
  packages/hardhat-core/src/internal/cli/project-creation.ts
  packages/hardhat-ethers/package.json
  packages/hardhat-foundry/package.json
  packages/hardhat-ledger/package.json
  packages/hardhat-network-helpers/package.json
  packages/hardhat-shorthand/package.json
  packages/hardhat-solhint/package.json
  packages/hardhat-solpp/package.json
  packages/hardhat-toolbox-viem/package.json
  packages/hardhat-toolbox/package.json
  packages/hardhat-truffle4/package.json
  packages/hardhat-truffle5/package.json
  packages/hardhat-verify/package.json
  packages/hardhat-viem/package.json
  packages/hardhat-vyper/package.json
  packages/hardhat-web3-legacy/package.json
  packages/hardhat-web3-v4/package.json
  packages/hardhat-web3/package.json
  pnpm-lock.yaml
Labels: status:ready

#4954 Don't run async event handlers if there are no listeners
  packages/hardhat-core/src/internal/hardhat-network/provider/provider.ts
Labels: status:ready, no changeset needed

#4949 Fix json-rpc provider error object
  crates/edr_napi/src/logger.rs
  crates/edr_provider/src/data.rs
  crates/edr_provider/src/error.rs
  crates/edr_provider/src/requests/eth/call.rs
  crates/edr_provider/src/requests/eth/transactions.rs
  packages/hardhat-core/src/internal/hardhat-network/provider/provider.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/error-object.ts
Labels: status:ready, no changeset needed

#4902 Re-add edr changeset
  .changeset/cold-pens-study.md
Labels: status:ready

#4956 edr-0.2.0
  crates/edr_napi/package.json
  packages/hardhat-core/package.json
  pnpm-lock.yaml
Labels: status:ready, no changeset needed

#4959 Add readme and add files entry to package.json
  crates/edr_napi/README.md
  crates/edr_napi/package.json
Labels: status:ready

#4957 Update polygon zkevm cardona testnet
  .changeset/olive-kiwis-guess.md
  packages/hardhat-verify/src/internal/chain-config.ts
Labels: status:triaging

#4960 edr-0.2.1
  crates/edr_napi/package.json
Labels: status:ready, no changeset needed

#4972 docs: add benchmark & profiling book chapters
  book/src/01_getting_started/04_benchmark.md
  book/src/01_getting_started/05_profiling.md
Labels: status:triaging, no changeset needed, area:edr

#4941 build: bump Rust to v1.76
  .changeset/slimy-weeks-juggle.md
  crates/edr_evm/src/collections.rs
  crates/edr_napi/src/provider/config.rs
  crates/edr_provider/src/pending.rs
  crates/edr_provider/src/requests.rs
  rust-toolchain
Labels: status:triaging, area:edr

#4964 research: add data analysis ipython notebook
  .gitignore
  crates/tools/python/README.md
  crates/tools/python/env.yml
  crates/tools/python/scenarios.ipynb
Labels: no changeset needed

#4981 [Website] Remove the solidity survey banner
  docs/src/config.ts
Labels: status:ready, no changeset needed

#4990 feat: set cancun as default hardfork
  .changeset/gold-comics-do.md
  docs/src/content/hardhat-network/docs/reference/index.md
  packages/hardhat-core/src/internal/core/config/default-config.ts
  packages/hardhat-core/test/internal/core/config/default-config.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/baseFeePerGas.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/forking-different-hardfork.ts
Labels: status:ready

#4986 EDR book improvements
  book/src/01_getting_started/01_setup.md
  book/src/01_getting_started/02_build.md
  book/src/01_getting_started/03_test.md
  book/src/02_development/01_tools.md
Labels: status:ready, no changeset needed

#4758 Add a guide for using the create2 strategy
  docs/src/content/ignition/docs/guides/_dirinfo.yaml
  docs/src/content/ignition/docs/guides/create2.md
Labels: status:ready, no changeset needed

#4992 fix: set content-type and user-agent in RPC client
  .changeset/red-snails-fix.md
  crates/edr_eth/src/remote/client.rs
  crates/edr_evm/tests/issue_4974.rs
  crates/edr_evm/tests/optimism.rs
Labels: status:triaging, area:edr

#4996 edr-0.3.1
  .changeset/red-snails-fix.md
  crates/edr_napi/CHANGELOG.md
  crates/edr_napi/package.json
Labels: no changeset needed, area:edr

#5000 fix: retrieve code for forked accounts when modifying state
  .changeset/fair-lies-cough.md
  crates/edr_evm/benches/state/state_debug.rs
  crates/edr_evm/src/block/builder.rs
  crates/edr_evm/src/state/debug.rs
  crates/edr_evm/src/state/fork.rs
  crates/edr_evm/src/state/trie.rs
  crates/edr_evm/tests/issues.rs
  crates/edr_evm/tests/mem_pool.rs
  crates/edr_provider/src/data.rs
Labels: status:triaging, area:edr

#5001 refactor: clean up set_account_storage_slot
  .changeset/quiet-goats-remember.md
  crates/edr_evm/benches/state/state_debug.rs
  crates/edr_evm/benches/state/util.rs
  crates/edr_evm/src/state/debug.rs
  crates/edr_evm/src/state/fork.rs
  crates/edr_evm/src/state/trie.rs
  crates/edr_provider/src/data.rs
Labels: status:triaging, area:edr

#4951 Create env before args are parsed
  .changeset/dull-pigs-pay.md
  packages/hardhat-core/src/internal/cli/cli.ts
Labels: status:triaging

#4998 ci: add performance benchmarks
  .github/workflows/edr-benchmark.yml
  .gitignore
  crates/tools/js/benchmark/README.md
  crates/tools/js/benchmark/index.js
  crates/tools/js/benchmark/package.json
  crates/tools/python/benchmark-variance.ipynb
  crates/tools/python/js-benchmark-variance/1.json
  crates/tools/python/js-benchmark-variance/10.json
  crates/tools/python/js-benchmark-variance/11.json
  crates/tools/python/js-benchmark-variance/12.json
  crates/tools/python/js-benchmark-variance/13.json
  crates/tools/python/js-benchmark-variance/14.json
  crates/tools/python/js-benchmark-variance/15.json
  crates/tools/python/js-benchmark-variance/16.json
  crates/tools/python/js-benchmark-variance/17.json
  crates/tools/python/js-benchmark-variance/18.json
  crates/tools/python/js-benchmark-variance/19.json
  crates/tools/python/js-benchmark-variance/2.json
  crates/tools/python/js-benchmark-variance/20.json
  crates/tools/python/js-benchmark-variance/21.json
  crates/tools/python/js-benchmark-variance/22.json
  crates/tools/python/js-benchmark-variance/23.json
  crates/tools/python/js-benchmark-variance/24.json
  crates/tools/python/js-benchmark-variance/25.json
  crates/tools/python/js-benchmark-variance/26.json
  crates/tools/python/js-benchmark-variance/27.json
  crates/tools/python/js-benchmark-variance/28.json
  crates/tools/python/js-benchmark-variance/29.json
  crates/tools/python/js-benchmark-variance/3.json
  crates/tools/python/js-benchmark-variance/30.json
  crates/tools/python/js-benchmark-variance/4.json
  crates/tools/python/js-benchmark-variance/5.json
  crates/tools/python/js-benchmark-variance/6.json
  crates/tools/python/js-benchmark-variance/7.json
  crates/tools/python/js-benchmark-variance/8.json
  crates/tools/python/js-benchmark-variance/9.json
  crates/tools/python/rs-benchmark-variance.txt
  crates/tools/scenarios/openzeppelin-contracts_8b12f83a.jsonl.gz
  crates/tools/scenarios/snapshot.json
  pnpm-lock.yaml
Labels: no changeset needed, area:edr

#5008 ci: disable snapshot tests in benchmarks
  .github/workflows/edr-benchmark.yml
  crates/tools/js/benchmark/index.js
  crates/tools/scenarios/snapshot.json
Labels: no changeset needed

#4968 build: bump revm to 7.1
  .github/workflows/edr-benchmark.yml
  Cargo.lock
  crates/edr_eth/Cargo.toml
  crates/edr_eth/src/lib.rs
  crates/edr_eth/src/log.rs
  crates/edr_eth/src/log/block.rs
  crates/edr_eth/src/log/filter.rs
  crates/edr_eth/src/log/receipt.rs
  crates/edr_eth/src/receipt.rs
  crates/edr_eth/src/remote/filter.rs
  crates/edr_evm/Cargo.toml
  crates/edr_evm/src/block.rs
  crates/edr_evm/src/block/builder.rs
  crates/edr_evm/src/blockchain.rs
  crates/edr_evm/src/blockchain/storage/sparse.rs
  crates/edr_evm/src/db.rs
  crates/edr_evm/src/debug.rs
  crates/edr_evm/src/debug_trace.rs
  crates/edr_evm/src/evm.rs
  crates/edr_evm/src/inspector.rs
  crates/edr_evm/src/lib.rs
  crates/edr_evm/src/miner.rs
  crates/edr_evm/src/runtime.rs
  crates/edr_evm/src/state/debug.rs
  crates/edr_evm/src/state/overrides.rs
  crates/edr_evm/src/trace.rs
  crates/edr_evm/src/transaction.rs
  crates/edr_evm/src/transaction/executable.rs
  crates/edr_evm/tests/blockchain.rs
  crates/edr_napi/index.d.ts
  crates/edr_napi/src/call_override.rs
  crates/edr_napi/src/log.rs
  crates/edr_napi/src/logger.rs
  crates/edr_napi/src/result.rs
  crates/edr_napi/src/trace.rs
  crates/edr_provider/src/console_log.rs
  crates/edr_provider/src/data.rs
  crates/edr_provider/src/data/call.rs
  crates/edr_provider/src/data/gas.rs
  crates/edr_provider/src/debug_mine.rs
  crates/edr_provider/src/debugger.rs
  crates/edr_provider/src/error.rs
  crates/edr_provider/src/filter/criteria.rs
  crates/edr_provider/src/lib.rs
  crates/edr_provider/src/mock.rs
  crates/edr_provider/src/test_utils.rs
  crates/edr_solidity/Cargo.toml
  crates/edr_solidity/src/contracts_identifier.rs
  crates/edr_solidity/src/opcodes.rs
Labels: no changeset needed, area:edr

#5014 Ignore EDR `benchmarks` package in our Changeset config
  .changeset/config.json
Labels: status:ready, no changeset needed

#4991 feat: add Cancun activation block number
  .changeset/perfect-insects-hide.md
  crates/edr_eth/src/spec.rs
  packages/hardhat-core/test/internal/hardhat-network/provider/baseFeePerGas.ts
Labels: status:triaging, area:edr

#4994 chore: fix some comments
  crates/edr_eth/src/access_list.rs
  packages/hardhat-core/test/internal/solidity/resolver.ts
Labels: status:triaging

#5025 fix: use weak references for stored threadsafe functions
  .changeset/ten-spoons-study.md
  Cargo.lock
  crates/edr_napi/Cargo.toml
  crates/edr_napi/package.json
  crates/edr_napi/src/call_override.rs
  crates/edr_napi/src/lib.rs
  crates/edr_napi/src/log.rs
  crates/edr_napi/src/logger.rs
  crates/edr_napi/src/result.rs
  crates/edr_napi/src/subscribe.rs
  crates/edr_napi/src/sync.rs
  crates/edr_napi/src/threadsafe_function.rs
  crates/edr_napi/src/trace.rs
  e2e/fixture-projects/script/hardhat.config.js
  e2e/fixture-projects/script/package.json
  e2e/fixture-projects/script/script.js
  e2e/fixture-projects/script/test.sh
  packages/hardhat-core/package.json
Labels: status:ready, area:edr

#5033 fix: support hex string in `eth_signTypedData_v4` salt
  .changeset/neat-apes-mix.md
  crates/edr_provider/src/requests/methods.rs
  crates/edr_provider/src/requests/serde.rs
  crates/edr_provider/tests/issue_346.rs
Labels: status:ready, area:edr

#5035 edr-0.3.3
  .changeset/neat-apes-mix.md
  .changeset/perfect-insects-hide.md
  .changeset/ten-spoons-study.md
  crates/edr_napi/CHANGELOG.md
  crates/edr_napi/package.json
Labels: status:ready, no changeset needed

#5041 docs: repair doc
  docs/src/content/hardhat-runner/docs/advanced/building-plugins.md
Labels: status:ready, no changeset needed

#5037 ci: enable snapshot testing
  .github/workflows/edr-benchmark.yml
  crates/tools/js/benchmark/index.js
  crates/tools/scenarios/openzeppelin-contracts_0a5fba7a.jsonl.gz
  crates/tools/scenarios/openzeppelin-contracts_8b12f83a.jsonl.gz
Labels: no changeset needed

#5042 fix: blocks with EIP-4844 transactions
  .changeset/stupid-balloons-end.md
  crates/edr_eth/src/transaction/signed.rs
  crates/edr_eth/src/transaction/signed/eip4844.rs
  crates/edr_evm/src/block/builder.rs
  crates/edr_provider/src/data.rs
Labels: status:ready, area:edr

#5039 fix: bump EDR version to 0.3.3
  .changeset/neat-readers-beam.md
  packages/hardhat-core/package.json
  pnpm-lock.yaml
Labels: status:ready
