Repository NomicFoundation/hardhat, pull requests merged in 2024-08, with the labels that each got.

#5556 fix: exit check task with exit code 1 when solhint raises errors
  .changeset/breezy-chairs-relax.md
  .changeset/early-laws-trade.md
  CONTRIBUTING.md
  packages/hardhat-solhint/package.json
  packages/hardhat-solhint/src/index.ts
  packages/hardhat-solhint/test/fixture-projects/no-errors-project/.solhint.json
  packages/hardhat-solhint/test/fixture-projects/no-errors-project/contracts/Greeter.sol
  packages/hardhat-solhint/test/fixture-projects/no-errors-project/hardhat.config.js
  packages/hardhat-solhint/test/tests.ts
  pnpm-lock.yaml
Labels: status:ready

#5559 ci(v3): update GitHub actions and review workflow triggers
  .github/workflows/v-next-changesets-release.yml
  .github/workflows/v-next-ci.yml
Labels: status:triaging, no changeset needed

#5566 ci(v2): update GitHub actions and review workflow triggers
  .github/workflows/LATEST_DEPENDENCY_VERSIONS.yml
  .github/workflows/add-issue-to-project.yml
  .github/workflows/add-label-to-new-issue.yml
  .github/workflows/autoassign-issues.yml
  .github/workflows/autoassign-prs.yml
  .github/workflows/check-changeset-added.yml
  .github/workflows/check-docs-site.yml
  .github/workflows/close-stale-issues.yml
  .github/workflows/comment-on-linter-error.yml
  .github/workflows/e2e-tests.yml
  .github/workflows/hardhat-chai-matchers-ci.yml
  .github/workflows/hardhat-core-ci.yml
  .github/workflows/hardhat-ethers-ci.yml
  .github/workflows/hardhat-foundry-ci.yml
  .github/workflows/hardhat-ledger-ci.yml
  .github/workflows/hardhat-network-helpers-ci.yml
  .github/workflows/hardhat-network-tracing-all-solc-versions.yml
  .github/workflows/hardhat-shorthand-ci.yml
  .github/workflows/hardhat-solhint-ci.yml
  .github/workflows/hardhat-solpp-ci.yml
  .github/workflows/hardhat-toolbox-ci.yml
  .github/workflows/hardhat-truffle4-ci.yml
  .github/workflows/hardhat-truffle5-ci.yml
  .github/workflows/hardhat-verify-ci.yml
  .github/workflows/hardhat-viem-ci.yml
  .github/workflows/hardhat-vyper-ci.yml
  .github/workflows/hardhat-web3-ci.yml
  .github/workflows/hardhat-web3-legacy-ci.yml
  .github/workflows/hardhat-web3-v4-ci.yml
  .github/workflows/lint.yml
  .github/workflows/lock.yml
  .github/workflows/pre-release.yml
  .github/workflows/review-approved-slack-notification.yml
  .github/workflows/review-requested-slack-notification.yml
Labels: status:ready, no changeset needed

#5563 ci(v3): improve usage of github actions cache
  .github/actions/setup-env/action.yml
  .github/workflows/cache.yml
  .github/workflows/v-next-changesets-release.yml
  .github/workflows/v-next-ci.yml
Labels: status:ready, no changeset needed

#5562 ci(v2): remove duplicated lint jobs/steps
  .github/workflows/check-docs-site.yml
  .github/workflows/comment-on-linter-error.yml
  .github/workflows/lint.yml
Labels: status:ready, no changeset needed

#5564 ci(v3): test and lint v-next packages lazily
  .github/workflows/v-next-ci.yml
  .gitignore
  scripts/generate-filters.js
Labels: status:ready, no changeset needed

#5565 ci(v2): parameterise v2 packages ci to minimise duplication
  .github/workflows/hardhat-chai-matchers-ci.yml
  .github/workflows/hardhat-ci.yml
  .github/workflows/hardhat-ethers-ci.yml
  .github/workflows/hardhat-foundry-ci.yml
  .github/workflows/hardhat-ledger-ci.yml
  .github/workflows/hardhat-network-helpers-ci.yml
  .github/workflows/hardhat-network-tracing-all-solc-versions.yml
  .github/workflows/hardhat-shorthand-ci.yml
  .github/workflows/hardhat-solhint-ci.yml
  .github/workflows/hardhat-solpp-ci.yml
  .github/workflows/hardhat-toolbox-ci.yml
  .github/workflows/hardhat-truffle4-ci.yml
  .github/workflows/hardhat-truffle5-ci.yml
  .github/workflows/hardhat-verify-ci.yml
  .github/workflows/hardhat-viem-ci.yml
  .github/workflows/hardhat-vyper-ci.yml
  .github/workflows/hardhat-web3-ci.yml
  .github/workflows/hardhat-web3-legacy-ci.yml
  .github/workflows/hardhat-web3-v4-ci.yml
  .gitignore
  scripts/generate-filters.js
Labels: status:ready, no changeset needed

#5576 Upgrade EDR to v0.5.2
  .changeset/chilled-ads-wash.md
  packages/hardhat-core/package.json
  pnpm-lock.yaml
Labels: status:ready

#5558 fix: issue 543
  .changeset/blue-ravens-smile.md
  packages/hardhat-core/src/internal/hardhat-network/provider/provider.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/minimal-vm.ts
Labels: status:ready

#5541 Basic debug logging
  pnpm-lock.yaml
  v-next/core/package.json
  v-next/hardhat-utils/package.json
  v-next/hardhat-utils/src/debug.ts
  v-next/hardhat/package.json
  v-next/hardhat/src/internal/cli/main.ts
Labels: v-next

#5578 chore: do not send hardhat_setLedgerOutputEnabled over http
  .changeset/shaggy-bags-work.md
  packages/hardhat-core/src/internal/core/providers/http.ts
  packages/hardhat-core/test/internal/core/providers/http.ts
Labels: status:ready

#5585 fix: run pnpm install to fix the lockfile
  pnpm-lock.yaml
Labels: status:ready, no changeset needed

#5591 chore: cleanup comments in hook types
  v-next/core/src/types/hooks.ts
Labels: status:ready, v-next

#5594 Update artifacts.md to fix typos
  docs/src/content/hardhat-runner/docs/advanced/artifacts.md
Labels: status:ready, no changeset needed

#5587 chore: upgrade typescript to ~5.5.0
  package.json
  pnpm-lock.yaml
Labels: status:ready, no changeset needed, v-next

#5592 feat: add a built-in console task
  v-next/hardhat/src/internal/builtin-plugins/console/index.ts
  v-next/hardhat/src/internal/builtin-plugins/console/task-action.ts
  v-next/hardhat/src/internal/builtin-plugins/index.ts
  v-next/hardhat/src/internal/builtin-plugins/run/task-action.ts
  v-next/hardhat/test/internal/builtin-plugins/console/task-action.ts
  v-next/hardhat/test/internal/cli/main.ts
Labels: status:ready, v-next

#5580 feat: port the Http Provider to v3
  v-next/hardhat-errors/src/descriptors.ts
  v-next/hardhat-errors/src/errors.ts
  v-next/hardhat-utils/src/errors/request.ts
  v-next/hardhat-utils/src/internal/request.ts
  v-next/hardhat-utils/src/lang.ts
  v-next/hardhat-utils/src/request.ts
  v-next/hardhat-utils/test/helpers/request.ts
  v-next/hardhat-utils/test/lang.ts
  v-next/hardhat-utils/test/request.ts
  v-next/hardhat/src/internal/network/http-provider.ts
  v-next/hardhat/src/internal/network/provider-errors.ts
  v-next/hardhat/src/internal/network/utils/json-rpc.ts
  v-next/hardhat/src/internal/utils/package.ts
  v-next/hardhat/src/types/providers.ts
  v-next/hardhat/test/internal/network/http-provider.ts
  v-next/hardhat/test/utils.ts
Labels: status:ready, v-next

#5606 [v-next] Remove slack notifications
  .github/workflows/review-approved-slack-notification.yml
  .github/workflows/review-requested-slack-notification.yml
Labels: status:ready

#5607 Remove Slack notifications
  .github/workflows/review-approved-slack-notification.yml
  .github/workflows/review-requested-slack-notification.yml
Labels: status:ready, no changeset needed

#5655 fix: return no accounts if `eth_accounts` is deprecated
  .changeset/popular-ways-whisper.md
  packages/hardhat-ethers/src/internal/helpers.ts
  packages/hardhat-ethers/test/index.ts
Labels: status:ready

#5545 Add logic to send analytics data
  v-next/core/src/global-dir.ts
  v-next/hardhat/src/internal/cli/telemetry/analytics/analytics.ts
  v-next/hardhat/src/internal/cli/telemetry/analytics/subprocess.ts
  v-next/hardhat/src/internal/cli/telemetry/analytics/types.ts
  v-next/hardhat/src/internal/cli/telemetry/analytics/utils.ts
  v-next/hardhat/src/internal/cli/telemetry/telemetry-permissions.ts
  v-next/hardhat/test/internal/cli/telemetry/analytics/analytics.ts
  v-next/hardhat/test/internal/cli/telemetry/analytics/utils.ts
  v-next/hardhat/test/internal/cli/telemetry/helpers.ts
  v-next/hardhat/test/internal/cli/telemetry/telemetry-permissions.ts
Labels: status:ready, v-next

#5658 refactor!: Remove the experimental MessageTrace hook
  .changeset/violet-apes-kick.md
  packages/hardhat-core/src/internal/cli/cli.ts
  packages/hardhat-core/src/internal/context.ts
  packages/hardhat-core/src/internal/core/config/config-env.ts
  packages/hardhat-core/src/internal/core/providers/construction.ts
  packages/hardhat-core/src/internal/core/runtime-environment.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/provider.ts
  packages/hardhat-core/src/internal/lib/hardhat-lib.ts
  packages/hardhat-core/src/register.ts
  packages/hardhat-core/src/types/experimental.ts
  packages/hardhat-core/src/types/index.ts
  packages/hardhat-core/test/internal/core/providers/construction.ts
Labels: status:ready

#5664 Add await in provider creation
  .changeset/loud-cooks-obey.md
  packages/hardhat-core/src/internal/hardhat-network/provider/provider.ts
Labels: status:ready

#5570 Port sentry logic
  pnpm-lock.yaml
  v-next/hardhat/package.json
  v-next/hardhat/src/internal/cli/telemetry/sentry/anonymizer.ts
  v-next/hardhat/src/internal/cli/telemetry/sentry/reporter.ts
  v-next/hardhat/src/internal/cli/telemetry/sentry/subprocess.ts
  v-next/hardhat/src/internal/cli/telemetry/sentry/transport.ts
  v-next/hardhat/test/fixture-projects/cli/telemetry/sentry/node_modules/@nomicfoundation/errors.ts
  v-next/hardhat/test/fixture-projects/cli/telemetry/sentry/node_modules/@nomicfoundation/package.json
  v-next/hardhat/test/internal/cli/telemetry/analytics/analytics.ts
  v-next/hardhat/test/internal/cli/telemetry/analytics/utils.ts
  v-next/hardhat/test/internal/cli/telemetry/helpers.ts
  v-next/hardhat/test/internal/cli/telemetry/sentry/anonymizer.ts
  v-next/hardhat/test/internal/cli/telemetry/sentry/reporter.ts
  v-next/hardhat/test/internal/cli/telemetry/sentry/subprocess.ts
Labels: status:ready, v-next

#5584 Node test runner plugin supporting js tests
  pnpm-lock.yaml
  v-next/core/src/internal/hre.ts
  v-next/core/src/types/config.ts
  v-next/core/test/internal/configuration-variables/configuration-variables.ts
  v-next/core/test/internal/hook-manager.ts
  v-next/core/test/internal/user-interruptions/user-interruptions-manager.ts
  v-next/example-project/hardhat.config.ts
  v-next/example-project/package.json
  v-next/example-project/test/example-test.ts
  v-next/example-project/test/other-example-test.js
  v-next/hardhat-node-test-runner/.eslintrc.cjs
  v-next/hardhat-node-test-runner/.gitignore
  v-next/hardhat-node-test-runner/.prettierignore
  v-next/hardhat-node-test-runner/LICENSE
  v-next/hardhat-node-test-runner/README.md
  v-next/hardhat-node-test-runner/package.json
  v-next/hardhat-node-test-runner/src/index.ts
  v-next/hardhat-node-test-runner/src/task-action.ts
  v-next/hardhat-node-test-runner/test/index.ts
  v-next/hardhat-node-test-runner/tsconfig.json
Labels: v-next

#5674 Block-scope cases that declare the same variable
  packages/hardhat-core/src/internal/hardhat-network/stack-traces/solidity-errors.ts
Labels: status:ready, no changeset needed

#5662 docs: enhance the test reporter's README
  v-next/hardhat-node-test-reporter/README.md
  v-next/hardhat-node-test-reporter/demo.gif
  v-next/hardhat-node-test-reporter/src/error-formatting.ts
  v-next/hardhat-node-test-reporter/src/formatting.ts
  v-next/hardhat-node-test-reporter/src/reporter.ts
Labels: no changeset needed

#5666 ci: do not pipe output to stdout during console test
  v-next/hardhat/test/internal/builtin-plugins/console/task-action.ts
Labels: status:ready, no changeset needed

#5676 ci: trigger v-next ci on pull requests to v-next branch
  .github/workflows/v-next-ci.yml
Labels: status:ready

#5671 Update scripts/check-v-next-dependencies.js
  scripts/check-v-next-dependencies.js
Labels: status:ready

#5672 Change how we load tsx
  v-next/hardhat/src/cli.ts
  v-next/hardhat/src/internal/cli/main.ts
Labels: status:ready

#5679 chore: rename files to follow snake-case convention
  v-next/hardhat/src/internal/builtin-plugins/hardhat-foo/hook-handlers/config.ts
  v-next/hardhat/src/internal/builtin-plugins/hardhat-foo/hook-handlers/configuration-variables.ts
  v-next/hardhat/src/internal/builtin-plugins/hardhat-foo/index.ts
Labels: status:ready, v-next

#5653 ci: start tracking hardhat dependencies
  .github/workflows/v-next-ci.yml
  v-next/core/.gitignore
  v-next/example-project/.gitignore
  v-next/hardhat-build-system/.gitignore
  v-next/hardhat-errors/.gitignore
  v-next/hardhat-node-test-reporter/.gitignore
  v-next/hardhat-test-utils/.gitignore
  v-next/hardhat-utils/.gitignore
  v-next/hardhat-zod-utils/.gitignore
  v-next/hardhat/.gitignore
  v-next/template-package/.gitignore
Labels: status:ready, no changeset needed

#5682 ci: fix hardhat dependencies reporting
  .github/workflows/v-next-ci.yml
Labels: status:ready

#5681 Help messages don't display the default values of options and positional arguments
  v-next/hardhat-errors/src/descriptors.ts
  v-next/hardhat/src/internal/cli/helpers/utils.ts
  v-next/hardhat/test/fixture-projects/cli/parsing/default-values/hardhat.config.ts
  v-next/hardhat/test/internal/cli/helpers/utils.ts
  v-next/hardhat/test/internal/cli/main.ts
Labels: status:triaging, v-next

#5685 Render the node-test-reporter integration test results as SVG
  scripts/setup.sh
  v-next/hardhat-node-test-reporter/integration-tests/README.md
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/example-test/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/example-test/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/hooks-test/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/hooks-test/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/multi-test/fail.ts
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/multi-test/import.ts
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/multi-test/pass.ts
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/multi-test/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/multi-test/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/nested-test/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/nested-test/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/only-test/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/only-test/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/slow-test/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/slow-test/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/todo-test/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/todo-test/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/top-level-test/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/top-level-test/result.txt
  v-next/hardhat-node-test-reporter/scripts/regenerate-fixtures.sh
Labels: status:ready

#5687 chore: set exit code to 1 on test failures
  v-next/hardhat-mocha-test-runner/src/task-action.ts
  v-next/hardhat-node-test-runner/src/task-action.ts
Labels: status:ready

#5669 chore: implement additional test cases for the node test reporter
  scripts/setup.sh
  v-next/hardhat-node-test-reporter/integration-tests/README.md
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/example-test/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/example-test/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/hooks-test/after-each.ts
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/hooks-test/after.ts
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/hooks-test/before-each.ts
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/hooks-test/before.ts
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/hooks-test/describe.ts
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/hooks-test/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/hooks-test/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/multi-test/fail.ts
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/multi-test/import.ts
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/multi-test/pass.ts
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/multi-test/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/multi-test/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/nested-test/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/nested-test/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/nested-test/test.ts
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/only-test/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/only-test/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/only-test/test.ts
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/slow-test/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/slow-test/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/slow-test/test.ts
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/todo-test/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/todo-test/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/todo-test/test.ts
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/top-level-test/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/top-level-test/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/top-level-test/test.ts
  v-next/hardhat-node-test-reporter/integration-tests/index.ts
  v-next/hardhat-node-test-reporter/scripts/regenerate-fixtures.sh
Labels: status:ready

#5693 Zod utils improvements
  config-v-next/eslint.cjs
  v-next/hardhat-mocha-test-runner/src/hookHandlers/config.ts
  v-next/hardhat-zod-utils/src/index.ts
  v-next/hardhat-zod-utils/test/index.ts
  v-next/hardhat-zod-utils/tsconfig.json
  v-next/hardhat/src/internal/builtin-plugins/hardhat-foo/hook-handlers/config.ts
  v-next/hardhat/src/internal/cli/telemetry/analytics/subprocess.ts
  v-next/hardhat/src/internal/cli/telemetry/sentry/reporter.ts
  v-next/hardhat/src/internal/cli/telemetry/sentry/subprocess.ts
Labels: status:ready
