Repository NomicFoundation/hardhat, pull requests merged in 2024-12, with the labels that each got.

#6002 fix: typos in documentation files
  docs/temp/info.md
Labels: status:triaging, no changeset needed

#6008 Update test-contracts.md
  docs/src/content/hardhat-runner/docs/guides/test-contracts.md
Labels: status:triaging, no changeset needed

#6011 Fix typos in documentation for using Viem and formatting instructions
  docs/src/content/hardhat-runner/docs/advanced/using-viem.md
  docs/src/content/hardhat-vscode/docs/formatting.md
Labels: status:triaging, no changeset needed

#5953 fix: copy .gitignore files during project initialization
  v-next/hardhat/src/internal/cli/init/init.ts
  v-next/hardhat/src/internal/cli/init/template.ts
  v-next/hardhat/templates/README.md
  v-next/hardhat/templates/mocha-ethers/gitignore
  v-next/hardhat/templates/node-test-runner-viem/gitignore
  v-next/hardhat/test/internal/cli/init/init.ts
Labels: status:ready

#6010 Add check for test networks in hardhat-network-helpers
  v-next/hardhat-errors/src/descriptors.ts
  v-next/hardhat-network-helpers/src/internal/hook-handlers/network.ts
  v-next/hardhat-network-helpers/src/internal/network-helpers/network-helpers.ts
  v-next/hardhat-network-helpers/src/internal/network-helpers/time/time.ts
  v-next/hardhat-network-helpers/test/helpers/helpers.ts
  v-next/hardhat-network-helpers/test/helpers/mocked-web3-client-version.ts
  v-next/hardhat-network-helpers/test/index.ts
Labels: status:ready, no changeset needed

#6003 Network manager cleanup Pt1
  v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/edr-provider.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/hook-handlers/config.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/http-provider.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/network-manager.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/http-provider.ts
Labels: status:ready, v-next

#6027 fixed small typo
  docs/src/content/ignition/docs/guides/error-handling.md
Labels: status:triaging, no changeset needed

#6028 Documentation Grammar and Spelling Improvements
  docs/README.md
  docs/src/content/hardhat-runner/docs/guides/deploying.md
Labels: status:triaging, no changeset needed

#6017 micro-eth-signer issue when deploying local accounts
  pnpm-lock.yaml
  v-next/hardhat-errors/src/descriptors.ts
  v-next/hardhat/package.json
  v-next/hardhat/src/internal/builtin-plugins/network-manager/request-handlers/handlers/accounts/local-accounts.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/rpc/types/address.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/rpc/types/tx-request.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/request-handlers/handlers/accounts/local-accounts.ts
Labels: no changeset needed

#6024 Revisit the 'create' method in HardhatEthersSigner
  v-next/hardhat-ethers/src/internal/signers/signers.ts
Labels: status:ready, no changeset needed

#6033 Enable debug logging via CLI flag
  v-next/hardhat/src/internal/builtin-global-options.ts
  v-next/hardhat/src/internal/cli/main.ts
  v-next/hardhat/test/internal/cli/helpers/getGlobalHelpString.ts
  v-next/hardhat/test/internal/cli/main.ts
  v-next/hardhat/test/internal/hre-intialization.ts
Labels: status:ready, no changeset needed

#6044 docs: Fix grammatical issue Update README.md
  docs/README.md
Labels: status:triaging, no changeset needed

#6009 Update oracles.md
  docs/src/content/hardhat-runner/docs/supporter-guides/oracles.md
Labels: status:triaging, no changeset needed

#6041 Suggest running hardhat --init when no config file is found
  v-next/hardhat-errors/src/descriptors.ts
Labels: status:triaging

#6016 Make arguments of Task.run() optional, defaulting to empty object
  v-next/hardhat/src/internal/core/tasks/resolved-task.ts
  v-next/hardhat/src/types/tasks.ts
  v-next/hardhat/test/internal/core/tasks/task-manager.ts
Labels: status:ready, v-next

#6032 Minor refactoring tasks for v-next
  v-next/hardhat/src/internal/cli/help/get-global-help-string.ts
  v-next/hardhat/src/internal/cli/help/get-help-string.ts
  v-next/hardhat/src/internal/cli/help/utils.ts
  v-next/hardhat/src/internal/cli/init/constants.ts
  v-next/hardhat/src/internal/cli/init/init.ts
  v-next/hardhat/src/internal/cli/main.ts
  v-next/hardhat/test/internal/cli/help/get-global-help-string.ts
  v-next/hardhat/test/internal/cli/help/get-help-string.ts
  v-next/hardhat/test/internal/cli/help/utils.ts
Labels: status:triaging

#5965 Add reference docs for CLI commands
  docs/pnpm-lock.yaml
  docs/src/content/ignition/docs/reference/_dirinfo.yaml
  docs/src/content/ignition/docs/reference/cli-commands.md
Labels: status:triaging, no changeset needed

#6052 fix ts import for hardhat-ledger package
  docs/src/content/ignition/docs/guides/ledger.md
Labels: status:triaging, no changeset needed

#6047 Add validations for HardhatUserConfig.paths
  v-next/hardhat/src/internal/core/config-validation.ts
  v-next/hardhat/test/internal/core/config-validation.ts
Labels: status:ready, no changeset needed, v-next

#6060 Fix incorrect usage of articles ("a" vs "an") in documentation
  docs/src/content/hardhat-runner/docs/advanced/building-plugins.md
  packages/hardhat-chai-matchers/src/internal/reverted/reverted.ts
  packages/hardhat-chai-matchers/test/reverted/reverted.ts
  packages/hardhat-core/src/internal/cli/cli.ts
  packages/hardhat-core/src/internal/cli/is-node-version-to-warn-on.ts
  packages/hardhat-core/src/internal/core/config/config-validation.ts
  packages/hardhat-core/src/internal/core/typescript-support.ts
Labels: status:triaging

#6025 feat: port the node task to hardhat v3
  pnpm-lock.yaml
  v-next/hardhat-errors/src/descriptors.ts
  v-next/hardhat/package.json
  v-next/hardhat/src/internal/builtin-plugins/index.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/json-rpc.ts
  v-next/hardhat/src/internal/builtin-plugins/node/index.ts
  v-next/hardhat/src/internal/builtin-plugins/node/json-rpc/handler.ts
  v-next/hardhat/src/internal/builtin-plugins/node/json-rpc/server.ts
  v-next/hardhat/src/internal/builtin-plugins/node/task-action.ts
  v-next/hardhat/test/internal/builtin-plugins/node/json-rpc/server.ts
  v-next/hardhat/test/internal/cli/main.ts
Labels: status:ready

#6059 Add doc for passing param path to deploy function
  docs/src/content/ignition/docs/guides/deploy.md
Labels: no changeset needed

#6043 Add support tests for project root resolution
  v-next/hardhat/test/fixture-projects/resolve-project-root/no-path-param/folder/empty.txt
  v-next/hardhat/test/fixture-projects/resolve-project-root/no-path-param/package.json
  v-next/hardhat/test/fixture-projects/resolve-project-root/with-path-param/folder-no-package/empty.txt
  v-next/hardhat/test/fixture-projects/resolve-project-root/with-path-param/folder-with-package/package.json
  v-next/hardhat/test/fixture-projects/resolve-project-root/with-path-param/package.json
  v-next/hardhat/test/internal/hre-intialization.ts
Labels: status:ready, no changeset needed, v-next

#6063 Fix typo in Bash script Update run-fixture-projects.sh
  e2e/run-fixture-projects.sh
Labels: status:triaging, no changeset needed

#6031 Network Config types cleanup and Edr Network config resolution
  v-next/example-project/hardhat.config.ts
  v-next/hardhat-network-helpers/src/internal/network-helpers/helpers/reset.ts
  v-next/hardhat-utils/src/date.ts
  v-next/hardhat-viem/test/clients.ts
  v-next/hardhat-viem/test/contracts.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/accounts/derive-private-keys.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/config-resolution.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/edr-provider.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/types/config.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/types/node-types.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/utils/convert-to-edr.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/hook-handlers/config.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/request-handlers/handlers/accounts/hd-wallet-handler.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/request-handlers/hanlders-array.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/type-extensions/config.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/type-validation.ts
  v-next/hardhat/src/internal/builtin-plugins/node/task-action.ts
  v-next/hardhat/src/internal/constants.ts
  v-next/hardhat/src/types/config.ts
  v-next/hardhat/templates/mocha-ethers/hardhat.config.ts
  v-next/hardhat/templates/node-test-runner-viem/hardhat.config.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/hook-handlers/config.ts
Labels: status:ready

#6074 fix: update broken links and correct typos in documentation
  docs/src/content/tutorial/deploying-to-a-live-network.md
  packages/hardhat-core/test/helpers/errors.ts
  packages/hardhat-verify/test/unit/etherscan.ts
Labels: status:triaging, no changeset needed

#6084 Update NextJS documentation link
  docs/README.md
Labels: status:triaging, no changeset needed

#6094 fix: typos in documentation files
  docs/src/components/CookiePopUp.tsx
Labels: type:bug, status:ready, no changeset needed

#6097 chore: ensure module type early in the init flow
  v-next/hardhat/src/internal/cli/init/init.ts
Labels: status:ready

#5856 Refactor build assert
  packages/hardhat-chai-matchers/src/utils.ts
Labels: status:ready, no changeset needed
