Repository NomicFoundation/hardhat, pull requests merged in 2024-11, with the labels that each got.

#5917 Hardhat v3 alpha release: Thu 31 Oct 2024 11:47 PM UTC
  .changeset/few-students-serve.md
  .changeset/pre.json
  pnpm-lock.yaml
  v-next/example-project/package.json
  v-next/hardhat-errors/package.json
  v-next/hardhat-ethers/package.json
  v-next/hardhat-keystore/package.json
  v-next/hardhat-mocha-test-runner/package.json
  v-next/hardhat-network-helpers/package.json
  v-next/hardhat-node-test-reporter/package.json
  v-next/hardhat-node-test-runner/package.json
  v-next/hardhat-utils/package.json
  v-next/hardhat-viem/package.json
  v-next/hardhat-zod-utils/package.json
  v-next/hardhat/package.json
  v-next/hardhat/templates/mocha-ethers/package.json
  v-next/hardhat/templates/node-test-runner-viem/package.json
  v-next/template-package/package.json
Labels: status:ready

#5918 Fix hardhat package resolution
  v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/resolver/dependency-resolver.ts
Labels: status:ready

#5919 Alpha testing release: 2024-11-01 00:13 UTC
  .changeset/polite-rats-mix.md
  .changeset/pre.json
  pnpm-lock.yaml
  v-next/example-project/package.json
  v-next/hardhat-errors/package.json
  v-next/hardhat-ethers/package.json
  v-next/hardhat-keystore/package.json
  v-next/hardhat-mocha-test-runner/package.json
  v-next/hardhat-network-helpers/package.json
  v-next/hardhat-node-test-reporter/package.json
  v-next/hardhat-node-test-runner/package.json
  v-next/hardhat-utils/package.json
  v-next/hardhat-viem/package.json
  v-next/hardhat-zod-utils/package.json
  v-next/hardhat/package.json
  v-next/hardhat/templates/mocha-ethers/package.json
  v-next/hardhat/templates/node-test-runner-viem/package.json
  v-next/template-package/package.json
Labels: status:ready

#5920 add v-next keystore to the templates
  pnpm-lock.yaml
  v-next/hardhat/templates/mocha-ethers/hardhat.config.ts
  v-next/hardhat/templates/mocha-ethers/package.json
  v-next/hardhat/templates/node-test-runner-viem/hardhat.config.ts
  v-next/hardhat/templates/node-test-runner-viem/package.json
Labels: status:ready, no changeset needed

#5923 Some fixes
  v-next/hardhat-keystore/src/internal/tasks/set.ts
  v-next/hardhat-keystore/test/integration/tasks.ts
  v-next/hardhat/.prettierignore
  v-next/hardhat/src/internal/builtin-plugins/network-manager/json-rpc-request-modifiers/accounts/local-accounts.ts
  v-next/hardhat/src/types/network.ts
Labels: status:ready

#5922 chore: add optimism example script to viem template
  v-next/hardhat/templates/node-test-runner-viem/README.md
  v-next/hardhat/templates/node-test-runner-viem/hardhat.config.ts
  v-next/hardhat/templates/node-test-runner-viem/scripts/deploy-counter-contract.ts
  v-next/hardhat/templates/node-test-runner-viem/scripts/send-op-tx.ts
Labels: status:ready

#5925 Make the dependencies installation work in powershell
  v-next/hardhat/src/internal/cli/init/init.ts
Labels: status:ready

#5926 Fix node-test-runner tsx injection on windows
  v-next/hardhat-node-test-runner/src/task-action.ts
Labels: status:ready

#5927 Hardhat v3 alpha release: Windows fixes
  .changeset/great-dots-rhyme.md
  .changeset/pre.json
  .changeset/shy-doors-peel.md
  pnpm-lock.yaml
  v-next/example-project/package.json
  v-next/hardhat-errors/package.json
  v-next/hardhat-ethers/package.json
  v-next/hardhat-keystore/package.json
  v-next/hardhat-mocha-test-runner/package.json
  v-next/hardhat-network-helpers/package.json
  v-next/hardhat-node-test-reporter/package.json
  v-next/hardhat-node-test-runner/package.json
  v-next/hardhat-utils/package.json
  v-next/hardhat-viem/package.json
  v-next/hardhat-zod-utils/package.json
  v-next/hardhat/package.json
  v-next/hardhat/templates/mocha-ethers/package.json
  v-next/hardhat/templates/node-test-runner-viem/package.json
  v-next/template-package/package.json
Labels: status:ready

#5929 Print the Node.js warning before loading main
  v-next/hardhat/src/cli.ts
  v-next/hardhat/src/internal/cli/main.ts
  v-next/hardhat/src/internal/cli/node-version.ts
Labels: status:ready

#5932 Add ethers to the Mocha+Ethers template's package.json
  pnpm-lock.yaml
  v-next/hardhat/templates/mocha-ethers/package.json
Labels: status:ready

#5933 Improve how we detect if the project is CJS
  v-next/hardhat/src/internal/cli/error-handler.ts
  v-next/hardhat/src/internal/cli/main.ts
Labels: status:ready

#5935 Better ESM-only error message.
  v-next/hardhat/src/internal/cli/main.ts
Labels: status:ready

#5934 Upgrade EDR
  pnpm-lock.yaml
  v-next/example-project/contracts/Counter.t.sol
  v-next/example-project/hardhat.config.ts
  v-next/example-project/scripts/send-op-tx-viem.ts
  v-next/hardhat/package.json
  v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/stack-traces/stack-trace-solidity-errors.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/utils/convert-to-edr.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity-test/runner.ts
Labels: status:ready

#5938 Update the `node:test`+`viem` template
  pnpm-lock.yaml
  v-next/example-project/package.json
  v-next/hardhat-viem/package.json
  v-next/hardhat/templates/node-test-runner-viem/README.md
  v-next/hardhat/templates/node-test-runner-viem/contracts/Counter.sol
  v-next/hardhat/templates/node-test-runner-viem/contracts/Counter.t.sol
  v-next/hardhat/templates/node-test-runner-viem/contracts/Lock.sol
  v-next/hardhat/templates/node-test-runner-viem/contracts/TestWithForgeStd.t.sol
  v-next/hardhat/templates/node-test-runner-viem/hardhat.config.ts
  v-next/hardhat/templates/node-test-runner-viem/package.json
  v-next/hardhat/templates/node-test-runner-viem/scripts/send-op-tx.ts
  v-next/hardhat/templates/node-test-runner-viem/test/Lock.ts
  v-next/hardhat/templates/node-test-runner-viem/tsconfig.json
Labels: status:ready

#5939 Update the `mocha`+`ethers` template
  v-next/hardhat/templates/mocha-ethers/README.md
  v-next/hardhat/templates/mocha-ethers/contracts/Counter.sol
  v-next/hardhat/templates/mocha-ethers/contracts/Counter.t.sol
  v-next/hardhat/templates/mocha-ethers/contracts/Lock.sol
  v-next/hardhat/templates/mocha-ethers/contracts/TestWithForgeStd.t.sol
  v-next/hardhat/templates/mocha-ethers/hardhat.config.ts
  v-next/hardhat/templates/mocha-ethers/scripts/deploy-counter-contract.ts
  v-next/hardhat/templates/mocha-ethers/scripts/send-op-tx.ts
  v-next/hardhat/templates/mocha-ethers/test/Lock.ts
  v-next/hardhat/templates/mocha-ethers/test/setup.ts
  v-next/hardhat/templates/mocha-ethers/tsconfig.json
  v-next/hardhat/templates/node-test-runner-viem/README.md
Labels: status:ready

#5940 Alpha testing release: 2024-11-07 17:06 UTC
  .changeset/clever-buckets-kneel.md
  .changeset/pre.json
  pnpm-lock.yaml
  v-next/example-project/package.json
  v-next/hardhat-errors/package.json
  v-next/hardhat-ethers/package.json
  v-next/hardhat-keystore/package.json
  v-next/hardhat-mocha-test-runner/package.json
  v-next/hardhat-network-helpers/package.json
  v-next/hardhat-node-test-reporter/package.json
  v-next/hardhat-node-test-runner/package.json
  v-next/hardhat-utils/package.json
  v-next/hardhat-viem/package.json
  v-next/hardhat-zod-utils/package.json
  v-next/hardhat/package.json
  v-next/hardhat/templates/mocha-ethers/package.json
  v-next/hardhat/templates/node-test-runner-viem/package.json
  v-next/template-package/package.json
Labels: status:ready

#5955 fix: bump EDR to 0.6.5
  .changeset/five-eagles-confess.md
  packages/hardhat-core/package.json
  pnpm-lock.yaml
Labels: status:ready

#5968 Grammar Fix in Linaria Documentation
  docs/README.md
  docs/src/content/hardhat-runner/docs/config/index.md
  docs/src/content/ignition/docs/guides/upgradeable-proxies.md
Labels: status:triaging, no changeset needed

#5972 chore: add piotr to issue auto-assigner
  .github/workflows/autoassign-issues.yml
Labels: status:ready, no changeset needed

#5843 Add pnpm to tabgroup at hardhat-and-foundry.md
  docs/src/content/hardhat-runner/docs/advanced/hardhat-and-foundry.md
Labels: status:triaging, no changeset needed

#5749 docs: hardhat-completion add windows troubleshooting
  docs/src/content/hardhat-runner/docs/guides/command-line-completion.md
Labels: status:triaging, no changeset needed

#5894 updated some outdated links
  packages/hardhat-core/README.md
Labels: status:triaging, no changeset needed

#5754 Update verifying.md
  docs/src/content/hardhat-runner/docs/guides/verifying.md
Labels: status:triaging, no changeset needed

#5947 feat: adds --output to flatten
  .changeset/thick-lizards-yell.md
  packages/hardhat-core/src/builtin-tasks/flatten.ts
  packages/hardhat-core/test/builtin-tasks/flatten.ts
Labels: status:ready

#5971 chore: prevent network configuration properties from being modified
  v-next/hardhat-ethers/src/internal/hardhat-ethers-provider/hardhat-ethers-provider.ts
  v-next/hardhat-ethers/src/internal/hardhat-helpers/hardhat-helpers.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/json-rpc-request-modifiers/json-rpc-request-modifier.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/network-connection.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/network-manager.ts
  v-next/hardhat/src/types/network.ts
Labels: status:ready
