Repository NomicFoundation/hardhat, pull requests merged in 2024-09, with the labels that each got.

#5699 fix: correct peer dependency for Hardhat
  .changeset/bright-falcons-impress.md
  .changeset/lovely-onions-notice.md
  .changeset/olive-comics-kick.md
  .changeset/pink-bees-search.md
  .changeset/six-colts-cover.md
Labels: status:ready

#5701 Improve missing value for the task argument
  v-next/hardhat-errors/src/descriptors.ts
Labels: v-next

#5702 Remove hardhatFoo plugin from Hardhat package
  v-next/hardhat/src/internal/builtin-plugins/hardhat-foo/hook-handlers/config.ts
  v-next/hardhat/src/internal/builtin-plugins/hardhat-foo/hook-handlers/configuration-variables.ts
  v-next/hardhat/src/internal/builtin-plugins/hardhat-foo/index.ts
  v-next/hardhat/src/internal/builtin-plugins/hardhat-foo/type-extensions.ts
  v-next/hardhat/src/internal/builtin-plugins/index.ts
  v-next/hardhat/test/hre/index.ts
  v-next/hardhat/test/internal/cli/main.ts
Labels: v-next

#5703 Add hardhat-switch-network plugin
  docs/src/content/hardhat-runner/plugins/plugins.ts
Labels: no changeset needed

#5698 `core` in `hardhat` continuation
  v-next/hardhat/.eslintrc.cjs
  v-next/hardhat/src/config.ts
  v-next/hardhat/src/hre.ts
  v-next/hardhat/src/index.ts
  v-next/hardhat/src/internal/builtin-global-options.ts
  v-next/hardhat/src/internal/builtin-plugins/clean/task-action.ts
  v-next/hardhat/src/internal/builtin-plugins/console/task-action.ts
  v-next/hardhat/src/internal/cli/helpers/utils.ts
  v-next/hardhat/src/internal/cli/init/init.ts
  v-next/hardhat/src/internal/cli/main.ts
  v-next/hardhat/src/internal/cli/telemetry/analytics/utils.ts
  v-next/hardhat/src/internal/cli/telemetry/telemetry-permissions.ts
  v-next/hardhat/src/internal/config-loading.ts
  v-next/hardhat/src/internal/core/config-validation.ts
  v-next/hardhat/src/internal/core/config.ts
  v-next/hardhat/src/internal/core/index.ts
  v-next/hardhat/src/internal/global-dir.ts
  v-next/hardhat/src/internal/helpers/config-loading.ts
  v-next/hardhat/src/internal/hre-intialization.ts
  v-next/hardhat/test/fixture-projects/config-custom-path/other.config.js
  v-next/hardhat/test/internal/builtin-plugins/clean/task-action.ts
  v-next/hardhat/test/internal/builtin-plugins/console/task-action.ts
  v-next/hardhat/test/internal/builtin-plugins/run/task-action.ts
  v-next/hardhat/test/internal/cli/init/init.ts
  v-next/hardhat/test/internal/cli/main.ts
  v-next/hardhat/test/internal/cli/telemetry/telemetry-permissions.ts
  v-next/hardhat/test/internal/core/config-validation.ts
  v-next/hardhat/test/internal/core/configuration-variables/configuration-variables.ts
  v-next/hardhat/test/internal/core/global-options.ts
  v-next/hardhat/test/internal/core/hook-manager.ts
  v-next/hardhat/test/internal/core/tasks/builders.ts
  v-next/hardhat/test/internal/core/tasks/task-manager.ts
  v-next/hardhat/test/internal/core/user-interruptions/user-interruptions-manager.ts
  v-next/hardhat/test/internal/global-dir.ts
  v-next/hardhat/test/internal/hre-intialization.ts
Labels: status:ready, v-next

#5704 Remove unused plugin property
  v-next/example-project/hardhat.config.ts
Labels: status:triaging, v-next

#5706 No `.help` on console start
  v-next/hardhat/src/internal/builtin-plugins/console/index.ts
Labels: status:ready

#5707 Fix two bugs in the telemetry consent workflow
  v-next/hardhat-test-utils/src/fs.ts
  v-next/hardhat-test-utils/src/index.ts
  v-next/hardhat/src/internal/cli/prompt/prompt.ts
  v-next/hardhat/src/internal/cli/telemetry/telemetry-permissions.ts
  v-next/hardhat/src/internal/constants.ts
  v-next/hardhat/src/internal/global-dir.ts
  v-next/hardhat/test/internal/cli/telemetry/telemetry-permissions.ts
Labels: status:ready

#5680 Network manager implementation (M1)
  pnpm-lock.yaml
  v-next/example-project/hardhat.config.ts
  v-next/example-project/package.json
  v-next/example-project/scripts/viem-plugin-example.ts
  v-next/example-project/viem-scketch-plugin.ts
  v-next/hardhat-errors/src/descriptors.ts
  v-next/hardhat/package.json
  v-next/hardhat/src/index.ts
  v-next/hardhat/src/internal/builtin-plugins/console/task-action.ts
  v-next/hardhat/src/internal/builtin-plugins/index.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/hook-handlers/config.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/hook-handlers/hre.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/http-provider.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/index.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/json-rpc.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/network-connection.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/network-manager.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/provider-errors.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/type-extensions/config.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/type-extensions/global-options.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/type-extensions/hooks.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/type-extensions/hre.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/type-validation.ts
  v-next/hardhat/src/internal/cli/telemetry/sentry/reporter.ts
  v-next/hardhat/src/internal/core/hre.ts
  v-next/hardhat/src/types/network.ts
  v-next/hardhat/src/types/providers.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/http-provider.ts
  v-next/hardhat/test/internal/cli/main.ts
  v-next/hardhat/test/internal/cli/telemetry/sentry/reporter.ts
  v-next/hardhat/test/internal/hre-intialization.ts
  v-next/hardhat/test/types/global-options.ts
Labels: v-next

#5705 Re-throw hardhat errors from scripts
  v-next/hardhat/src/internal/builtin-plugins/run/task-action.ts
  v-next/hardhat/test/fixture-projects/run-ts-script/scripts/throws-hardhat-error.ts
  v-next/hardhat/test/internal/builtin-plugins/run/task-action.ts
Labels: status:ready

#5713 `ethereum-cryptography` cleanup
  pnpm-lock.yaml
  v-next/hardhat-utils/package.json
  v-next/hardhat-utils/src/crypto.ts
  v-next/hardhat/package.json
Labels: status:ready

#5725 hh-utils flaky subprocess test: ensure the JSON file is fully written before attempting to read it
  v-next/hardhat-utils/test/subprocess.ts
Labels: no changeset needed, v-next

#5715 Remove hardhat-change-network plugin
  docs/src/content/hardhat-runner/plugins/plugins.ts
Labels: no changeset needed

#5670 docs: add pnpm to document
  docs/src/content/hardhat-chai-matchers/docs/migrate-from-waffle.md
  docs/src/content/hardhat-chai-matchers/docs/overview.md
  docs/src/content/hardhat-network-helpers/docs/overview.md
  docs/src/content/hardhat-runner/docs/advanced/create-task.md
  docs/src/content/hardhat-runner/docs/advanced/migrating-from-hardhat-waffle.md
  docs/src/content/hardhat-runner/docs/advanced/using-esm.md
  docs/src/content/hardhat-runner/docs/getting-started/index.md
  docs/src/content/hardhat-runner/docs/guides/project-setup.md
  docs/src/content/hardhat-runner/docs/supporter-guides/oracles.md
  docs/src/content/ignition/docs/advanced/migrating.md
  docs/src/content/ignition/docs/getting-started/index.md
  docs/src/content/ignition/docs/guides/ledger.md
  docs/src/content/ignition/docs/guides/upgradeable-proxies.md
  docs/src/content/ignition/docs/guides/viem.md
  docs/src/content/tutorial/creating-a-new-hardhat-project.md
  docs/temp/tabsConfig.json
Labels: no changeset needed

#5717 fix: pnpm build before pnpm test:only
  v-next/example-project/package.json
  v-next/hardhat-build-system/package.json
  v-next/hardhat-errors/package.json
  v-next/hardhat-mocha-test-runner/package.json
  v-next/hardhat-node-test-reporter/package.json
  v-next/hardhat-node-test-runner/package.json
  v-next/hardhat-test-utils/package.json
  v-next/hardhat-utils/package.json
  v-next/hardhat-zod-utils/package.json
  v-next/hardhat/package.json
  v-next/template-package/package.json
Labels: status:ready

#5734 Move the global-dir functions from hardhat to harhdat-utils
  pnpm-lock.yaml
  v-next/hardhat-utils/package.json
  v-next/hardhat-utils/src/global-dir.ts
  v-next/hardhat-utils/src/internal/global-dir.ts
  v-next/hardhat-utils/test/global-dir.ts
  v-next/hardhat/src/internal/builtin-plugins/clean/task-action.ts
  v-next/hardhat/src/internal/builtin-plugins/console/task-action.ts
  v-next/hardhat/src/internal/cli/telemetry/analytics/utils.ts
  v-next/hardhat/src/internal/cli/telemetry/telemetry-permissions.ts
  v-next/hardhat/src/internal/global-dir.ts
  v-next/hardhat/test/internal/builtin-plugins/clean/task-action.ts
  v-next/hardhat/test/internal/global-dir.ts
Labels: no changeset needed, v-next

#5710 Add streaming response
  .changeset/warm-beans-tie.md
  packages/hardhat-core/package.json
  packages/hardhat-core/src/internal/hardhat-network/jsonrpc/handler.ts
  pnpm-lock.yaml
Labels: status:triaging

#5736 Remove unused package 'env-paths' from hardhat
  pnpm-lock.yaml
  v-next/hardhat/package.json
  v-next/hardhat/test/internal/global-dir.ts
Labels: status:triaging, no changeset needed, v-next

#5730 Make the config's `paths` field more extensible and implement its resolution logic
  pnpm-lock.yaml
  v-next/example-project/hardhat.config.ts
  v-next/hardhat-mocha-test-runner/src/hookHandlers/config.ts
  v-next/hardhat-mocha-test-runner/src/task-action.ts
  v-next/hardhat-mocha-test-runner/src/type-extensions.ts
  v-next/hardhat-node-test-runner/package.json
  v-next/hardhat-node-test-runner/src/hookHandlers/config.ts
  v-next/hardhat-node-test-runner/src/index.ts
  v-next/hardhat-node-test-runner/src/task-action.ts
  v-next/hardhat-node-test-runner/src/type-extensions.ts
  v-next/hardhat-node-test-runner/tsconfig.json
  v-next/hardhat-utils/package.json
  v-next/hardhat-utils/src/path.ts
  v-next/hardhat-utils/test/path.ts
  v-next/hardhat/src/internal/builtin-plugins/console/task-action.ts
  v-next/hardhat/src/internal/builtin-plugins/index.ts
  v-next/hardhat/src/internal/builtin-plugins/run/task-action.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/hook-handlers/config.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/index.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/type-extensions.ts
  v-next/hardhat/src/internal/config-loading.ts
  v-next/hardhat/src/internal/core/hre.ts
  v-next/hardhat/src/types/config.ts
Labels: status:ready

#5654 Hardhat-keystore
  .changeset/pre.json
  pnpm-lock.yaml
  v-next/example-project/README.md
  v-next/example-project/hardhat.config.ts
  v-next/example-project/package.json
  v-next/example-project/test/mocha/other-mocha-test.ts
  v-next/example-project/test/node/other-example-test.js
  v-next/example-project/tsconfig.json
  v-next/hardhat-errors/src/descriptors.ts
  v-next/hardhat-keystore/.eslintrc.cjs
  v-next/hardhat-keystore/.gitignore
  v-next/hardhat-keystore/.prettierignore
  v-next/hardhat-keystore/LICENSE
  v-next/hardhat-keystore/README.md
  v-next/hardhat-keystore/package.json
  v-next/hardhat-keystore/src/index.ts
  v-next/hardhat-keystore/src/internal/constants.ts
  v-next/hardhat-keystore/src/internal/hook-handlers/config.ts
  v-next/hardhat-keystore/src/internal/hook-handlers/configuration-variables.ts
  v-next/hardhat-keystore/src/internal/keystores/unencrypted-keystore.ts
  v-next/hardhat-keystore/src/internal/loaders/file-manager.ts
  v-next/hardhat-keystore/src/internal/loaders/keystore-file-loader.ts
  v-next/hardhat-keystore/src/internal/tasks/delete.ts
  v-next/hardhat-keystore/src/internal/tasks/get.ts
  v-next/hardhat-keystore/src/internal/tasks/list.ts
  v-next/hardhat-keystore/src/internal/tasks/set.ts
  v-next/hardhat-keystore/src/internal/type-extensions.ts
  v-next/hardhat-keystore/src/internal/types-validation.ts
  v-next/hardhat-keystore/src/internal/types.ts
  v-next/hardhat-keystore/src/internal/ui/request-secret-input.ts
  v-next/hardhat-keystore/src/internal/ui/user-display-messages.ts
  v-next/hardhat-keystore/src/internal/utils/get-keystore-file-path.ts
  v-next/hardhat-keystore/src/internal/utils/setup-keystore-loader-from.ts
  v-next/hardhat-keystore/src/internal/utils/validate-key.ts
  v-next/hardhat-keystore/test/fixture-projects/unencrypted-keystore/.gitignore
  v-next/hardhat-keystore/test/fixture-projects/unencrypted-keystore/existing-keystore.json
  v-next/hardhat-keystore/test/helpers/assert-output-includes.ts
  v-next/hardhat-keystore/test/helpers/mock-file-manager.ts
  v-next/hardhat-keystore/test/helpers/setup-keystore-file-location-override-at.ts
  v-next/hardhat-keystore/test/hook-handlers/configuration-variables.ts
  v-next/hardhat-keystore/test/integration/tasks.ts
  v-next/hardhat-keystore/test/integration/turn-off-keystore-in-ci.ts
  v-next/hardhat-keystore/test/keystores/unencrypted-keystore.ts
  v-next/hardhat-keystore/test/loaders/keystore-file-loader.ts
  v-next/hardhat-keystore/test/tasks/delete.ts
  v-next/hardhat-keystore/test/tasks/get.ts
  v-next/hardhat-keystore/test/tasks/list.ts
  v-next/hardhat-keystore/test/tasks/set.ts
  v-next/hardhat-keystore/tsconfig.json
Labels: no changeset needed, v-next

#5708 fix(hardhat-viem): type consistency + retryCount 0 on devnet
  .changeset/kind-radios-begin.md
  packages/hardhat-viem/src/internal/clients.ts
  packages/hardhat-viem/src/internal/type-extensions.ts
  packages/hardhat-viem/src/types.ts
  packages/hardhat-viem/test/clients.ts
  packages/hardhat-viem/test/mocks/provider.ts
Labels: status:triaging

#5714 feat: hide node and test runner internals from the stack
  v-next/hardhat-node-test-reporter/README.md
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/errors-test/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/errors-test/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/example-test/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/example-test/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/hooks-test/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/hooks-test/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/multi-test/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/multi-test/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/nested-test/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/nested-test/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/only-test-with-the-flag/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/only-test-with-the-flag/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/only-test-without-the-flag/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/only-test-without-the-flag/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/slow-test/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/slow-test/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/todo-test/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/todo-test/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/top-level-test/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/top-level-test/result.txt
  v-next/hardhat-node-test-reporter/src/error-formatting.ts
  v-next/hardhat-node-test-reporter/test/error-formatting.ts
Labels: status:ready

#5738 fix: hardhat-chai-matchers - add check byte32 string to reverted matcher
  .changeset/ninety-trainers-rush.md
  packages/hardhat-chai-matchers/src/internal/reverted/reverted.ts
  packages/hardhat-chai-matchers/src/internal/reverted/utils.ts
  packages/hardhat-chai-matchers/test/reverted/reverted.ts
Labels: status:triaging

#5742 Bootstrap time optimizations
  v-next/example-project/viem-scketch-plugin.ts
  v-next/hardhat-node-test-runner/package.json
  v-next/hardhat/src/cli.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/hook-handlers/hre.ts
  v-next/hardhat/src/internal/cli/main.ts
  v-next/hardhat/src/internal/core/plugins/detect-plugin-npm-dependency-problems.ts
Labels: status:ready, no changeset needed

#5724 chore: improve the test reporter's messaging
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/async-describe-test/describe-async.ts
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/async-describe-test/describe-only-async.ts
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/async-describe-test/describe.only.ts
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/async-describe-test/describe.ts
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/async-describe-test/options.json
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/async-describe-test/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/async-describe-test/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/example-test/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/example-test/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/execution-failure-test/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/execution-failure-test/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/hooks-test/before.ts
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/hooks-test/describe.ts
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/hooks-test/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/hooks-test/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/multi-test/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/multi-test/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/nested-test/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/nested-test/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/nested-test/test.ts
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/only-test-with-the-flag/test.ts
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/only-test-without-the-flag/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/only-test-without-the-flag/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/only-test-without-the-flag/test.ts
  v-next/hardhat-node-test-reporter/integration-tests/index.ts
  v-next/hardhat-node-test-reporter/src/error-formatting.ts
  v-next/hardhat-node-test-reporter/src/formatting.ts
  v-next/hardhat-node-test-reporter/src/node-test-utils.ts
  v-next/hardhat-node-test-reporter/src/reporter.ts
  v-next/hardhat-node-test-reporter/src/types.ts
  v-next/hardhat-node-test-runner/src/task-action.ts
Labels: status:ready, v-next

#5746 hardhat-core: upgrade chokidar to v4
  .changeset/warm-tables-dress.md
  packages/hardhat-core/package.json
  pnpm-lock.yaml
Labels: status:triaging

#5743 Introduce the Zod `conditionalUnionType` helper
  config-v-next/eslint.cjs
  pnpm-lock.yaml
  v-next/hardhat-mocha-test-runner/src/hookHandlers/config.ts
  v-next/hardhat-node-test-runner/src/hookHandlers/config.ts
  v-next/hardhat-zod-utils/package.json
  v-next/hardhat-zod-utils/src/index.ts
  v-next/hardhat-zod-utils/test/index.ts
  v-next/hardhat-zod-utils/tsconfig.json
Labels: status:ready

#5744 Add link to Ignition docs in sample projects
  .changeset/late-camels-bow.md
  packages/hardhat-core/sample-projects/javascript-esm/ignition/modules/Lock.js
  packages/hardhat-core/sample-projects/javascript/ignition/modules/Lock.js
  packages/hardhat-core/sample-projects/typescript-viem/ignition/modules/Lock.ts
  packages/hardhat-core/sample-projects/typescript/ignition/modules/Lock.ts
Labels: status:ready

#5731 Fix provider events when init is called
  .changeset/chilled-sheep-buy.md
  packages/hardhat-core/src/internal/core/providers/lazy-initialization.ts
  packages/hardhat-core/test/internal/core/providers/lazy-initialization.ts
Labels: status:ready

#5712 Add QuickNode Faucet
  docs/src/content/hardhat-runner/docs/guides/verifying.md
  docs/src/content/ignition/docs/guides/create2.md
  docs/src/content/ignition/docs/guides/ledger.md
  docs/src/content/ignition/docs/guides/verify.md
  docs/src/content/tutorial/deploying-to-a-live-network.md
Labels: no changeset needed

#5716 Docs update config to allow access to rpc from external ip on specific port using hostname flag
  docs/src/content/hardhat-runner/docs/getting-started/index.md
Labels: no changeset needed

#5751 fix: rework `runSequentialHandlers` plugin ordering
  v-next/hardhat/src/internal/core/hook-manager.ts
  v-next/hardhat/src/types/hooks.ts
  v-next/hardhat/test/internal/core/hook-manager.ts
Labels: status:ready

#5741 add mock artifacts plugins
  v-next/hardhat-errors/src/descriptors.ts
  v-next/hardhat/src/internal/builtin-plugins/artifacts/artifacts-manager.ts
  v-next/hardhat/src/internal/builtin-plugins/artifacts/hook-handlers/hre.ts
  v-next/hardhat/src/internal/builtin-plugins/artifacts/index.ts
  v-next/hardhat/src/internal/builtin-plugins/artifacts/type-extensions.ts
  v-next/hardhat/src/internal/builtin-plugins/index.ts
  v-next/hardhat/src/internal/core/hre.ts
  v-next/hardhat/src/types/artifacts.ts
  v-next/hardhat/test/internal/example-mock-artifacts-plugin-using-test.ts
  v-next/hardhat/test/test-helpers/create-mock-hardhat-runtime-environment.ts
  v-next/hardhat/test/test-helpers/mock-artifacts-manager.ts
Labels: status:ready, v-next

#5759 refactor: Streamline `console.sol` generation
  packages/hardhat-core/console.sol
  packages/hardhat-core/scripts/console-library-generator.ts
  packages/hardhat-core/src/internal/hardhat-network/stack-traces/consoleLogger.ts
  packages/hardhat-core/src/internal/hardhat-network/stack-traces/logger.ts
Labels: status:ready, no changeset needed

#5758 Add new config fields to ignition docs
  docs/src/content/ignition/docs/config/index.md
Labels: no changeset needed

#5764 feat!: Stop supporting console.log selectors with "(u)int" aliases
  .changeset/hot-spoons-sparkle.md
  packages/hardhat-core/scripts/console-library-generator.ts
  packages/hardhat-core/src/internal/hardhat-network/stack-traces/logger.ts
  packages/hardhat-core/test/internal/hardhat-network/stack-traces/test-files/0_5/console-logs/backward-compatibility/c.sol
  packages/hardhat-core/test/internal/hardhat-network/stack-traces/test-files/0_5/console-logs/backward-compatibility/test.json
  packages/hardhat-core/test/internal/hardhat-network/stack-traces/test-files/0_6/console-logs/backward-compatibility/c.sol
  packages/hardhat-core/test/internal/hardhat-network/stack-traces/test-files/0_6/console-logs/backward-compatibility/test.json
  packages/hardhat-core/test/internal/hardhat-network/stack-traces/test-files/0_7/console-logs/backward-compatibility/c.sol
  packages/hardhat-core/test/internal/hardhat-network/stack-traces/test-files/0_7/console-logs/backward-compatibility/test.json
  packages/hardhat-core/test/internal/hardhat-network/stack-traces/test-files/0_8/console-logs/backward-compatibility/c.sol
  packages/hardhat-core/test/internal/hardhat-network/stack-traces/test-files/0_8/console-logs/backward-compatibility/test.json
Labels: status:blocked, status:ready

#5776 Define the `HookContext` as a partial view of the `HRE`
  v-next/hardhat/src/internal/core/hre.ts
  v-next/hardhat/src/types/hooks.ts
  v-next/hardhat/test/internal/core/hook-manager.ts
Labels: status:ready, v-next

#5762 Network Manager M1 remaining tasks
  v-next/hardhat-zod-utils/src/index.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/hook-handlers/config.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/http-provider.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/network-manager.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/type-extensions/config.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/type-validation.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/hook-handlers/config.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/http-provider.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/network-connection.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/network-manager.ts
  v-next/hardhat/test/utils.ts
Labels: v-next

#5772 Move Chaintype type
  v-next/example-project/viem-scketch-plugin.ts
  v-next/hardhat-network-helpers/src/internal/hook-handlers/network.ts
  v-next/hardhat-network-helpers/src/type-extensions.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/network-connection.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/network-manager.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/type-extensions/config.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/type-extensions/hooks.ts
  v-next/hardhat/src/types/network.ts
Labels: v-next

#5775 chore: Bump EDR to 0.6.2 that includes fixes to tracing logic
  .changeset/soft-poets-grab.md
  packages/hardhat-core/package.json
  pnpm-lock.yaml
Labels: status:ready

#5792 Add @medga/hardhat-clone plugin
  docs/src/content/hardhat-runner/plugins/plugins.ts
Labels: no changeset needed
