Repository NomicFoundation/hardhat, pull requests merged in 2024-01, with the labels that each got.

#4724 test: enable `HardhatNode` integration tests
  packages/hardhat-core/test/internal/hardhat-network/provider/node.ts
Labels: area:edr

#4723 test: fix and enable `eth_sendRawTransaction` tests
  crates/edr_eth/src/transaction/signed.rs
  crates/edr_provider/src/data.rs
  crates/edr_provider/src/error.rs
  crates/edr_provider/src/requests/eth/transactions.rs
  crates/edr_provider/src/requests/validation.rs
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/sendRawTransaction.ts
Labels: area:edr

#4728 Add default value for telemetry consent hit
  packages/hardhat-core/src/internal/util/report-telemetry-consent.ts
Labels: status:ready, no changeset needed

#4726 fix: typos
  docs/README.md
  docs/src/content/ignition/docs/guides/creating-modules.md
  packages/hardhat-chai-matchers/src/internal/emit.ts
  packages/hardhat-chai-matchers/test/events.ts
  packages/hardhat-core/src/internal/util/fs-utils.ts
  packages/hardhat-core/test/internal/core/providers/gas-providers.ts
Labels: status:triaging

#4721 test: enable hardhat module tests
  crates/edr_eth/src/receipt.rs
  crates/edr_evm/src/mempool.rs
  crates/edr_evm/src/state/trie.rs
  crates/edr_napi/src/provider.rs
  crates/edr_provider/src/config.rs
  crates/edr_provider/src/data.rs
  crates/edr_provider/src/error.rs
  crates/edr_provider/src/interval.rs
  crates/edr_provider/src/lib.rs
  crates/edr_provider/src/requests.rs
  crates/edr_provider/src/requests/eth.rs
  crates/edr_provider/src/requests/eth/mine.rs
  crates/edr_provider/src/requests/eth/state.rs
  crates/edr_provider/src/requests/hardhat.rs
  crates/edr_provider/src/requests/hardhat/config.rs
  crates/edr_provider/src/requests/hardhat/miner.rs
  crates/edr_provider/src/requests/hardhat/rpc_types/metadata.rs
  crates/edr_provider/src/requests/hardhat/transactions.rs
  crates/edr_provider/src/requests/methods.rs
  crates/edr_provider/src/requests/serde.rs
  crates/edr_provider/src/snapshot.rs
  crates/edr_provider/tests/common.rs
  crates/edr_provider/tests/hardhat_request_serialization.rs
  packages/hardhat-core/src/internal/hardhat-network/provider/modules/hardhat.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/hardhat.ts
Labels: area:edr

#4745 Update README.md
  packages/hardhat-core/README.md
Labels: status:ready, no changeset needed

#4731 test: enable and fix forked-provider tests
  crates/edr_provider/src/data.rs
  crates/edr_provider/src/lib.rs
  crates/edr_provider/src/requests/eth/config.rs
  packages/hardhat-core/test/internal/hardhat-network/provider/forked-provider.ts
Labels: area:edr

#4746 test: enable and fix hardfork Hardhat tests
  Cargo.lock
  crates/edr_defaults/src/lib.rs
  crates/edr_eth/src/access_list.rs
  crates/edr_eth/src/receipt.rs
  crates/edr_eth/src/receipt/block.rs
  crates/edr_eth/src/receipt/transaction.rs
  crates/edr_eth/src/remote/cacheable_method_invocation.rs
  crates/edr_eth/src/remote/client.rs
  crates/edr_eth/src/remote/eth.rs
  crates/edr_eth/src/remote/eth/get_logs.rs
  crates/edr_eth/src/serde.rs
  crates/edr_evm/benches/state/util.rs
  crates/edr_evm/src/block/builder.rs
  crates/edr_evm/src/block/local.rs
  crates/edr_evm/src/block/remote.rs
  crates/edr_evm/src/blockchain/local.rs
  crates/edr_evm/src/blockchain/storage/reservable.rs
  crates/edr_evm/src/miner.rs
  crates/edr_evm/tests/blockchain.rs
  crates/edr_napi/index.d.ts
  crates/edr_napi/src/context.rs
  crates/edr_napi/src/miner.rs
  crates/edr_napi/src/receipt.rs
  crates/edr_provider/Cargo.toml
  crates/edr_provider/src/data.rs
  crates/edr_provider/src/error.rs
  crates/edr_provider/src/lib.rs
  crates/edr_provider/src/requests/eth.rs
  crates/edr_provider/src/requests/eth/blockchain.rs
  crates/edr_provider/src/requests/eth/blocks.rs
  crates/edr_provider/src/requests/eth/call.rs
  crates/edr_provider/src/requests/eth/gas.rs
  crates/edr_provider/src/requests/eth/logs.rs
  crates/edr_provider/src/requests/eth/state.rs
  crates/edr_provider/src/requests/eth/transactions.rs
  crates/edr_provider/src/requests/methods.rs
  crates/edr_provider/src/requests/validation.rs
  crates/edr_provider/tests/eth_request_serialization.rs
  packages/hardhat-core/src/internal/hardhat-network/provider/provider.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/utils/convertToEdr.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/hardforks.ts
Labels: area:edr

#4747 feat: port filters to EDR provider
  Cargo.lock
  crates/edr_eth/src/remote/block_spec.rs
  crates/edr_eth/src/remote/cacheable_method_invocation.rs
  crates/edr_eth/src/remote/client.rs
  crates/edr_eth/src/remote/eth.rs
  crates/edr_eth/src/remote/eth/get_logs.rs
  crates/edr_eth/src/remote/filter.rs
  crates/edr_eth/src/remote/request_methods.rs
  crates/edr_evm/src/block.rs
  crates/edr_evm/src/blockchain.rs
  crates/edr_evm/src/blockchain/forked.rs
  crates/edr_evm/src/blockchain/local.rs
  crates/edr_evm/src/blockchain/remote.rs
  crates/edr_evm/src/blockchain/storage/reservable.rs
  crates/edr_evm/src/blockchain/storage/sparse.rs
  crates/edr_evm/tests/blockchain.rs
  crates/edr_napi/index.d.ts
  crates/edr_napi/src/lib.rs
  crates/edr_napi/src/miner.rs
  crates/edr_napi/src/provider.rs
  crates/edr_napi/src/subscribe.rs
  crates/edr_provider/Cargo.toml
  crates/edr_provider/src/data.rs
  crates/edr_provider/src/error.rs
  crates/edr_provider/src/filter.rs
  crates/edr_provider/src/filter/criteria.rs
  crates/edr_provider/src/lib.rs
  crates/edr_provider/src/pending.rs
  crates/edr_provider/src/requests/eth.rs
  crates/edr_provider/src/requests/eth/blocks.rs
  crates/edr_provider/src/requests/eth/filter.rs
  crates/edr_provider/src/requests/eth/logs.rs
  crates/edr_provider/src/requests/methods.rs
  crates/edr_provider/src/requests/validation.rs
  crates/edr_provider/src/subscribe.rs
  crates/edr_provider/tests/eth_request_serialization.rs
  packages/hardhat-core/src/internal/hardhat-network/provider/provider.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/blockFilters.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/gasPrice.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/getFilterLogs.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/getLogs.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/subscribe.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/unsubscribe.ts
Labels: area:edr

#4753 test: enable and fix unsupported methods tests
  crates/edr_napi/src/provider.rs
  crates/edr_provider/src/lib.rs
  crates/edr_provider/src/requests.rs
  crates/edr_provider/src/requests/serde.rs
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/index.ts
Labels: area:edr

#4751 test: enable already passing integration tests
  packages/hardhat-core/test/internal/hardhat-network/provider/forking-different-hardfork.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/selfdestruct.ts
Labels: area:edr

#4752 test: fix and enable console log tests
  packages/hardhat-core/src/internal/hardhat-network/stack-traces/consoleLogger.ts
  packages/hardhat-core/test/internal/hardhat-network/console-log.ts
Labels: status:triaging, area:edr

#4756 test: fix and enable hardhat network options tests
  crates/edr_provider/src/error.rs
  packages/hardhat-core/src/internal/hardhat-network/provider/provider.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/hardhat-network-options.ts
Labels: area:edr

#4750 Fix project initialization bug
  .changeset/dry-pianos-scream.md
  packages/hardhat-core/src/internal/cli/project-creation.ts
Labels: status:ready

#4755 Remove underflow mention from error messages
  packages/hardhat-chai-matchers/src/internal/reverted/panic.ts
  packages/hardhat-chai-matchers/test/reverted/revertedWithPanic.ts
  packages/hardhat-core/src/internal/hardhat-network/stack-traces/panic-errors.ts
Labels: status:ready, no changeset needed

#4722 Notify of new hardhat versions
  .changeset/beige-ladybugs-confess.md
  docs/redirects.config.js
  packages/hardhat-core/package.json
  packages/hardhat-core/src/internal/cli/cli.ts
  packages/hardhat-core/src/internal/cli/version-notifier.ts
  pnpm-lock.yaml
Labels: status:ready

#4763 feat: add `eth_estimateGas` support
  crates/edr_evm/src/transaction/pending.rs
  crates/edr_provider/src/data.rs
  crates/edr_provider/src/data/call.rs
  crates/edr_provider/src/data/gas.rs
  crates/edr_provider/src/requests/eth/call.rs
  crates/edr_provider/src/requests/eth/gas.rs
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/estimateGas.ts
Labels: area:edr

#4770 feat: add `eth_signTypedData_v4` support
  Cargo.lock
  crates/edr_eth/src/remote/eth.rs
  crates/edr_eth/src/remote/eth/eip712.rs
  crates/edr_provider/Cargo.toml
  crates/edr_provider/src/data.rs
  crates/edr_provider/src/error.rs
  crates/edr_provider/src/lib.rs
  crates/edr_provider/src/requests/eth/sign.rs
  crates/edr_provider/src/requests/methods.rs
  crates/edr_provider/src/requests/serde.rs
  crates/edr_provider/src/test_utils.rs
  crates/edr_provider/tests/eth_request_serialization.rs
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/signTypedData_v4.ts
Labels: area:edr

#4774 test: fix and enable provider error integration tests
  crates/edr_provider/src/error.rs
  packages/hardhat-core/test/internal/core/providers/errors.ts
Labels: area:edr

#4775 fix: change panics to errors in forked blockchain
  crates/edr_evm/src/block.rs
  crates/edr_evm/src/block/remote.rs
  crates/edr_evm/src/blockchain.rs
  crates/edr_evm/src/blockchain/forked.rs
  crates/edr_evm/src/blockchain/remote.rs
Labels: area:edr

#4784 feat: add support for `debug_*` methods
  crates/edr_eth/src/remote/eth.rs
  crates/edr_evm/src/debug_trace.rs
  crates/edr_evm/src/lib.rs
  crates/edr_provider/src/data.rs
  crates/edr_provider/src/error.rs
  crates/edr_provider/src/lib.rs
  crates/edr_provider/src/requests.rs
  crates/edr_provider/src/requests/debug.rs
  crates/edr_provider/src/requests/methods.rs
  packages/hardhat-core/src/internal/hardhat-network/provider/provider.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/utils/convertToEdr.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/debug/traceCall.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/debug/traceTransaction.ts
Labels: area:edr

#4757 refactor: remove EDR_BINARY
  packages/hardhat-core/test/internal/hardhat-network/helpers/providers.ts
  packages/hardhat-core/test/internal/hardhat-network/helpers/spawnEdrProvider.ts
  packages/hardhat-core/test/internal/hardhat-network/helpers/useProvider.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/forked-provider.ts
  packages/hardhat-core/test/setup.ts
Labels: area:edr

#4791 Add support for programmatic verification in Sourcify
  .changeset/twelve-mails-heal.md
  packages/hardhat-verify/src/index.ts
  packages/hardhat-verify/src/internal/tasks/etherscan.ts
  packages/hardhat-verify/src/internal/tasks/sourcify.ts
Labels: status:ready

#4768 added @dgma/hardhat-sol-bundler plugin
  docs/src/content/hardhat-runner/plugins/plugins.ts
Labels: status:triaging, no changeset needed

#4760 Docs: Update to lock chai at version 4
  docs/src/content/hardhat-runner/docs/advanced/create-task.md
  docs/src/content/hardhat-runner/docs/advanced/migrating-from-hardhat-waffle.md
  docs/src/content/hardhat-runner/docs/guides/typescript.md
  docs/src/content/hardhat-runner/docs/other-guides/waffle-testing.md
  docs/src/content/tutorial/creating-a-new-hardhat-project.md
  packages/hardhat-chai-matchers/README.md
Labels: status:triaging, no changeset needed

#4771 Race condition in compiler download when more than one Hardhat process is compiling
  .changeset/lazy-jobs-turn.md
  packages/hardhat-core/src/internal/solidity/compiler/downloader.ts
  packages/hardhat-core/src/internal/util/multi-process-mutex.ts
  packages/hardhat-core/test/internal/multi-process-mutex.ts
Labels: status:ready

#4783 Make sure that solc default import callback is not being used
  packages/hardhat-core/src/builtin-tasks/compile.ts
  packages/hardhat-core/src/internal/solidity/compiler/index.ts
Labels: status:ready, no changeset needed

#4748 Fix broken link
  docs/src/content/hardhat-runner/plugins/plugins.ts
Labels: status:triaging

#4801 Run pre/post scripts for docs
  docs/.npmrc
Labels: no changeset needed

#4800 Use a uniform distribution for the autoassigner
  .github/workflows/autoassign-issues.yml
Labels: status:ready, no changeset needed

#4792 feat: add missing `hardhat_*` JSON-RPC stack trace generation methods to EdrProviderWrapper
  Cargo.lock
  crates/edr_evm/src/trace.rs
  crates/edr_napi/index.d.ts
  crates/edr_napi/index.js
  crates/edr_napi/src/logger.rs
  crates/edr_napi/src/provider.rs
  crates/edr_napi/src/trace.rs
  crates/edr_provider/Cargo.toml
  crates/edr_provider/src/data.rs
  crates/edr_provider/src/data/gas.rs
  crates/edr_provider/src/error.rs
  crates/edr_provider/src/requests/eth/call.rs
  crates/edr_provider/src/requests/eth/transactions.rs
  packages/hardhat-core/src/internal/hardhat-network/provider/provider.ts
  packages/hardhat-core/src/internal/hardhat-network/stack-traces/solidity-errors.ts
  packages/hardhat-core/test/builtin-tasks/node.ts
  packages/hardhat-core/test/builtin-tasks/test.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/integration.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/logs.ts
Labels: area:edr

#4802 Update hardhat-verify: add holesky & arbitrumSepolia, remove arbitrumTestnet & Goerli
  .changeset/modern-clocks-leave.md
  packages/hardhat-verify/src/internal/chain-config.ts
Labels: status:ready

#4715 Accept Typed object in matcher
  .changeset/bright-onions-switch.md
  packages/hardhat-chai-matchers/src/internal/addressable.ts
  packages/hardhat-chai-matchers/src/internal/typed.ts
  packages/hardhat-chai-matchers/test/addressable.ts
Labels: status:triaging

#4805 test: enable remaining Hardhat tests
  crates/edr_napi/index.d.ts
  crates/edr_provider/src/interval.rs
  packages/hardhat-core/src/internal/hardhat-network/provider/provider.ts
  packages/hardhat-core/test/internal/hardhat-network/helpers/providers.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/interval-mining-provider.ts
  packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/websocket.ts
Labels: area:edr

#4806 fix: transport layer RPC errors
  .github/workflows/hardhat-core-ci.yml
  Cargo.lock
  crates/edr_eth/Cargo.toml
  crates/edr_eth/src/receipt.rs
  crates/edr_eth/src/remote.rs
  crates/edr_eth/src/remote/cacheable_method_invocation.rs
  crates/edr_eth/src/remote/chain_id.rs
  crates/edr_eth/src/remote/client.rs
  crates/edr_eth/tests/receipt.rs
  crates/edr_evm/Cargo.toml
  crates/edr_evm/benches/state/util.rs
  crates/edr_evm/src/blockchain/forked.rs
  crates/edr_evm/src/blockchain/remote.rs
  crates/edr_evm/src/state/fork.rs
  crates/edr_evm/src/state/remote.rs
  crates/edr_evm/src/state/remote/cached.rs
  crates/edr_evm/src/state/trie/account.rs
  crates/edr_evm/tests/blockchain.rs
  crates/edr_evm/tests/transaction.rs
  crates/edr_napi/Cargo.toml
  crates/edr_napi/index.d.ts
  crates/edr_napi/src/blockchain.rs
  crates/edr_napi/src/debug_trace.rs
  crates/edr_napi/src/provider.rs
  crates/edr_provider/Cargo.toml
  crates/edr_provider/src/data.rs
  packages/hardhat-core/package.json
  packages/hardhat-core/src/internal/hardhat-network/provider/provider.ts
Labels: area:edr
