Repository NomicFoundation/hardhat, pull requests merged in 2025-02, with the labels that each got.

#6216 Fix regex pattern for bigint parameter validation
  docs/src/content/ignition/docs/guides/deploy.md
Labels: status:triaging

#6199 chore: remove duplicated information from assertion error details
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/multi-test/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/multi-test/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/nested-test/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/nested-test/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/only-test-with-the-flag/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/only-test-with-the-flag/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/only-test-without-the-flag/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/only-test-without-the-flag/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/slow-test/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/slow-test/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/todo-test/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/todo-test/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/top-level-test/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/top-level-test/result.txt
  v-next/hardhat-node-test-reporter/src/error-formatting.ts
  v-next/hardhat-node-test-reporter/test/error-formatting.ts
Labels: status:ready, v-next

#6205 feat: add accounts info printing to the hardhat node task
  v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/edr-provider.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/utils/convert-to-edr.ts
  v-next/hardhat/src/internal/builtin-plugins/node/helpers.ts
  v-next/hardhat/src/internal/builtin-plugins/node/task-action.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/edr/edr-provider.ts
  v-next/hardhat/test/internal/builtin-plugins/node/helpers.ts
Labels: status:ready, v-next

#6224 Fix generation of type files in the typechain plugin
  v-next/hardhat-typechain/src/internal/generate-types.ts
  v-next/hardhat-typechain/test/index.ts
Labels: no changeset needed, v-next

#6213 Clean up and implement the ArtifactManager interface
  v-next/hardhat-errors/src/descriptors.ts
  v-next/hardhat-ethers/src/internal/hardhat-helpers/hardhat-helpers.ts
  v-next/hardhat-ethers/src/internal/initialization.ts
  v-next/hardhat-ethers/test/helpers/artifact-manager-mock.ts
  v-next/hardhat-ethers/test/helpers/helpers.ts
  v-next/hardhat-ethers/test/no-accounts.ts
  v-next/hardhat-ethers/test/plugin-functionalities.ts
  v-next/hardhat-viem/src/internal/contracts.ts
  v-next/hardhat-viem/src/internal/initialization.ts
  v-next/hardhat/src/index.ts
  v-next/hardhat/src/internal/builtin-plugins/artifacts/artifact-manager.ts
  v-next/hardhat/src/internal/builtin-plugins/artifacts/artifacts-manager.ts
  v-next/hardhat/src/internal/builtin-plugins/artifacts/hook-handlers/hre.ts
  v-next/hardhat/src/internal/builtin-plugins/artifacts/type-extensions.ts
  v-next/hardhat/src/internal/core/hre.ts
  v-next/hardhat/src/types/artifacts.ts
  v-next/hardhat/test/test-helpers/create-mock-hardhat-runtime-environment.ts
  v-next/hardhat/test/test-helpers/mock-artifact-manager.ts
Labels: status:ready

#6225 feat: hook up global exception handler in Hardhat 3
  v-next/hardhat/src/internal/cli/main.ts
  v-next/hardhat/src/internal/cli/telemetry/sentry/reporter.ts
Labels: status:ready, v-next

#6219 ignition: port ignition UI
  pnpm-lock.yaml
  scripts/check-v-next-npm-scripts.js
  temp-ignition/hardhat-ignition-ui/.eslintrc.cjs
  temp-ignition/hardhat-ignition-ui/.mocharc.json
  temp-ignition/hardhat-ignition-ui/package.json
  v-next/hardhat-ignition-ui/.eslintrc.cjs
  v-next/hardhat-ignition-ui/.gitignore
  v-next/hardhat-ignition-ui/.mocharc.json
  v-next/hardhat-ignition-ui/.npmignore
  v-next/hardhat-ignition-ui/.nycrc
  v-next/hardhat-ignition-ui/.prettierignore
  v-next/hardhat-ignition-ui/CHANGELOG.md
  v-next/hardhat-ignition-ui/README.md
  v-next/hardhat-ignition-ui/examples/ComplexModule.js
  v-next/hardhat-ignition-ui/index.html
  v-next/hardhat-ignition-ui/package.json
  v-next/hardhat-ignition-ui/public/.gitkeep
  v-next/hardhat-ignition-ui/scripts/generate-example-deployment-json.js
  v-next/hardhat-ignition-ui/src/assets/ExternalLinkIcon.tsx
  v-next/hardhat-ignition-ui/src/assets/TooltipIcon.tsx
  v-next/hardhat-ignition-ui/src/assets/purple-rocket.png
  v-next/hardhat-ignition-ui/src/components/mermaid.tsx
  v-next/hardhat-ignition-ui/src/components/socials/dc-logo.tsx
  v-next/hardhat-ignition-ui/src/components/socials/gh-logo.tsx
  v-next/hardhat-ignition-ui/src/components/socials/index.tsx
  v-next/hardhat-ignition-ui/src/components/socials/tw-logo.tsx
  v-next/hardhat-ignition-ui/src/main.css
  v-next/hardhat-ignition-ui/src/main.tsx
  v-next/hardhat-ignition-ui/src/pages/visualization-overview/components/deployment-flow.tsx
  v-next/hardhat-ignition-ui/src/pages/visualization-overview/components/execution-batches.tsx
  v-next/hardhat-ignition-ui/src/pages/visualization-overview/components/future-batch.tsx
  v-next/hardhat-ignition-ui/src/pages/visualization-overview/components/future-header.tsx
  v-next/hardhat-ignition-ui/src/pages/visualization-overview/components/summary.tsx
  v-next/hardhat-ignition-ui/src/pages/visualization-overview/visualization-overview.tsx
  v-next/hardhat-ignition-ui/src/queries/futures.ts
  v-next/hardhat-ignition-ui/src/utils/argumentTypeToString.tsx
  v-next/hardhat-ignition-ui/src/utils/to-escaped-id.ts
  v-next/hardhat-ignition-ui/src/utils/to-mermaid.ts
  v-next/hardhat-ignition-ui/src/vite-env.d.ts
  v-next/hardhat-ignition-ui/test/to-mermaid.ts
  v-next/hardhat-ignition-ui/tsconfig.json
  v-next/hardhat-ignition-ui/tsconfig.node.json
  v-next/hardhat-ignition-ui/vite.config.ts
Labels: status:ready, no changeset needed, v-next

#6129 feat: implement the solidity compilation cache
  v-next/hardhat-utils/src/crypto.ts
  v-next/hardhat-utils/src/fs.ts
  v-next/hardhat-utils/test/crypto.ts
  v-next/hardhat-utils/test/fs.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/artifacts.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/build-system.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/cache.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/compilation-job.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/resolved-file.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/resolver/dependency-resolver.ts
  v-next/hardhat/src/types/solidity/build-system.ts
  v-next/hardhat/src/types/solidity/compilation-job.ts
  v-next/hardhat/src/types/solidity/resolved-file.ts
  v-next/hardhat/test/fixture-projects/solidity/example-project/.gitignore
  v-next/hardhat/test/fixture-projects/solidity/example-project/artifacts/artifacts.d.ts
  v-next/hardhat/test/fixture-projects/solidity/example-project/artifacts/build-info/217a3c654dd9a8cdd3a7470ec31c8ccd.json
  v-next/hardhat/test/fixture-projects/solidity/example-project/artifacts/build-info/217a3c654dd9a8cdd3a7470ec31c8ccd.output.json
  v-next/hardhat/test/fixture-projects/solidity/example-project/artifacts/build-info/652e717a54777ac28e86bc7084fcbc8f.json
  v-next/hardhat/test/fixture-projects/solidity/example-project/artifacts/build-info/652e717a54777ac28e86bc7084fcbc8f.output.json
  v-next/hardhat/test/fixture-projects/solidity/example-project/artifacts/contracts/A.sol/A.json
  v-next/hardhat/test/fixture-projects/solidity/example-project/artifacts/contracts/A.sol/artifacts.d.ts
  v-next/hardhat/test/fixture-projects/solidity/example-project/artifacts/contracts/B.sol/B.json
  v-next/hardhat/test/fixture-projects/solidity/example-project/artifacts/contracts/B.sol/artifacts.d.ts
  v-next/hardhat/test/fixture-projects/solidity/example-project/artifacts/contracts/C.sol/C.json
  v-next/hardhat/test/fixture-projects/solidity/example-project/artifacts/contracts/C.sol/C2.json
  v-next/hardhat/test/fixture-projects/solidity/example-project/artifacts/contracts/C.sol/artifacts.d.ts
  v-next/hardhat/test/fixture-projects/solidity/example-project/artifacts/contracts/D.sol/artifacts.d.ts
  v-next/hardhat/test/fixture-projects/solidity/example-project/artifacts/contracts/E.sol/artifacts.d.ts
  v-next/hardhat/test/fixture-projects/solidity/example-project/artifacts/contracts/NoImports.sol/NoImports.json
  v-next/hardhat/test/fixture-projects/solidity/example-project/artifacts/contracts/NoImports.sol/artifacts.d.ts
  v-next/hardhat/test/fixture-projects/solidity/example-project/artifacts/contracts/UserRemappedImport.sol/artifacts.d.ts
  v-next/hardhat/test/internal/builtin-plugins/solidity/build-system/build-system.ts
  v-next/hardhat/test/internal/builtin-plugins/solidity/build-system/cache.ts
  v-next/hardhat/test/internal/builtin-plugins/solidity/build-system/compilation-job.ts
  v-next/hardhat/test/internal/builtin-plugins/solidity/build-system/dependency-graph.ts
  v-next/hardhat/test/internal/builtin-plugins/solidity/build-system/root-paths-utils.ts
  v-next/hardhat/test/internal/builtin-plugins/solidity/build-system/solc-config-selection.ts
Labels: status:ready, v-next

#6235 feat: integrate stack traces into solidity test
  pnpm-lock.yaml
  v-next/example-project/contracts/Counter.t.sol
  v-next/hardhat/package.json
  v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/stack-traces/stack-trace-solidity-errors.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity-test/config.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity-test/reporter.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity-test/runner.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity-test/task-action.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity-test/type-extensions.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/build-results.ts
Labels: status:ready

#6238 Don't parse build infos
  v-next/hardhat/src/internal/builtin-plugins/solidity-test/task-action.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/build-results.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/artifacts.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/build-system.ts
  v-next/hardhat/src/types/solidity/build-system.ts
Labels: status:ready

#6250 feat: send EDR panics to sentry
  v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/edr-provider.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/http-provider.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/provider-errors.ts
  v-next/hardhat/src/internal/cli/telemetry/sentry/reporter.ts
Labels: status:ready

#6252 chore: release hardhat3 from v-next to @ignored
  .changeset/itchy-elephants-fetch.md
  .changeset/pre.json
  pnpm-lock.yaml
  v-next/example-project/package.json
  v-next/hardhat-chai-matchers/package.json
  v-next/hardhat-errors/package.json
  v-next/hardhat-ethers/package.json
  v-next/hardhat-keystore/package.json
  v-next/hardhat-mocha-test-runner/package.json
  v-next/hardhat-network-helpers/package.json
  v-next/hardhat-node-test-reporter/package.json
  v-next/hardhat-node-test-runner/package.json
  v-next/hardhat-typechain/package.json
  v-next/hardhat-utils/package.json
  v-next/hardhat-viem/package.json
  v-next/hardhat-zod-utils/package.json
  v-next/hardhat/package.json
  v-next/hardhat/templates/mocha-ethers/package.json
  v-next/hardhat/templates/node-test-runner-viem/package.json
  v-next/template-package/package.json
Labels: status:ready

#6253 Fix node version check
  v-next/hardhat/src/internal/cli/node-version.ts
  v-next/hardhat/test/internal/cli/node-version.ts
Labels: status:triaging

#6261 feat: bump `@ignored/edr` to 0.8.0-alpha.2
  .changeset/loud-hornets-approve.md
  pnpm-lock.yaml
  v-next/hardhat/package.json
Labels: status:ready

#6259 fix: display all unused diagnostics at the end of the test report
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/asynchronous-activity-test/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/asynchronous-activity-test/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/asynchronous-activity-test/test.ts
  v-next/hardhat-node-test-reporter/integration-tests/index.ts
  v-next/hardhat-node-test-reporter/src/formatting.ts
Labels: status:ready, v-next

#6257 build: upgrade to edr-optimism v0.6.5-alpha.3
  pnpm-lock.yaml
  v-next/hardhat/package.json
  v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/edr-provider.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/network-manager.ts
Labels: status:ready, v-next

#6266 Viem improvements
  v-next/hardhat-viem/src/internal/chains.ts
  v-next/hardhat-viem/src/types.ts
  v-next/hardhat-viem/test/fixture-projects/.gitignore
Labels: status:ready, v-next

#6267 Sort template projects
  pnpm-lock.yaml
  v-next/hardhat/src/internal/cli/init/template.ts
  v-next/hardhat/templates/01-node-test-runner-viem/.gitignore
  v-next/hardhat/templates/01-node-test-runner-viem/README.md
  v-next/hardhat/templates/01-node-test-runner-viem/contracts/Counter.sol
  v-next/hardhat/templates/01-node-test-runner-viem/contracts/Counter.t.sol
  v-next/hardhat/templates/01-node-test-runner-viem/contracts/Lock.sol
  v-next/hardhat/templates/01-node-test-runner-viem/contracts/TestWithForgeStd.t.sol
  v-next/hardhat/templates/01-node-test-runner-viem/gitignore
  v-next/hardhat/templates/01-node-test-runner-viem/hardhat.config.ts
  v-next/hardhat/templates/01-node-test-runner-viem/package.json
  v-next/hardhat/templates/01-node-test-runner-viem/scripts/send-op-tx.ts
  v-next/hardhat/templates/01-node-test-runner-viem/test/Lock.ts
  v-next/hardhat/templates/01-node-test-runner-viem/tsconfig.json
  v-next/hardhat/templates/02-mocha-ethers/.gitignore
  v-next/hardhat/templates/02-mocha-ethers/README.md
  v-next/hardhat/templates/02-mocha-ethers/contracts/Counter.sol
  v-next/hardhat/templates/02-mocha-ethers/contracts/Counter.t.sol
  v-next/hardhat/templates/02-mocha-ethers/contracts/Lock.sol
  v-next/hardhat/templates/02-mocha-ethers/contracts/TestWithForgeStd.t.sol
  v-next/hardhat/templates/02-mocha-ethers/gitignore
  v-next/hardhat/templates/02-mocha-ethers/hardhat.config.ts
  v-next/hardhat/templates/02-mocha-ethers/package.json
  v-next/hardhat/templates/02-mocha-ethers/scripts/send-op-tx.ts
  v-next/hardhat/templates/02-mocha-ethers/test/Lock.ts
  v-next/hardhat/templates/02-mocha-ethers/test/setup.ts
  v-next/hardhat/templates/02-mocha-ethers/tsconfig.json
Labels: status:ready

#6269 Rename the `hardhat3` cli to `hardhat`
  v-next/example-project/package.json
  v-next/hardhat/package.json
  v-next/hardhat/templates/01-node-test-runner-viem/README.md
  v-next/hardhat/templates/02-mocha-ethers/README.md
Labels: status:ready

#6251 chore: update sentry and google analytics configuration
  v-next/hardhat/src/internal/cli/telemetry/analytics/subprocess.ts
  v-next/hardhat/src/internal/cli/telemetry/sentry/reporter.ts
Labels: status:ready, v-next

#6263 feat: turn package into esm on init
  v-next/hardhat/src/internal/cli/init/init.ts
  v-next/hardhat/src/internal/cli/init/prompt.ts
  v-next/hardhat/test/internal/cli/init/init.ts
Labels: status:ready, v-next

#6232 Encrypted keystore
  pnpm-lock.yaml
  v-next/hardhat-errors/src/descriptors.ts
  v-next/hardhat-keystore/package.json
  v-next/hardhat-keystore/src/internal/hook-handlers/configuration-variables.ts
  v-next/hardhat-keystore/src/internal/keystores/encryption.ts
  v-next/hardhat-keystore/src/internal/keystores/keystore.ts
  v-next/hardhat-keystore/src/internal/keystores/password.ts
  v-next/hardhat-keystore/src/internal/keystores/unencrypted-keystore.ts
  v-next/hardhat-keystore/src/internal/loaders/file-manager.ts
  v-next/hardhat-keystore/src/internal/loaders/keystore-file-loader.ts
  v-next/hardhat-keystore/src/internal/tasks/delete.ts
  v-next/hardhat-keystore/src/internal/tasks/get.ts
  v-next/hardhat-keystore/src/internal/tasks/list.ts
  v-next/hardhat-keystore/src/internal/tasks/set.ts
  v-next/hardhat-keystore/src/internal/types-validation.ts
  v-next/hardhat-keystore/src/internal/types.ts
  v-next/hardhat-keystore/src/internal/ui/request-secret-input.ts
  v-next/hardhat-keystore/src/internal/ui/user-display-messages.ts
  v-next/hardhat-keystore/test/fixture-projects/keystore/.gitignore
  v-next/hardhat-keystore/test/fixture-projects/keystore/existing-keystore.json
  v-next/hardhat-keystore/test/fixture-projects/unencrypted-keystore/existing-keystore.json
  v-next/hardhat-keystore/test/helpers/insert-password-hook.ts
  v-next/hardhat-keystore/test/helpers/mock-file-manager.ts
  v-next/hardhat-keystore/test/helpers/mock-request-secret.ts
  v-next/hardhat-keystore/test/helpers/test-password.ts
  v-next/hardhat-keystore/test/hook-handlers/configuration-variables.ts
  v-next/hardhat-keystore/test/integration/tasks.ts
  v-next/hardhat-keystore/test/integration/turn-off-keystore-in-ci.ts
  v-next/hardhat-keystore/test/keystores/encryption.ts
  v-next/hardhat-keystore/test/keystores/keystore.ts
  v-next/hardhat-keystore/test/keystores/unencrypted-keystore.ts
  v-next/hardhat-keystore/test/loaders/keystore-file-loader.ts
  v-next/hardhat-keystore/test/tasks/delete.ts
  v-next/hardhat-keystore/test/tasks/get.ts
  v-next/hardhat-keystore/test/tasks/set.ts
  v-next/hardhat-test-utils/src/errors.ts
Labels: no changeset needed, v-next

#6271 Update template projects
  pnpm-lock.yaml
  v-next/hardhat/templates/02-mocha-ethers/hardhat.config.ts
  v-next/hardhat/templates/02-mocha-ethers/package.json
  v-next/hardhat/templates/02-mocha-ethers/test/Lock.ts
  v-next/hardhat/templates/02-mocha-ethers/test/setup.ts
Labels: status:triaging, v-next

#5803 feat: update hardhat ascii art
  v-next/hardhat/src/internal/cli/init/init.ts
Labels: status:ready, v-next

#6277 chore: release everything from v-next to @ignored
  .changeset/clever-months-pump.md
  .changeset/pre.json
  pnpm-lock.yaml
  v-next/example-project/package.json
  v-next/hardhat-chai-matchers/package.json
  v-next/hardhat-errors/package.json
  v-next/hardhat-ethers/package.json
  v-next/hardhat-ignition-core/package.json
  v-next/hardhat-ignition-ui/package.json
  v-next/hardhat-keystore/package.json
  v-next/hardhat-mocha-test-runner/package.json
  v-next/hardhat-network-helpers/package.json
  v-next/hardhat-node-test-reporter/package.json
  v-next/hardhat-node-test-runner/package.json
  v-next/hardhat-typechain/package.json
  v-next/hardhat-utils/package.json
  v-next/hardhat-viem/package.json
  v-next/hardhat-zod-utils/package.json
  v-next/hardhat/package.json
  v-next/hardhat/templates/01-node-test-runner-viem/package.json
  v-next/hardhat/templates/02-mocha-ethers/package.json
  v-next/template-package/package.json
Labels: status:ready

#6279 Update the logo that's printed on `--init`
  v-next/hardhat/src/internal/cli/init/init.ts
Labels: status:ready

#6278 Two small improvements
  v-next/hardhat/src/internal/builtin-plugins/flatten/index.ts
  v-next/hardhat/src/internal/cli/init/prompt.ts
  v-next/hardhat/test/internal/cli/main.ts
Labels: status:ready

#6240 Add hardhat-task-gen plugin
  docs/src/content/hardhat-runner/plugins/plugins.ts
Labels: status:ready, no changeset needed

#6294 add ignition to the viem template
  pnpm-lock.yaml
  v-next/hardhat/templates/01-node-test-runner-viem/contracts/Rocket.sol
  v-next/hardhat/templates/01-node-test-runner-viem/hardhat.config.ts
  v-next/hardhat/templates/01-node-test-runner-viem/ignition/modules/Apollo.ts
  v-next/hardhat/templates/01-node-test-runner-viem/package.json
  v-next/hardhat/templates/01-node-test-runner-viem/scripts/deploy-rocket-from-script.ts
Labels: status:ready, v-next

#6296 Create hardhat-3-alpha.yml
  .github/ISSUE_TEMPLATE/hardhat-3-alpha.yml
Labels: no changeset needed

#6297 Update hardhat-3-alpha.yml
  .github/ISSUE_TEMPLATE/hardhat-3-alpha.yml
Labels: status:ready, no changeset needed

#6298 Update hardhat-3-alpha.yml
  .github/ISSUE_TEMPLATE/hardhat-3-alpha.yml
Labels: status:ready, no changeset needed

#6300 Update hardhat-3-alpha.yml
  .github/ISSUE_TEMPLATE/hardhat-3-alpha.yml
Labels: status:ready, no changeset needed

#6306 test: fix the update after kill test
  v-next/hardhat-ignition/test/deploy/rerun/rerun-after-kill.ts
Labels: status:ready, v-next

#6305 fix: make the root paths in solidity test unique
  v-next/hardhat/src/internal/builtin-plugins/solidity-test/task-action.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/dependency-graph.ts
  v-next/hardhat/test/internal/builtin-plugins/solidity/build-system/dependency-graph.ts
Labels: status:ready

#6304 ci: remove unused codepath in v-next ci
  .github/workflows/v-next-ci.yml
Labels: status:ready

#6307 fix: correct the Ignition module import in the ethers template script
  v-next/hardhat/templates/02-mocha-ethers/scripts/deploy-rocket-from-script.ts
Labels: status:ready, v-next

#6308 chore: switch the website banner back from survey to hiring
  .github/ISSUE_TEMPLATE/hardhat-3-alpha.yml
  docs/src/config.ts
Labels: status:ready, no changeset needed

#6303 Use proper quotes in error messages
  v-next/hardhat-errors/src/descriptors.ts
  v-next/hardhat-ignition/test/module-parameters.ts
  v-next/hardhat-ignition/test/utils/bigintReviver.ts
  v-next/hardhat-ignition/test/utils/load-module.ts
Labels: status:ready

#6312 [Typechain] getContractAt override is not working
  v-next/example-project/test/node/example-test.ts
  v-next/hardhat-ethers/src/types.ts
Labels: no changeset needed, v-next

#6332 fix: correctly identify test suites
  v-next/hardhat/src/internal/builtin-plugins/solidity-test/helpers.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity-test/task-action.ts
Labels: status:ready

#6334 chore: deduplicate build ids before getting build infos
  v-next/hardhat/src/internal/builtin-plugins/solidity/build-results.ts
Labels: status:ready

#6337 Hardhat v3 alpha release
  .changeset/every-regions-try.md
  .changeset/pre.json
  pnpm-lock.yaml
  v-next/example-project/package.json
  v-next/hardhat-errors/package.json
  v-next/hardhat-ethers-chai-matchers/package.json
  v-next/hardhat-ethers/package.json
  v-next/hardhat-ignition-core/package.json
  v-next/hardhat-ignition-ethers/package.json
  v-next/hardhat-ignition-ui/package.json
  v-next/hardhat-ignition-viem/package.json
  v-next/hardhat-ignition/package.json
  v-next/hardhat-keystore/package.json
  v-next/hardhat-mocha-test-runner/package.json
  v-next/hardhat-network-helpers/package.json
  v-next/hardhat-node-test-reporter/package.json
  v-next/hardhat-node-test-runner/package.json
  v-next/hardhat-typechain/package.json
  v-next/hardhat-utils/package.json
  v-next/hardhat-viem/package.json
  v-next/hardhat-zod-utils/package.json
  v-next/hardhat/package.json
  v-next/hardhat/templates/01-node-test-runner-viem/package.json
  v-next/hardhat/templates/02-mocha-ethers/package.json
  v-next/template-package/package.json
Labels: status:ready

#6326 fix: prompt to turn the project into esm
  v-next/hardhat/src/internal/cli/init/init.ts
Labels: status:ready

#6325 Change the ESM init message wording
  v-next/hardhat/src/internal/cli/init/prompt.ts
Labels: status:ready

#6338 chore: remove duplicate package.json from the esm prompt
  v-next/hardhat/src/internal/cli/init/prompt.ts
Labels: status:ready

#6318 Sync templates with tutorial
  v-next/hardhat/templates/01-node-test-runner-viem/README.md
  v-next/hardhat/templates/01-node-test-runner-viem/contracts/Counter.sol
  v-next/hardhat/templates/01-node-test-runner-viem/contracts/Counter.t.sol
  v-next/hardhat/templates/01-node-test-runner-viem/contracts/Lock.sol
  v-next/hardhat/templates/01-node-test-runner-viem/contracts/Rocket.sol
  v-next/hardhat/templates/01-node-test-runner-viem/contracts/TestWithForgeStd.t.sol
  v-next/hardhat/templates/01-node-test-runner-viem/hardhat.config.ts
  v-next/hardhat/templates/01-node-test-runner-viem/ignition/modules/Apollo.ts
  v-next/hardhat/templates/01-node-test-runner-viem/ignition/modules/Counter.ts
  v-next/hardhat/templates/01-node-test-runner-viem/scripts/check-predeploy.ts
  v-next/hardhat/templates/01-node-test-runner-viem/scripts/deploy-rocket-from-script.ts
  v-next/hardhat/templates/01-node-test-runner-viem/scripts/send-op-tx.ts
  v-next/hardhat/templates/01-node-test-runner-viem/test/Counter.ts
  v-next/hardhat/templates/01-node-test-runner-viem/test/Lock.ts
  v-next/hardhat/templates/02-mocha-ethers/README.md
  v-next/hardhat/templates/02-mocha-ethers/contracts/Counter.sol
  v-next/hardhat/templates/02-mocha-ethers/contracts/Counter.t.sol
  v-next/hardhat/templates/02-mocha-ethers/contracts/Lock.sol
  v-next/hardhat/templates/02-mocha-ethers/contracts/Rocket.sol
  v-next/hardhat/templates/02-mocha-ethers/contracts/TestWithForgeStd.t.sol
  v-next/hardhat/templates/02-mocha-ethers/hardhat.config.ts
  v-next/hardhat/templates/02-mocha-ethers/ignition/modules/Apollo.ts
  v-next/hardhat/templates/02-mocha-ethers/ignition/modules/Counter.ts
  v-next/hardhat/templates/02-mocha-ethers/scripts/check-predeploy.ts
  v-next/hardhat/templates/02-mocha-ethers/scripts/deploy-rocket-from-script.ts
  v-next/hardhat/templates/02-mocha-ethers/scripts/send-op-tx.ts
  v-next/hardhat/templates/02-mocha-ethers/test/Counter.ts
  v-next/hardhat/templates/02-mocha-ethers/test/Lock.ts
Labels: status:ready

#6340 Update tsx
  pnpm-lock.yaml
  v-next/hardhat-errors/package.json
  v-next/hardhat-ethers-chai-matchers/package.json
  v-next/hardhat-ethers/package.json
  v-next/hardhat-keystore/package.json
  v-next/hardhat-mocha-test-runner/package.json
  v-next/hardhat-network-helpers/package.json
  v-next/hardhat-node-test-reporter/package.json
  v-next/hardhat-node-test-runner/package.json
  v-next/hardhat-test-utils/package.json
  v-next/hardhat-typechain/package.json
  v-next/hardhat-utils/package.json
  v-next/hardhat-viem/package.json
  v-next/hardhat-zod-utils/package.json
  v-next/hardhat/package.json
  v-next/template-package/package.json
Labels: status:ready

#6343 Hardhat v3 alpha release
  .changeset/many-hats-shave.md
  .changeset/pre.json
  pnpm-lock.yaml
  v-next/example-project/package.json
  v-next/hardhat-errors/package.json
  v-next/hardhat-ethers-chai-matchers/package.json
  v-next/hardhat-ethers/package.json
  v-next/hardhat-ignition-core/package.json
  v-next/hardhat-ignition-ethers/package.json
  v-next/hardhat-ignition-ui/package.json
  v-next/hardhat-ignition-viem/package.json
  v-next/hardhat-ignition/package.json
  v-next/hardhat-keystore/package.json
  v-next/hardhat-mocha-test-runner/package.json
  v-next/hardhat-network-helpers/package.json
  v-next/hardhat-node-test-reporter/package.json
  v-next/hardhat-node-test-runner/package.json
  v-next/hardhat-test-utils/package.json
  v-next/hardhat-typechain/package.json
  v-next/hardhat-utils/package.json
  v-next/hardhat-viem/package.json
  v-next/hardhat-zod-utils/package.json
  v-next/hardhat/package.json
  v-next/hardhat/templates/01-node-test-runner-viem/package.json
  v-next/hardhat/templates/02-mocha-ethers/package.json
  v-next/template-package/package.json
Labels: status:ready

#6342 Clean up error descriptors
  v-next/hardhat-errors/src/descriptors.ts
Labels: status:ready

#6346 fix: explicitly enable forking when configuring it via override
  v-next/hardhat/src/internal/builtin-plugins/node/task-action.ts
Labels: status:ready

#6345 Update privacy policy
  docs/public/static/privacy-policy.html
Labels: status:ready, no changeset needed

#6348 Improve stub tasks
  v-next/hardhat/src/internal/builtin-plugins/coverage/index.ts
  v-next/hardhat/src/internal/builtin-plugins/coverage/task-action.ts
  v-next/hardhat/src/internal/builtin-plugins/verify/index.ts
  v-next/hardhat/src/internal/builtin-plugins/verify/task-action.ts
Labels: status:ready

#6349 feat: update not implemented message on ignition verify tasks
  v-next/hardhat-ignition/src/internal/tasks/deploy.ts
  v-next/hardhat-ignition/src/internal/tasks/verify.ts
Labels: status:ready

#6351 Disable secrets in the console task
  v-next/hardhat/src/internal/builtin-plugins/console/task-action.ts
Labels: status:ready

#6335 Init projects with pnpm when invoking hardhat from pnpx
  v-next/hardhat/src/internal/cli/init/package-manager.ts
  v-next/hardhat/test/internal/cli/init/package-manager.ts
Labels: status:triaging

#6354 chore: set visualize as not implemented
  v-next/hardhat-ignition/src/index.ts
  v-next/hardhat-ignition/src/internal/tasks/visualize.ts
  v-next/hardhat-ignition/test/plan/index.ts
Labels: status:ready

#6356 fix: return only origin in sanitizeUrl to prevent leaks
  v-next/hardhat-utils/src/internal/request.ts
  v-next/hardhat-utils/test/request.ts
Labels: status:ready, v-next

#6357 [Keystore] Improve test: ask for multiple config variables in parallel
  v-next/hardhat-keystore/test/hook-handlers/configuration-variables.ts
Labels: v-next

#6360 Hardhat v3 alpha release
  .changeset/pre.json
  .changeset/slow-radios-happen.md
  pnpm-lock.yaml
  v-next/example-project/package.json
  v-next/hardhat-errors/package.json
  v-next/hardhat-ethers-chai-matchers/package.json
  v-next/hardhat-ethers/package.json
  v-next/hardhat-ignition-core/package.json
  v-next/hardhat-ignition-ethers/package.json
  v-next/hardhat-ignition-ui/package.json
  v-next/hardhat-ignition-viem/package.json
  v-next/hardhat-ignition/package.json
  v-next/hardhat-keystore/package.json
  v-next/hardhat-mocha-test-runner/package.json
  v-next/hardhat-network-helpers/package.json
  v-next/hardhat-node-test-reporter/package.json
  v-next/hardhat-node-test-runner/package.json
  v-next/hardhat-test-utils/package.json
  v-next/hardhat-typechain/package.json
  v-next/hardhat-utils/package.json
  v-next/hardhat-viem/package.json
  v-next/hardhat-zod-utils/package.json
  v-next/hardhat/package.json
  v-next/hardhat/templates/01-node-test-runner-viem/package.json
  v-next/hardhat/templates/02-mocha-ethers/package.json
  v-next/template-package/package.json
Labels: status:ready

#6365 Fix template script
  v-next/hardhat/templates/01-node-test-runner-viem/scripts/check-predeploy.ts
  v-next/hardhat/templates/02-mocha-ethers/scripts/check-predeploy.ts
Labels: status:ready

#6374 chore: rename the package to `@nomicfoundation/hardhat-mocha`
  .changeset/pre.json
  pnpm-lock.yaml
  v-next/example-project/hardhat.config.ts
  v-next/example-project/package.json
  v-next/example-project/tsconfig.json
  v-next/hardhat-ethers-chai-matchers/package.json
  v-next/hardhat-ethers-chai-matchers/test/fixture-projects/hook-initialization/hardhat.config.ts
  v-next/hardhat-ethers-chai-matchers/test/fixture-projects/hook-initialization/package.json
  v-next/hardhat-ethers-chai-matchers/tsconfig.json
  v-next/hardhat-mocha/.eslintrc.cjs
  v-next/hardhat-mocha/.gitignore
  v-next/hardhat-mocha/.prettierignore
  v-next/hardhat-mocha/LICENSE
  v-next/hardhat-mocha/README.md
  v-next/hardhat-mocha/artifacts/artifacts.d.ts
  v-next/hardhat-mocha/package.json
  v-next/hardhat-mocha/src/hookHandlers/config.ts
  v-next/hardhat-mocha/src/index.ts
  v-next/hardhat-mocha/src/task-action.ts
  v-next/hardhat-mocha/src/type-extensions.ts
  v-next/hardhat-mocha/test/fixture-projects/invalid-mocha-config/hardhat.config.ts
  v-next/hardhat-mocha/test/fixture-projects/invalid-mocha-config/test/test.ts
  v-next/hardhat-mocha/test/fixture-projects/test-project/hardhat.config.ts
  v-next/hardhat-mocha/test/fixture-projects/test-project/test/test.ts
  v-next/hardhat-mocha/test/index.ts
  v-next/hardhat-mocha/tsconfig.json
  v-next/hardhat/templates/02-mocha-ethers/hardhat.config.ts
  v-next/hardhat/templates/02-mocha-ethers/package.json
Labels: status:ready

#6379 Use the latest hardfork by default
  v-next/hardhat/src/internal/builtin-plugins/network-manager/config-resolution.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/config-resolution.ts
Labels: status:ready

#6380 Wording fix
  v-next/hardhat/src/internal/cli/init/prompt.ts
  v-next/hardhat/templates/01-node-test-runner-viem/package.json
  v-next/hardhat/templates/02-mocha-ethers/package.json
Labels: status:ready

#6373 Hardhat 3 Alpha docs
  docs/redirects.config.js
  docs/src/content/hardhat3-alpha/_dirinfo.yaml
  docs/src/content/hardhat3-alpha/index.md
  docs/src/content/hardhat3-alpha/learn-more/_dirinfo.yaml
  docs/src/content/hardhat3-alpha/learn-more/alpha-limitations.md
  docs/src/content/hardhat3-alpha/learn-more/comparison.md
  docs/src/content/hardhat3-alpha/learn-more/solidity-tests.md
  docs/src/content/layouts.yaml
  docs/temp/tabsConfig.json
Labels: status:ready, no changeset needed

#6382 Small fix in the hh3 alpha tutorial
  docs/src/content/hardhat3-alpha/index.md
Labels: no changeset needed

#6384 Remove Ignition internal errors
  v-next/hardhat-ignition/src/internal/tasks/deploy.ts
  v-next/hardhat-ignition/src/internal/tasks/deployments.ts
  v-next/hardhat-ignition/src/internal/tasks/status.ts
  v-next/hardhat-ignition/src/internal/tasks/transactions.ts
  v-next/hardhat-ignition/src/internal/tasks/wipe.ts
  v-next/hardhat-ignition/src/internal/utils/load-module.ts
  v-next/hardhat-ignition/test/deploy/default-sender.ts
  v-next/hardhat-ignition/test/strategies/create2.ts
Labels: status:ready

#6385 Fix variable name in template project
  v-next/hardhat/templates/01-node-test-runner-viem/test/Counter.ts
Labels: status:ready

#6383 Comparison with HH2 draft
  docs/src/content/hardhat3-alpha/index.md
  docs/src/content/hardhat3-alpha/learn-more/alpha-limitations.md
  docs/src/content/hardhat3-alpha/learn-more/comparison.md
Labels: status:ready, no changeset needed

#6378 [WIP] update versions to prerelease 3
  .changeset/pre.json
  .changeset/strong-mugs-change.md
  pnpm-lock.yaml
  v-next/example-project/package.json
  v-next/hardhat-errors/package.json
  v-next/hardhat-ethers-chai-matchers/package.json
  v-next/hardhat-ethers/package.json
  v-next/hardhat-ignition-core/package.json
  v-next/hardhat-ignition-ethers/package.json
  v-next/hardhat-ignition-ui/package.json
  v-next/hardhat-ignition-viem/package.json
  v-next/hardhat-ignition/package.json
  v-next/hardhat-keystore/package.json
  v-next/hardhat-mocha/package.json
  v-next/hardhat-network-helpers/package.json
  v-next/hardhat-node-test-reporter/package.json
  v-next/hardhat-node-test-runner/package.json
  v-next/hardhat-test-utils/package.json
  v-next/hardhat-typechain/package.json
  v-next/hardhat-utils/package.json
  v-next/hardhat-viem/package.json
  v-next/hardhat-zod-utils/package.json
  v-next/hardhat/package.json
  v-next/hardhat/templates/01-node-test-runner-viem/package.json
  v-next/hardhat/templates/02-mocha-ethers/package.json
  v-next/template-package/package.json
Labels: status:ready

#6387 Comparison doc fixes
  docs/src/content/hardhat3-alpha/learn-more/comparison.md
Labels: status:ready, no changeset needed

#6228 fix: use unexistent exportation from upgrade module
  docs/src/content/ignition/docs/guides/upgradeable-proxies.md
Labels: status:triaging, no changeset needed

#6389 Update mermaid version (v2)
  package.json
  packages/hardhat-ignition-ui/package.json
  pnpm-lock.yaml
Labels: no changeset needed

#6408 Add opRetro project id to funding.json
  FUNDING.json
Labels: status:ready, no changeset needed

#6230 fix: 404 links
  packages/hardhat-core/src/internal/core/config/default-config.ts
  packages/hardhat-web3-v4/README.md
Labels: status:triaging, no changeset needed

#6428 chore: disable the v-next changeset release
  .github/workflows/v-next-changesets-release.yml
Labels: status:ready, no changeset needed
