Repository NomicFoundation/hardhat, pull requests merged in 2025-03, with the labels that each got.

#6434 ci: run the changeset check in the merge queue
  .github/workflows/check-changeset-added.yml
Labels: status:ready, no changeset needed

#6433 chore: remove commented out CI jobs
  .github/workflows/e2e-tests.yml
  .github/workflows/pre-release.yml
  .github/workflows/v-next-changesets-release.yml
Labels: status:ready, no changeset needed

#6416 chore: move shouldMergeCompilationJobs call to the build system
  .changeset/selfish-worms-remain.md
  v-next/hardhat/src/internal/builtin-plugins/solidity-test/task-action.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/build-system.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/tasks/compile.ts
Labels: status:ready

#6391 Re-write Multichain support section in comparison
  docs/src/content/hardhat3-alpha/learn-more/comparison.md
Labels: status:ready, no changeset needed

#6396 Show hardhat error on bad password
  .changeset/short-zoos-arrive.md
  v-next/hardhat-errors/src/descriptors.ts
  v-next/hardhat-keystore/src/internal/keystores/keystore.ts
  v-next/hardhat-keystore/test/tasks/delete.ts
  v-next/hardhat-keystore/test/tasks/get.ts
  v-next/hardhat-keystore/test/tasks/set.ts
Labels: status:ready, v-next

#6422 Exception rather than clear message on unknown build profile
  .changeset/many-wombats-grin.md
  v-next/hardhat-errors/src/descriptors.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/build-system.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/solc-config-selection.ts
  v-next/hardhat/test/internal/builtin-plugins/solidity/build-system/build-system.ts
Labels: v-next

#6401 [Cli parsing] When you run `npx hardhat task unexpected-argument` it doesn't fail if task is an empty task
  .changeset/short-beans-rest.md
  v-next/hardhat-errors/src/descriptors.ts
  v-next/hardhat/src/internal/cli/main.ts
  v-next/hardhat/test/fixture-projects/cli/parsing/tasks-and-subtasks/hardhat.config.ts
  v-next/hardhat/test/internal/cli/main.ts
Labels: v-next

#6446 fix: test the shouldUpdateDependency helper thoroughly
  v-next/hardhat/src/internal/cli/init/init.ts
  v-next/hardhat/test/internal/cli/init/init.ts
Labels: status:ready

#6426 Fix: bug in semver check on installProjectDependencies
  .changeset/cool-waves-wonder.md
  v-next/hardhat/src/internal/cli/init/init.ts
  v-next/hardhat/test/internal/cli/init/init.ts
Labels: status:triaging

#6442 [Typechain] Investigate how to support the attach method
  .changeset/small-buckets-ring.md
  v-next/hardhat-typechain/src/internal/generate-types.ts
  v-next/hardhat-typechain/test/index.ts
Labels: v-next

#6445 fix: correct package manager selection in CLI install
  .changeset/hot-birds-cover.md
  packages/hardhat-core/src/internal/cli/project-creation.ts
Labels: status:triaging

#6457 chore: bump EDR to 0.10.0
  .changeset/selfish-horses-peel.md
  packages/hardhat-core/package.json
  pnpm-lock.yaml
Labels: status:ready

#6410 Override max-width to fix ignition graph centering
  .changeset/metal-kings-hide.md
  packages/hardhat-ignition-ui/src/main.css
Labels: status:triaging

#6479 fix dead link README.md
  packages/hardhat-ledger/README.md
Labels: status:triaging, no changeset needed

#6400 [Typechain] generate types only for contracts and not test files
  .changeset/calm-clouds-work.md
  v-next/hardhat-typechain/src/internal/hook-handlers/solidity.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/build-system.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/type-extensions.ts
Labels: v-next

#6488 More prominence for hh3 on the main docs index
  docs/src/content/docs-landing/index.md
  docs/src/content/hardhat-runner/docs/getting-started/index.md
Labels: status:ready, no changeset needed

#6476 Consistency across plugin boilerplate files
  pnpm-lock.yaml
  v-next/hardhat-errors/.gitignore
  v-next/hardhat-errors/.prettierignore
  v-next/hardhat-errors/package.json
  v-next/hardhat-ethers-chai-matchers/.gitignore
  v-next/hardhat-ethers-chai-matchers/.prettierignore
  v-next/hardhat-ethers-chai-matchers/package.json
  v-next/hardhat-ethers/.gitignore
  v-next/hardhat-ethers/.prettierignore
  v-next/hardhat-ethers/package.json
  v-next/hardhat-ignition-core/package.json
  v-next/hardhat-ignition-ethers/package.json
  v-next/hardhat-ignition-viem/package.json
  v-next/hardhat-ignition/package.json
  v-next/hardhat-keystore/.gitignore
  v-next/hardhat-keystore/.prettierignore
  v-next/hardhat-keystore/package.json
  v-next/hardhat-mocha/.gitignore
  v-next/hardhat-mocha/.prettierignore
  v-next/hardhat-mocha/package.json
  v-next/hardhat-network-helpers/.gitignore
  v-next/hardhat-network-helpers/.prettierignore
  v-next/hardhat-network-helpers/package.json
  v-next/hardhat-node-test-reporter/.gitignore
  v-next/hardhat-node-test-reporter/.prettierignore
  v-next/hardhat-node-test-reporter/package.json
  v-next/hardhat-node-test-runner/.gitignore
  v-next/hardhat-node-test-runner/.prettierignore
  v-next/hardhat-node-test-runner/package.json
  v-next/hardhat-test-utils/.gitignore
  v-next/hardhat-test-utils/.prettierignore
  v-next/hardhat-test-utils/package.json
  v-next/hardhat-typechain/.gitignore
  v-next/hardhat-typechain/.prettierignore
  v-next/hardhat-typechain/package.json
  v-next/hardhat-utils/.gitignore
  v-next/hardhat-utils/.prettierignore
  v-next/hardhat-utils/package.json
  v-next/hardhat-viem/.eslintignore
  v-next/hardhat-viem/.gitignore
  v-next/hardhat-viem/.prettierignore
  v-next/hardhat-viem/package.json
  v-next/hardhat-viem/test/fixture-projects/default-ts-project/hardhat.config.ts
  v-next/hardhat-zod-utils/.gitignore
  v-next/hardhat-zod-utils/.prettierignore
  v-next/hardhat-zod-utils/package.json
  v-next/hardhat/.gitignore
  v-next/hardhat/package.json
  v-next/template-package/.gitignore
  v-next/template-package/.prettierignore
  v-next/template-package/package.json
Labels: no changeset needed

#6486 Hardhat v3 alpha release
  .changeset/calm-clouds-work.md
  .changeset/giant-chairs-drop.md
  .changeset/little-laws-shop.md
  .changeset/long-toes-deny.md
  .changeset/polite-crabs-relax.md
  .changeset/pre.json
  .changeset/release-3.0.0-next.2.md
  .changeset/small-buckets-ring.md
  pnpm-lock.yaml
  scripts/version-alpha.mjs
  v-next/example-project/package.json
  v-next/hardhat-errors/CHANGELOG.md
  v-next/hardhat-errors/package.json
  v-next/hardhat-ethers-chai-matchers/CHANGELOG.md
  v-next/hardhat-ethers-chai-matchers/package.json
  v-next/hardhat-ethers/CHANGELOG.md
  v-next/hardhat-ethers/package.json
  v-next/hardhat-ignition-core/CHANGELOG.md
  v-next/hardhat-ignition-core/package.json
  v-next/hardhat-ignition-ethers/CHANGELOG.md
  v-next/hardhat-ignition-ethers/package.json
  v-next/hardhat-ignition-ui/CHANGELOG.md
  v-next/hardhat-ignition-ui/package.json
  v-next/hardhat-ignition-viem/CHANGELOG.md
  v-next/hardhat-ignition-viem/package.json
  v-next/hardhat-ignition/CHANGELOG.md
  v-next/hardhat-ignition/package.json
  v-next/hardhat-keystore/CHANGELOG.md
  v-next/hardhat-keystore/package.json
  v-next/hardhat-mocha/CHANGELOG.md
  v-next/hardhat-mocha/package.json
  v-next/hardhat-network-helpers/CHANGELOG.md
  v-next/hardhat-network-helpers/package.json
  v-next/hardhat-node-test-reporter/CHANGELOG.md
  v-next/hardhat-node-test-reporter/package.json
  v-next/hardhat-node-test-runner/CHANGELOG.md
  v-next/hardhat-node-test-runner/package.json
  v-next/hardhat-test-utils/CHANGELOG.md
  v-next/hardhat-test-utils/package.json
  v-next/hardhat-typechain/CHANGELOG.md
  v-next/hardhat-typechain/package.json
  v-next/hardhat-utils/CHANGELOG.md
  v-next/hardhat-utils/package.json
  v-next/hardhat-viem/CHANGELOG.md
  v-next/hardhat-viem/package.json
  v-next/hardhat-zod-utils/CHANGELOG.md
  v-next/hardhat-zod-utils/package.json
  v-next/hardhat/CHANGELOG.md
  v-next/hardhat/package.json
  v-next/hardhat/templates/01-node-test-runner-viem/package.json
  v-next/hardhat/templates/02-mocha-ethers/package.json
  v-next/template-package/package.json
Labels: status:ready, no changeset needed

#6411 fix: compiler outputs might exceed the max buffer size
  .changeset/proud-walls-pump.md
  pnpm-lock.yaml
  v-next/hardhat-utils/package.json
  v-next/hardhat-utils/src/fs.ts
  v-next/hardhat-utils/test/fs.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/build-system.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/cache.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/compiler/compiler.ts
Labels: status:ready

#6467 Increase default http request timeout from 30s to 300s
  .changeset/eleven-bees-serve.md
  v-next/hardhat-utils/src/request.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/config-resolution.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/config-resolution.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/hook-handlers/config.ts
Labels: status:triaging

#6480 Restructure validation tests and add tests for missing fields
  v-next/hardhat/test/internal/builtin-plugins/network-manager/network-manager.ts
Labels: no changeset needed, v-next

#6492 Replace the usual banner with an `AlphaBanner` component
  docs/src/components/DocumentationLayout.tsx
  docs/src/components/LandingLayout.tsx
  docs/src/components/MobileSidebarMenu.tsx
  docs/src/components/PluginsLayout.tsx
  docs/src/components/ui/AlphaBanner.tsx
  docs/src/themes.tsx
Labels: status:ready, no changeset needed

#6495 Polish alpha 3 banner copy
  docs/src/components/ui/AlphaBanner.tsx
Labels: status:ready, no changeset needed

#6499 Fix infinite loop in `SolcConfigSelector`
  .changeset/smooth-pigs-sniff.md
  scripts/setup.sh
  v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/solc-config-selection.ts
  v-next/hardhat/test/internal/builtin-plugins/solidity/build-system/solc-config-selection.ts
Labels: status:ready

#6491 Hardhat v3 not compatible with vitest
  .changeset/angry-panthers-brush.md
  v-next/hardhat/src/internal/config-loading.ts
Labels: status:ready

#6501 chore: add comments explaining slow handlers imports
  v-next/hardhat/src/internal/builtin-plugins/network-manager/request-handlers/handlers-array.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/request-handlers/handlers/accounts/hd-wallet-handler.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/request-handlers/handlers/accounts/local-accounts.ts
Labels: status:ready, no changeset needed

#6490 [Investigation] Config overrides should be based on merging the user config, not the resolved
  v-next/hardhat-utils/src/internal/lang.ts
  v-next/hardhat-utils/src/lang.ts
  v-next/hardhat-utils/test/lang.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/config-override.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/config-resolution.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/hook-handlers/hre.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/network-manager.ts
  v-next/hardhat/src/types/hre.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/config-resolution.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/network-manager.ts
Labels: no changeset needed

#6470 Error when using a low interval mining value and mismatching timestamp
  .changeset/tasty-deers-doubt.md
  v-next/hardhat/src/internal/builtin-plugins/network-manager/type-validation.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/hook-handlers/config.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/network-manager.ts
Labels: status:triaging

#6223 Prague support
  .changeset/fuzzy-paws-explain.md
  docs/src/content/hardhat-network/docs/reference/index.md
  packages/hardhat-core/package.json
  packages/hardhat-core/src/builtin-tasks/node.ts
  packages/hardhat-core/src/internal/constants.ts
  packages/hardhat-core/src/internal/core/config/default-config.ts
  packages/hardhat-core/src/internal/core/errors-list.ts
  packages/hardhat-core/src/internal/core/jsonrpc/types/authorization-list.ts
  packages/hardhat-core/src/internal/core/jsonrpc/types/base-types.ts
  packages/hardhat-core/src/internal/core/jsonrpc/types/input/transactionRequest.ts
  packages/hardhat-core/src/internal/core/providers/accounts.ts
  packages/hardhat-core/src/internal/core/providers/util.ts
  packages/hardhat-core/src/internal/hardhat-network/jsonrpc/client.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/node-types.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/output.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/provider.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/utils/convertToEdr.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/utils/makeAccount.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/utils/makeCommon.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/utils/random.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/minimal-vm.ts
  packages/hardhat-core/src/internal/hardhat-network/provider/vm/types.ts
  packages/hardhat-core/src/internal/hardhat-network/stack-traces/consoleLogger.ts
  packages/hardhat-core/src/internal/hardhat-network/stack-traces/solidity-errors.ts
  packages/hardhat-core/src/internal/solidity/compiler/downloader.ts
  packages/hardhat-core/src/internal/util/hardforks.ts
  packages/hardhat-core/test/internal/core/jsonrpc/types/input/validation.ts
  packages/hardhat-core/test/internal/core/providers/accounts.ts
  packages/hardhat-core/test/internal/hardhat-network/helpers/assertions.ts
  packages/hardhat-core/test/internal/hardhat-network/helpers/blockchain.ts
  packages/hardhat-core/test/internal/hardhat-network/helpers/constants.ts
  packages/hardhat-core/test/internal/hardhat-network/helpers/getPendingBaseFeePerGas.ts
  packages/hardhat-core/test/internal/hardhat-network/helpers/leftPad32.ts
  packages/hardhat-core/test/internal/hardhat-network/helpers/providers.ts
  packages/hardhat-core/test/internal/hardhat-network/helpers/retrieveCommon.ts
  packages/hardhat-core/test/internal/hardhat-network/helpers/transactions.ts
  packages/hardhat-core/test/internal/hardhat-network/jsonrpc/client.ts
  packages/hardhat-core/test/internal/util/hardforks.ts
  packages/hardhat-core/test/internal/util/keys-derivation.ts
  packages/hardhat-ledger/package.json
  packages/hardhat-ledger/src/provider.ts
  pnpm-lock.yaml
Labels: status:ready

#6512 test: remove timeouts from the object cache test
  v-next/hardhat/test/internal/builtin-plugins/solidity/build-system/cache.ts
Labels: status:ready, no changeset needed

#6506 feat: support stack trace warnings and infer error messages from stack trace
  .changeset/pretty-lizards-roll.md
  v-next/hardhat/src/internal/builtin-plugins/solidity-test/reporter.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity-test/stack-trace-solidity-errors.ts
Labels: status:ready
