Repository NomicFoundation/hardhat, pull requests merged in 2025-08, with the labels that each got.

#7108 build: upgrade to @nomicfoundation/edr v0.12.0-next.3
  .changeset/proud-colts-itch.md
  .changeset/spotty-pianos-confess.md
  pnpm-lock.yaml
  v-next/hardhat/package.json
Labels: status:ready

#7104 Rename `optimism` chaintype to `op`
  .changeset/gorgeous-knives-yawn.md
  v-next/example-project/hardhat.config.ts
  v-next/example-project/scripts/send-op-tx-viem.ts
  v-next/example-project/scripts/send-op-tx.ts
  v-next/example-project/scripts/viem-plugin-example.ts
  v-next/hardhat-viem/src/internal/chains.ts
  v-next/hardhat-viem/src/internal/clients.ts
  v-next/hardhat-viem/src/types.ts
  v-next/hardhat-viem/test/clients.ts
  v-next/hardhat-viem/test/contracts.ts
  v-next/hardhat/src/internal/constants.ts
  v-next/hardhat/src/types/network.ts
  v-next/hardhat/templates/01-node-test-runner-viem/hardhat.config.ts
  v-next/hardhat/templates/01-node-test-runner-viem/scripts/check-predeploy.ts
  v-next/hardhat/templates/01-node-test-runner-viem/scripts/send-op-tx.ts
  v-next/hardhat/templates/01-node-test-runner-viem/test/Counter.ts
  v-next/hardhat/templates/02-mocha-ethers/hardhat.config.ts
  v-next/hardhat/templates/02-mocha-ethers/scripts/check-predeploy.ts
  v-next/hardhat/templates/02-mocha-ethers/scripts/send-op-tx.ts
  v-next/hardhat/templates/02-mocha-ethers/test/Counter.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/hook-handlers/config.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/network-manager.ts
  v-next/hardhat/test/internal/builtin-plugins/solidity-test/task-action.ts
Labels: status:ready

#7121 Don't use `undici`'s global dispatcher
  .changeset/pink-schools-exercise.md
  packages/hardhat-core/src/internal/util/download.ts
  packages/hardhat-verify/src/internal/undici.ts
  packages/hardhat-verify/test/integration/mocks/etherscan.ts
  packages/hardhat-verify/test/integration/mocks/sourcify.ts
Labels: status:ready

#7101 regroup test configs under a test object
  .changeset/khaki-seahorses-develop.md
  v-next/example-project/hardhat.config.ts
  v-next/hardhat-mocha/src/hookHandlers/config.ts
  v-next/hardhat-mocha/src/task-action.ts
  v-next/hardhat-mocha/src/type-extensions.ts
  v-next/hardhat-mocha/test/fixture-projects/invalid-mocha-config/hardhat.config.ts
  v-next/hardhat-mocha/test/index.ts
  v-next/hardhat/package.json
  v-next/hardhat/src/internal/builtin-plugins/solidity-test/config.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity-test/helpers.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity-test/task-action.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity-test/type-extensions.ts
  v-next/hardhat/src/internal/builtin-plugins/test/config.ts
  v-next/hardhat/src/internal/builtin-plugins/test/hook-handlers/config.ts
  v-next/hardhat/src/internal/builtin-plugins/test/index.ts
  v-next/hardhat/src/internal/builtin-plugins/test/type-extensions.ts
  v-next/hardhat/src/types/test.ts
  v-next/hardhat/test/internal/builtin-plugins/test/config.ts
Labels: status:ready

#7115 Change type of packageName
  .changeset/wicked-lies-reply.md
  v-next/hardhat/src/internal/core/config-validation.ts
  v-next/hardhat/src/internal/core/plugins/detect-plugin-npm-dependency-problems.ts
  v-next/hardhat/src/types/plugins.ts
  v-next/hardhat/test/internal/core/config-validation.ts
  v-next/hardhat/test/internal/core/hook-manager.ts
  v-next/hardhat/test/internal/core/plugins/detect-plugin-npm-dependency-problems.ts
  v-next/hardhat/test/internal/core/tasks/task-manager.ts
Labels: v-next

#7131 rename `edr` label in network config `edr-simulated`
  .changeset/long-rules-glow.md
  v-next/example-project/hardhat.config.ts
  v-next/example-project/scripts/send-op-tx-viem.ts
  v-next/hardhat-errors/src/descriptors.ts
  v-next/hardhat-ethers-chai-matchers/test/multi-network-connections.ts
  v-next/hardhat-ethers/src/internal/signers/signers.ts
  v-next/hardhat-ethers/test/hardhat-ethers-signer.ts
  v-next/hardhat-ignition-core/test-integrations/fixture-projects/dont-throw-on-reverts/hardhat.config.js
  v-next/hardhat-ignition-ethers/src/internal/ethers-ignition-helper.ts
  v-next/hardhat-ignition-viem/src/internal/viem-ignition-helper.ts
  v-next/hardhat-ignition/src/internal/tasks/deploy.ts
  v-next/hardhat-ignition/test/config.ts
  v-next/hardhat-ignition/test/fixture-projects/default-with-new-chain-id/hardhat.config.js
  v-next/hardhat-ignition/test/fixture-projects/reset-flag/hardhat.config.js
  v-next/hardhat-verify/test/fixture-projects/integration/hardhat.config.ts
  v-next/hardhat-viem/test/clients.ts
  v-next/hardhat-viem/test/contracts.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/config-override.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/config-resolution.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/hook-handlers/config.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/network-manager.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/type-extensions/config.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/type-validation.ts
  v-next/hardhat/src/internal/builtin-plugins/node/task-action.ts
  v-next/hardhat/templates/hardhat-3/01-node-test-runner-viem/hardhat.config.ts
  v-next/hardhat/templates/hardhat-3/02-mocha-ethers/hardhat.config.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/config-resolution.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/hook-handlers/config.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/network-manager.ts
Labels: status:ready

#7094 Add a development keystore
  .changeset/stupid-laws-carry.md
  v-next/hardhat-errors/src/descriptors.ts
  v-next/hardhat-keystore/src/index.ts
  v-next/hardhat-keystore/src/internal/hook-handlers/config.ts
  v-next/hardhat-keystore/src/internal/hook-handlers/configuration-variables.ts
  v-next/hardhat-keystore/src/internal/keystores/password.ts
  v-next/hardhat-keystore/src/internal/loaders/keystore-file-loader.ts
  v-next/hardhat-keystore/src/internal/tasks/change-password.ts
  v-next/hardhat-keystore/src/internal/tasks/delete.ts
  v-next/hardhat-keystore/src/internal/tasks/get.ts
  v-next/hardhat-keystore/src/internal/tasks/list.ts
  v-next/hardhat-keystore/src/internal/tasks/path.ts
  v-next/hardhat-keystore/src/internal/tasks/set.ts
  v-next/hardhat-keystore/src/internal/type-extensions.ts
  v-next/hardhat-keystore/src/internal/types.ts
  v-next/hardhat-keystore/src/internal/ui/user-display-messages.ts
  v-next/hardhat-keystore/src/internal/utils/get-keystore-file-path.ts
  v-next/hardhat-keystore/src/internal/utils/get-keystore-type.ts
  v-next/hardhat-keystore/src/internal/utils/setup-keystore-loader-from.ts
  v-next/hardhat-keystore/test/fixture-projects/keystore/.gitignore
  v-next/hardhat-keystore/test/fixture-projects/keystore/existing-keystore.json
  v-next/hardhat-keystore/test/helpers/mock-file-manager.ts
  v-next/hardhat-keystore/test/helpers/setup-keystore-file-location-override-at.ts
  v-next/hardhat-keystore/test/helpers/test-password.ts
  v-next/hardhat-keystore/test/hook-handlers/configuration-variables.ts
  v-next/hardhat-keystore/test/integration/tasks.ts
  v-next/hardhat-keystore/test/integration/turn-off-keystore-in-ci.ts
  v-next/hardhat-keystore/test/keystores/keystore.ts
  v-next/hardhat-keystore/test/loaders/keystore-file-loader.ts
  v-next/hardhat-keystore/test/tasks/change-password.ts
  v-next/hardhat-keystore/test/tasks/delete.ts
  v-next/hardhat-keystore/test/tasks/get.ts
  v-next/hardhat-keystore/test/tasks/list.ts
  v-next/hardhat-keystore/test/tasks/path.ts
  v-next/hardhat-keystore/test/tasks/set.ts
  v-next/hardhat-mocha/src/task-action.ts
  v-next/hardhat-node-test-runner/src/task-action.ts
Labels: v-next

#7136 7114 global options arent displayed in the help message of a task
  .changeset/neat-apes-beam.md
  v-next/hardhat/src/internal/cli/help/get-global-help-string.ts
  v-next/hardhat/src/internal/cli/help/get-help-string.ts
  v-next/hardhat/src/internal/cli/main.ts
  v-next/hardhat/test/internal/cli/help/get-global-help-string.ts
  v-next/hardhat/test/internal/cli/help/get-help-string.ts
  v-next/hardhat/test/internal/cli/main.ts
Labels: status:triaging

#7097 Version Packages (next)
  .changeset/e3f1b505-022f-4261-917c-99dc79f2f6b8.md
  .changeset/pre.json
  pnpm-lock.yaml
  v-next/example-project/package.json
  v-next/hardhat-errors/package.json
  v-next/hardhat-ethers-chai-matchers/package.json
  v-next/hardhat-ethers/package.json
  v-next/hardhat-ignition-core/package.json
  v-next/hardhat-ignition-ethers/package.json
  v-next/hardhat-ignition-ui/package.json
  v-next/hardhat-ignition-viem/package.json
  v-next/hardhat-ignition/package.json
  v-next/hardhat-keystore/package.json
  v-next/hardhat-mocha/package.json
  v-next/hardhat-network-helpers/package.json
  v-next/hardhat-node-test-reporter/package.json
  v-next/hardhat-node-test-runner/package.json
  v-next/hardhat-test-utils/package.json
  v-next/hardhat-toolbox-mocha-ethers/package.json
  v-next/hardhat-toolbox-viem/package.json
  v-next/hardhat-typechain/package.json
  v-next/hardhat-utils/package.json
  v-next/hardhat-verify/package.json
  v-next/hardhat-viem-assertions/package.json
  v-next/hardhat-viem/package.json
  v-next/hardhat-zod-utils/package.json
  v-next/hardhat/CHANGELOG.md
  v-next/hardhat/package.json
  v-next/hardhat/templates/hardhat-3/01-node-test-runner-viem/package.json
  v-next/hardhat/templates/hardhat-3/02-mocha-ethers/package.json
  v-next/template-package/package.json
Labels: status:triaging

#7145 Print error cause when showing stack traces
  .changeset/breezy-feet-impress.md
  v-next/hardhat/src/internal/cli/error-handler.ts
  v-next/hardhat/src/internal/cli/main.ts
  v-next/hardhat/test/internal/cli/error-handler.ts
Labels: status:ready

#7107 Compiler selection changes
  .changeset/nine-lies-press.md
  v-next/hardhat-utils/src/crypto.ts
  v-next/hardhat-verify/test/solc-versions.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/build-system.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/cache.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/compiler/compiler.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/compiler/downloader.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/compiler/index.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/config.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/hook-handlers/hre.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/type-extensions.ts
  v-next/hardhat/src/types/solidity/build-system.ts
  v-next/hardhat/test/internal/builtin-plugins/solidity/build-system/build-system.ts
  v-next/hardhat/test/internal/builtin-plugins/solidity/build-system/compiler/downloader.ts
  v-next/hardhat/test/internal/builtin-plugins/solidity/build-system/solc-config-selection.ts
  v-next/hardhat/test/internal/builtin-plugins/solidity/config.ts
Labels: status:triaging

#7144 Contributing update v3
  CONTRIBUTING.md
Labels: status:triaging, no changeset needed

#7143 Version Packages (next)
  .changeset/32b29249-86fa-4fa4-9c92-63582f2c0120.md
  .changeset/614582f7-ccfc-4d7d-9f33-7450a3a814a2.md
  .changeset/pre.json
  pnpm-lock.yaml
  v-next/example-project/package.json
  v-next/hardhat-errors/package.json
  v-next/hardhat-ethers-chai-matchers/package.json
  v-next/hardhat-ethers/package.json
  v-next/hardhat-ignition-core/package.json
  v-next/hardhat-ignition-ethers/package.json
  v-next/hardhat-ignition-ui/package.json
  v-next/hardhat-ignition-viem/package.json
  v-next/hardhat-ignition/package.json
  v-next/hardhat-keystore/package.json
  v-next/hardhat-mocha/package.json
  v-next/hardhat-network-helpers/package.json
  v-next/hardhat-node-test-reporter/package.json
  v-next/hardhat-node-test-runner/package.json
  v-next/hardhat-test-utils/package.json
  v-next/hardhat-toolbox-mocha-ethers/package.json
  v-next/hardhat-toolbox-viem/package.json
  v-next/hardhat-typechain/package.json
  v-next/hardhat-utils/package.json
  v-next/hardhat-verify/package.json
  v-next/hardhat-viem-assertions/package.json
  v-next/hardhat-viem/package.json
  v-next/hardhat-zod-utils/package.json
  v-next/hardhat/CHANGELOG.md
  v-next/hardhat/package.json
  v-next/hardhat/templates/hardhat-3/01-node-test-runner-viem/package.json
  v-next/hardhat/templates/hardhat-3/02-mocha-ethers/package.json
  v-next/template-package/package.json
Labels: status:triaging

#7155 Remove comments from template projects
  .changeset/curly-shrimps-speak.md
  v-next/hardhat/templates/hardhat-3/01-node-test-runner-viem/README.md
  v-next/hardhat/templates/hardhat-3/01-node-test-runner-viem/hardhat.config.ts
  v-next/hardhat/templates/hardhat-3/01-node-test-runner-viem/test/Counter.ts
  v-next/hardhat/templates/hardhat-3/02-mocha-ethers/README.md
  v-next/hardhat/templates/hardhat-3/02-mocha-ethers/hardhat.config.ts
  v-next/hardhat/templates/hardhat-3/02-mocha-ethers/test/Counter.ts
Labels: status:triaging

#7154 Solidity Config Resolution Enhancements
  .changeset/pink-crabs-bow.md
  v-next/hardhat-ignition-core/test/helpers/execution-result-fixtures.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/build-profiles.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/compilation-job.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/config.ts
  v-next/hardhat/test/internal/builtin-plugins/solidity/config.ts
Labels: status:ready

#7173 Version Packages (next)
  .changeset/pre.json
  pnpm-lock.yaml
  v-next/example-project/package.json
  v-next/hardhat-errors/package.json
  v-next/hardhat-ethers-chai-matchers/package.json
  v-next/hardhat-ethers/package.json
  v-next/hardhat-ignition-core/package.json
  v-next/hardhat-ignition-ethers/package.json
  v-next/hardhat-ignition-ui/package.json
  v-next/hardhat-ignition-viem/package.json
  v-next/hardhat-ignition/package.json
  v-next/hardhat-keystore/package.json
  v-next/hardhat-mocha/package.json
  v-next/hardhat-network-helpers/package.json
  v-next/hardhat-node-test-reporter/package.json
  v-next/hardhat-node-test-runner/package.json
  v-next/hardhat-test-utils/package.json
  v-next/hardhat-toolbox-mocha-ethers/package.json
  v-next/hardhat-toolbox-viem/package.json
  v-next/hardhat-typechain/package.json
  v-next/hardhat-utils/package.json
  v-next/hardhat-verify/package.json
  v-next/hardhat-viem-assertions/package.json
  v-next/hardhat-viem/package.json
  v-next/hardhat-zod-utils/package.json
  v-next/hardhat/CHANGELOG.md
  v-next/hardhat/package.json
  v-next/hardhat/templates/hardhat-3/01-node-test-runner-viem/package.json
  v-next/hardhat/templates/hardhat-3/02-mocha-ethers/package.json
  v-next/template-package/package.json
Labels: status:triaging

#7175 Improve unhandled errors
  .changeset/neat-waves-kiss.md
  v-next/hardhat/src/internal/cli/telemetry/sentry/init.ts
Labels: status:ready

#7176 chai matchers improvements
  .changeset/beige-carpets-hide.md
  .changeset/lemon-flowers-count.md
  v-next/hardhat-errors/src/descriptors.ts
  v-next/hardhat-ethers-chai-matchers/src/internal/add-chai-matchers.ts
  v-next/hardhat-ethers-chai-matchers/src/internal/constants.ts
  v-next/hardhat-ethers-chai-matchers/src/internal/matchers/changeEtherBalance.ts
  v-next/hardhat-ethers-chai-matchers/src/internal/matchers/changeEtherBalances.ts
  v-next/hardhat-ethers-chai-matchers/src/internal/matchers/changeTokenBalance.ts
  v-next/hardhat-ethers-chai-matchers/src/internal/matchers/reverted/legacyReverted.ts
  v-next/hardhat-ethers-chai-matchers/src/internal/matchers/reverted/revert.ts
  v-next/hardhat-ethers-chai-matchers/src/internal/utils/balance.ts
  v-next/hardhat-ethers-chai-matchers/src/type-extensions.ts
  v-next/hardhat-ethers-chai-matchers/test/matchers/changeEtherBalance.ts
  v-next/hardhat-ethers-chai-matchers/test/matchers/changeEtherBalances.ts
  v-next/hardhat-ethers-chai-matchers/test/matchers/changeTokenBalance.ts
  v-next/hardhat-ethers-chai-matchers/test/matchers/reverted/legacyReverted.ts
  v-next/hardhat-ethers-chai-matchers/test/matchers/reverted/revert.ts
  v-next/hardhat-ethers-chai-matchers/test/multi-network-connections.ts
Labels: status:ready

#7174 Bind all network helpers
  .changeset/gentle-planets-travel.md
  .changeset/wild-rivers-float.md
  v-next/hardhat-network-helpers/src/internal/network-helpers/network-helpers.ts
  v-next/hardhat-network-helpers/src/internal/network-helpers/time/time.ts
  v-next/hardhat-network-helpers/test/index.ts
  v-next/hardhat-utils/src/lang.ts
  v-next/hardhat-utils/test/lang.ts
Labels: status:ready

#7193 Better path anonymization
  .changeset/green-peas-grow.md
  v-next/hardhat/src/internal/cli/telemetry/sentry/anonymize-paths.ts
  v-next/hardhat/src/internal/cli/telemetry/sentry/anonymizer.ts
  v-next/hardhat/test/internal/cli/telemetry/sentry/anonymize-paths.ts
  v-next/hardhat/test/internal/cli/telemetry/sentry/anonymizer.ts
Labels: status:ready

#7189 Version Packages (v3) (next)
  .changeset/e97bb459-f835-48e0-b6c1-8fccdf27f430.md
  .changeset/fc94f6ee-6a9e-42de-8fa3-f3ce48986cdc.md
  .changeset/pre.json
  pnpm-lock.yaml
  v-next/example-project/package.json
  v-next/hardhat-errors/package.json
  v-next/hardhat-ethers-chai-matchers/package.json
  v-next/hardhat-ethers/package.json
  v-next/hardhat-ignition-core/package.json
  v-next/hardhat-ignition-ethers/package.json
  v-next/hardhat-ignition-ui/package.json
  v-next/hardhat-ignition-viem/package.json
  v-next/hardhat-ignition/package.json
  v-next/hardhat-keystore/package.json
  v-next/hardhat-mocha/package.json
  v-next/hardhat-network-helpers/package.json
  v-next/hardhat-node-test-reporter/package.json
  v-next/hardhat-node-test-runner/package.json
  v-next/hardhat-test-utils/package.json
  v-next/hardhat-toolbox-mocha-ethers/package.json
  v-next/hardhat-toolbox-viem/package.json
  v-next/hardhat-typechain/package.json
  v-next/hardhat-utils/package.json
  v-next/hardhat-verify/package.json
  v-next/hardhat-viem-assertions/package.json
  v-next/hardhat-viem/package.json
  v-next/hardhat-zod-utils/package.json
  v-next/hardhat/CHANGELOG.md
  v-next/hardhat/package.json
  v-next/hardhat/templates/hardhat-3/01-node-test-runner-viem/package.json
  v-next/hardhat/templates/hardhat-3/02-mocha-ethers/package.json
  v-next/template-package/package.json
Labels: status:triaging

#7202 chore: update header image link to absolute
  README.md
Labels: status:ready, no changeset needed

#7203 ci: update regression tests config
  .github/config/regression-tests.yml
Labels: status:ready, no changeset needed

#7210 chore: remove unneeded changeset
  .changeset/thick-ladybugs-mix.md
Labels: status:ready

#7196 Add temporary fix for incorrect error message
  .changeset/shy-lies-camp.md
  v-next/hardhat/src/internal/builtin-plugins/solidity-test/reporter.ts
Labels: status:triaging

#7201 docs: update reamde to include note on branches
  packages/hardhat-core/README.md
Labels: status:ready, no changeset needed

#7242 fix: broken links in plugin READMEs
  v-next/hardhat-keystore/README.md
  v-next/hardhat-verify/README.md
  v-next/hardhat-viem/README.md
Labels: status:triaging, no changeset needed

#7224 chore: relax ffi error check
  v-next/hardhat/src/internal/builtin-plugins/solidity-test/reporter.ts
Labels: status:ready, no changeset needed

#7239 loggingEnabled is ignored by EDR
  v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/edr-provider.ts
Labels: no changeset needed

#7256 chore: restore testFail cases exclusion
  .github/config/regression-tests.yml
Labels: status:ready, no changeset needed

#7244 Fix v3 yarn support
  .changeset/metal-owls-itch.md
  pnpm-lock.yaml
  v-next/hardhat/templates/hardhat-3/01-node-test-runner-viem/package.json
  v-next/hardhat/templates/hardhat-3/02-mocha-ethers/package.json
Labels: status:triaging

#7262 feat: warn user if they are not using the latest version of hardhat
  .changeset/smooth-seahorses-explain.md
  v-next/hardhat/src/internal/cli/init/init.ts
Labels: status:ready

#7251 improve exception filtering before sending to Sentry
  .changeset/three-rats-share.md
  v-next/hardhat/src/internal/cli/telemetry/sentry/anonymizer.ts
  v-next/hardhat/src/internal/cli/telemetry/sentry/reporter.ts
  v-next/hardhat/src/internal/cli/telemetry/sentry/subprocess.ts
  v-next/hardhat/src/internal/cli/telemetry/sentry/transport.ts
  v-next/hardhat/test/internal/cli/telemetry/sentry/anonymizer.ts
Labels: status:ready

#7274 chore: update pnpm lock file in release PR
  .github/workflows/release.yml
Labels: status:ready, no changeset needed

#7277 chore: fix changeset PR creation
  .github/workflows/release.yml
Labels: status:ready

#7199 docs: add JSDoc for assertions API to improve IntelliSense discoverability
  .changeset/honest-queens-perform.md
  v-next/hardhat-viem-assertions/src/predicates.ts
  v-next/hardhat-viem-assertions/src/type-extensions.ts
  v-next/hardhat-viem-assertions/src/types.ts
Labels: status:triaging

#7184 build: update checkout action to v5
  .github/workflows/LATEST_DEPENDENCY_VERSIONS.yml
  .github/workflows/cache.yml
  .github/workflows/check-changeset-added.yml
  .github/workflows/regression-tests.yml
  .github/workflows/release.yml
  .github/workflows/spellcheck.yml
  .github/workflows/v-next-ci.yml
Labels: no changeset needed

#7300 chore: update the dependency check CI job to point at v2
  .github/workflows/LATEST_DEPENDENCY_VERSIONS.yml
Labels: status:ready, no changeset needed

#7301 Change header image in readme
  img/hardhat-header.png
Labels: status:ready, no changeset needed

#7295 Descriptions unified for built-in commands and options
  .changeset/hip-knives-pull.md
  archive/hardhat-ledger/README.md
  v-next/example-project/hardhat.config.ts
  v-next/hardhat-keystore/src/index.ts
  v-next/hardhat/src/internal/builtin-global-options.ts
  v-next/hardhat/src/internal/builtin-plugins/clean/index.ts
  v-next/hardhat/src/internal/builtin-plugins/console/index.ts
  v-next/hardhat/src/internal/builtin-plugins/flatten/index.ts
  v-next/hardhat/src/internal/builtin-plugins/node/index.ts
  v-next/hardhat/src/internal/builtin-plugins/run/index.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/index.ts
  v-next/hardhat/src/internal/builtin-plugins/telemetry/index.ts
  v-next/hardhat/src/internal/builtin-plugins/test/index.ts
  v-next/hardhat/test/fixture-projects/run-js-script/hardhat.config.js
  v-next/hardhat/test/fixture-projects/run-ts-script/hardhat.config.ts
  v-next/hardhat/test/internal/cli/help/get-global-help-string.ts
  v-next/hardhat/test/internal/cli/main.ts
  v-next/hardhat/test/internal/example-mock-artifacts-plugin-using-test.ts
Labels: status:triaging
