Repository NomicFoundation/hardhat, pull requests merged in 2025-09, with the labels that each got.

#7333 fix/update v2 to work with latest type deps
  .changeset/clear-guests-rhyme.md
  .changeset/config.json
  packages/hardhat-core/src/internal/solidity/compiler/index.ts
  packages/hardhat-ledger/src/errors.ts
Labels: status:ready

#7348 Update README.md
  v-next/example-project/README.md
Labels: status:triaging, no changeset needed

#7291 fix: add safe optional chaining for contract access in verify module
  .changeset/popular-bats-doubt.md
  v-next/hardhat-verify/src/internal/contract.ts
Labels: status:triaging

#7367 Fix REPORT_GAS envvar in toolboxes
  .changeset/wild-wombats-compare.md
  packages/hardhat-toolbox-viem/src/index.ts
  packages/hardhat-toolbox/src/index.ts
Labels: status:ready

#7356 feat: add Linea network support for contract verification
  .changeset/add-linea-chain-support.md
  v-next/hardhat-ignition-core/src/internal/chain-config.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/chain-descriptors.ts
Labels: status:triaging

#7383 remove ci jobs in v2 now on main
  .github/workflows/LATEST_DEPENDENCY_VERSIONS.yml
  .github/workflows/add-issue-to-project.yml
  .github/workflows/add-label-to-new-issue.yml
  .github/workflows/autoassign-issues.yml
  .github/workflows/autoassign-prs.yml
  .github/workflows/check-changeset-added.yml
  .github/workflows/close-stale-issues.yml
  .github/workflows/lock.yml
Labels: status:ready

#7398 chore: update changesets in prep for release
  .changeset/cold-shrimps-float.md
Labels: no changeset needed
