Repository NomicFoundation/hardhat, pull requests merged in 2025-04, with the labels that each got.

#6500 feat: implement automated regression tests
  .github/config/regression-tests.yml
  .github/workflows/regression-tests.yml
  .gitignore
Labels: status:ready, no changeset needed

#6526 feat: implement automated regression tests (cherry-pick on the default branch)
  .github/config/regression-tests.yml
  .github/workflows/regression-tests.yml
  .gitignore
Labels: status:ready, no changeset needed

#6170 Add hardforkHistory for avalanche network
  .changeset/shiny-trees-laugh.md
  .github/config/regression-tests.yml
  .github/workflows/regression-tests.yml
  packages/hardhat-core/src/internal/core/config/default-config.ts
Labels: status:triaging

#6543 feat: bump @ignored/edr to 0.10.0-alpha.2
  .changeset/stale-insects-design.md
  pnpm-lock.yaml
  v-next/hardhat/package.json
Labels: status:ready

#6529 fix: pass all artifacts to edr when executing solidity tests
  .changeset/wet-students-act.md
  v-next/hardhat-mocha/src/index.ts
  v-next/hardhat-node-test-runner/src/index.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity-test/index.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity-test/task-action.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/build-results.ts
Labels: status:ready

#6558 feat: update chains map with prague activation blocks
  packages/hardhat-core/src/internal/core/config/default-config.ts
Labels: status:ready, no changeset needed

#6562 Move pluginId to the error category from the error descriptors
  v-next/hardhat-errors/src/descriptors.ts
  v-next/hardhat-errors/src/errors.ts
  v-next/hardhat-errors/test/errors.ts
  v-next/hardhat/test/internal/cli/error-handler.ts
Labels: status:ready, no changeset needed

#6536 Fix broken link
  packages/hardhat-ignition-examples/ens/README.md
Labels: status:triaging, no changeset needed

#6534 Fix `GetArtifactByName` spelling
  .changeset/shaggy-timers-sleep.md
  v-next/hardhat-ethers/test/helpers/artifact-manager-mock.ts
  v-next/hardhat/src/internal/builtin-plugins/artifacts/artifact-manager.ts
  v-next/hardhat/src/internal/builtin-plugins/artifacts/hook-handlers/hre.ts
  v-next/hardhat/src/types/artifacts.ts
  v-next/hardhat/test/test-helpers/mock-artifact-manager.ts
Labels: status:triaging, v-next

#6523 Toolbox hardhat-toolbox-viem v3
  .changeset/pre.json
  .changeset/sweet-pumpkins-yell.md
  pnpm-lock.yaml
  v-next/hardhat-toolbox-viem/.eslintrc.cjs
  v-next/hardhat-toolbox-viem/.gitignore
  v-next/hardhat-toolbox-viem/.prettierignore
  v-next/hardhat-toolbox-viem/LICENSE
  v-next/hardhat-toolbox-viem/README.md
  v-next/hardhat-toolbox-viem/package.json
  v-next/hardhat-toolbox-viem/src/index.ts
  v-next/hardhat-toolbox-viem/src/type-extensions.ts
  v-next/hardhat-toolbox-viem/test/fixture-projects/toolbox/.gitignore
  v-next/hardhat-toolbox-viem/test/fixture-projects/toolbox/hardhat.config.ts
  v-next/hardhat-toolbox-viem/test/fixture-projects/toolbox/package.json
  v-next/hardhat-toolbox-viem/test/fixture-projects/toolbox/scripts/script.ts
  v-next/hardhat-toolbox-viem/test/index.ts
  v-next/hardhat-toolbox-viem/tsconfig.json
  v-next/hardhat/templates/01-node-test-runner-viem/hardhat.config.ts
  v-next/hardhat/templates/01-node-test-runner-viem/package.json
Labels: v-next

#6531 Toolbox hardhat-toolbox-mocha-ethers v3
  .changeset/polite-clocks-obey.md
  .changeset/pre.json
  pnpm-lock.yaml
  v-next/hardhat-toolbox-mocha-ethers/.eslintrc.cjs
  v-next/hardhat-toolbox-mocha-ethers/.gitignore
  v-next/hardhat-toolbox-mocha-ethers/.prettierignore
  v-next/hardhat-toolbox-mocha-ethers/LICENSE
  v-next/hardhat-toolbox-mocha-ethers/README.md
  v-next/hardhat-toolbox-mocha-ethers/package.json
  v-next/hardhat-toolbox-mocha-ethers/src/index.ts
  v-next/hardhat-toolbox-mocha-ethers/src/type-extensions.ts
  v-next/hardhat-toolbox-mocha-ethers/test/fixture-projects/toolbox/.gitignore
  v-next/hardhat-toolbox-mocha-ethers/test/fixture-projects/toolbox/contracts/Counter.sol
  v-next/hardhat-toolbox-mocha-ethers/test/fixture-projects/toolbox/hardhat.config.ts
  v-next/hardhat-toolbox-mocha-ethers/test/fixture-projects/toolbox/package.json
  v-next/hardhat-toolbox-mocha-ethers/test/fixture-projects/toolbox/scripts/script.ts
  v-next/hardhat-toolbox-mocha-ethers/test/index.ts
  v-next/hardhat-toolbox-mocha-ethers/tsconfig.json
  v-next/hardhat/templates/02-mocha-ethers/hardhat.config.ts
  v-next/hardhat/templates/02-mocha-ethers/package.json
Labels: v-next

#6540 test: add busy error handling for remove funtion on Windows platform
  .changeset/serious-rice-invent.md
  v-next/hardhat-utils/src/fs.ts
  v-next/hardhat-utils/test/fs.ts
  v-next/hardhat-utils/test/lang.ts
Labels: status:triaging, v-next

#6566 chore: fix up changesets for next release
  .changeset/hungry-dogs-stare.md
  .changeset/polite-clocks-obey.md
  .changeset/pre.json
  .changeset/shaggy-cherries-work.md
  .changeset/shaggy-timers-sleep.md
  .changeset/stale-insects-design.md
  .changeset/wet-students-act.md
  pnpm-lock.yaml
  v-next/hardhat-toolbox-viem/package.json
  v-next/hardhat/templates/01-node-test-runner-viem/package.json
Labels: status:ready

#6572 add skipped test names to report
  .changeset/six-moles-jam.md
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/async-describe-test/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/async-describe-test/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/asynchronous-activity-test/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/asynchronous-activity-test/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/errors-test/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/errors-test/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/example-test/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/example-test/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/execution-failure-test/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/execution-failure-test/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/hooks-test/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/hooks-test/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/multi-test/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/multi-test/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/nested-test/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/nested-test/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/only-test-with-the-flag/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/only-test-with-the-flag/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/only-test-without-the-flag/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/only-test-without-the-flag/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/skipped-and-empty-describes/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/skipped-and-empty-describes/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/skipped-and-empty-describes/test.ts
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/slow-test/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/slow-test/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/todo-test/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/todo-test/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/top-level-test/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/top-level-test/result.txt
  v-next/hardhat-node-test-reporter/src/formatting.ts
  v-next/hardhat-node-test-reporter/src/reporter.ts
  v-next/hardhat-node-test-reporter/test/error-formatting.ts
Labels: status:triaging

#6588 feat: add a global --coverage flag which enables coverage
  .changeset/funny-points-prove.md
  v-next/hardhat/.gitignore
  v-next/hardhat/src/internal/builtin-plugins/coverage/index.ts
  v-next/hardhat/src/internal/builtin-plugins/coverage/task-action.ts
  v-next/hardhat/src/internal/builtin-plugins/coverage/type-extensions.ts
  v-next/hardhat/test/internal/cli/main.ts
  v-next/hardhat/test/internal/hre-intialization.ts
Labels: status:ready

#6599 Remove website from `v-next`
  docs/index.html
  docs/vercel.json
Labels: status:ready, no changeset needed

#6590 build: upgrade EDR to v0.11.0
  .changeset/five-birds-invite.md
  packages/hardhat-core/package.json
  pnpm-lock.yaml
Labels: status:ready

#6546 build: upgrade to @ignored/edr-optimism@0.10.0-alpha.1
  .changeset/weak-starfishes-brush.md
  pnpm-lock.yaml
  v-next/hardhat-zod-utils/src/index.ts
  v-next/hardhat/package.json
  v-next/hardhat/src/internal/builtin-plugins/network-manager/config-resolution.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/edr-context.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/edr-provider.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/types/hardfork.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/utils/convert-to-edr.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/utils/hardfork.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/type-extensions/config.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/type-validation.ts
  v-next/hardhat/src/types/utils.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/config-resolution.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/network-manager.ts
Labels: status:ready, v-next

#6606 docs: replace dead Truffle testing link
  packages/hardhat-truffle4/README.md
  packages/hardhat-truffle5/README.md
Labels: status:triaging, no changeset needed

#6609 docs: improve changeset message
  .changeset/weak-starfishes-brush.md
Labels: status:ready, no changeset needed, v-next

#6607 feat: support chainId values above 2^32 - 1 for local account transac…
  .changeset/weak-frogs-care.md
  packages/hardhat-core/src/internal/core/providers/accounts.ts
  packages/hardhat-core/test/internal/core/providers/accounts.ts
Labels: status:triaging

#6576 add ensureNodeErrnoExceptionError function to assert the error
  .changeset/eleven-lies-sin.md
  v-next/hardhat-utils/src/error.ts
  v-next/hardhat-utils/src/fs.ts
  v-next/hardhat-utils/src/synchronization.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/base-provider.ts
Labels: status:triaging

#6594 Ignition ethers & viem plugins test conversions
  .changeset/healthy-cars-remain.md
  pnpm-lock.yaml
  v-next/hardhat-ignition-ethers/package.json
  v-next/hardhat-ignition-ethers/test/default-sender.ts
  v-next/hardhat-ignition-ethers/test/deploy-with-ethers-result.ts
  v-next/hardhat-ignition-ethers/test/fixture-projects/.gitignore
  v-next/hardhat-ignition-ethers/test/ignition-helper-exclusivity.ts
  v-next/hardhat-ignition-ethers/test/setup.ts
  v-next/hardhat-ignition-ethers/test/strategies/helper-invocation.ts
  v-next/hardhat-ignition-ethers/test/test-helpers/create-hre.ts
  v-next/hardhat-ignition-ethers/test/test-helpers/use-ignition-project.ts
  v-next/hardhat-ignition-viem/package.json
  v-next/hardhat-ignition-viem/test/default-sender.ts
  v-next/hardhat-ignition-viem/test/fixture-projects/.gitignore
  v-next/hardhat-ignition-viem/test/ignition-helper-exclusivity.ts
  v-next/hardhat-ignition-viem/test/setup.ts
  v-next/hardhat-ignition-viem/test/strategies/helper-invocation.ts
  v-next/hardhat-ignition-viem/test/test-helpers/create-hre.ts
  v-next/hardhat-ignition-viem/test/test-helpers/use-ignition-project.ts
  v-next/hardhat-ignition-viem/test/use-module.ts
  v-next/hardhat-ignition-viem/test/viem-instances/artifact-contract-at.ts
  v-next/hardhat-ignition-viem/test/viem-instances/artifact-deployment-contract.ts
  v-next/hardhat-ignition-viem/test/viem-instances/named-contract-at.ts
  v-next/hardhat-ignition-viem/test/viem-instances/named-deployment-contract.ts
  v-next/hardhat-ignition-viem/test/viem-results.ts
Labels: v-next

#6573 feat: enable telemetry by default
  .changeset/thin-peas-end.md
  v-next/hardhat/src/internal/builtin-plugins/index.ts
  v-next/hardhat/src/internal/builtin-plugins/telemetry/index.ts
  v-next/hardhat/src/internal/builtin-plugins/telemetry/task-action.ts
  v-next/hardhat/src/internal/cli/init/init.ts
  v-next/hardhat/src/internal/cli/main.ts
  v-next/hardhat/src/internal/cli/prompt/prompt.ts
  v-next/hardhat/src/internal/cli/telemetry/analytics/analytics.ts
  v-next/hardhat/src/internal/cli/telemetry/analytics/types.ts
  v-next/hardhat/src/internal/cli/telemetry/sentry/subprocess.ts
  v-next/hardhat/src/internal/cli/telemetry/telemetry-permissions.ts
  v-next/hardhat/test/internal/cli/main.ts
  v-next/hardhat/test/internal/cli/telemetry/analytics/analytics.ts
  v-next/hardhat/test/internal/cli/telemetry/sentry/reporter.ts
  v-next/hardhat/test/internal/cli/telemetry/telemetry-permissions.ts
Labels: status:ready

#6626 Hardhat v3 alpha release
  .changeset/angry-rules-cheat.md
  .changeset/eleven-lies-sin.md
  .changeset/funny-points-prove.md
  .changeset/healthy-cars-remain.md
  .changeset/pre.json
  .changeset/release-3.0.0-next.5.md
  .changeset/six-moles-jam.md
  .changeset/thin-peas-end.md
  .changeset/tricky-cups-pay.md
  .changeset/weak-starfishes-brush.md
  pnpm-lock.yaml
  v-next/example-project/package.json
  v-next/hardhat-errors/package.json
  v-next/hardhat-ethers-chai-matchers/package.json
  v-next/hardhat-ethers/package.json
  v-next/hardhat-ignition-core/package.json
  v-next/hardhat-ignition-ethers/package.json
  v-next/hardhat-ignition-ui/package.json
  v-next/hardhat-ignition-viem/package.json
  v-next/hardhat-ignition/package.json
  v-next/hardhat-keystore/package.json
  v-next/hardhat-mocha/package.json
  v-next/hardhat-network-helpers/package.json
  v-next/hardhat-node-test-reporter/package.json
  v-next/hardhat-node-test-runner/package.json
  v-next/hardhat-test-utils/package.json
  v-next/hardhat-toolbox-mocha-ethers/package.json
  v-next/hardhat-toolbox-viem/package.json
  v-next/hardhat-typechain/package.json
  v-next/hardhat-utils/package.json
  v-next/hardhat-viem/package.json
  v-next/hardhat-zod-utils/package.json
  v-next/hardhat/CHANGELOG.md
  v-next/hardhat/package.json
  v-next/hardhat/templates/01-node-test-runner-viem/package.json
  v-next/hardhat/templates/02-mocha-ethers/package.json
  v-next/template-package/package.json
Labels: status:ready, no changeset needed

#6628 Disable hardhat-toolbox-mocha-ethers flaky test until issue is fixed
  v-next/hardhat-toolbox-mocha-ethers/test/index.ts
Labels: no changeset needed, v-next

#6634 build: upgrade to @ignored/edr v0.13.0-alpha.0
  pnpm-lock.yaml
  v-next/hardhat/package.json
Labels: status:ready, no changeset needed

#6643 feat: disable strict mode in Transaction.prepare
  .changeset/gold-months-try.md
  packages/hardhat-core/src/internal/core/providers/accounts.ts
Labels: status:ready

#6644 [v-next] feat: disable strict mode in Transaction.prepare
  .changeset/wet-walls-jog.md
  v-next/hardhat/src/internal/builtin-plugins/network-manager/request-handlers/handlers/accounts/local-accounts.ts
Labels: status:ready

#6648 fix: remove contract reverted without a reason string message from solidity tests
  .changeset/chatty-rocks-reply.md
  v-next/hardhat/src/internal/builtin-plugins/solidity-test/stack-trace-solidity-errors.ts
Labels: status:ready

#6636 Update pnpm/action-setup from v3 to v4
  .github/workflows/hardhat-ci.yml
Labels: status:triaging, no changeset needed

#6653 Create folder if not exists during `--init`
  .changeset/slimy-pots-applaud.md
  v-next/hardhat-errors/src/descriptors.ts
  v-next/hardhat/src/internal/cli/init/init.ts
  v-next/hardhat/test/internal/cli/init/init.ts
Labels: status:ready, hardhat-3-alpha

#6654 Hardhat v3 alpha release
  .changeset/hot-balloons-taste.md
  .changeset/pre.json
  .changeset/release-3.0.0-next.6.md
  .changeset/wet-walls-jog.md
  pnpm-lock.yaml
  v-next/example-project/package.json
  v-next/hardhat-errors/package.json
  v-next/hardhat-ethers-chai-matchers/package.json
  v-next/hardhat-ethers/package.json
  v-next/hardhat-ignition-core/package.json
  v-next/hardhat-ignition-ethers/package.json
  v-next/hardhat-ignition-ui/package.json
  v-next/hardhat-ignition-viem/package.json
  v-next/hardhat-ignition/package.json
  v-next/hardhat-keystore/package.json
  v-next/hardhat-mocha/package.json
  v-next/hardhat-network-helpers/package.json
  v-next/hardhat-node-test-reporter/package.json
  v-next/hardhat-node-test-runner/package.json
  v-next/hardhat-test-utils/package.json
  v-next/hardhat-toolbox-mocha-ethers/package.json
  v-next/hardhat-toolbox-viem/package.json
  v-next/hardhat-typechain/package.json
  v-next/hardhat-utils/package.json
  v-next/hardhat-viem/package.json
  v-next/hardhat-zod-utils/package.json
  v-next/hardhat/CHANGELOG.md
  v-next/hardhat/package.json
  v-next/hardhat/templates/01-node-test-runner-viem/package.json
  v-next/hardhat/templates/02-mocha-ethers/package.json
  v-next/template-package/package.json
Labels: status:ready, no changeset needed
