Repository NomicFoundation/hardhat, pull requests merged in 2025-07, with the labels that each got.

#6958 Enable multichain testing support in Solidity test runner
  .changeset/fluffy-glasses-beam.md
  pnpm-lock.yaml
  v-next/config/eslint.config.js
  v-next/hardhat/package.json
  v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/edr-provider.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/utils/chain-type.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/utils/convert-to-edr.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/network-manager.ts
  v-next/hardhat/src/internal/builtin-plugins/node/task-action.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity-test/helpers.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity-test/index.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity-test/runner.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity-test/task-action.ts
  v-next/hardhat/src/internal/builtin-plugins/test/index.ts
  v-next/hardhat/src/internal/builtin-plugins/test/task-action.ts
  v-next/hardhat/src/internal/edr/chain-type.ts
  v-next/hardhat/test/fixture-projects/solidity-test/contracts/Predeploy.sol
  v-next/hardhat/test/fixture-projects/solidity-test/test/contracts/failing/Failing.t.sol
  v-next/hardhat/test/fixture-projects/solidity-test/test/contracts/op/Predeploy.t.sol
  v-next/hardhat/test/internal/builtin-plugins/solidity-test/task-action.ts
Labels: status:ready, v-next

#6969 Fix a changeset
  .changeset/fluffy-glasses-beam.md
Labels: status:ready, no changeset needed

#6947 Version Packages (next)
  .changeset/e4584a9c-37b1-4fe2-b8d2-d0522f7393d0.md
  .changeset/pre.json
  pnpm-lock.yaml
  v-next/example-project/package.json
  v-next/hardhat-errors/package.json
  v-next/hardhat-ethers-chai-matchers/package.json
  v-next/hardhat-ethers/package.json
  v-next/hardhat-ignition-core/package.json
  v-next/hardhat-ignition-ethers/package.json
  v-next/hardhat-ignition-ui/package.json
  v-next/hardhat-ignition-viem/package.json
  v-next/hardhat-ignition/package.json
  v-next/hardhat-keystore/package.json
  v-next/hardhat-mocha/package.json
  v-next/hardhat-network-helpers/package.json
  v-next/hardhat-node-test-reporter/package.json
  v-next/hardhat-node-test-runner/package.json
  v-next/hardhat-test-utils/package.json
  v-next/hardhat-toolbox-mocha-ethers/package.json
  v-next/hardhat-toolbox-viem/package.json
  v-next/hardhat-typechain/package.json
  v-next/hardhat-utils/package.json
  v-next/hardhat-verify/package.json
  v-next/hardhat-viem-assertions/package.json
  v-next/hardhat-viem/package.json
  v-next/hardhat-zod-utils/package.json
  v-next/hardhat/CHANGELOG.md
  v-next/hardhat/package.json
  v-next/hardhat/templates/01-node-test-runner-viem/package.json
  v-next/hardhat/templates/02-mocha-ethers/package.json
  v-next/template-package/package.json
Labels: status:triaging

#6941 feat: added support for short option names
  .changeset/green-hornets-joke.md
  v-next/hardhat-errors/src/descriptors.ts
  v-next/hardhat/src/internal/cli/help/utils.ts
  v-next/hardhat/src/internal/cli/main.ts
  v-next/hardhat/src/internal/core/arguments.ts
  v-next/hardhat/src/internal/core/config.ts
  v-next/hardhat/src/internal/core/global-options.ts
  v-next/hardhat/src/internal/core/tasks/builders.ts
  v-next/hardhat/src/internal/core/tasks/task-manager.ts
  v-next/hardhat/src/internal/core/tasks/validations.ts
  v-next/hardhat/src/types/arguments.ts
  v-next/hardhat/src/types/tasks.ts
  v-next/hardhat/test/fixture-projects/cli/parsing/base-project/hardhat.config.ts
  v-next/hardhat/test/fixture-projects/cli/parsing/tasks-and-subtasks/hardhat.config.ts
  v-next/hardhat/test/internal/cli/help/utils.ts
  v-next/hardhat/test/internal/cli/main.ts
  v-next/hardhat/test/internal/core/arguments.ts
  v-next/hardhat/test/internal/core/global-options.ts
  v-next/hardhat/test/internal/core/tasks/builders.ts
  v-next/hardhat/test/internal/core/tasks/task-manager.ts
Labels: status:ready

#6942 feat: added FLAG and LEVEL arguments types
  .changeset/long-bats-nail.md
  v-next/hardhat-typechain/src/index.ts
  v-next/hardhat/src/internal/builtin-global-options.ts
  v-next/hardhat/src/internal/builtin-plugins/coverage/index.ts
  v-next/hardhat/src/internal/cli/help/utils.ts
  v-next/hardhat/src/internal/cli/main.ts
  v-next/hardhat/src/internal/core/arguments.ts
  v-next/hardhat/src/internal/core/config-validation.ts
  v-next/hardhat/src/internal/core/config.ts
  v-next/hardhat/src/internal/core/tasks/builders.ts
  v-next/hardhat/src/types/arguments.ts
  v-next/hardhat/src/types/tasks.ts
  v-next/hardhat/test/fixture-projects/cli/parsing/base-project/hardhat.config.ts
  v-next/hardhat/test/fixture-projects/cli/parsing/tasks-and-subtasks/hardhat.config.ts
  v-next/hardhat/test/internal/cli/help/get-help-string.ts
  v-next/hardhat/test/internal/cli/help/utils.ts
  v-next/hardhat/test/internal/cli/main.ts
  v-next/hardhat/test/internal/core/arguments.ts
  v-next/hardhat/test/internal/core/config-validation.ts
  v-next/hardhat/test/internal/core/tasks/builders.ts
Labels: status:ready

#6963 feat: allow requesting help via the -h flag
  .changeset/loud-buses-wave.md
  v-next/hardhat/src/internal/builtin-global-options.ts
  v-next/hardhat/src/internal/cli/main.ts
  v-next/hardhat/test/internal/cli/help/get-global-help-string.ts
  v-next/hardhat/test/internal/cli/main.ts
Labels: status:ready

#6965 fix: node crash when sending tx with insufficient funds
  .changeset/twenty-lies-destroy.md
  v-next/hardhat/src/internal/builtin-plugins/node/json-rpc/handler.ts
  v-next/hardhat/test/internal/builtin-plugins/node/json-rpc/handler.ts
  v-next/hardhat/test/utils.ts
Labels: status:ready

#6982 chore: update minimal supported version of node to v20
  .changeset/sharp-views-scream.md
  .devcontainer/devcontainer.json
  .github/actions/setup-env/action.yml
  .github/workflows/hardhat-ci.yml
  .github/workflows/hardhat-core-ci.yml
  .nvmrc
  packages/hardhat-chai-matchers/package.json
  packages/hardhat-core/package.json
  packages/hardhat-core/src/builtin-tasks/compile.ts
  packages/hardhat-core/src/internal/cli/constants.ts
  packages/hardhat-core/src/internal/cli/project-creation.ts
  packages/hardhat-core/src/internal/core/config/config-loading.ts
  packages/hardhat-core/test/builtin-tasks/compile.ts
  packages/hardhat-core/test/internal/cli/is-node-version-to-warn-on.ts
  packages/hardhat-ethers/package.json
  packages/hardhat-foundry/package.json
  packages/hardhat-ignition-core/package.json
  packages/hardhat-ignition-ethers/package.json
  packages/hardhat-ignition-viem/package.json
  packages/hardhat-ignition/package.json
  packages/hardhat-ledger/package.json
  packages/hardhat-network-helpers/package.json
  packages/hardhat-shorthand/package.json
  packages/hardhat-solhint/package.json
  packages/hardhat-solpp/package.json
  packages/hardhat-toolbox-viem/package.json
  packages/hardhat-toolbox/package.json
  packages/hardhat-truffle4/package.json
  packages/hardhat-truffle5/package.json
  packages/hardhat-verify/package.json
  packages/hardhat-viem/package.json
  packages/hardhat-vyper/package.json
  packages/hardhat-web3-legacy/package.json
  packages/hardhat-web3-v4/package.json
  packages/hardhat-web3/package.json
  pnpm-lock.yaml
Labels: status:ready

#6973 update the version of micro-eth-signer
  .changeset/light-breads-fail.md
  packages/hardhat-core/package.json
  pnpm-lock.yaml
Labels: status:ready

#6998 Remove unneeded types deps
  .changeset/khaki-needles-attend.md
  packages/hardhat-core/package.json
  pnpm-lock.yaml
Labels: status:ready

#7008 fix: change the changeset level to patch on edr version bump
  .changeset/common-planes-enjoy.md
Labels: status:ready

#6937 feat: enable providers by default and throw if apiKey is empty
  .changeset/wild-boats-study.md
  v-next/hardhat-errors/src/descriptors.ts
  v-next/hardhat-verify/src/internal/etherscan.ts
  v-next/hardhat-verify/src/internal/hook-handlers/config.ts
  v-next/hardhat-verify/test/etherscan.ts
  v-next/hardhat-verify/test/hook-handlers/config.ts
Labels: status:ready

#7016 Use input source names in the link references
  .changeset/tough-rice-jam.md
  v-next/hardhat-utils/src/internal/bytecode.ts
  v-next/hardhat-viem/test/contracts.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/artifacts.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/build-system.ts
  v-next/hardhat/src/types/artifacts.ts
Labels: status:ready

#7020 chore: update changesets in prep for release
  .changeset/green-hornets-joke.md
  .changeset/long-bats-nail.md
  .changeset/loud-buses-wave.md
  .changeset/sixty-phones-juggle.md
  .changeset/tough-rice-jam.md
  .changeset/twenty-lies-destroy.md
Labels: status:ready, no changeset needed

#6978 Version Packages (next)
  .changeset/0258c87f-3175-4ed3-8325-2e59c06ada3e.md
  .changeset/2bf45130-19a8-44bc-99ee-1f0a07f62372.md
  .changeset/pre.json
  pnpm-lock.yaml
  v-next/example-project/package.json
  v-next/hardhat-errors/package.json
  v-next/hardhat-ethers-chai-matchers/package.json
  v-next/hardhat-ethers/package.json
  v-next/hardhat-ignition-core/package.json
  v-next/hardhat-ignition-ethers/package.json
  v-next/hardhat-ignition-ui/package.json
  v-next/hardhat-ignition-viem/package.json
  v-next/hardhat-ignition/package.json
  v-next/hardhat-keystore/package.json
  v-next/hardhat-mocha/package.json
  v-next/hardhat-network-helpers/package.json
  v-next/hardhat-node-test-reporter/package.json
  v-next/hardhat-node-test-runner/package.json
  v-next/hardhat-test-utils/package.json
  v-next/hardhat-toolbox-mocha-ethers/package.json
  v-next/hardhat-toolbox-viem/package.json
  v-next/hardhat-typechain/package.json
  v-next/hardhat-utils/package.json
  v-next/hardhat-verify/package.json
  v-next/hardhat-viem-assertions/package.json
  v-next/hardhat-viem/package.json
  v-next/hardhat-zod-utils/package.json
  v-next/hardhat/CHANGELOG.md
  v-next/hardhat/package.json
  v-next/hardhat/templates/01-node-test-runner-viem/package.json
  v-next/hardhat/templates/02-mocha-ethers/package.json
  v-next/template-package/package.json
Labels: status:triaging

#7030 fix: global flag option parsing
  .changeset/spicy-ravens-type.md
  v-next/hardhat/src/internal/core/arguments.ts
  v-next/hardhat/test/internal/core/arguments.ts
  v-next/hardhat/test/internal/core/global-options.ts
Labels: status:ready

#6989 feat: implement call traces display for solidity tests
  .changeset/fluffy-days-study.md
  v-next/example-project/contracts/Counter.t.sol
  v-next/hardhat/src/internal/builtin-global-options.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity-test/formatters.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity-test/helpers.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity-test/index.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity-test/reporter.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity-test/task-action.ts
  v-next/hardhat/src/internal/builtin-plugins/test/index.ts
  v-next/hardhat/src/internal/builtin-plugins/test/task-action.ts
  v-next/hardhat/src/internal/cli/main.ts
  v-next/hardhat/src/internal/cli/telemetry/sentry/transports/subprocess.ts
  v-next/hardhat/src/internal/core/config.ts
  v-next/hardhat/src/internal/core/tasks/builders.ts
  v-next/hardhat/src/types/tasks.ts
  v-next/hardhat/test/internal/builtin-plugins/solidity-test/formatters.ts
  v-next/hardhat/test/internal/builtin-plugins/solidity-test/helpers.ts
  v-next/hardhat/test/internal/cli/help/get-global-help-string.ts
  v-next/hardhat/test/internal/cli/main.ts
  v-next/hardhat/test/internal/hre-initialization.ts
Labels: status:ready

#7037 Support verifying contracts on all enabled providers from the main verify task
  .changeset/old-wolves-rhyme.md
  pnpm-lock.yaml
  v-next/hardhat-errors/src/descriptors.ts
  v-next/hardhat-verify/package.json
  v-next/hardhat-verify/src/internal/hook-handlers/config.ts
  v-next/hardhat-verify/src/internal/tasks/verify/blockscout/task-action.ts
  v-next/hardhat-verify/src/internal/tasks/verify/etherscan/task-action.ts
  v-next/hardhat-verify/src/internal/tasks/verify/index.ts
  v-next/hardhat-verify/src/internal/tasks/verify/task-action.ts
  v-next/hardhat-verify/src/internal/verification.ts
  v-next/hardhat-verify/src/type-extensions.ts
  v-next/hardhat-verify/test/hook-handlers/config.ts
  v-next/hardhat-verify/test/tasks/verify/task-action.ts
  v-next/hardhat-verify/test/utils.ts
  v-next/hardhat-verify/test/verification.ts
Labels: status:ready, v-next

#7033 Version Packages (next)
  .changeset/885c49e7-dc27-4d8b-a4dc-a2c0549263d8.md
  .changeset/ec54a241-dde4-478a-b815-182b978704c2.md
  .changeset/pre.json
  pnpm-lock.yaml
  v-next/example-project/package.json
  v-next/hardhat-errors/package.json
  v-next/hardhat-ethers-chai-matchers/package.json
  v-next/hardhat-ethers/package.json
  v-next/hardhat-ignition-core/package.json
  v-next/hardhat-ignition-ethers/package.json
  v-next/hardhat-ignition-ui/package.json
  v-next/hardhat-ignition-viem/package.json
  v-next/hardhat-ignition/package.json
  v-next/hardhat-keystore/package.json
  v-next/hardhat-mocha/package.json
  v-next/hardhat-network-helpers/package.json
  v-next/hardhat-node-test-reporter/package.json
  v-next/hardhat-node-test-runner/package.json
  v-next/hardhat-test-utils/package.json
  v-next/hardhat-toolbox-mocha-ethers/package.json
  v-next/hardhat-toolbox-viem/package.json
  v-next/hardhat-typechain/package.json
  v-next/hardhat-utils/package.json
  v-next/hardhat-verify/package.json
  v-next/hardhat-viem-assertions/package.json
  v-next/hardhat-viem/package.json
  v-next/hardhat-zod-utils/package.json
  v-next/hardhat/CHANGELOG.md
  v-next/hardhat/package.json
  v-next/hardhat/templates/01-node-test-runner-viem/package.json
  v-next/hardhat/templates/02-mocha-ethers/package.json
  v-next/template-package/package.json
Labels: status:triaging

#7041 Remove hardhat_reset usage from the codebase
  .changeset/fast-actors-cough.md
  v-next/hardhat-ethers/test/hardhat-ethers-provider.ts
  v-next/hardhat-ethers/test/hardhat-ethers-signer.ts
  v-next/hardhat-ethers/test/plugin-functionalities.ts
  v-next/hardhat-network-helpers/src/internal/network-helpers/helpers/reset.ts
  v-next/hardhat-network-helpers/src/internal/network-helpers/network-helpers.ts
  v-next/hardhat-network-helpers/src/types.ts
  v-next/hardhat-network-helpers/test/network-helpers/reset.ts
  v-next/hardhat-network-helpers/test/network-helpers/set-nonce.ts
Labels: status:triaging

#7045 fix: change deployment folder rule for ignition
  .changeset/sour-pandas-attend.md
  v-next/hardhat-ignition-ethers/src/internal/ethers-ignition-helper.ts
  v-next/hardhat-ignition-viem/src/internal/viem-ignition-helper.ts
  v-next/hardhat-ignition/src/internal/tasks/deploy.ts
  v-next/hardhat-ignition/test/deploy/reset.ts
  v-next/hardhat-ignition/test/deploy/writeLocalhost.ts
  v-next/hardhat-ignition/test/plan/index.ts
Labels: status:ready

#7060 docs: add a warning to Hardhat utils indicating it is internal
  v-next/hardhat-utils/README.md
Labels: status:ready, no changeset needed

#7075 ci: regression tests framework improvements
  .github/workflows/regression-tests.yml
Labels: status:ready, no changeset needed

#7079 Update build info ids to include compiler and version
  .changeset/calm-taxis-film.md
  v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/compilation-job.ts
Labels: status:triaging

#7090 Indent results summary
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/assert-test/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/assert-test/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/async-describe-test/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/async-describe-test/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/asynchronous-activity-test/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/asynchronous-activity-test/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/errors-test/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/errors-test/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/example-test/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/example-test/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/execution-failure-test/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/execution-failure-test/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/falsy-expression-test/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/falsy-expression-test/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/hooks-test/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/hooks-test/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/multi-test/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/multi-test/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/nested-test/result.v22.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/nested-test/result.v22.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/nested-test/result.v24.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/nested-test/result.v24.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/no-match-test/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/no-match-test/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/only-test-with-the-flag/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/only-test-with-the-flag/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/only-test-without-the-flag/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/only-test-without-the-flag/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/skipped-and-empty-describes/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/skipped-and-empty-describes/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/slow-test/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/slow-test/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/todo-test/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/todo-test/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/top-level-test/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/top-level-test/result.txt
  v-next/hardhat-node-test-reporter/src/formatting.ts
Labels: status:ready, no changeset needed

#7095 Add viem predicates examples to the readme
  v-next/hardhat-viem-assertions/README.md
Labels: status:triaging, no changeset needed

#7096 Fix hh-viem l2 actions when using the optimism chain type
  .changeset/chilled-mails-call.md
  v-next/hardhat-viem/src/internal/chains.ts
  v-next/hardhat-viem/src/internal/clients.ts
  v-next/hardhat-viem/test/chains.ts
  v-next/hardhat-viem/test/clients.ts
Labels: status:ready

#7082 Version Packages (next)
  .changeset/1c1394d9-3ebb-4e04-8827-21090ee39a57.md
  .changeset/58192d66-fad7-4223-8b47-db58eb6507fc.md
  .changeset/pre.json
  pnpm-lock.yaml
  v-next/example-project/package.json
  v-next/hardhat-errors/package.json
  v-next/hardhat-ethers-chai-matchers/package.json
  v-next/hardhat-ethers/package.json
  v-next/hardhat-ignition-core/package.json
  v-next/hardhat-ignition-ethers/package.json
  v-next/hardhat-ignition-ui/package.json
  v-next/hardhat-ignition-viem/package.json
  v-next/hardhat-ignition/package.json
  v-next/hardhat-keystore/package.json
  v-next/hardhat-mocha/package.json
  v-next/hardhat-network-helpers/package.json
  v-next/hardhat-node-test-reporter/package.json
  v-next/hardhat-node-test-runner/package.json
  v-next/hardhat-test-utils/package.json
  v-next/hardhat-toolbox-mocha-ethers/package.json
  v-next/hardhat-toolbox-viem/package.json
  v-next/hardhat-typechain/package.json
  v-next/hardhat-utils/package.json
  v-next/hardhat-verify/package.json
  v-next/hardhat-viem-assertions/package.json
  v-next/hardhat-viem/package.json
  v-next/hardhat-zod-utils/package.json
  v-next/hardhat/CHANGELOG.md
  v-next/hardhat/package.json
  v-next/hardhat/templates/01-node-test-runner-viem/package.json
  v-next/hardhat/templates/02-mocha-ethers/package.json
  v-next/template-package/package.json
Labels: status:triaging

#7100 rename path.tests.nodeTest to path.tests.nodejs
  .changeset/friendly-cameras-notice.md
  v-next/example-project/hardhat.config.ts
  v-next/hardhat-node-test-runner/src/hookHandlers/config.ts
  v-next/hardhat-node-test-runner/src/hookHandlers/test.ts
  v-next/hardhat-node-test-runner/src/task-action.ts
  v-next/hardhat-node-test-runner/src/type-extensions.ts
  v-next/hardhat-node-test-runner/test/registerFileForTestRunner.ts
Labels: status:ready
