Repository NomicFoundation/hardhat, pull requests merged in 2025-05, with the labels that each got.

#6661 Fix "initialization" spelling
  .changeset/chilled-clouds-smile.md
  v-next/hardhat-ignition-core/src/internal/batcher.ts
  v-next/hardhat-utils/src/fs.ts
  v-next/hardhat/src/hre.ts
  v-next/hardhat/src/index.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/hook-handlers/network.ts
  v-next/hardhat/src/internal/cli/main.ts
  v-next/hardhat/src/internal/core/hook-manager.ts
  v-next/hardhat/src/internal/hre-initialization.ts
  v-next/hardhat/test/internal/builtin-plugins/clean/task-action.ts
  v-next/hardhat/test/internal/builtin-plugins/console/task-action.ts
  v-next/hardhat/test/internal/builtin-plugins/node/json-rpc/server.ts
  v-next/hardhat/test/internal/builtin-plugins/run/task-action.ts
  v-next/hardhat/test/internal/cli/main.ts
  v-next/hardhat/test/internal/hre-initialization.ts
Labels: status:triaging

#6658 fix: the error message produced by the errorenous regex matches
  .changeset/short-hornets-end.md
  v-next/hardhat-node-test-reporter/integration-tests/README.md
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/no-match-test/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/no-match-test/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/no-match-test/test.ts
  v-next/hardhat-node-test-reporter/src/error-formatting.ts
Labels: status:ready

#6655 Allow undefined params in JSON RPC handler
  .changeset/famous-cooks-leave.md
  v-next/hardhat/src/internal/builtin-plugins/node/json-rpc/handler.ts
  v-next/hardhat/test/internal/builtin-plugins/node/json-rpc/handler.ts
Labels: v-next

#6429 Port transaction hash bug to v3
  .changeset/giant-ants-protect.md
  v-next/hardhat-errors/src/descriptors.ts
  v-next/hardhat-ignition-core/src/index.ts
  v-next/hardhat-ignition-core/src/internal/execution/deployment-state-helpers.ts
  v-next/hardhat-ignition-core/src/internal/execution/execution-engine.ts
  v-next/hardhat-ignition-core/src/internal/execution/future-processor/future-processor.ts
  v-next/hardhat-ignition-core/src/internal/execution/future-processor/handlers/send-transaction.ts
  v-next/hardhat-ignition-core/src/internal/execution/future-processor/helpers/network-interaction-execution.ts
  v-next/hardhat-ignition-core/src/internal/execution/jsonrpc-client.ts
  v-next/hardhat-ignition-core/src/internal/execution/reducers/execution-state-reducer.ts
  v-next/hardhat-ignition-core/src/internal/execution/reducers/helpers/network-interaction-helpers.ts
  v-next/hardhat-ignition-core/src/internal/execution/types/jsonrpc.ts
  v-next/hardhat-ignition-core/src/internal/execution/types/messages.ts
  v-next/hardhat-ignition-core/src/internal/execution/types/network-interaction.ts
  v-next/hardhat-ignition-core/src/internal/journal/utils/emitExecutionEvent.ts
  v-next/hardhat-ignition-core/src/internal/journal/utils/log.ts
  v-next/hardhat-ignition-core/src/internal/views/execution-state/get-network-execution-states.ts
  v-next/hardhat-ignition-core/src/track-transaction.ts
  v-next/hardhat-ignition-core/src/types/execution-events.ts
  v-next/hardhat-ignition-core/test/execution/execution-engine.ts
  v-next/hardhat-ignition-core/test/execution/future-processor/helpers/network-interaction-execution.ts
  v-next/hardhat-ignition-core/test/mocks/trackTransaction/known-tx/journal.jsonl
  v-next/hardhat-ignition-core/test/mocks/trackTransaction/success/journal.jsonl
  v-next/hardhat-ignition-core/test/mocks/trackTransaction/uninitialized/blank
  v-next/hardhat-ignition-core/test/track-transaction.ts
  v-next/hardhat-ignition-ui/.gitignore
  v-next/hardhat-ignition/package.json
  v-next/hardhat-ignition/src/helpers/pretty-event-handler.ts
  v-next/hardhat-ignition/src/index.ts
  v-next/hardhat-ignition/src/internal/tasks/track-tx.ts
  v-next/hardhat-ignition/src/internal/ui/verbose-event-handler.ts
Labels: status:triaging, v-next

#6663 ci: do not attempt to comment on PRs from forks
  .github/workflows/v-next-ci.yml
Labels: status:ready, no changeset needed

#6630 hardhat-vscode integration support
  .changeset/dull-queens-dress.md
  v-next/hardhat/package.json
  v-next/hardhat/src/hre.ts
  v-next/hardhat/src/internal/builtin-plugins/flatten/task-action.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/build-system.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/dependency-graph-building.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/read-source-file.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/resolver/dependency-resolver.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/type-extensions.ts
  v-next/hardhat/src/lsp-helpers.ts
  v-next/hardhat/test/internal/builtin-plugins/solidity/build-system/dependency-graph-building.ts
Labels: status:triaging

#6635 Chains config refactor
  .changeset/young-baboons-sniff.md
  v-next/hardhat/src/internal/builtin-plugins/network-manager/chain-descriptors.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/config-resolution.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/edr-provider.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/utils/convert-to-edr.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/hook-handlers/config.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/hook-handlers/hre.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/network-manager.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/type-extensions/config.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/type-validation.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/config-resolution.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/network-manager.ts
Labels: status:ready

#6662 Fix instance of dead code
  v-next/hardhat/src/internal/config-loading.ts
Labels: status:triaging, no changeset needed

#6668 Merge user's output selection with our defaults
  .changeset/happy-carrots-kick.md
  v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/artifacts.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/build-system.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/compilation-job.ts
  v-next/hardhat/src/types/solidity/compilation-job.ts
  v-next/hardhat/test/internal/builtin-plugins/solidity/build-system/compilation-job.ts
Labels: status:triaging

#6641 Default to production builds for ignition deploy
  .changeset/orange-beans-buy.md
  v-next/hardhat-ignition/src/internal/tasks/deploy.ts
  v-next/hardhat-ignition/test/deploy/build-profile.ts
  v-next/hardhat-ignition/test/fixture-projects/create2-bad-config/hardhat.config.js
  v-next/hardhat-ignition/test/fixture-projects/create2-exists-chain/hardhat.config.js
  v-next/hardhat-ignition/test/fixture-projects/create2-not-exists-chain/hardhat.config.js
  v-next/hardhat-ignition/test/fixture-projects/lock/hardhat.config.js
  v-next/hardhat-ignition/test/fixture-projects/minimal/hardhat.config.js
  v-next/hardhat-ignition/test/fixture-projects/multiple-contracts-with-same-name/hardhat.config.js
  v-next/hardhat-ignition/test/fixture-projects/reset-flag/hardhat.config.js
  v-next/hardhat-ignition/test/fixture-projects/user-modules/hardhat.config.js
  v-next/hardhat-ignition/test/fixture-projects/verify-no-api-key/hardhat.config.js
  v-next/hardhat-ignition/test/fixture-projects/with-config/hardhat.config.js
  v-next/hardhat-ignition/test/fixture-projects/with-invalid-config/hardhat.config.js
  v-next/hardhat/src/internal/builtin-plugins/solidity-test/task-action.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/index.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/tasks/compile.ts
  v-next/hardhat/test/internal/hre-initialization.ts
Labels: v-next

#6673 Support options with equals signs
  .changeset/sixty-sloths-cheer.md
  v-next/hardhat/src/internal/cli/main.ts
  v-next/hardhat/test/internal/cli/main.ts
Labels: status:triaging

#6656 feat: add mkdtemp helper function
  .changeset/strong-rats-dress.md
  v-next/hardhat-test-utils/src/fs.ts
  v-next/hardhat-utils/src/fs.ts
  v-next/hardhat-utils/test/fs.ts
Labels: status:triaging

#6676 chore/tweak changeset notes
  .changeset/calm-drinks-taste.md
  .changeset/chilled-clouds-smile.md
  .changeset/dull-queens-dress.md
  .changeset/famous-cooks-leave.md
  .changeset/happy-carrots-kick.md
  .changeset/short-hornets-end.md
  .changeset/slimy-pots-applaud.md
  .changeset/strong-rats-dress.md
  .changeset/young-baboons-sniff.md
Labels: status:ready, no changeset needed

#6677 feat: set prague as the default hardfork
  .changeset/large-papayas-enjoy.md
  packages/hardhat-core/src/internal/core/config/config-resolution.ts
  packages/hardhat-core/src/internal/core/config/default-config.ts
  packages/hardhat-core/test/internal/core/config/config-resolution.ts
  packages/hardhat-ethers/test/error-messages.ts
Labels: status:ready

#6686 clarify telemetry status message
  v-next/hardhat/src/internal/builtin-plugins/telemetry/task-action.ts
Labels: status:triaging, no changeset needed

#6645 build: upgrade to @ignored/edr-optimism v0.13.0-alpha.1
  pnpm-lock.yaml
  v-next/hardhat/package.json
  v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/edr-provider.ts
Labels: status:ready, no changeset needed

#6689 test: add integration test for assertions in node test reporter
  v-next/hardhat-node-test-reporter/integration-tests/README.md
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/assert-test/assert.ts
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/assert-test/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/assert-test/result.txt
Labels: status:ready, no changeset needed

#6497 Prepare for next Node LTS version - branch: main
  .changeset/short-mangos-watch.md
  .github/workflows/hardhat-ci.yml
  .github/workflows/hardhat-core-ci.yml
  packages/hardhat-chai-matchers/test/contracts.ts
  packages/hardhat-core/src/internal/cli/constants.ts
  packages/hardhat-core/src/internal/core/config/config-loading.ts
  packages/hardhat-core/test/internal/cli/is-node-version-to-warn-on.ts
  packages/hardhat-ethers/test/helpers.ts
  packages/hardhat-ignition-core/test/execution/future-processor/utils.ts
  packages/hardhat-ignition-core/test/reconciliation/helpers.ts
  packages/hardhat-ignition-core/test/track-transaction.ts
  packages/hardhat-ignition/test/test-helpers/test-ignition-helper.ts
  packages/hardhat-ignition/test/test-helpers/use-ignition-project.ts
  packages/hardhat-solpp/test/tests.ts
Labels: status:ready

#6565 ci: automate the v-next release process using changesets
  .changeset/config.json
  .github/actions/setup-env/action.yml
  .github/workflows/check-changeset-added.yml
  .github/workflows/release.yml
  scripts/check-release.mjs
  scripts/lib/changesets.mjs
  scripts/lib/packages.mjs
  scripts/prepare-github-release.mjs
  scripts/validate-merge-group.mjs
  scripts/validate-pull-request.mjs
  scripts/version-alpha.mjs
  v-next/hardhat/test/internal/cli/init/init.ts
Labels: status:ready, no changeset needed

#6699 ci: add missing changelogs that are read by changesets action
  v-next/hardhat-toolbox-mocha-ethers/CHANGELOG.md
  v-next/hardhat-toolbox-viem/CHANGELOG.md
Labels: status:ready, no changeset needed

#6698 Fix sample projects and add tests to avoid them breaking again
  .changeset/bright-planes-talk.md
  pnpm-lock.yaml
  v-next/hardhat/templates/01-node-test-runner-viem/package.json
  v-next/hardhat/templates/01-node-test-runner-viem/scripts/check-predeploy.ts
  v-next/hardhat/templates/01-node-test-runner-viem/scripts/send-op-tx.ts
  v-next/hardhat/templates/01-node-test-runner-viem/test/Counter.ts
  v-next/hardhat/templates/02-mocha-ethers/package.json
  v-next/hardhat/templates/02-mocha-ethers/scripts/check-predeploy.ts
  v-next/hardhat/templates/02-mocha-ethers/scripts/send-op-tx.ts
  v-next/hardhat/templates/02-mocha-ethers/test/Counter.ts
  v-next/hardhat/test/internal/cli/init/template.ts
Labels: status:ready

#6700 Version Packages (next)
  .changeset/242be992-0f33-40a2-b3fb-9bcaf6e14249.md
  .changeset/b4fed7af-8bd1-401f-8763-1c165f5b8085.md
  .changeset/pre.json
  pnpm-lock.yaml
  v-next/example-project/package.json
  v-next/hardhat-errors/package.json
  v-next/hardhat-ethers-chai-matchers/package.json
  v-next/hardhat-ethers/package.json
  v-next/hardhat-ignition-core/package.json
  v-next/hardhat-ignition-ethers/package.json
  v-next/hardhat-ignition-ui/package.json
  v-next/hardhat-ignition-viem/package.json
  v-next/hardhat-ignition/package.json
  v-next/hardhat-keystore/package.json
  v-next/hardhat-mocha/package.json
  v-next/hardhat-network-helpers/package.json
  v-next/hardhat-node-test-reporter/package.json
  v-next/hardhat-node-test-runner/package.json
  v-next/hardhat-test-utils/package.json
  v-next/hardhat-toolbox-mocha-ethers/package.json
  v-next/hardhat-toolbox-viem/package.json
  v-next/hardhat-typechain/package.json
  v-next/hardhat-utils/package.json
  v-next/hardhat-viem/package.json
  v-next/hardhat-zod-utils/package.json
  v-next/hardhat/CHANGELOG.md
  v-next/hardhat/package.json
  v-next/hardhat/templates/01-node-test-runner-viem/package.json
  v-next/hardhat/templates/02-mocha-ethers/package.json
  v-next/template-package/package.json
Labels: status:triaging

#6701 ci: grant release workflow id-token write permission
  .github/workflows/release.yml
Labels: status:ready, no changeset needed

#6702 Update the ignition `repository` fields in the `package.json` files
  v-next/hardhat-ignition-core/package.json
  v-next/hardhat-ignition-ethers/package.json
  v-next/hardhat-ignition-ui/package.json
  v-next/hardhat-ignition-viem/package.json
  v-next/hardhat-ignition/package.json
Labels: status:ready, no changeset needed

#6703 Fix typechain factories for abstract contracts
  .changeset/nervous-cherries-switch.md
  v-next/hardhat-typechain/src/internal/generate-types.ts
  v-next/hardhat-typechain/test/fixture-projects/custom-out-dir/contracts/A.sol
  v-next/hardhat-typechain/test/index.ts
Labels: status:ready

#6690 feat: bump @ignored/edr to 0.10.0-alpha.4 and add --grep in Solidity tests
  .changeset/gorgeous-eyes-allow.md
  .changeset/mean-avocados-matter.md
  pnpm-lock.yaml
  v-next/hardhat/package.json
  v-next/hardhat/src/internal/builtin-plugins/solidity-test/helpers.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity-test/index.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity-test/task-action.ts
Labels: status:triaging

#6710 Add a `directoryFilter` param to `getAllFilesMatching`
  .changeset/sixty-socks-roll.md
  v-next/hardhat-utils/src/fs.ts
  v-next/hardhat-utils/test/fs.ts
Labels: status:ready

#6711 Fix #6613
  .changeset/olive-suits-deny.md
  v-next/hardhat/src/internal/builtin-plugins/artifacts/artifact-manager.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/build-system.ts
Labels: status:ready

#6692 build: upgrade to edr-0.13.0-alpha.2
  pnpm-lock.yaml
  v-next/hardhat/package.json
  v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/utils/convert-to-edr.ts
Labels: status:ready, no changeset needed

#6718 build: upgrade to edr-0.13.0-alpha.3
  pnpm-lock.yaml
  v-next/hardhat/package.json
  v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/edr-provider.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/utils/convert-to-edr.ts
Labels: status:ready, no changeset needed

#6728 Cleanup text of changesets before release
  .changeset/dull-frogs-wait.md
  .changeset/gorgeous-eyes-allow.md
  .changeset/mean-avocados-matter.md
  .changeset/nervous-cherries-switch.md
  .changeset/olive-suits-deny.md
  .changeset/sixty-socks-roll.md
  .changeset/yellow-dolls-behave.md
Labels: status:ready, no changeset needed

#6687 feat: report coverage from test, test mocha and test node tasks
  .changeset/fair-penguins-collect.md
  .changeset/sharp-flowers-invent.md
  v-next/example-project/test/mocha/mocha-test.ts
  v-next/hardhat-mocha/src/task-action.ts
  v-next/hardhat-node-test-runner/src/coverage.ts
  v-next/hardhat-node-test-runner/src/task-action.ts
  v-next/hardhat/src/internal/builtin-plugins/coverage/coverage-manager.ts
  v-next/hardhat/src/internal/builtin-plugins/coverage/exports.ts
  v-next/hardhat/src/internal/builtin-plugins/coverage/helpers.ts
  v-next/hardhat/src/internal/builtin-plugins/coverage/hook-handlers/solidity.ts
  v-next/hardhat/src/internal/builtin-plugins/coverage/types.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/compilation-job.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/type-extensions.ts
  v-next/hardhat/src/internal/builtin-plugins/test/task-action.ts
  v-next/hardhat/test/internal/builtin-plugins/coverage/coverage-manager.ts
  v-next/hardhat/test/internal/builtin-plugins/solidity/build-system/compilation-job.ts
Labels: status:ready

#6705 Version Packages (next)
  .changeset/6e9378f1-b635-48ff-899e-ae0ce985ba9b.md
  .changeset/e342b7f0-45cb-473d-8637-02b8d1374b4a.md
  .changeset/pre.json
  pnpm-lock.yaml
  v-next/example-project/package.json
  v-next/hardhat-errors/package.json
  v-next/hardhat-ethers-chai-matchers/package.json
  v-next/hardhat-ethers/package.json
  v-next/hardhat-ignition-core/package.json
  v-next/hardhat-ignition-ethers/package.json
  v-next/hardhat-ignition-ui/package.json
  v-next/hardhat-ignition-viem/package.json
  v-next/hardhat-ignition/package.json
  v-next/hardhat-keystore/package.json
  v-next/hardhat-mocha/package.json
  v-next/hardhat-network-helpers/package.json
  v-next/hardhat-node-test-reporter/package.json
  v-next/hardhat-node-test-runner/package.json
  v-next/hardhat-test-utils/package.json
  v-next/hardhat-toolbox-mocha-ethers/package.json
  v-next/hardhat-toolbox-viem/package.json
  v-next/hardhat-typechain/package.json
  v-next/hardhat-utils/package.json
  v-next/hardhat-viem/package.json
  v-next/hardhat-zod-utils/package.json
  v-next/hardhat/CHANGELOG.md
  v-next/hardhat/package.json
  v-next/hardhat/templates/01-node-test-runner-viem/package.json
  v-next/hardhat/templates/02-mocha-ethers/package.json
  v-next/template-package/package.json
Labels: status:triaging

#6727 Support Etherscan API v2
  .changeset/nasty-readers-explode.md
  packages/hardhat-ignition/src/utils/getApiKeyAndUrls.ts
  packages/hardhat-ignition/test/verify/getApiKeyAndUrls.ts
  packages/hardhat-verify/src/internal/blockscout.ts
  packages/hardhat-verify/src/internal/etherscan.ts
  packages/hardhat-verify/test/integration/index.ts
  packages/hardhat-verify/test/unit/etherscan.ts
Labels: status:triaging

#6736 chore: remove ignored packages from changesets
  .changeset/eight-buckets-know.md
Labels: status:ready, no changeset needed

#6729 Version Packages (next)
  .changeset/26bcaae9-5d69-4a23-84ee-81b6f75859e0.md
  .changeset/pre.json
  pnpm-lock.yaml
  v-next/example-project/package.json
  v-next/hardhat-errors/package.json
  v-next/hardhat-ethers-chai-matchers/package.json
  v-next/hardhat-ethers/package.json
  v-next/hardhat-ignition-core/package.json
  v-next/hardhat-ignition-ethers/package.json
  v-next/hardhat-ignition-ui/package.json
  v-next/hardhat-ignition-viem/package.json
  v-next/hardhat-ignition/package.json
  v-next/hardhat-keystore/package.json
  v-next/hardhat-mocha/package.json
  v-next/hardhat-network-helpers/package.json
  v-next/hardhat-node-test-reporter/package.json
  v-next/hardhat-node-test-runner/package.json
  v-next/hardhat-test-utils/package.json
  v-next/hardhat-toolbox-mocha-ethers/package.json
  v-next/hardhat-toolbox-viem/package.json
  v-next/hardhat-typechain/package.json
  v-next/hardhat-utils/package.json
  v-next/hardhat-viem/package.json
  v-next/hardhat-zod-utils/package.json
  v-next/hardhat/CHANGELOG.md
  v-next/hardhat/package.json
  v-next/hardhat/templates/01-node-test-runner-viem/package.json
  v-next/hardhat/templates/02-mocha-ethers/package.json
  v-next/template-package/package.json
Labels: status:triaging

#6738 fix: distribute coverage.sol inside hardhat package
  .changeset/kind-bags-yawn.md
  v-next/hardhat/package.json
Labels: status:ready

#6734 add readme for viem matchers
  .changeset/sixty-beans-pretend.md
  pnpm-lock.yaml
  v-next/example-project/contracts/FailingContract.sol
  v-next/example-project/contracts/Rocket.sol
  v-next/example-project/hardhat.config.ts
  v-next/example-project/package.json
  v-next/example-project/test/node/example-test-of-assertions.ts
  v-next/example-project/tsconfig.json
  v-next/hardhat-toolbox-viem/package.json
  v-next/hardhat-toolbox-viem/src/index.ts
  v-next/hardhat-toolbox-viem/src/type-extensions.ts
  v-next/hardhat-toolbox-viem/tsconfig.json
  v-next/hardhat-viem-matchers/README.md
Labels: status:ready

#6747 chore: update the changelog text in preparation for release
  .changeset/sixty-beans-pretend.md
Labels: status:ready, no changeset needed

#6748 chore: add an empty changelog
  v-next/hardhat-viem-matchers/CHANGLELOG.md
Labels: status:ready, no changeset needed

#6749 chore/rename changeset
  .changeset/lemon-meals-kick.md
Labels: status:ready, no changeset needed

#6750 emptyTask should not require a description
  .changeset/chilly-nails-return.md
  v-next/hardhat/src/internal/core/tasks/builders.ts
  v-next/hardhat/src/types/tasks.ts
  v-next/hardhat/test/internal/core/tasks/builders.ts
Labels: v-next

#6745 Support grep on the npx hardhat test task
  .changeset/spicy-grapes-crash.md
  v-next/hardhat/src/internal/builtin-plugins/test/index.ts
  v-next/hardhat/src/internal/builtin-plugins/test/task-action.ts
Labels: v-next

#6746 Warn on usage of verbose foundry flag for solidity tests
  .changeset/wild-flowers-greet.md
  v-next/hardhat/src/internal/cli/main.ts
Labels: status:triaging

#6767 test: disable reporter test that fails on macos only
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/errors-test/result.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/errors-test/result.txt
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/errors-test/test.ts
Labels: status:ready, no changeset needed

#6759 Version Packages (next)
  .changeset/93c8319f-d0f7-4338-a697-898433b3f23d.md
  .changeset/95d2a8b7-30b9-4c63-8754-3214113e82f6.md
  .changeset/pre.json
  pnpm-lock.yaml
  v-next/example-project/package.json
  v-next/hardhat-errors/package.json
  v-next/hardhat-ethers-chai-matchers/package.json
  v-next/hardhat-ethers/package.json
  v-next/hardhat-ignition-core/package.json
  v-next/hardhat-ignition-ethers/package.json
  v-next/hardhat-ignition-ui/package.json
  v-next/hardhat-ignition-viem/package.json
  v-next/hardhat-ignition/package.json
  v-next/hardhat-keystore/package.json
  v-next/hardhat-mocha/package.json
  v-next/hardhat-network-helpers/package.json
  v-next/hardhat-node-test-reporter/package.json
  v-next/hardhat-node-test-runner/package.json
  v-next/hardhat-test-utils/package.json
  v-next/hardhat-toolbox-mocha-ethers/package.json
  v-next/hardhat-toolbox-viem/package.json
  v-next/hardhat-typechain/package.json
  v-next/hardhat-utils/package.json
  v-next/hardhat-viem-matchers/package.json
  v-next/hardhat-viem/package.json
  v-next/hardhat-zod-utils/package.json
  v-next/hardhat/CHANGELOG.md
  v-next/hardhat/package.json
  v-next/hardhat/templates/01-node-test-runner-viem/package.json
  v-next/hardhat/templates/02-mocha-ethers/package.json
  v-next/template-package/package.json
Labels: status:triaging

#6776 chore: remove `hardhat-verify` from toolboxes
  .changeset/soft-peaches-trade.md
  pnpm-lock.yaml
  v-next/hardhat-toolbox-mocha-ethers/package.json
  v-next/hardhat-toolbox-mocha-ethers/src/index.ts
  v-next/hardhat-toolbox-mocha-ethers/src/type-extensions.ts
  v-next/hardhat-toolbox-mocha-ethers/tsconfig.json
  v-next/hardhat-toolbox-viem/package.json
  v-next/hardhat-toolbox-viem/src/index.ts
  v-next/hardhat-toolbox-viem/src/type-extensions.ts
  v-next/hardhat-toolbox-viem/tsconfig.json
Labels: status:ready, no changeset needed

#6777 fix: pass buildProfile to getCompilationJobs
  v-next/hardhat-verify/src/internal/artifacts.ts
  v-next/hardhat-verify/src/internal/verification.ts
Labels: status:ready, no changeset needed
