Repository NomicFoundation/hardhat, pull requests merged in 2025-06, with the labels that each got.

#6780 delete wrong comment
  packages/hardhat-ethers/src/internal/type-extensions.ts
Labels: status:triaging, no changeset needed

#6788 fix: use production build profile by default
  v-next/hardhat-verify/src/internal/artifacts.ts
  v-next/hardhat-verify/src/internal/verification.ts
Labels: status:ready, no changeset needed

#6790 chore: add Zoey and Armando to issue assigner
  .github/workflows/autoassign-issues.yml
Labels: status:ready, no changeset needed

#6770 Version Packages (next)
  .changeset/afc29c4c-3790-45ba-a043-07ba6bc309a5.md
  .changeset/pre.json
  pnpm-lock.yaml
  v-next/example-project/package.json
  v-next/hardhat-errors/package.json
  v-next/hardhat-ethers-chai-matchers/package.json
  v-next/hardhat-ethers/package.json
  v-next/hardhat-ignition-core/package.json
  v-next/hardhat-ignition-ethers/package.json
  v-next/hardhat-ignition-ui/package.json
  v-next/hardhat-ignition-viem/package.json
  v-next/hardhat-ignition/package.json
  v-next/hardhat-keystore/package.json
  v-next/hardhat-mocha/package.json
  v-next/hardhat-network-helpers/package.json
  v-next/hardhat-node-test-reporter/package.json
  v-next/hardhat-node-test-runner/package.json
  v-next/hardhat-test-utils/package.json
  v-next/hardhat-toolbox-mocha-ethers/package.json
  v-next/hardhat-toolbox-viem/package.json
  v-next/hardhat-typechain/package.json
  v-next/hardhat-utils/package.json
  v-next/hardhat-verify/package.json
  v-next/hardhat-viem-assertions/package.json
  v-next/hardhat-viem/package.json
  v-next/hardhat-zod-utils/package.json
  v-next/hardhat/CHANGELOG.md
  v-next/hardhat/package.json
  v-next/hardhat/templates/01-node-test-runner-viem/package.json
  v-next/hardhat/templates/02-mocha-ethers/package.json
  v-next/template-package/package.json
Labels: status:triaging

#6789 Allow async matcher functions in fs helpers
  .changeset/witty-pots-fold.md
  v-next/hardhat-utils/src/fs.ts
  v-next/hardhat-utils/test/fs.ts
Labels: status:ready

#6798 feat: prepare regression tests for hardhat2 commands
  .github/config/regression-tests.yml
  .github/workflows/regression-tests.yml
Labels: no changeset needed

#6779 Linting for template projects
  .changeset/nine-rivers-promise.md
  v-next/hardhat/eslint.config.js
  v-next/hardhat/package.json
  v-next/hardhat/templates/01-node-test-runner-viem/hardhat.config.ts
  v-next/hardhat/templates/01-node-test-runner-viem/test/Counter.ts
  v-next/hardhat/templates/02-mocha-ethers/hardhat.config.ts
  v-next/hardhat/templates/02-mocha-ethers/test/Counter.ts
Labels: status:triaging

#6787 Viem assertion viem.assertions.emitWithArgs only looks at the first event
  .changeset/nervous-gorillas-mix.md
  v-next/hardhat-viem-assertions/src/internal/assertions/emit/emit-with-args.ts
  v-next/hardhat-viem-assertions/test/internal/assertions/emit/emit-with-args.ts
Labels: v-next

#6825 Revert "chore(regression-tests): unignore testBumpSlot"
  .github/config/regression-tests.yml
Labels: status:ready, no changeset needed

#6840 fix: check the --no-commit flag is supported on installed forge version
  .changeset/fruity-brooms-stare.md
  packages/hardhat-foundry/src/foundry.ts
Labels: status:triaging

#6757 feat: replace @sentry/node with @sentry/core
  .changeset/lucky-roses-act.md
  pnpm-lock.yaml
  v-next/hardhat/.prettierignore
  v-next/hardhat/package.json
  v-next/hardhat/src/internal/cli/telemetry/sentry/anonymizer.ts
  v-next/hardhat/src/internal/cli/telemetry/sentry/init.ts
  v-next/hardhat/src/internal/cli/telemetry/sentry/integrations/onuncaughtexception.ts
  v-next/hardhat/src/internal/cli/telemetry/sentry/integrations/onunhandledrejection.ts
  v-next/hardhat/src/internal/cli/telemetry/sentry/reporter.ts
  v-next/hardhat/src/internal/cli/telemetry/sentry/subprocess.ts
  v-next/hardhat/src/internal/cli/telemetry/sentry/transports/fetch.ts
  v-next/hardhat/src/internal/cli/telemetry/sentry/transports/subprocess.ts
  v-next/hardhat/src/internal/cli/telemetry/sentry/vendor/debug-build.ts
  v-next/hardhat/src/internal/cli/telemetry/sentry/vendor/integrations/context.ts
  v-next/hardhat/src/internal/cli/telemetry/sentry/vendor/integrations/contextlines.ts
  v-next/hardhat/src/internal/cli/telemetry/sentry/vendor/utils/module.ts
  v-next/hardhat/test/internal/cli/telemetry/sentry/transports/subprocess.ts
Labels: status:ready

#6850 fix/node 24 module status 3
  .changeset/tiny-feet-promise.md
  v-next/hardhat-utils/src/subprocess.ts
Labels: status:ready

#6853 chore: update the text of the latest changesets
  .changeset/nervous-gorillas-mix.md
  .changeset/nine-rivers-promise.md
  .changeset/witty-pots-fold.md
Labels: status:ready, no changeset needed

#6802 Version Packages (next)
  .changeset/9a46c252-cece-46df-a82b-92ac5ac509aa.md
  .changeset/c0a5ea37-4927-4913-af38-3e58bb12ad20.md
  .changeset/pre.json
  pnpm-lock.yaml
  v-next/example-project/package.json
  v-next/hardhat-errors/package.json
  v-next/hardhat-ethers-chai-matchers/package.json
  v-next/hardhat-ethers/package.json
  v-next/hardhat-ignition-core/package.json
  v-next/hardhat-ignition-ethers/package.json
  v-next/hardhat-ignition-ui/package.json
  v-next/hardhat-ignition-viem/package.json
  v-next/hardhat-ignition/package.json
  v-next/hardhat-keystore/package.json
  v-next/hardhat-mocha/package.json
  v-next/hardhat-network-helpers/package.json
  v-next/hardhat-node-test-reporter/package.json
  v-next/hardhat-node-test-runner/package.json
  v-next/hardhat-test-utils/package.json
  v-next/hardhat-toolbox-mocha-ethers/package.json
  v-next/hardhat-toolbox-viem/package.json
  v-next/hardhat-typechain/package.json
  v-next/hardhat-utils/package.json
  v-next/hardhat-verify/package.json
  v-next/hardhat-viem-assertions/package.json
  v-next/hardhat-viem/package.json
  v-next/hardhat-zod-utils/package.json
  v-next/hardhat/CHANGELOG.md
  v-next/hardhat/package.json
  v-next/hardhat/templates/01-node-test-runner-viem/package.json
  v-next/hardhat/templates/02-mocha-ethers/package.json
  v-next/template-package/package.json
Labels: status:triaging

#6861 Handle type 4 in transactions
  pnpm-lock.yaml
  v-next/hardhat-errors/src/descriptors.ts
  v-next/hardhat/package.json
  v-next/hardhat/src/internal/builtin-plugins/network-manager/request-handlers/handlers/accounts/local-accounts.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/rpc/types/authorization-list.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/rpc/types/rpc-parity.ts
  v-next/hardhat/src/internal/builtin-plugins/network-manager/rpc/types/tx-request.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/request-handlers/handlers/accounts/local-accounts.ts
Labels: v-next

#6900 Debugging CI issue #6848
  v-next/hardhat-ignition/test/test-helpers/wait-for-pending-txs.ts
  v-next/hardhat-keystore/test/loaders/keystore-file-loader.ts
  v-next/hardhat-network-helpers/test/index.ts
  v-next/hardhat-toolbox-mocha-ethers/test/fixture-projects/toolbox/scripts/script.ts
  v-next/hardhat-toolbox-viem/test/fixture-projects/toolbox/scripts/script.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/compiler/solcjs-runner.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/request-handlers/handlers/accounts/local-accounts.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/request-handlers/handlers/gas/automatic-gas-price-handler.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/request-handlers/handlers/gas/fixed-gas-handler.ts
  v-next/hardhat/test/internal/builtin-plugins/network-manager/request-handlers/handlers/gas/fixed-gas-price-handler.ts
  v-next/hardhat/test/internal/builtin-plugins/solidity/build-system/solc-config-selection.ts
  v-next/hardhat/test/internal/cli/init/init.ts
  v-next/hardhat/test/utils.ts
Labels: status:ready, no changeset needed

#6899 Fix warning: passing args to `spawn` when shell is set to true
  .changeset/stupid-cars-suffer.md
  v-next/hardhat/src/internal/cli/init/init.ts
Labels: status:triaging

#6898 Add task to hardhat-keystore to show path to keystore file
  .changeset/clean-spies-fail.md
  v-next/hardhat-keystore/src/index.ts
  v-next/hardhat-keystore/src/internal/tasks/path.ts
  v-next/hardhat-keystore/test/integration/tasks.ts
  v-next/hardhat-keystore/test/tasks/path.ts
Labels: v-next

#6903 Rename 'node' task to 'nodejs' for node-test-runner
  .changeset/brave-poems-pull.md
  v-next/example-project/package.json
  v-next/hardhat-node-test-runner/README.md
  v-next/hardhat-node-test-runner/src/coverage.ts
  v-next/hardhat-node-test-runner/src/hookHandlers/test.ts
  v-next/hardhat-node-test-runner/src/index.ts
  v-next/hardhat-node-test-runner/src/task-action.ts
  v-next/hardhat-toolbox-viem/test/index.ts
  v-next/hardhat/templates/01-node-test-runner-viem/README.md
Labels: status:triaging

#6906 Allow js/ts test runners to run test files outside their configured paths
  .changeset/gold-cows-provide.md
  v-next/hardhat-mocha/src/hookHandlers/test.ts
  v-next/hardhat-mocha/test/registerFileForTestRunner.ts
  v-next/hardhat-node-test-runner/src/hookHandlers/test.ts
  v-next/hardhat-node-test-runner/test/fixture-projects/test-project/hardhat.config.ts
  v-next/hardhat-node-test-runner/test/fixture-projects/test-project/package.json
  v-next/hardhat-node-test-runner/test/fixture-projects/test-project/test/test.ts
  v-next/hardhat-node-test-runner/test/registerFileForTestRunner.ts
Labels: status:triaging

#6919 chore: bump the version of the viem toolbox
  .changeset/pre.json
  .changeset/twelve-taxes-help.md
  pnpm-lock.yaml
  v-next/hardhat-toolbox-viem/package.json
  v-next/hardhat/templates/01-node-test-runner-viem/package.json
Labels: status:ready

#6918 Version Packages (next)
  .changeset/52f994d5-ccc4-4151-92bc-2051eaf7c635.md
  .changeset/pre.json
  pnpm-lock.yaml
  v-next/example-project/package.json
  v-next/hardhat-errors/package.json
  v-next/hardhat-ethers-chai-matchers/package.json
  v-next/hardhat-ethers/package.json
  v-next/hardhat-ignition-core/package.json
  v-next/hardhat-ignition-ethers/package.json
  v-next/hardhat-ignition-ui/package.json
  v-next/hardhat-ignition-viem/package.json
  v-next/hardhat-ignition/package.json
  v-next/hardhat-keystore/package.json
  v-next/hardhat-mocha/package.json
  v-next/hardhat-network-helpers/package.json
  v-next/hardhat-node-test-reporter/package.json
  v-next/hardhat-node-test-runner/package.json
  v-next/hardhat-test-utils/package.json
  v-next/hardhat-toolbox-mocha-ethers/package.json
  v-next/hardhat-toolbox-viem/package.json
  v-next/hardhat-typechain/package.json
  v-next/hardhat-utils/package.json
  v-next/hardhat-verify/package.json
  v-next/hardhat-viem-assertions/package.json
  v-next/hardhat-viem/package.json
  v-next/hardhat-zod-utils/package.json
  v-next/hardhat/CHANGELOG.md
  v-next/hardhat/package.json
  v-next/hardhat/templates/01-node-test-runner-viem/package.json
  v-next/hardhat/templates/02-mocha-ethers/package.json
  v-next/template-package/package.json
Labels: status:triaging

#6932 Regenerate the test fixtures with Node 24.3.0
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/nested-test/result.v24.svg
  v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/nested-test/result.v24.txt
Labels: status:ready, no changeset needed

#6915 Apply feedback from #6889
  v-next/hardhat-mocha/.gitignore
  v-next/hardhat-verify/src/internal/contract.ts
  v-next/hardhat/src/internal/builtin-plugins/flatten/task-action.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/artifacts.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/build-system.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/compilation-job.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/dependency-graph-building.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/dependency-graph.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/resolved-file.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/resolver/dependency-resolver.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/resolver/remapped-npm-packages-graph.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/resolver/remappings.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/resolver/types.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/root-paths-utils.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/solc-config-selection.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/config.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity/type-extensions.ts
  v-next/hardhat/src/types/solidity/build-system.ts
  v-next/hardhat/src/types/solidity/compiler-io.ts
  v-next/hardhat/src/types/solidity/dependency-graph.ts
  v-next/hardhat/src/types/solidity/errors.ts
  v-next/hardhat/src/types/solidity/resolved-file.ts
  v-next/hardhat/src/types/solidity/solidity-artifacts.ts
  v-next/hardhat/test/internal/builtin-plugins/solidity/build-system/compilation-job.ts
  v-next/hardhat/test/internal/builtin-plugins/solidity/build-system/dependency-graph-building.ts
  v-next/hardhat/test/internal/builtin-plugins/solidity/build-system/dependency-graph.ts
  v-next/hardhat/test/internal/builtin-plugins/solidity/build-system/resolver/dependency-resolver.ts
  v-next/hardhat/test/internal/builtin-plugins/solidity/build-system/resolver/remapped-npm-packages-graph.ts
  v-next/hardhat/test/internal/builtin-plugins/solidity/build-system/resolver/utils.ts
  v-next/hardhat/test/internal/builtin-plugins/solidity/build-system/root-paths-utils.ts
  v-next/hardhat/test/internal/builtin-plugins/solidity/build-system/solc-config-selection.ts
Labels: status:ready, no changeset needed

#6930 Version Packages (next)
  .changeset/0a3a785a-8c6c-416d-91c1-7b783facff26.md
  .changeset/7dded2c1-f04e-404d-b8e0-7c5041633b6c.md
  .changeset/pre.json
  pnpm-lock.yaml
  v-next/example-project/package.json
  v-next/hardhat-errors/package.json
  v-next/hardhat-ethers-chai-matchers/package.json
  v-next/hardhat-ethers/package.json
  v-next/hardhat-ignition-core/package.json
  v-next/hardhat-ignition-ethers/package.json
  v-next/hardhat-ignition-ui/package.json
  v-next/hardhat-ignition-viem/package.json
  v-next/hardhat-ignition/package.json
  v-next/hardhat-keystore/package.json
  v-next/hardhat-mocha/package.json
  v-next/hardhat-network-helpers/package.json
  v-next/hardhat-node-test-reporter/package.json
  v-next/hardhat-node-test-runner/package.json
  v-next/hardhat-test-utils/package.json
  v-next/hardhat-toolbox-mocha-ethers/package.json
  v-next/hardhat-toolbox-viem/package.json
  v-next/hardhat-typechain/package.json
  v-next/hardhat-utils/package.json
  v-next/hardhat-verify/package.json
  v-next/hardhat-viem-assertions/package.json
  v-next/hardhat-viem/package.json
  v-next/hardhat-zod-utils/package.json
  v-next/hardhat/CHANGELOG.md
  v-next/hardhat/package.json
  v-next/hardhat/templates/01-node-test-runner-viem/package.json
  v-next/hardhat/templates/02-mocha-ethers/package.json
  v-next/template-package/package.json
Labels: status:triaging

#6912 build: upgrade to @ignored/edr-optimism v0.13.0-alpha.5
  .changeset/lovely-lizards-decide.md
  pnpm-lock.yaml
  v-next/hardhat/package.json
  v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/edr-provider.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity-test/edr-artifacts.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity-test/formatters.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity-test/helpers.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity-test/reporter.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity-test/runner.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity-test/task-action.ts
  v-next/hardhat/src/internal/builtin-plugins/solidity-test/types.ts
  v-next/hardhat/src/internal/edr/context.ts
Labels: status:ready
